### ISSUE TITLE
Cannot Smash Human Samples

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#1001]
![screen shot 2019-01-30 at 3 18 42 pm](https://user-images.githubusercontent.com/139987/52010017-62a82780-24a2-11e9-8d92-84cac091adad.png)

I assume this is a missing human QN target.

**Comment by dvenprasad** [comment]
![screen shot 2019-01-30 at 3 20 12 pm](https://user-images.githubusercontent.com/15315514/52010094-95eab680-24a2-11e9-9760-b39511b284db.png)


Also got this error for mouse samples.
