### ISSUE TITLE
Unsupported datasets that slipped through the cracks

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/refinebio#1022]
### Context

Some clearly not supported datasets such as this [SNP dataset](https://www.refine.bio/experiments/GSE12494) have made it into refine.bio

### Problem or idea

The first edition of the accession experiment id list that I made for #642, I noted in a later [comment](https://github.com/AlexsLemonade/refinebio/issues/642#issuecomment-425442571) that some of
the ped cancer related experiment ids (because I got them a different way) didn't make it through the supported platforms filtering step. So I had redone them and posted that new list. 

However, it looks like some of those very unsupported datasets that was in my first edition of the list and are from the ped_cancer_keyword search are the ones that accidentally slipped in. For example GSE12494 was in the ped_cancer list because it is neuroblastoma (which is one of the key words). 

### Solution or next step

I used my code that I used previously to obtain the pediatric cancer experiment lists on #642 and reversed so that only experiments using unsupported platforms will show up. According to the [supported_microarray.csv](https://raw.githubusercontent.com/AlexsLemonade/identifier-refinery/master/supported_microarray_platforms.csv). I also had to exclude the RNA-seq datasets that came up in this list though, because they are supported, but they aren't in the supported *microarray* list. 

One thing we need to figure out though before we go ahead and remove these, is that there are a two "SuperSeries" experiment sets on this list that include both unsupported and supported data: [GSE19578](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE19578) and [GSE10792](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE10792)  

@kurtwheeler If you remove the experiments these by their experiment accession codes, how can we make sure that you remove the unsupported entries but not the supported samples? Let me know if I can help you get information to do this. Maybe you already have a system in place to differentiate the samples. 

Assuming you have a way to deal with those two mixed platform experiments: 
Here is the redaction list ready to go, along with the code I used to obtain it:
[experiment_redaction.zip](https://github.com/AlexsLemonade/refinebio/files/2832954/experiment_redaction.zip)

Besides the two mixed platform experiments mentioned above, I've double/triple checked this experiment list and they are all exon microarrays, methylation arrays, and SNP arrays, which are all non supported, so I believe this list of 47 experiments is correct. 

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
This is good work

**Comment by cgreene** [comment]
The ones with no right-type samples should clearly be removed. It may be ok to have records for wrong-type samples too for experiments where there are some right-type samples. I'm not sure what our precedent is on this, but I think we were expecting there to be a fair number of these cases.

**Comment by cansav09** [comment]
For this particular instance, in this particular list of experiments, this unsupported and supported platforms thing only comes up twice. However, this does beg the question of what do we typically do with datasets like these?

**Comment by cgreene** [comment]
We should process the samples that we support, because they may be useful individually and they should also be useful for our compendia. For items that we don't support, @dvenprasad's new design should allow folks to request them if they want them. This will help us gather information on whether or not people actually want them.

**Comment by arielsvn** [comment]
Can this be closed? We still have unsupported experiments in the DB and people can request them via the "Request Experiment" button.

Also, with https://github.com/AlexsLemonade/refinebio-frontend/pull/689 these experiments won't be included in the search results unless users specify that they want to see experiments with no downloadable samples.

**Comment by cgreene** [comment]
> Also, with AlexsLemonade/refinebio-frontend#689 these experiments won't be included in the search results unless users specify that they want to see experiments with no downloadable samples.

I think that with this it should be fine. Thanks!
