### ISSUE TITLE
Remove Control Probes And _at Before Making QN Targets

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#1026]
Smasher previously sanitized these, new technique is dropping inputs that could be valid because some might have `_at` and some might not.

**Comment by Miserlou** [comment]
It's filtering out the rogue mice though, so that's good.

**Comment by jaclyn-taroni** [comment]
> dropping inputs that could be valid because some might have `_at` and some might not.

If we're only using data that _we've_ processed (i.e., with BrainArray), when would samples not have `_at` ?

**Comment by jaclyn-taroni** [comment]
Yes, my question was when would this **not** occur if all samples are coming from the same platform and are processed in the same way.
