### ISSUE TITLE
Improve Project Description in Readme

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#103]
The description of the project in the README file is vague to the point of uselessness. 

So far, it has evolved from:

> A project to download, process, aggregate, and serve bioinformatic data now supported by Alex's Lemonade Stand Foundation, with some initial development supported by the Gordon and Betty Moore Foundation via GBMF 4552 to Casey Greene.

to 

> A project to download, harmonize, aggregate, and serve massive amounts of bioinformatic data.

But this is still pretty useless.

I think we need a single sentence that captures what the project _actually_ does, and then a longer paragraph that explains in a little bit more practical detail.

@dvenprasad - do you want to take a stab at this?

(Also - this might be too late to discuss - but "Data Refinery" itself is also extremely vague for a project name - what kind of data? Refined how? etc.)

**Comment by dvenprasad** [comment]
Here are some alternatives (although @jaclyn-taroni will need to verify how technically accurate it is)
1. Data repository for harmonized, aggregated cancer datasets, ready-to-use for cancer researchers and AI/ML scientists.

2. Data refinery harmonizes cancer datasets from various public datasources and makes it readily available for download.

3. Data refinery creates a repository of shovel-ready cancer datasets available to for download. 

Possible longer explaination
Data refinery processes publicly available cancer datasets from sources like ArrayExpress. The datasets are processed with the best techniques determined by publications and domain experts. The processed datasets can be used
- As validation datasets
- As training data for ML models

**Comment by Miserlou** [comment]
+1 to having 'cancer', +1 to 'shovel-ready', +1 to 'cancer researchers and AI/ML scientists'.

I think "searchable", or better yet "query-able", should go along with "download".

I also think that the _size_ of the dataset is worth including here, even if it in the broad description it's just something like "massive", "global", "petabyte-scale", etc.

> Data Refinery harmonizes petabytes of publicly available cancer data into ready-to-use datasets for cancer researchers and AI/ML scientists.

**Comment by dvenprasad** [comment]
> Data Refinery harmonizes petabytes of publicly available cancer data into ready-to-use datasets for cancer researchers and AI/ML scientists to query and download. 

I think this covers all the bases.

**Comment by jaclyn-taroni** [comment]
A couple points I want to note (and I think these are important as they distinguish us a bit from other projects):

* We're processing much more than cancer data (e.g., cancer cell lines, tumor samples from both adult and pediatric cancers).
* We're not just processing human data. Right now, we intend to process all genome-wide RNA assays for organisms that have >500 assays available.

Thinking about pediatric cancer research specifically, I suspect having experiments that examine and/or perturb developmental processes in multiple organisms is going to be important.

I also think "Data Refinery" is, to a certain extent, purposefully vague. A new technique/data type that we would like to include could come out at any point.

**Comment by cgreene** [comment]
This has been changed to:

> Refine.bio harmonizes petabytes of publicly available biological data into ready-to-use datasets for cancer researchers and AI/ML scientists.

That appears to satisfy all of the cases described above. 👍
