### ISSUE TITLE
Our Deploy Process Is a Sisyphean Hellscape

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#1030]
I currently need to make a one line change to production. 

Deploying this change will require:

- 2 pull requests
- 3 pull request approvals from a minimum of two other people
- 30 distinct Docker image builds
- 5 hours of CircleCI compute time across 16 workflow components
- 5 hours of real time - minimum! - assuming that all PRs are approved immediately, there are no CircleCI technical failures (which there often are) and there are no random outages in any of the 5 remote services we test against (which there often are). In practice, this usually takes 6 to 8 hours or has to be spread across multiple days.

Can somebody remind me of the benefits of this system? 

I understand that this is a "best practice", but we are functionally a 2 man organization with a CI system that is designed to serve 200.

My suggestion is that we build a backdoor into our own system to hack around ourselves, allowing us to rapidly deploy hotfixes without wasting dozens and dozens of hours a week blocked by this monstrosity. 

Every day I push the rock.

**Comment by Miserlou** [comment]
I want to be able to push a tag with `-hotfix` that will skip PR and testing and go directly to prod deployment.

**Comment by kurtwheeler** [comment]
I agree that we should be able to deploy hotfixes faster than this, but I think that there could potentially be a middle ground between no process and the amount of process we have now. I think this probably merits a bit more discussion and thought, let's talk more tomorrow.

**Comment by Miserlou** [comment]
Result from discussion:

- Require all PRs to be "up to date" via branch protection
- Don't re-run tests before deploy
- Allow tags with `-hotfix` suffix to be added to the dev branch, triggering production deploy.

Allows hotfixes to be deployed without tests, but does require a single human review. Still vulnerable to the kurt-and-ariel get the flu problem but should at least save a lot of time for common cases.

**Comment by Miserlou** [comment]
Just as an example of how ridiculous the current arrangement is - there is a hotfix/master deploy I want to push right now, and I can't because Ariel is out sick and Casey left to go wherever it is that he goes.

**Comment by cgreene** [comment]
:joy: faculty meeting.

**Comment by Miserlou** [comment]
Closing as sanity has been temporarily restored.
