### ISSUE TITLE
Engage With Early Adopters

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#1031]
Four parts:

 - Slack message to #robots ought to suffice for now
 - Add users (who agree to be contacted) to CRM
 - Set up a drip for those users
 - Create and seed a user support community (Slack) + invitation microservice

**Comment by kurtwheeler** [comment]
I think we've done these things. We've collect emails so we can email people, @dvenprasad has reached out to many of our early downloaders, and we've got the Cancer Data Science Community slack.
