### ISSUE TITLE
Fastqc is mysteriously erroring for some samples

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1065]
### Context

Some of the zebrafish jobs I tried to rerun failed with a failure message like:
```
data_refinery=> select failure_reason from processor_jobs where id=2025954;
               failure_reason
--------------------------------------------
 Started analysis of SRR3666782_1.fastq    +
 Started analysis of SRR3666782_2.fastq    +
 Approx 5% complete for SRR3666782_1.fastq +
 Approx 5% complete for SRR3666782_2.fastq +
 Approx 10% complete for SRR3666782_2.fastq+
 Approx 10% complete for SRR3666782_1.fastq+
....
```

### Problem or idea

We should figure out what's causing those jobs to fail and fix it!

### Solution or next step

@jaclyn-taroni mentioned that fastqc may switch its standard error and its standard out, so there could be an error message that we're not capturing. Capturing that and rerunning a failed job may give more insight.

Either way, fix the bug!

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
This will be closed by the move to pipes because fastqc will be unavailable. The salmon folks may propose an alternative for us, but I'm going to close this for now.
