### ISSUE TITLE
Downloader job recreation seems to be broken for GEO jobs

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1068]
### Context

#1006 

### Problem or idea

GEO downloader jobs that were recreated don't get any original files associated with them.

### Solution or next step

Figure out why not and fix it

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by arielsvn** [comment]
@kurtwheeler can we close this?

**Comment by kurtwheeler** [comment]
Yes! Good call! We definitely created a lot of successful GEO jobs!!!
