### ISSUE TITLE
Measure and Analyze KPIs

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#1070]
We are interested in tracking and optimizing:

- Growth % (Successfully Delivered Datasets [Compendia & Non-Compendia], Month over Month)
- User -> Community Member Conversion %, community Participation Rates
- Overall Traffic / Time on Site / Funnel Conversion Rates

Growth percentages and absolutes can be an addition to the `stats` endpoint, community statistics will need to be created by combining figures from our internal and external data sources, and traffic statistics can be provided by GA/Hotjar.

**Comment by Miserlou** [comment]
@dvenprasad - If you have control of the GA, can you set up the conversion/onboarding funnel ([ex](https://neilpatel.com/blog/conversion-funnel-survival-guide/)) and give the correct embed codes to the frontend so that we track this properly (if we don't already).

**Comment by kurtwheeler** [comment]
We discuss these KPIs at our quarterly all hands meetings.
