### ISSUE TITLE
Platform filter not working in search

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1075]
### Context

Search API should support filtering the results by platform.

### Problem or idea

This was working when we did the initial deploy, but for some reason now it's not working. For example this returns no results:

https://api.refine.bio/es/?platform=IlluminaHiSeq2000

### Solution or next step

Not sure how to fix it. Tagging @Miserlou for advice.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
I made a spelling mistake: https://github.com/AlexsLemonade/refinebio/blame/dev/api/data_refinery_api/views.py#L206
