### ISSUE TITLE
Search for whole, single proper nouns seems potentially broken

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#1078]
### Context

@lemonadejay was searching for "Ewing" and getting empty results. We have Ewing sarcoma data, and even "Ewing sarcoma" the search returns 301 results.

### Problem or idea

A search that returns zero results that should not is this one: https://www.refine.bio/search?q=Ewing

It's possible that a field is not getting appropriately indexed, something odd is happening with proper nouns, or something else is happening.

### Solution or next step

We should use this as a test case to track down the issue with our indexing and search.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by arielsvn** [comment]
We now have 105 results for `Ewing` and for `Ewing sarcoma` 316 results.

@Miserlou is this the expected behavior? I'd assume we would return less results when adding more terms to the search query.

**Comment by Miserlou** [comment]
There's a difference between `"Ewing sarcoma"` and `Ewing sarcoma`, so it's likely detecting non-Ewing sarcomas. So, I guess this is the correct behavior. It'd be great if we could order by match for this case, so it's not just by sample.

**Comment by cgreene** [comment]
The search in question now returns more than zero results.
