### ISSUE TITLE
[Investigation] Are there 2-channel samples in production?

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#1104]
### Context

Related to: #1076 
Moving discussion from #1079 because that is the right solution to the problem, but we still don't know if any 2 channel/2 color samples made it in to production. This issue is for tracking that.

### Problem and next steps

The SCAN processor we have for Agilent would have output separate for each channel and therefore have two columns for an individual sample. That's consistent with what is reported in the aforementioned issue and PR -- i.e., this would cause smasher trouble.

No Agilent platforms are on [our supported microarray platforms list](https://github.com/AlexsLemonade/refinebio/blob/b82715bd10aa0d3dbac4455b6e944f337ffdb229/config/supported_microarray_platforms.csv). If there are Agilent samples in production, it is likely because it "snuck through" as part of a GEO SuperSeries.

- [ ] Figure out if 2 channel samples are in production data. (This is possibly slightly complicated by #1102.) 
- [ ] If so, did they sneak in because they are part of a SuperSeries? If it's not because of a SuperSeries, let's figure out what happened.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
1079 was caused by bad test data from `GSE51081`, but that experiment isn't available through our search.

**Comment by cgreene** [comment]
Given more investigation in #1102 I don't see any reason to, at this time, expect that we have two-channel data in production (at least not Agilent-derived).
