### ISSUE TITLE
Is a day too short for dataset expiration?

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1112]
### Context

@arielsvn and I were discussing #1109 and his initial reaction to only 1 day was that it seemed too short. 

### Problem or idea

I don't have a strong opinion about this one, but his use case of "someone makes a dataset, is told to wait 10 minutes, then forgets about it until the next day" does seem moderately compelling.

### Solution or next step

@dvenprasad what do you think?

It's rather trivial to change this, it's just a setting on the bucket and then we should also change the timeout for the presigned urls to match.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by dvenprasad** [comment]
Yes, I agree with @arielsvn. 1 day seems too short. 
I think ensuring the link is active for up to 7 days would be ideal but at minimum 3 days. 

@kurtwheeler are there any concerns for leaving the link active for that long?

**Comment by kurtwheeler** [comment]
Nah, it's just additional S3 storage costs but that should be relatively trivial compared to everything else we're storing in S3.

**Comment by cgreene** [comment]
I agree - the costs are minor for better user experience 👍
