### ISSUE TITLE
Process Samples for Pilot Phase

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#112]

**Comment by Miserlou** [comment]
The purpose of this ticket is to track the specific samples which we want to process for the first shovel-ready set of processed samples we want to host, aka "Version Jackie".

This will be a much smaller subset of all possible samples, which will we will eventually crunch, but this will give us the information we need in order to see the bottlenecks of the system (in terms of inbound data transfer, internal data transfer, disk I/O, database performance, scaling performance, instance types for different pipeline stages) and, most importantly, cost per sample.

I'm imagining that the deliverable for this ticket will be either a text file with a list of values, a range of sequential values, or a script which generates a set of values.

**Comment by Miserlou** [comment]
First set, shared via Slack:

## Neuroblastoma accessions

### Affymetrix
GSE16254	Versteeg
GSE81895	Heiskanen
GSE7529	Albino/Moretti
GSE12460	Delattre
GSE81896	Heiskanen
GSE16237	Hiyama
GSE13136	Lastowska
GSE54720	Lavarino
GSE3960	Maris
GSE3446	Seeger
E-MEXP-669	Speleman
GSE16476	Versteeg
GSE27608	Khan


### Agilent 2-color


### Agilent 1-color
GSE45547	Kocak
GSE49710	SEQC (microarray)
GSE73517	Westermann
GSE65303	Schramm
GSE79910	Capasso	(Custom 44k array)
GSE25624	Corrias

### Illumina
GSE19274	Jagannathan


### RNA-seq
GSE62564	SEQC (RNA-seq)


### Custom
E-TABM-38	Oberthuer
GSE80154	Bradner


### Other data from different sources:
TARGET

**Comment by kurtwheeler** [comment]
This is an older set, which has some caveats. Before we try to run all of these, we should know what to for the Agilent experiments, along with having SCAN for Illumina ready to process those experiments.

E-GEOD-59071
E-MTAB-2967
E-GEOD-36807
E-MTAB-184
E-GEOD-22619
E-GEOD-25220
E-GEOD-24287
E-GEOD-13367
E-GEOD-4183
E-GEOD-3365
E-GEOD-57183
E-GEOD-67596
E-GEOD-58667
E-GEOD-55319
E-GEOD-26112
E-GEOD-41831
E-GEOD-41744
E-GEOD-26554
E-GEOD-20307
E-GEOD-23687
E-GEOD-21521
E-GEOD-13501
E-GEOD-13849
E-GEOD-15645
E-GEOD-11083
E-GEOD-15083
E-GEOD-11907
E-GEOD-8650
E-GEOD-7753
E-GEOD-68004
E-GEOD-63881
E-GEOD-48498
E-GEOD-16797
E-MTAB-5542
E-GEOD-81622
E-GEOD-65391
E-GEOD-72798
E-GEOD-72747
E-GEOD-78193
E-GEOD-62764
E-GEOD-45291
E-GEOD-50772
E-GEOD-61635
E-GEOD-45923
E-GEOD-49454
E-GEOD-29536
E-GEOD-52471
E-GEOD-50635
E-GEOD-37463
E-GEOD-37460
E-GEOD-37455
E-GEOD-39088
E-GEOD-32591
E-GEOD-36941
E-GEOD-32279
E-GEOD-26975
E-GEOD-24060
E-GEOD-24706
E-MEXP-1635
E-MTAB-5262
E-GEOD-72246
E-GEOD-80047
E-GEOD-69967
E-GEOD-82140
E-GEOD-75890
E-GEOD-67853
E-GEOD-75343
E-GEOD-50614
E-GEOD-57376
E-GEOD-61281
E-GEOD-47751
E-GEOD-58121
E-GEOD-51440
E-GEOD-55201
E-GEOD-53552
E-GEOD-50790
E-GEOD-47598
E-GEOD-41664
E-GEOD-41663
E-GEOD-41662
E-GEOD-34248
E-GEOD-30999
E-GEOD-31652
E-GEOD-30768
E-GEOD-27887
E-GEOD-18948
E-GEOD-11903
E-GEOD-13355
E-GEOD-2737
E-GEOD-78068
E-GEOD-74143
E-GEOD-58795
E-GEOD-48780
E-GEOD-55584
E-GEOD-55457
E-GEOD-55235
E-GEOD-35455
E-GEOD-45867
E-GEOD-30023
E-GEOD-42296
E-GEOD-39340
E-GEOD-37107
E-GEOD-33377
E-MEXP-3390
E-GEOD-25160
E-GEOD-24742
E-GEOD-15573
E-MTAB-11
E-GEOD-15258
E-GEOD-15602
E-GEOD-12021
E-GEOD-8350
E-GEOD-1402
E-GEOD-56998
E-GEOD-42832
E-GEOD-37912
E-GEOD-32887
E-GEOD-19314
E-GEOD-18781
E-GEOD-16538
E-GEOD-66795
E-GEOD-40568
E-MTAB-2073
E-GEOD-51092
E-GEOD-48378
E-GEOD-40611
E-GEOD-23117
E-MEXP-1883
E-GEOD-81292
E-GEOD-76886
E-GEOD-76809
E-GEOD-65405
E-GEOD-65336
E-GEOD-58095
E-MEXP-1214
E-GEOD-48149
E-MEXP-32
E-GEOD-33463
E-GEOD-32413
E-GEOD-19617
E-MTAB-1944
E-GEOD-17114

**Comment by Miserlou** [comment]
Related: 

#87 
#89

**Comment by jaclyn-taroni** [comment]
Can we prioritize the neuroblastoma data from SEQC, specifically `GSE62564` (RNA-seq)? The other SEQC accession (`GSE49710`) is Agilent one-color so we'll just take the processed data as is for now. Have some experiments in mind 🙂

**Comment by jaclyn-taroni** [comment]
Upon further consideration, for "Version Jackie" let's grab both raw and processed data even if we don't have a processor yet (i.e., for Agilent one-color). This is a good point to try out somethings re: processors.

**Comment by Miserlou** [comment]
Documenting, for my own understanding: GSE16254 becomes E-GEOD-16254. #causebio

This one is a tricky one:  GSE62564 / E-GEOD-62564

The AE page has no samples: 
https://www.ebi.ac.uk/arrayexpress/experiments/E-GEOD-62564/

from [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE62564), with about 10 magical clicks that I don't remember, you can get to a page with a some downloads. I have no idea how to do it again even though I watched Jackie do it. I don't think there is an API to do this, so we may have to write an HTML scraper, which I'm not thrilled about for this task.

**Comment by Miserlou** [comment]
Notes to myself:

> GSE81895
`{'experiments': {'api-version': 3, 'api-revision': '091015', 'version': 3.0, 'revision': '091015', 'total': 0, 'total-samples': 0, 'total-assays': 0}}`
???

Also GSE16237, GSE54720.

> E-GEOD-45547
Is not considered to be on a supported platform, per our new list. In fact, none of the ones on the Agilent 1-Color section are on a supported platform.

> GSE19274
Also has no Experiment data like above.

> GSE62564
Is not on a supported platform.

> E-TABM-38 Oberthuer
> GSE80154 Bradner
Also not supported.

I could add a --force option to skip the platform detection, but that won't solve the issue for API responses which don't return samples. Are those super-series?

**Comment by Miserlou** [comment]
From Kurt's set:
> E-GEOD-25220
is not on a supported platform.

As is E-GEOD-24287, E-GEOD-41744, E-MTAB-5542, E-GEOD-78193, E-GEOD-45923, E-GEOD-32591, E-GEOD-26975, E-GEOD-24060, E-GEOD-72246, E-GEOD-82140, E-GEOD-75890, E-GEOD-78068, E-GEOD-58795, E-GEOD-35455, E-MEXP-3390, E-GEOD-8350, E-MTAB-2073, E-GEOD-81292, E-GEOD-76886, E-GEOD-65405, E-GEOD-48149, E-MEXP-32, E-GEOD-32413, E-GEOD-19617

> E-GEOD-20307

Shares samples but I think it's okay.

> E-GEOD-45291

Has soooo many samples. But that's okay.

> E-GEOD-76809

Appears to hang silently, not sure why.

Everything else listed here surveys okay though.

**Comment by Miserlou** [comment]
Result of discussion:

If there is both raw and processed data, but we don't have a processor which can support that raw data, accept the processed data as a NO_OP. However, samples should somehow note that there is also unprocessesable raw data.

**Comment by jaclyn-taroni** [comment]
Taking a look at the NB (first) set:

> GSE19274
Is not a SuperSeries but it is available on GEO, here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE19274

> GSE62564
We'd want to grab the processed data from this one because it is an RNA-seq experiment w/o raw data available in SRA.

> E-TABM-38 Oberthuer
We do not have a processor and I don't know that we will. It looks to be a chip that was specifically designed for the study of neuroblastoma. We'll have to see if it's even appropriate to combine it with genome-wide data (looks like it's 10k genes from the name?)

> GSE80154 Bradner
So I would be interested to see what would happen if we ran SCAN on this guy. It's an Affymetrix array with some extra controls it looks like. Let's add `A-GEOD-16043` to the whitelist, then.

**Comment by jaclyn-taroni** [comment]
Note Kurt's set corresponds to milestone 3 in #122

Breaking down the one's @Miserlou posted:

One-color Agilent data (no processor or immediate plans currently) but has raw data associated with it:

	E-GEOD-25220
	E-MTAB-5542
	E-GEOD-72246
	E-GEOD-78068


Two-color Agilent data (no processor, but may use `SCAN::SCAN_TwoColor` following milestone 2 in #122) but has raw data associated with it:

	SERIES (ignore quick design notes those are for me)
	E-GEOD-24287 <- disease v. control reference design 
	E-GEOD-78193 <- loop design
	E-GEOD-24060 <- cell line ref design
	E-GEOD-65405 <- UHR ref
	E-GEOD-32413 <- UHR ref

	SUPERSERIES:
	E-GEOD-76886


Standard Affymetrix chip with some custom element (looks to me like they used BrainArray in processing?), should be able to SCAN the raw files:

	E-GEOD-45923
	E-GEOD-32591
	E-GEOD-26975
	E-GEOD-82140
	E-GEOD-75890
	E-GEOD-81292

Older Affymetrix chip, should apply SCAN:
	
	E-MEXP-32


Custom and/or unfamiliar Affymetrix chip with raw data (not sure if SCAN will work, try it):

	E-GEOD-58795
	E-GEOD-45291

Not one of the "big 3" manufacturers but of sufficient scientific interest, take processed:

	E-GEOD-35455
	E-MEXP-3390
	E-GEOD-8350


Illumina, no raw data on ArrayExpress: 
	E-GEOD-48149

No thank you :) after I've taken a closer look at the design:

	E-GEOD-41744
	E-MTAB-2073 <- includes mixtures, dye swap??


> E-GEOD-76809

☝️ SuperSeries, we probably want to get this from GEO (so, post GEO surveyor) but some of it's SubSeries are listed above -- good case for deciding what to do if a user supplies the SuperSeries and some of the SubSeries accession numbers


----

As a result, let's add `A-GEOD-11670`, `A-GEOD-14663`, `A-GEOD-17692`, `A-GEOD-10379`, `A-GEOD-18991`, `A-AFFY-9`, `A-GEOD-13158` to the whitelist in #137

**Comment by jaclyn-taroni** [comment]
Replaced by #227 for Keytar Kurt
