### ISSUE TITLE
[Idea] Sort By Match

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#1136]
All of the ordering filters are based on the number of results rather than the match of the input search string. It should be easy to give `Match` as an additional option in the dropdown.

Related: https://github.com/AlexsLemonade/refinebio/issues/1078

**Comment by Miserlou** [comment]
@arielsvn does this make sense to you?

**Comment by arielsvn** [comment]
Yes, I like the idea! Depending on how relevant are the results we could make it the default sort option as well.

**Comment by arielsvn** [comment]
The remaining changes of this can be done in the FE with https://github.com/AlexsLemonade/refinebio-frontend/issues/573. Closing this.
