### ISSUE TITLE
Migrate off of Waffle

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1139]
### Context

https://waffle.io/closing-its-doors

### Problem or idea

We should probably just migrate to Github Projects?

### Solution or next step

There's a big Migrate Now button on https://waffle.io/AlexsLemonade/CCDL that we can probably just follow.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
I'm also evaluating blossom.co and sprint.ly. I did set up a github projects for refine.bio this weekend as well. I'll give them a spin before choosing.

**Comment by cgreene** [comment]
GitHub Projects isn't ideal because it requires an additional step for each issue to add it to the project. ZenHub automatically imports issues, and looks to be a lower friction option.

**Comment by cgreene** [comment]
We now have a zenhub board for refine.bio:
https://app.zenhub.com/workspaces/refinebio-5c92300a9d1bd30b8d3101f2/board
