### ISSUE TITLE
Samples that belong to multiple experiments counted several times in search filters

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1145]
### Context

https://github.com/AlexsLemonade/refinebio/pull/1124 Added sample counts to the filters.

### Problem or idea

Each experiment has a cached value `num_processed_samples`, for each filter value these values were added on Elastic Search. The problem is that some samples might belong to multiple experiments, and because of this, they are being counted several times in the filters.

![image](https://user-images.githubusercontent.com/1882507/54555357-ec498100-498c-11e9-9269-2f31a3ba1963.png)

### Solution or next step

I'm not sure how we could be able to calculate the number of samples accurately, and quickly. @Miserlou any ideas?

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Can you give an example search where the values are wrong, with what they should be?

**Comment by arielsvn** [comment]
Yes, that image I pasted above was from searching with an empty query. 

I'm not sure what the correct values should be, but these numbers seem a bit high. Do we have **539,210 microarray samples**?

**Comment by Miserlou** [comment]
From Kurt:

```
data_refinery=> select count(*), is_processed from samples where technology='MICROARRAY' group by is_processed;
 count  | is_processed 
--------+--------------
 337309 | f
 472020 | t
(2 rows)
```

**Comment by Miserlou** [comment]
If that's the bug, then I'm guessing the shortest path is to split num_processed_samples into num_microarray_processed_samples and num_rnaseq_processed_samples

**Comment by arielsvn** [comment]
hmm that might solve it for the technology filters, but the same happens for all other filter categories where at least one processed sample belongs to more than one experiment.

**Comment by arielsvn** [comment]
@dvenprasad I don't think there's a way to get the sample counts for each filter without reducing the speed of the search.

I remember we discussed once showing experiment counts instead, would that work?

**Comment by arielsvn** [comment]
We deployed #1416 with a fix for this, the estimates are not terrible I think:

![image](https://user-images.githubusercontent.com/1882507/62736291-01d24c80-b9fb-11e9-9dee-a637d330258a.png)

And here are the actual numbers of downloadable samples for each Technology:

```sql
data_refinery=> select count(*), technology 
data_refinery-> from samples inner join organisms on samples.organism_id = organisms.id
data_refinery-> where is_processed='t' and qn_target_id is not null group by technology;

 count  | technology 
--------+------------
 512569 | MICROARRAY
  94211 | RNA-SEQ
(2 rows)
```
