### ISSUE TITLE
Choose ProcessorPipeline based on platform type.

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#115]
Currently we only support the Affymetrix platform, but this is very implicit in the fact that https://github.com/data-refinery/data-refinery/blob/dev/common/data_refinery_common/job_lookup.py#L15 only has one processor for Gene Expression data, and we do not perform any logic based on the platform type for a sample.

We need to add logic into the Surveyor which will specify what ProcessorPipeline should be applied based off of the platform for each sample. If we do not have a processor for that platform, we should then download the submitter processed data and apply the NO_OP ProcessorPipeline to it.

**Comment by Miserlou** [comment]
[ae_platform_counts_sorted_with_names.pdf](https://github.com/data-refinery/data-refinery/files/1709001/ae_platform_counts_sorted_with_names.pdf)

**Comment by kurtwheeler** [comment]
We have created a heuristic for what should be done in different scenarios:

If the sample only has raw data available:
  - Download this raw data and process it
If the sample has both raw and derived data:
  - If the raw data is on a platform we support:
    -  Download the raw data and process it, abandon the derived data
  - If the raw data is not on a platform we support
     - Download the derived data and no-op it, abandon the raw data
- If the sample only has derived data:
  - Download the derived data and no-op it.

**Comment by kurtwheeler** [comment]
For the Neuroblastoma Milestone this will mean that for the following data sources we will want to do the following:

**Affymetrix**:
  - Download and process the raw data if available, otherwise download and no-op the derived data.

**Agilent 1-color, Illumin, RNA-seq, and Custom**:
  - Download the derived and no-op it

**The Target data**:
  - Will be a future concern, we can't handle this data yet.
