### ISSUE TITLE
Landing page / contact gathering

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#119]
We should quickly put together a landing page that will allow us to collect information from interested beta users. Ideally we could ask people if they are interested in API access or web access and then we could send notifications when we have each ready. Since we think the API will be ready sooner, this will let us tell the right people at the right time.

**Comment by kurtwheeler** [comment]
I created [an issue in the refinebio-design repo](https://github.com/AlexsLemonade/refinebio-design/issues/4) to get a design mocked up for this landing page. This issue can be for actually implementing/deploying that design.

**Comment by dvenprasad** [comment]
Copy for the Landing page:
Search and download from about <X> assays of harmonized publicly available transcriptome data from multiple organisms.
refine.bio has data from 
- cancer cell lines 
- tumor samples from adult and pediatric cancers. 
- relevant animal models

**Comment by cgreene** [comment]
```
refine.bio provides researchers with web-based access to gene expression data from:
* cancer cell lines
* tumor samples from adult and pediatric cancers.
* relevant animal models
```

**Comment by dvenprasad** [comment]
Mockups

Option 1:
![abstractmoleculelanding](https://user-images.githubusercontent.com/15315514/36617118-49eed4b4-18b4-11e8-85b1-991a7fd786c8.png)


Option 2:
![factorylanding](https://user-images.githubusercontent.com/15315514/36617125-527fff0e-18b4-11e8-99a3-8affd18313d3.png)

Option 3:
![cranelanding](https://user-images.githubusercontent.com/15315514/36617186-7c1ae0f4-18b4-11e8-9eee-c05b1dc78eff.png)


Mobile:
![mobile](https://user-images.githubusercontent.com/15315514/36617197-80e71530-18b4-11e8-8fa3-0202cc334ad3.png)


@ramenhog

**Comment by dvenprasad** [comment]
Links for landing page
Github: https://github.com/AlexsLemonade/refinebio
Twitter: https://twitter.com/CancerDataLab
Gitter: https://gitter.im/refinebio/

**Comment by dvenprasad** [comment]
For favicon:

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
