### ISSUE TITLE
Three letter search terms return zero results

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#1198]
### Context
Trying to search 'p53' or 'alk' 

### Problem or idea

Results for p53 exists. Searching for 'tp53' works but 'p53' doesn't. 
Three letter searches should work.

### Solution or next step
Tagging @miserlou @kurtwheeler for next steps

### New Issue Checklist

- [ ] The title is short and descriptive.
- [ ] You have explained the context that led you to write this issue.
- [ ] You have reported a problem or idea.
- [ ] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
PR'd. This may or may not have a significant impact on our ES performance, let's find out.

**Comment by Miserlou** [comment]
Sorted: https://www.refine.bio/search?q=p53
