### ISSUE TITLE
Organism filter is broken for QN target query

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#1224]
### Context

Working on creating a QN your own data example (https://github.com/AlexsLemonade/refinebio-examples/issues/26).

### Problem or idea

I used `https://api.refine.bio/qn_targets/?organism=DANIO_RERIO`. I thought it was returning multiple zebrafish targets created at different times (12 to be exact), but when I read in the latest QN target it had about 3000 more genes than I was expecting to see. It was actually the mouse target.

### Solution or next step

Return only QN target info for the specified organism. 

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Can you give me the filename which you said is problematic? I'm guessing that the one you took for latest might actually be one that was created a very long time ago.

**Comment by jaclyn-taroni** [comment]
The s3 url is `https://s3.amazonaws.com/data-refinery-s3-circleci-prod/lw4if2ermiymv6hflsh87ujk_1550696149_target.tsv` which was created at `"2019-02-20 23:30:25 UTC"`.

**Comment by jaclyn-taroni** [comment]
The platform accession for that says `mouse4302` as far as I can tell.

**Comment by Miserlou** [comment]
Ah, okay. Thank you!

**Comment by jaclyn-taroni** [comment]
Here's where I figured this out in case that's helpful: https://github.com/AlexsLemonade/refinebio-examples/blob/772d5699089a346a9b1e3f63ee0c86e9e3db0fe9/normalize-own-data/quantile_normalize_own_data.Rmd#L47

**Comment by Miserlou** [comment]
It's pretty simple actually, this feature simply isn't implemented. I'm implementing the filtering now, but where did you get the idea that this would work? Is there misdocumentation somewhere?

**Comment by jaclyn-taroni** [comment]
This is what I was after with https://github.com/AlexsLemonade/refinebio/issues/1094, which I understood to be resolved during an in-person meeting + `https://api.refine.bio/qn_targets/?organism=DANIO_RERIO` did not use to work at all.

**Comment by Miserlou** [comment]
This works now: https://api.refine.bio/qn_targets/?organism=DANIO_RERIO
