### ISSUE TITLE
SuperSeries samples with wrong platform labels

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/refinebio#1229]
### Context

I downloaded this [sample](https://api.refine.bio/v1/samples/?accession_codes=GSM1060464) in a set of other samples. We noticed it has a mouse platform instead of a human platform even though the sample is human. After checking the [GEO entry for this sample](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1060464) we can see that this platform is labeled incorrectly with the platform of the other dataset in the SuperSeries. 
Here is the [API entry for sample](https://api.refine.bio/v1/samples/?accession_codes=GSM1060464)

### Problem or idea

I suspect this may have to do with how SuperSeries metadata labels are being handled. 
We should determine if this is a problem with other SuperSeries `refinebio_platform` labels. 

Another observation that may or may not be related to this is that this sample is also the only one of its set to be processed and it also has sample title that is different from the rest of it's dataset. The rest of the samples in it's set are called `SAMPLE 1`. Based on it's description GEO and [what's shown on refinebio](https://www.refine.bio/experiments/GSE43319/gadd45a-and-ing1-interaction-in-epigenetic-gene-regulation), to fit with the other samples in its dataset, GSM1060464 should be called `SAMPLE 6` but it is called `ING1b_rep2` instead. I don't know if this ties into the mislabeled platform but it's suspicious. 

### Solution or next step

@kurtwheeler @Miserlou investigate what's behind the mislabeling. 

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [ ] You have proposed a solution or next step.

**Comment by cansav09** [comment]
Here's another sample that is a part of a SuperSeries and mislabeled: https://api.refine.bio/samples/?accession_code=GSM1212437

The hybridization protocol says `Affymetrix GeneChip Human Gene 2.0 ST` but the platform says `Illumina Genome Analyzer II`. The [GEO page for this sample](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1212437) confirms it is an Affy GeneChip 2.0 ST.

**Comment by Miserlou** [comment]
Related:

https://github.com/AlexsLemonade/refinebio/issues/169
https://github.com/AlexsLemonade/refinebio/issues/94
https://github.com/AlexsLemonade/refinebio/issues/963
https://github.com/AlexsLemonade/refinebio/issues/210

**Comment by kurtwheeler** [comment]
I think this will also be addressed by #1566
