### ISSUE TITLE
Allow users to download RNA-seq experiments without quantile normalization when aggregating by experiment

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#1232]
### Context

This was spurred by thinking about what we teach in training and what additional refine.bio examples we'd like to put together (https://github.com/AlexsLemonade/refinebio-examples/issues/29). Also related: #512

There are specific tools for performing differential expression analysis in RNA-seq data. These generally expect unnormalized counts. Differential gene expression analysis is a popular use case.

### Problem or idea

When returning **individual RNA-seq experiments**, we can return data that is amenable to use with downstream differential gene expression workflows if it is possible to 'opt out' of quantile normalization. I think this "advanced option" belongs on the web UI, too, as it is relevant to a wide audience of potential users.

For instance:

1. The gene-level count-scale estimates we generate (e.g., `lengthScaledTPM.tsv`) are ["bias corrected counts without an offset"](https://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html#use-with-downstream-bioconductor-dge-packages) ([Love et al. _Importing transcript abundance datasets with tximport._](https://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html)) that can be used as count matrices for such as `limma-voom`. We would aggregate the `lengthScaledTPM` without performing the quantile normalization step.

2. From #512, could return for an individual experiment:
    > the tximport output (`countsFromAbundance = 'no'`) as serialized R object (`.RDS`) that can be used with DESeq2

    This is the ["original counts and offset"]((https://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html#use-with-downstream-bioconductor-dge-packages)) route ([Love et al. _Importing transcript abundance datasets with tximport._](https://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html)).

I suspect returning the first one will considerably easier to implement and is therefore the way to go, but it's worth documenting both options.

### Solution or next step

This requires backend, design, frontend, and science team input. Here's what I think are the minimum requirements for this ticket (assuming option 1 above):

~* Changes to the smasher - when aggregating by experiment and technology=RNA-SEQ, make the quantile normalization step optional. _Note that quantile normalization being optional via the API is probably something we will want to do in the future._~
* If this is an offering on the web UI, we need to design for it.
  * We need copy around this option, including a warning about the limitations in comparing datasets.
* We need an example (Tracked here: https://github.com/AlexsLemonade/refinebio-examples/issues/29).
* Update documentation to reflect this new option (Issue TBD).

We might want to split the first two points into individual tickets in the appropriate repositories, but I will leave that up to the folks that need to do the design and implementation for what they think is best.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
QN is already optional via API, it's all simply a matter of setting `quantile_normalize` to true or false as desired when creating a Dataset object. There is no interface for this currently though.

**Comment by jaclyn-taroni** [comment]
Based on last week's standups, I believe this is in design.
