### ISSUE TITLE
Improve and/or automate ability to tune number of DL jobs per node

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1244]
### Context

https://github.com/AlexsLemonade/refinebio/blob/0f391e7a70e920f4349dba39f17820938f427a2c/foreman/data_refinery_foreman/foreman/main.py#L53

This number controls how many downloader jobs the Foreman will put in the queue based on how many nodes are available. If this number is too high then we'll have a lot of downloader failures because we'll overload SRA. If this number is too low then our inbound bandwidth will be too low and we won't properly utilize our resources.

The other issue here is that if we're downloading too much data for too long and SRA is able to keep up with us then we can fill up our disks. If we fill up our disks a lot of stuff stops working so we really want to avoid this.

### Problem or idea

@Miserlou and I discussed a solution which would address both of these problems today.

The idea is to take that one constant and split it into two environment variables, a high value (MAX_DL_JOBS_HIGH) and a low value (MAX_DL_JOBS_LOW). 

The higher value will be used when we want to increase our total disk usage and the lower value will be used to decrease our total disk usage. Initial values could be 25 for high and 10 for low, because today we saw that 25 jobs per node was causing our overall disk usage to rise.

We would like to base which value to use on the total disk usage of all active volumes. If this percentage rises above 60% then we should seek to decrease disk usage by using MAX_DL_JOBS_LOW and if the percentage dips below 30% then we should seek to pad our disks some by using MAX_DL_JOBS_HIGH. Ideally our disk usage will end up oscillating between these two values.

The values of 60% and 30% were just made up by me and should instead be environment variables so that we can also tune these. 

### Solution or next step

These four environment variables should read from an S3 file so we can tweak/tune them without redeploying, if not in S3 then we can get them from the normal way we do env vars, and also have a default value in code.

This change will also necessitate us being able to tell what our overall disk usage is. The way we propose to do this is to have each node run a cron job which will push disk usage to cloudwatch regularly. The Foreman can then pull these stats, filter out the nodes which are not currently active, and then aggregate them to get our total disk usage as a percentage. 

With some careful tuning of these four variables we will hopefully be able to get the disks reliably oscillating between 20% and 40% and then halve their sizes, thereby cutting some costs while also making our performance more steady.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
We now handle downloader jobs differently.
