### ISSUE TITLE
Microarray Accession List (April 2019 Update)

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#1250]
### Context

We last got accessions in #936. Some time has passed.

### Problem or idea

We should get more.

### Solution or next step

@cansav09 should re-run scripts to get new accessions. We should also subtract things that were already obtained in #936 

### New Issue Checklist

- [ ] The title is short and descriptive.
- [ ] You have explained the context that led you to write this issue.
- [ ] You have reported a problem or idea.
- [ ] You have proposed a solution or next step.

**Comment by cansav09** [comment]
@kurtwheeler What is the simplest way to obtain a list of all the experiment accession codes currently in refine.bio? 

If I have that list, I can easily make a new list that excludes whatever is currently in refine.bio or queued up to refine.bio.

**Comment by kurtwheeler** [comment]
Yes, the JSON from https://api.refine.bio/experiments/ will give you everything! We don't have any experiments with is_public=False

**Comment by kurtwheeler** [comment]
[experiment_accessions.txt](https://github.com/AlexsLemonade/refinebio/files/3086296/experiment_accessions.txt)

**Comment by cansav09** [comment]
Here's the list:
arrays_not_done_04-16-19.csv.zip

As we discussed in person, many of these are likely experiments that failed before they even really started processing. There are however, some of these that are brand new to GEO/Array Express
This list was obtained by using `AlexsLemonade/accession_retrieval` repo. (Note that I had to do a few minor error fixes that are not on the master branch just yet but are PRed). 
```r
Rscript experiment_accession_retrieval.R \
   -s https://raw.githubusercontent.com/AlexsLemonade/identifier-refinery/master/supported_microarray_platforms.csv
   -e experiment_accessions.txt
```
Where experiment accessions.txt is the file @kurtwheeler has put at the above comment. He got that file by running: 
```
import requests

url = 'https://api.refine.bio/experiments/'

with open('experiment_accessions.txt', 'w') as out:
    while url:
        parsed_response = requests.get(url=url).json()
        url = parsed_response['next']

        for experiment in parsed_response['results']:
            out.write(experiment['accession_code']+'\n')
```

**Comment by kurtwheeler** [comment]
Ayyyy!!! Nice work @cansav09! I'll run these tomorrow once we've cleared out our Salmon backlog and reduced our volume count.

**Comment by jaclyn-taroni** [comment]
It looks like the list has been put together and now it's time to run them (this is in progress IIRC) so I've unassigned @cansav09 and assigned @kurtwheeler
