### ISSUE TITLE
Receive notification about datasets that fail to process

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1251]
### Context

Datasets almost never fail any more and when they do it tends to be for legitimate reasons. 

### Problem or idea

However if they ever don't we should know about them so we can:
  * Look into the issue
  * Fix it
  * Reach out to the user to let them know that we're looking into the issue and that we will get them their data!

### Solution or next step

When the foreman finds a smasher job that has failed three times it should notify us so we can look into it, probably via slack.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
Proposal: Notify means send to our slack channel. If the number becomes unsustainable that way we can come up with better automation.
