### ISSUE TITLE
Run new microarray samples + re-run failures

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#1252]
### Context

New array data has been uploaded since our last array processing run. #1250 involves updating these.

### Problem or idea

We should run the new microarray data + old samples that failed to process. Our infrastructure has gotten substantially better, so this may allow us to recover from past failures.

### Solution or next step

Once the list of accessions from #1250 is available, these should be queued. This should be run separately from the shepherding process to aid in debugging.

### New Issue Checklist

- [ ] The title is short and descriptive.
- [ ] You have explained the context that led you to write this issue.
- [ ] You have reported a problem or idea.
- [ ] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
@kurtwheeler meant to close by #1286
