### ISSUE TITLE
Generate New Compendia

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#1258]
### Context

We have enough data now to start generating compendia for many organisms.

### Problem or idea

Depends #1221 - once we get the updated array data we should generate compendia for the organisms with QN targets.

### Solution or next step

@Miserlou will use this as an opportunity to walk @kurtwheeler through compendia generation.

**Comment by kurtwheeler** [comment]
I was just able to rebuild the fish compendium! I should kick off compendia jobs for all organisms that meet the criteria for it right @cgreene ? Just making sure nothing has changed in the last few months.

**Comment by cgreene** [comment]
Let's kick this off for the top 3 or top 5 organisms or so to test our process. We will want to generate new compendia when we hit 1m samples to be distributed as the first compendia from the non-beta release.

**Comment by cgreene** [comment]
This is done! 🎊
