### ISSUE TITLE
Sharing Current Download Queue workflow

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#126]
When users add datasets to their download queue, they should be able to generate a link to share the list of datasets in their download queue. (Use Case 38, refer #97 ) 
 
Solution: Add a share button to the download queue window. 
Next step: Incorporate share button into the workflow.

**Comment by cgreene** [comment]
@dvenprasad : can you put the screenshots that you put into slack here & close this?

**Comment by dvenprasad** [comment]
![download-dataset-share-link](https://user-images.githubusercontent.com/15315514/39307797-c9e16eb8-4931-11e8-8eea-256666edbbd1.png)
![download-dataset-share-link-modal](https://user-images.githubusercontent.com/15315514/39307796-c9d6aa8c-4931-11e8-9119-d04d83828912.png)
![download-dataset-share-link-modal-copied](https://user-images.githubusercontent.com/15315514/39307794-c9cb3cec-4931-11e8-9e5a-75cbeaaaf9d8.png)
