### ISSUE TITLE
Use EFS

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#127]
### New Issue Checklist
- [x] The title is short and descriptive
- [X] The issue contains an:
  - [X] Idea (new feature, user story, etc)
  - [ ] Problem
- [X] You have explained the:
  - [x] Context
  - [x] Problem or idea
  - [X] Solution or next step
  
### Context

The Downloaders currently download data from our external sources, upload it to S3, where it is downloaded by the processors, then uploaded back into S3. These pushes and pulls from S3 take time.

### Problem or idea

Use EFS to mount onto the worker instances so S3 isn't needed until the very end. This also enables us to create separate Uploaders later whose job will just to upload the processed data to S3.

### Solution or next step

Mount EFS onto all worker instances and use it at the Docker mount point.

**Comment by Miserlou** [comment]
Fixed in https://github.com/AlexsLemonade/refinebio/pull/152

**Comment by Miserlou** [comment]
We
