### ISSUE TITLE
Advanced Download Options: Scope and Design

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#1285]
### Context

#1232 

### Problem or idea

Based on what is described in #1232, an `Advanced Download Options` should be added on the web UI. 
The options would be:
- [ ] Don't quantile normalize my data
 ~~Include counts and offsets~~ (Chatted briefly with @jaclyn-taroni and decided that this would not be in scope) 

Questions: 
- What would be the changes to the download folder structure?
- Are these options only applicable to RNA-seq data?
- Are there any warnings/wisdom we need to add when people choose these options? If so, what are they?

### Solution or next step

Tagging @jaclyn-taroni for input.

**Comment by jaclyn-taroni** [comment]
> What would be the changes to the download folder structure?

Because this will only be applicable to RNA-seq experiments when aggregating by experiment, I do not believe there need to be any changes to the download folder structure.

> Are these options only applicable to RNA-seq data?

For now, yes.

**Comment by jaclyn-taroni** [comment]
> Are there any warnings/wisdom we need to add when people choose these options? If so, what are they?

Main thing: If one does not quantile normalize the selected data, it is less comparable to other data you might get from refine.bio.

**Comment by jaclyn-taroni** [comment]
@dvenprasad will go through the low fi today and we can then meet to discuss

**Comment by dvenprasad** [comment]
Summary of Low-fi Review:
- Use `Quantile Normalization` instead of `Normalization`
- Include tool tip ? on `Skip QN` option which will link users to the docs (https://github.com/AlexsLemonade/refinebio-docs/issues/95)
- The option will be disabled if there are no RNA-seq samples or if the user chooses to aggregate by species.
- Add indications of whether or not experiment/sample will be normalized on 'My dataset' page.
- Show these indications only on Experiment View and Species View. 
- Change warning copy to ```Skipping quantile normalization will make your dataset less comparable to other refine.bio data```
- Add whether or not QN was skipped in aggregated_metadata.json file in the dataset download.  (#1288)

Low-Fi Sketches:
![download-page-options1](https://user-images.githubusercontent.com/15315514/56984990-57be6b00-6b55-11e9-884f-6b0e5727bbde.jpg)

![download-options-exapanded-opt1](https://user-images.githubusercontent.com/15315514/56984997-5bea8880-6b55-11e9-895f-f45a0742741e.jpg)

![download-page-options2](https://user-images.githubusercontent.com/15315514/56985003-5ee57900-6b55-11e9-82d5-ed536b118da7.jpg)

![download-options-selected](https://user-images.githubusercontent.com/15315514/56985015-63aa2d00-6b55-11e9-87a6-50d4beb2936c.jpg)

![dataset-ready-page](https://user-images.githubusercontent.com/15315514/56985023-673db400-6b55-11e9-90d9-9f8901962f95.jpg)

![non-normalized-samples-species-view](https://user-images.githubusercontent.com/15315514/56985027-6a38a480-6b55-11e9-875c-eeed8c950477.jpg)

**Comment by dvenprasad** [comment]
Summary of High-fi Review: 
- Rework placement of `Advanced Options` button
- Refer to download items in terms of samples. i.e `Skip Quantile Normalization for RNA-seq Samples` 

Below are the mockups with the above feedback incorporated:
![download-dataset-advanced-options](https://user-images.githubusercontent.com/15315514/57308111-be8ed780-70b3-11e9-811f-6b9d393340a4.png)

![download-dataset-advanced-options-expanded](https://user-images.githubusercontent.com/15315514/57308126-c484b880-70b3-11e9-869e-3ffdabc2726a.png)

![download-dataset-advanced-options-expanded-selected-species](https://user-images.githubusercontent.com/15315514/57308133-c8183f80-70b3-11e9-8032-ac514440bc35.png)

![download-dataset-advanced-options-expanded-selected -experiment](https://user-images.githubusercontent.com/15315514/57308143-cbabc680-70b3-11e9-886d-860ba967e506.png)

![download-dataset-processing-qn-skipped-species](https://user-images.githubusercontent.com/15315514/57308149-cf3f4d80-70b3-11e9-920f-e289f05ac780.png)

![download-dataset-processing-qn-skipped-experiment](https://user-images.githubusercontent.com/15315514/57308162-d36b6b00-70b3-11e9-879f-d8139f717912.png)


Invision: 
https://invis.io/9SNAJ70ME4D#/361214008_download-Dataset-Advanced-Options
https://invis.io/9SNAJ70ME4D#/361214007_download-Dataset-Advanced-Options-Expanded
https://invis.io/9SNAJ70ME4D#/361214006_download-Dataset-Advanced-Options-Expanded-Selected-Species
https://invis.io/9SNAJ70ME4D#/361214005_download-Dataset-Advanced-Options-Expanded-Selected_-experiment
https://invis.io/9SNAJ70ME4D#/361214004_download-Dataset-Processing-Qn-Skipped-Species
https://invis.io/9SNAJ70ME4D#/361214003_download-Dataset-Processing-Qn-Skipped-Experiment

Style Guide for QN badge:

![Screen Shot 2019-05-07 at 10 39 34 AM](https://user-images.githubusercontent.com/15315514/57308495-71f7cc00-70b4-11e9-80cd-a8a45bec3d3a.png)

![Screen Shot 2019-05-07 at 10 39 46 AM](https://user-images.githubusercontent.com/15315514/57308551-92c02180-70b4-11e9-9de1-c48edf7383e5.png)
