### ISSUE TITLE
Create Continuous Deployment Infrastucture and Release Scripts

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#130]
We need to create a system whereby a tagged git commits on `master` and `dev` branches correspond to a triggered deployment to `production` and `dev` environments on AWS.

This will necessitate the creation of the following components:

* A `RefineBioContinuousDeployment` robot user for AWS, Dockerhub and `git-crypt`.
* `refinebio-tfstate` (or similarly named) private S3 buckets
* Installation of Terraform binaries to our CircleCI environment

So, whenever a release with a tag is received by Circle, the release process will be:
 * Run the test suite 
 * When tests pass, build new Docker images for the Surveyors and Workers
 * Push the new Docker images to Dockerhub as new versions (with branch info) 
 * Set new Dockerhub versions to a local environment variable or file
 * Download the appropriate TF state file from private S3 bucket
 * Decrypt the TF state file
 * `terraform plan; terraform apply`
 * Encrypt new TF state file
 * Reupload encrypted TF state file to private S3 bucket
 * Party! 🍺

I think that's all that needs to happen, but there may be an issue with Nomad that I'm not aware of as well.

**Comment by Miserlou** [comment]
Can we get a status report on this issue?

I think we're actually ready to run some big jobs and the only blocker is are the prod-ready Docker images!

**Comment by dongbohu** [comment]
I have done a lot of tests on my own repo. Docker image updating and git-crypt parts are done. I am now working on the uploading/downloading tf state files from the private S3 bucket. Once that is done, I will change circleci config to glue everything together and test the refinebio repo. 

My plan is to file a pull request by the end of this week.

**Comment by dongbohu** [comment]
@Miserlou Do you think it makes more sense to trigger the deployment with any commit on `dev` or `master`, no matter the commit has a tag or not?

**Comment by dongbohu** [comment]
@kurtwheeler or @Miserlou: I don't have permission to create a new aws user `RefineBioContinuousDeployment`. Right now I am using an aws key pair of my own account for testing. Can one of you create that user and give me access, or give me the user creation privilege? Thanks.

**Comment by dongbohu** [comment]
According to CircleCI documentation:
https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
It seems impossible to set a deployment based on a tagged commit in a certain branch, because `tag` and `branch` are independent from each other. I have the following proposal to trigger "build" and "deploy" jobs:

`build` job will be triggered by:
-  any branch commit, or:
- tag commits whose names start with letter "v" (for release version purpose, such as "v1.23").

`deploy` will be triggered ONLY by tag commits whose name start with letter "v".

Does this make sense to you?
