### ISSUE TITLE
Parse Salmon Output Into Filterable Information

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#131]
Salmon provides multiple types of output which we want to parse into searchable and filterable information.

The first is inside of a `quant.sf` file, which shows gene expression amounts for many common genes. There are thousands values per sample, so we may want to try to make this into a bitmap in our database's Gene representation in order to keep our database as small and fast as possible. (PG may do this automatically under the hood?)

Additionally, there are two JSON files, `lib_format_counts.json` and `aux_info/meta_info.json` which contain some key-pairs which we will want to expose to an end user. We are specifically interested in exposing `compatible_fragment_ratio`, `strand_mapping_bias` from `lib_format_counts.json` and `percent_mapped`, `library_types` from `aux_info/meta_info.json`, but I think we might as well just get everything we can. There is also an `unmapped_names.txt` file but this might not be worth parsing.

Finally, there may be to-be-determined quality control information called from running another command. This will land in a future version of Salmon.

**Comment by Miserlou** [comment]
Related: https://github.com/data-refinery/data-refinery/issues/113

**Comment by Miserlou** [comment]
Apparently related: #83

**Comment by jaclyn-taroni** [comment]
In order to represent which _genes_ are measured in a sample (rather than which _transcripts_, the output of salmon), we will need to summarize the quantifications to the gene-level with tximport (#82)

**Comment by jaclyn-taroni** [comment]
I agree that `unmapped_names.txt` will not need to be parsed such that it is searchable and filterable.

**Comment by Miserlou** [comment]
@jaclyn-taroni - The `tximport` section is actually stubbed out in the code here: https://github.com/AlexsLemonade/refinebio/blob/miserlou/db-refactor/workers/data_refinery_workers/processors/salmon.py#L290

but I don't know what options we want to run it with or how, or what the output will be and how to read/parse/represent it.

**Comment by jaclyn-taroni** [comment]
The parsing of the JSON files should be handled by MultiQC #205

**Comment by jaclyn-taroni** [comment]
As mentioned MultiQC (#205) will report the fields from the JSON file once the upstream ticket (https://github.com/ewels/MultiQC/issues/733) has been closed. In the future we may want to additionally store things like the mapping rate as a way to “route” or exclude samples. The gene representation bit should be tracked on #113 and is dependent on tximport (#82) as stated above.
