### ISSUE TITLE
Fall back to downloading from ENA when SRA provides corrupted data

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1313]
### Context

https://github.com/ncbi/sra-tools/issues/204

Quick summary of that: for certain accessions SRA's data is corrupted in a way that causes salmon to hang forever.

### Problem or idea

When we encounter one of these we should do the following:
1. Detect it by putting a timeout on salmon. I propose 3 hours, although that may be too long. A better timeout may be determined by looking at the maximum run time for a successful salmon job.
2. Survey ENA to create OriginalFiles that have `source_urls` pointing to the files in ENA.
3. Create a new downloader job with those OriginalFiles associated.
4. Mark the salmon job as a failure, set `no_retry` to true so it doesn't get rerun, and set a failure_reason which provides good context as to what happened.

### Solution or next step

Implement the above solution. Note that it's been a long time since we've run our code to download from ENA and it may have rotted to some degree. I think the last time we tried switching back there was something broken, but we were just looking for a way to download data while SRA was down so we didn't diagnose what had broken. There may be some work to fix that code as well.

Additionally we should verify that the download job recreation code can handle jobs whose data came from ENA. I think including a unit or end-to-end test for this would be a good idea.

**Comment by cgreene** [comment]
Pretty sure @kurtwheeler's changes that check ENA FTP and then decide where to download from have already addressed this.
