### ISSUE TITLE
GSE56035: refinebio_age isn't quite right

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#1332]
### Context
The harmonization on some metadata isn't correct due to the weirdness of how the metadata was written.

### Problem or idea
For GSE56035, there are two columns `age` and `age (yrs)`. refinebio_age is populated only with the values in `age` so it looks like there is a lot of missing data when that exists in another column `age (yrs)` 

### Solution or next step

Tracking this here so that when we use the MetaSRA annotations we can check if this is fixed.

**Comment by wvauclain** [comment]
Technically this isn't fixed until we run the management command to refresh the metadata, but this sample will be fixed when that happens.
