### ISSUE TITLE
Syntax errors cause our tests to silently not run

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1348]
### Context

#1347 

### Problem or idea

If we have a syntax error in our code then our test runner fails silently instead of failing the tests. This is because we use tags, and if we say to only run tags the test runner for some reason doesn't even consider syntax errors a problem.

### Solution or next step

Maybe there's a way to tell the python unit test runner to fail if there's syntax errors. If not then we need to check to make sure that the test output never says "ran 0 tests".

**Comment by wvauclain** [comment]
Apparently the Django devs are aware of this issue but can't fix it because it's a problem with python itself (https://code.djangoproject.com/ticket/29127). No one recommended a fix in the issue.

One possible fix would be to add a linting test to our PRs, which could fail on syntax errors.
