### ISSUE TITLE
Nomad version's API returns wrong number of jobs

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1352]
![image](https://user-images.githubusercontent.com/1882507/60186865-39da5300-97f2-11e9-83f6-7ca0762b2ebd.png)

**Comment by arielsvn** [comment]
These are being reported directly from nomad's service.

https://github.com/AlexsLemonade/refinebio/blob/dev/common/data_refinery_common/utils.py#L91-L94

The problem seems to appear when jobs are started and terminated shortly after. We checked and the totals are correct when things are running correctly.

**Comment by arielsvn** [comment]
Seems that this is happening now, and we're not running. I'll try to call the service to see what's being returned:

https://github.com/AlexsLemonade/refinebio/blob/dev/common/data_refinery_common/utils.py#L91-L94

**Comment by cgreene** [comment]
Happening now as we are running. I wonder if it's just a sporadic issue with what nomad is returning to the dashboard. That will make it very hard to track down. Screenshots + the current JSON response. The dashboard is showing the stats from the API.
![Screenshot_20190901-094828](https://user-images.githubusercontent.com/542643/64077442-a401ef00-cc9e-11e9-802c-e37faa84961f.png)
![Screenshot_20190901-094841](https://user-images.githubusercontent.com/542643/64077443-a401ef00-cc9e-11e9-9908-31a1a9e7c762.png)
![Screenshot_20190901-094851](https://user-images.githubusercontent.com/542643/64077444-a401ef00-cc9e-11e9-8d91-f89ebc3d7993.png)

JSON here:
https://gist.github.com/cgreene/be5324c58c1e9ec6affdf8ae00cf8445#file-api-refine-bio-negjobs-dashboard-json

**Comment by arielsvn** [comment]
Also Nomad's service response here https://pastebin.com/56RMfMDc

**Comment by arielsvn** [comment]
Closing this as it seems to be an issue with Nomad version `v0.8.3`.
