### ISSUE TITLE
Missing Study PRJEB21766

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#1354]
### Context

We had a request come in via the Data Request form.

### Problem or idea

We should look into why https://www.ebi.ac.uk/ena/data/view/PRJEB21766 wasn't processed and see if we can do what we can to make it go.

### Solution or next step

At this point, I think the next step is for @kurtwheeler to look into this, but we may want to teach more folks how to do this so we can start to dig into individual processing failures.

After this is resolved, search the slack for ERP024052 and send an email to the person listed on the request letting them know the experiment is available.

**Comment by kurtwheeler** [comment]
Looks like we just haven't gotten to this experiment yet. It hadn't even been surveyed yet. It's probably somewhere in the list of mouse experiments we've been working our way through. I've queued this experiment up and it should be running today. I'll update here with how that goes.

**Comment by jaclyn-taroni** [comment]
https://www.refine.bio/experiments/ERP024052/rna-seq-of-neuroblastoma-th-mycn-mouse-model-samples-sensitive-to-chemotherapy-and-those-with-chemotherapy-resistance

The researcher that requested the experiment has been notified.
