### ISSUE TITLE
Many tests are failing (eUtils)

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#1390]
### Context

All of our salmon tests are currently failing with an `eutils` issue.

### Problem or idea

```
2019-07-15 15:36:50,651 local [volume: 0] data_refinery_common.models.organism ERROR [text: <?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD esearch 20060628//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20060628/esearch.dtd">
<eSearchResult>
	<ERROR>Search Backend failed: Unable to open connection to #PMQuerySrv?dbaf=taxonomy</ERROR>
</eSearchResult>
]: Bad response from eUtils.
E2019-07-15 15:36:50,758 local [volume: 0] data_refinery_common.models.organism ERROR [text: <?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD esearch 20060628//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20060628/esearch.dtd">
<eSearchResult>
	<ERROR>Search Backend failed: Unable to open connection to #PMQuerySrv?dbaf=taxonomy</ERROR>
</eSearchResult>
]: Bad response from eUtils.
E2019-07-15 15:36:50,956 local [volume: 0] data_refinery_common.models.organism ERROR [text: <?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD esearch 20060628//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20060628/esearch.dtd">
<eSearchResult>
	<ERROR>Search Backend failed: Unable to open connection to #PMQuerySrv?dbaf=taxonomy</ERROR>
</eSearchResult>
]: Bad response from eUtils.
```

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by cgreene** [comment]
https://www.biostars.org/p/71735/

**Comment by cgreene** [comment]
I clicked "rerun" on one of our previously failed builds. We'll see if it has returned 🤞

**Comment by wvauclain** [comment]
It looks like the issues went away while I was debugging. eUtils must have gone down.

**Comment by cgreene** [comment]
Still seems to be a problem. Biostars has this, if you want to send them a note:
> In the first instance the E-utilities help-desk (eutilities@ncbi.nlm.nih.gov) should be able to help you out with details of the service status.

**Comment by wvauclain** [comment]
I heard back from NLM Support, and they said, "I know the taxonomy group recently were doing some upgrades and fixes that might have resulted in temporary errors."
