### ISSUE TITLE
Some samples have a typo on the manufacturer field

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1399]
### Context

I was running some queries in the DB for #1391 

### Problem or idea

Noticed that some samples  have `AFFYMETRTIX` in the manufacturer field instead of `AFFYMETRIX`.

```
data_refinery=> select count(id), manufacturer from samples group by manufacturer;
 count  | manufacturer 
--------+--------------
  49906 | UNKNOWN
 532028 | ILLUMINA
   1351 | ION_TORRENT
  20858 | AFFYMETRTIX
    112 | NEXTSEQ
 607980 | AFFYMETRIX
(6 rows)
```

### Solution or next step

Not sure if it's better to fix this with a migration or a management command.

**Comment by cgreene** [comment]
Once we know where this is coming in from and we have a fix deployed, that seems like the right time to write a migration and fix the previously imported data as well.

**Comment by jaclyn-taroni** [comment]
NEXTSEQ is a type of Illumina machine while we’re at it. I’m fairly sure where this issue is coming from was fixed months ago, so we might want to fix this while we’re at it.

**Comment by wvauclain** [comment]
These lines might be causing the problem:

https://github.com/AlexsLemonade/refinebio/blob/bbb45aa44673382eb61ab8318308f68356b19780/workers/data_refinery_workers/processors/management/commands/correct_affy_samples.py#L130

https://github.com/AlexsLemonade/refinebio/blob/1b3e65574f9c4ecf6fc7eccb8ecd2ff7906cf214/workers/data_refinery_workers/downloaders/utils.py#L212

https://github.com/AlexsLemonade/refinebio/blob/da9300e33eac74601c1958dad05d029abb78a805/foreman/data_refinery_foreman/surveyor/geo.py#L378

**Comment by wvauclain** [comment]
It looks like the NEXTSEQ issue was fixed in this commit, but I should also add it to the migration: https://github.com/AlexsLemonade/refinebio/commit/6a081be926c1fba85de3c68655a57e378acf6771

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio/pull/1463 Should have fixed the samples that are mislabeled, is there a way to check if the migration ran correctly? @kurtwheeler 

Seems that we now have more samples labeled with the typo than when the issue was created:

```sql
data_refinery=> select count(id), manufacturer from samples group by manufacturer;
 count  | manufacturer 
--------+--------------
 595038 | ILLUMINA
  49789 | UNKNOWN
   1911 | ION_TORRENT
  97500 | AFFYMETRTIX
    112 | NEXTSEQ
 531810 | AFFYMETRIX
(6 rows)
```

**Comment by kurtwheeler** [comment]
Hmm... that's really weird! I don't actually really know how to check the output of a migration, the database has a record of it running and presumably a migration that fails would stop things:
```
AFFYMETRTIX
```43 | data_refinery_common | 0026_fix_typo_in_sample_manufacturer     | 2019-08-08 19:45:10.584936+00
```

**Comment by kurtwheeler** [comment]
```
data_refinery=> select count(id), manufacturer from samples group by manufacturer;
 count  | manufacturer 
--------+--------------
 605510 | ILLUMINA
  50013 | UNKNOWN
   2284 | ION_TORRENT
 629310 | AFFYMETRIX
(4 rows)
```
