### ISSUE TITLE
Allow hotfix deploys on `dev`

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1404]
### Context

We deploy prod when a new tag is created that ends in `-hotfix`

### Problem or idea

Even if the tag is created on `dev`, it will always deploy to production. I think we should make it so that creating the tag on `dev` deploys to staging. Just like all other tags. With the advantage would be that in both cases the tests aren't run before the deploy.

### Solution or next step

Removing these two lines should do the work:

https://github.com/AlexsLemonade/refinebio/blob/dev/.circleci/remote_deploy.sh#L74-L75

**Comment by wvauclain** [comment]
You also probably need to remove these lines:

https://github.com/AlexsLemonade/refinebio/blob/bbb45aa44673382eb61ab8318308f68356b19780/.circleci/update_docker_img.sh#L10-L11
