### ISSUE TITLE
Make gene annotation (BrainArray, possibly Ensembl genome version) less human-specific

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#141]
### New Issue Checklist
- [x] The title is short and descriptive
- [ ] The issue contains an:
  - [ ] Idea (new feature, user story, etc)
  - [x] Problem
- [ ] You have explained the:
  - [x] Context
  - [x] Problem or idea
  - [x] Solution or next step
  
### Context

While @Miserlou and I were taking a look at #137, we discovered that some species (e.g., human) information was hard-coded. 

#### Microarray
When we get Affymetrix data from ArrayExpress and process it AND it is BrainArray supported (see also #64), we'll need to use the organism information (e.g., the first letter of the genus and first letter of the species) to specify which BrainArray package to use. Referenced here: https://github.com/data-refinery/data-refinery/pull/137/files#diff-f935c7992de9ff4aedc8bccb3910ab18R66 We'll also need to change the other part of the string, `entrezgprobe` will need to be changed to something that reflects that ENSG  are being used (see #85; this is also noted in that diff).

#### RNA-seq
Here, for Ensembl builds
https://github.com/data-refinery/data-refinery/blob/988885e5dce3b79df04294a969ae1971a82d99df/foreman/data_refinery_foreman/surveyor/transcriptome_index.py#L50

assembly version 37 is specified. It is unclear to me what this corresponds to and if it is specific to human -- will require more investigation. If it was the version of _Ensembl_ I would expect it to be version 91 (the current version).

### Solution or next step

@kurtwheeler -- let's look into what that assembly version 37 is. We should also consider putting together a timeline for #85 because I will need to provide a new PCL file for testing and presumably some guidance on the package & string to use.

**Comment by jaclyn-taroni** [comment]
It may be the case that there is a species that _is_ supported by BrainArray, but a particular chip is not, e.g., a human Affymetrix chip that SCAN will process successfully but there's no corresponding BrainArray. Not sure how often that will be true.

**Comment by jaclyn-taroni** [comment]
Based on a conversation with @kurtwheeler yesterday -- we're thinking assembly version 37 may be specific to Ensembl Plants. @kurtwheeler suggested a strategy where we make a table that contains the current versions for each of the Ensembl divisions.

**Comment by kurtwheeler** [comment]
Ok, turns out this code isn't overly specific, just under documented. All divisions other than the "main division" are in lock-step version-wise and were at version 37 when I wrote that. You can see that for the "main division" I specified a different version [here](https://github.com/AlexsLemonade/refinebio/blob/dev/foreman/data_refinery_foreman/surveyor/transcriptome_index.py#L118).

I have created a PR which breaks these versions out into constants and also documents things better [here](https://github.com/AlexsLemonade/refinebio/pull/162)!

**Comment by kurtwheeler** [comment]
So this issue was addressed by #162. However it should be noted that #163 is related to it.

**Comment by jaclyn-taroni** [comment]
The _RNA-seq_ bit was resolved by #162, but the the _microarray_ bit (which is related to #85) has not yet been resolved

**Comment by dongbohu** [comment]
The microarray bit is fixed in PR #180.
