### ISSUE TITLE
Salmon processor jobs failing for Nomad reasons

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#1410]
### Context

I was checking on some of the dead salmon jobs to see why they died.

### Problem or idea

```
ubuntu@ip-10-0-205-197:~$ nomad status 51410cd7
ID                  = 51410cd7
Eval ID             = 8f4b1cb7
Name                = SALMON_4_32768/dispatch-1563888675-330fad7b.jobs[0]
Node ID             = 76758d96
Job ID              = SALMON_4_32768/dispatch-1563888675-330fad7b
Job Version         = 0
Client Status       = failed
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created             = 13m9s ago
Modified            = 8m1s ago

Task "salmon" is "dead"
Task Resources
CPU       Memory  Disk    IOPS  Addresses
1024 MHz  32 GiB  10 MiB  0

Task Events:
Started At     = N/A
Finished At    = 2019-07-23T16:18:41Z
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type            Description
2019-07-23T16:18:41Z  Not Restarting  Policy allows no restarts
2019-07-23T16:18:41Z  Driver Failure  failed to start task "salmon" for alloc "51410cd7-1165-aa01-ee6e-cbf38b46d249": Failed to start container e1d625cfda84735be12b5cd7ea8a4c0b30e2262e026dc45e8e8c3c17bb419ac9: Post http://unix.sock/containers/e1d625cfda84735be12b5cd7ea8a4c0b30e2262e026dc45e8e8c3c17bb419ac9/start: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2019-07-23T16:13:39Z  Task Setup      Building Task Directory
2019-07-23T16:13:39Z  Received        Task received by client
```

### Solution or next step

We need to figure out what this error means

**Comment by wvauclain** [comment]
It's worth noting that this could be killing us on processor jobs failing, since there are a lot of jobs dead for this reason

**Comment by wvauclain** [comment]
Someone on Nomad's issues page had a similar issue: https://github.com/hashicorp/nomad/issues/2835, but their actual problem was that the issue crashed Nomad for them. They don't say why Docker timed out in the first place.

**Comment by davidsmejia** [comment]
There seems to be a timeout during allocation in the docker driver. Which you probably knew already...

I can't really make out if the timeout applies to just pulling the image or all http requests during alloc.

I would suggest checking the output of ```nomad alloc logs <alloc-id> <task>``` [ref](https://github.com/hashicorp/nomad/blob/v0.8.3/command/alloc.go#L26) (other available flags [here](https://github.com/hashicorp/nomad/blob/v0.8.3/command/alloc_logs.go)) to see if more information is available.

Below are relevant links and code snippets:

https://github.com/hashicorp/nomad/blob/v0.8.3/client/driver/docker.go#L66
```golang
	// recoverableErrTimeouts returns a recoverable error if the error was due
	// to timeouts
	recoverableErrTimeouts = func(err error) error {
		r := false
		if strings.Contains(err.Error(), "Client.Timeout exceeded while awaiting headers") ||
			strings.Contains(err.Error(), "EOF") {
			r = true
		}
		return structs.NewRecoverableError(err, r)
	}
```

https://github.com/hashicorp/nomad/blob/v0.8.3/client/driver/docker.go#L111
```golang
	// dockerTimeout is the length of time a request can be outstanding before
	// it is timed out.
	dockerTimeout = 5 * time.Minute
```

https://github.com/fsouza/go-dockerclient/blob/cb91b9d898e126e9c5efb61491d90f39c0e03391/client.go#L165

https://github.com/fsouza/go-dockerclient/blob/cb91b9d898e126e9c5efb61491d90f39c0e03391/client.go#L355
```golang
// SetTimeout takes a timeout and applies it to the HTTPClient. It should not
// be called concurrently with any other Client methods.
func (c *Client) SetTimeout(t time.Duration) {
	if c.HTTPClient != nil {
		c.HTTPClient.Timeout = t
	}
}
```

**Comment by wvauclain** [comment]
It looks like `nomad alloc logs` doesn't give us any information, since the issue was during the allocation's startup rather than during execution.

**Comment by davidsmejia** [comment]
I see it looks like there should be [debug] logs available though I'm unsure if there is a way to get them with the CLI tools. 

Is there a way to determine if it gets this far?
https://github.com/hashicorp/nomad/blob/v0.8.3/client/driver/docker.go#L1095

**Comment by davidsmejia** [comment]
Or here: 
https://github.com/hashicorp/nomad/blob/v0.8.3/client/driver/docker.go#L1088

I mean it ought to be since thats the error thats getting presented but I'm not sure how to go about inspecting that besides grepping the log file.

**Comment by wvauclain** [comment]
They might turn off debug logs in production releases, because I can't find a way to access Nomad's logs. `nomad alloc logs` shows STDOUT and STDERR for that alloc.

**Comment by davidsmejia** [comment]
Are you seeing the output from STDERR?

```nomad alloc logs -stderr <alloc-id>```

**Comment by wvauclain** [comment]
No, `nomad alloc logs -stderr` still said that logs were not available because the job had not started yet.

**Comment by wvauclain** [comment]
This seems like a sporadic issue, because I was checking again this morning, and I could not find any allocations that failed to start from the Docker Driver, so it seems like we should just monitor this periodically. This is the script I used to check:
```sh
# Get all dead jobs
nomad status | grep dead | awk '{ print $1 }' > jobs.txt

# Get all allocation ids, which are 8-digit hex numbers in the first column
while read -r line; do nomad status "$line" | awk '{ print $1 }' | egrep -o "[0-9a-f]{8}"; done < jobs.txt > allocs.txt

# Look for any allocations that had a driver failure
while read -r line; do nomad status "$line"; done < allocs.txt 2>/dev/null | grep "Driver Failure"
```

If there were any errors, I would have expected to see lines like this:

```2019-07-23T16:18:41Z  Driver Failure  failed to start task "salmon" for alloc "51410cd7-1165-aa01-ee6e-cbf38b46d249": Failed to start container e1d625cfda84735be12b5cd7ea8a4c0b30e2262e026dc45e8e8c3c17bb419ac9: Post http://unix.sock/containers/e1d625cfda84735be12b5cd7ea8a4c0b30e2262e026dc45e8e8c3c17bb419ac9/start: net/http: request canceled (Client.Timeout exceeded while awaiting headers)```

I know the script works because you can see alloc statuses when you remove the last `grep` invocation, but it looks like there just weren't any recently that failed from a `Driver Error`.

**Comment by arielsvn** [comment]
Looked into this [processor job](https://api.refine.bio/v1/jobs/processor/?format=json&id=3068854) which is associated with sample [SRR6253492](https://www.refine.bio/samples/SRR6253492). Looks like it has a failure reason, so maybe nomad was able to execute it afterward?

> Shell call to salmon failed because: ### salmon (mapping-based) v0.13.1 ### [ program ] => salmon ### [ command ] => quant ### [ libType ] => { A } ### [ index ] => { /home/user/data_store/TRANSCRIPTOME_INDEX/HOMO_SAPIENS/short } ### [ mates1 ] => { /tmp/alpha } ### [ mates2 ] => { /tmp/beta } ### [ threads ] => { 16 } ### [ output ] => { /home/user/data_store/processor_job_3068854/SRR6253492_output/ } ### [ seqBias ] => { } ### [ dumpEq ] => { } ### [ writeUnmappedNames ] => { } Logs will be written to /home/user/data_store/processor_job_3068854/SRR6253492_output/logs [2019-07-23 16:32:02.138] [jointLog] [info] Fragment incompatibility prior below threshold. Incompatible fragments will be ignored. [2019-07-23 16:32:02.138] [jointLog] [warning] NOTE: It appears you are running salmon without the `--validateMappings` option. Mapping validation can generally improve both the sensitivity and specificity of mapping, with only a moderate increase in use of computational resources. Mapping validation is planned to become a default option (i.e. turned on by default) in the next release of salmon. Unless there is a specific reason to do this (e.g. testing on clean simulated data), `--validateMappings` is generally recommended. [2019-07-23 16:32:02.138] [jointLog] [info] parsing read library format [2019-07-23 16:32:02.138] [jointLog] [info] There is 1 library. [2019-07-23 16:32:02.177] [jointLog] [info] Loading Quasi index [2019-07-23 16:32:02.177] [jointLog] [info] Loading 32-bit quasi index [2019-07-23 16:32:02.177] [stderrLog] [info] Loading Suffix Array [2019-07-23 16:32:02.814] [stderrLog] [info] Loading Transcript Info [2019-07-23 16:32:03.001] [stderrLog] [info] Loading Rank-Select Bit Array [2019-07-23 16:32:03.070] [stderrLog] [info] There were 189440 set bits in the bit array [2019-07-23 16:32:03.115] [stderrLog] [info] Computing transcript lengths [2019-07-23 16:32:03.115] [stderrLog] [info] Waiting to finish loading hash [2019-07-23 16:32:08.141] [stderrLog] [info] Done loading index [2019-07-23 16:32:08.141] [jointLog] [info] done [2019-07-23 16:32:08.141] [jointLog] [info] Index contained 189440 targets [2019-07-23 16:32:08.371] [jointLog] [warning] salmon was only able to assign 0 fragments to transcripts in the index, but the minimum number of required assigned fragments (--minAssignedFrags) was 10. This could be indicative of a mismatch between the reference and sample, or a very bad sample. You can change the --minAssignedFrags parameter to force salmon to quantify with fewer assigned fragments (must have at least 1).

**Comment by kurtwheeler** [comment]
Nomad is no more!
