### ISSUE TITLE
Consider Microarray Processor Whitelist & Blacklist

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#145]
### New Issue Checklist
- [x] The title is short and descriptive
- [x] The issue contains an:
  - [x] Idea (new feature, user story, etc)
  - [ ] Problem
- [x] You have explained the:
  - [x] Context
  - [x] Problem or idea
  - [x] Solution or next step
  
### Context

_Explain the conditions that led you to write this issue. If you are proposing a new feature, the context should be your user story. If this relates to a certain page or API endpoint, provide a link._

The current implementation (as of #137) of refinebio uses a whitelist for supported microarray platforms (related: #115). Specifically, we currently whitelist Affymetrix platforms that we consider appropriate for processing with SCAN. For "version Jackie," all experiments that are _not_ whitelisted/supported and have processed data associated with them are no-op'd.

### Problem or idea

_The context should lead to something, an idea or a problem that you’re facing._

In a future, broader version of refinebio, we may not want processed data from _all_ platforms. For example, we may not want to include data from platforms that are not genome-wide in version 1, e.g., miRNA chips or custom arrays designed to sample some subset of the transcriptome specific to a particular disease or condition.

Example of a miRNA experiment that is labeled "transcription profiling by array": https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-5318/

In the above example, even if we were to only process experiments of the type "transcription profiling by array," this experiment would be included. 

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

Consider a system along the following lines:

- **Whitelist**: These are platforms that we process when raw data is available, take processed data (NO-OP) if raw data is unavailable
- **NO-OP list**: These are platforms that meet certain criteria (e.g., are genome-wide, etc.) and if they have processed data associated with them, we believe we should include them in refinebio as we're likely to be able to integrate them with the data we've processed from raw.
- **Blacklist**: These platforms are not appropriate for comparison with most other refinebio data (or some other reason), don't NO-OP the processed data

**Comment by Miserlou** [comment]
What's the difference between the whitelist and NO-OP list in this scenario? I'd prefer to maintain the minimum number of lists if possible, and those seem the same to me.

Are there _any_ scenarios where we want to serve blacklisted data? If not, then though we'll need to codify the blacklist during surveying, we won't need any design changes other than the already planned, _made-by-CCDL-green-thumbs-up_ and _made-by-submitter-use-at-your-own-risk_ labeling.

**Comment by jaclyn-taroni** [comment]
> What's the difference between the whitelist and NO-OP list in this scenario? I'd prefer to maintain the minimum number of lists if possible, and those seem the same to me.

Ah, sorry that was not more clear. 
Whitelist platforms - can process raw data
NO-OP platform - no processor for raw data (currently) available

> Are there _any_ scenarios where we want to serve blacklisted data? 

I can not think of a specific example _at the moment_. But here's some future examples I can think of:
- We now are interested in building a compendium of non-coding RNA and now want to include non-coding arrays (e.g., the miRNA example above)
- There was a set of platforms where we didn't know how to aggregate/harmonize them with the rest of the compendium, but we've since come up with a strategy to do so and now we could use the submitter-processed data from those platforms. 

I suppose there are two ways to approach these cases (that I can think of): 1) NO-OP the submitter-processed data "now" (with the planned _made-by-submitter_ tag) , but don't include/harmonize it if a user wants a harmonized set of "all the data" or 2) don't NO-OP the submitter-processed data until we have a need/strategy

**Comment by cgreene** [comment]
> NO-OP the submitter-processed data "now" (with the planned made-by-submitter tag) , but don't include/harmonize it if a user wants a harmonized set of "all the data"

This is an interesting solution. It makes the data _discoverable_ and _downloadable_ from us, but doesn't take on the risk of serving large collections of data that we have major qualms about. You could download from us but with a warning and only in isolation. We would not be providing anything worse than what's already in GEO/ArrayExpress. It would be good run this by @dvenprasad to get her thoughts too.

**Comment by cgreene** [comment]
If I understand the policy is entirely whitelist based (nicer than having to maintain a whitelist _and_ blacklist). The first whitelist is that we process the data using our processors. The second whitelist is that we noop the data and merge them with the processed data using reasonable normalization strategies. Anything that doesn't fall into one of those can only be downloaded at the individual experiment level. Did I summarize the proposal in my own words @jaclyn-taroni? (checking my understanding)

**Comment by jaclyn-taroni** [comment]
> If I understand the policy is entirely whitelist based (nicer than having to maintain a whitelist and blacklist). The first whitelist is that we process the data using our processors. The second whitelist is that we noop the data and merge them with the processed data using reasonable normalization strategies. Anything that doesn't fall into one of those can only be downloaded at the individual experiment level. Did I summarize the proposal in my own words @jaclyn-taroni? (checking my understanding)

Yup, sounds good to me 👍

**Comment by cgreene** [comment]
@dvenprasad : can you now take a look and ask questions if items are unclear (we're all a bit in the weeds on this one) and give us what you expect the user perspective will be?

**Comment by dvenprasad** [comment]
To clarify, refine.bio will have some datasets which are processed by CCDL, some datasets which are not processed by us but CCDL feels that the processed data(wherever it sourced from) has been processed well. These datasets will turn up in the search results and users can download them individually but refine.bio doesn't include them in the aggregate of all datasets. 

I think the users will appreciate that they will not have to hit multiple sources to get the data they need. 
Are there any implications of using no-op datasets that the users should be alerted to? Esp. the novice users.

**Comment by jaclyn-taroni** [comment]
I would put it slightly differently and into 3 categories:
1) CCDL processed
2) submitter-processed (NO-OP) on a platform we feel we can harmonize 
3) submitter-processed (NO-OP) but on a platform we're not confident we can harmonize

So 2 would be included in the aggregated compendium but 3 would not. I think we should alert users if they are using either category 2 or 3 data, but they should likely be notified differently.

**Comment by dvenprasad** [comment]
We can mark the datasets on the UI as CCDL processed, not CCDL processed but harmonizable, and not CCDL processed, and not harmonizable. 

When they are trying to download datasets, it can be designed so that they will not be able to choose datasets in category 3 to be aggregated ("smashed") with rest of their download queue.

**Comment by Miserlou** [comment]
I still don't think we're providing much positive utility by offering #3 at all. Of your examples above, #1 seems obscure, and we're not blocked from doing #2, it just means that we have to get the data later, which is probably smarter to do anyway because that's how our pipeline is constructed.

Including search results that can't be downloaded just seem confusing and generally pointless. 

If we get a hoard of people asking for the unharmonizable data then we can easily add it later, but I think we should just stick to clean data for right now.

**Comment by jaclyn-taroni** [comment]
Just to clarify - 1 = whitelist, 2 = NO-OP, 3 = blacklist in the [original comment](https://github.com/AlexsLemonade/refinebio/issues/145#issue-301052640)

> Of your examples above, #1 seems obscure, and we're not blocked from doing #2, it just means that we have to get the data later, which is probably smarter to do anyway because that's how our pipeline is constructed.

Is this in reference to how the experiment is marked?

**Comment by cgreene** [comment]
If we do not provide it, then I think we will want to still index the metadata and provide a link out to the data on GEO, ArrayExpress, SRA, or ENA. I think we might want to avoid someone thinking that our compendium is unintentionally incomplete. It's possible we could also track the clicks out as way of "nominating" certain platforms for inclusion.

**Comment by dvenprasad** [comment]
Number 3 can be downloaded as an individual experiment, if I'm not wrong. It just can't be smashed with other datasets. 

If we have those datasets, users should be able to download them. It's probably 1 less portal they have to visit/search through.

**Comment by jaclyn-taroni** [comment]
> Number 3 can be downloaded as an individual experiment, if I'm not wrong. It just can't be smashed with other datasets.

Yes, that would be the idea. I do think it would streamline the data discovery process.

**Comment by jaclyn-taroni** [comment]
> It's possible we could also track the clicks out as way of "nominating" certain platforms for inclusion.

I like this idea (although I can not speak to it's feasibility :) )

**Comment by jaclyn-taroni** [comment]
I'm going to close this for now, this is superseded by #228 for the Keytar Kurt milestone
