### ISSUE TITLE
Dashboard reports an inflated count for processor jobs

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1455]
### Context

The dashboard shows that the queue has ~16k processor jobs, when really the number should be closer to:
```
$ nomad status | grep dispatch | grep -v DOWNLO | grep running | wc -l
131
$ nomad status | grep dispatch | grep -v DOWNLO | grep pending | wc -l
35
```

### Problem or idea

I believe the issue is that when jobs get put into the nomad queue but then removed before being started, they get caught by the Foreman as "lost" jobs. It them marks them as a failure and creates new jobs to try again. However they don't get start times or end times, which I think is probably what that query is filtering on. This is possibly affecting downloader jobs as well.

### Solution or next step

We should update those queries to filter for jobs where `success is NULL` and that should make those numbers much more accurate.

**Comment by davidsmejia** [comment]
Fixed with #1564 and #1565
