### ISSUE TITLE
The dashboard stats cache seems to hammer our DB too hard

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1468]
### Context

I've disabled this feature for now in #1466 because it seems to be really hurting our DB.

### Problem or idea

@arielsvn mentioned that in the database query logs that he was seeing a lot of the same heavy request happening every 5 minutes. I'm thinking that perhaps because we start the scheduler in the `views.py` file, that every time we handle a request django creates a new worker to handle it which imports `views.py` and starts a new scheduler.

### Solution or next step

Try finding a new place to launch the scheduler, see if that fixes the issue. If not we gotta figure out a new hypothesis to fix this with.

**Comment by arielsvn** [comment]
Fixed by https://github.com/AlexsLemonade/refinebio/pull/1473
