### ISSUE TITLE
Avoid reindexing the full db in elastic search every 20 mins

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1477]
### Context

We reindex the entire db of experiments every 20 mins.

### Problem or idea

This impacts negatively the performance of the DB.

![image](https://user-images.githubusercontent.com/1882507/62874300-fdee4500-bcee-11e9-8b00-1ec569296ef4.png)

The biggest query that we do while reindexing calculates the accession codes of the downloadable samples for each experiment (we use this to calculate the totals in the search filters).

https://github.com/AlexsLemonade/refinebio/blob/dev/common/data_refinery_common/models/models.py#L427-L435

This has to be repeated once for each experiment.

### Solution or next step

Not sure if there's a way to improve that query.

Alternatively, we could only reindex the experiments that were modified in the 20 mins, or that have a sample that was modified in that interval. That way we would avoid throwing away the entire index.

**Comment by cgreene** [comment]
This is done with #1518 - note #1555 arises because of this fix.
