### ISSUE TITLE
Create groundwork for front end refinebio project

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#155]
### New Issue Checklist
- [X] The title is short and descriptive
- [x] The issue contains an:
  - [x] Idea (new feature, user story, etc)
  - [ ] Problem
- [x] You have explained the:
  - [x] Context
  - [x] Problem or idea
  - [x] Solution or next step
  
### Context

We do not yet have any interface for users to download data from. We don't even have a project started.

### Problem or idea

We know we want to use React/Redux, but we should put thought into how to start this project so we have a good foundation for the rest of our front end development.

### Solution or next step

Create the front end repo and get a minimal project going within it.

**Comment by cgreene** [comment]
From comparing the ease of the ADAGE & cognoma deployment processes, I think a separate frontend repo would help. I do not have similarly strong feelings about the API.

**Comment by ramenhog** [comment]
I also have enjoyed working with a separate frontend repo for Cognoma. I haven't minded having to run two separate web-servers and like the ability to switch between test and production endpoints. It'll also be easier for others to just run the frontend for design reviews and such. But I could be persuaded to keep the frontend as a subproject of refine.bio too
