### ISSUE TITLE
API search endpoint es indexing is a step function?

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#1555]
### Context

API search index has been acting strangely. 

### Problem or idea
This is probably unrelated but should be addressed or at the very least investigated. It occurs locally and on at least the last few deploys.
```
Indexing 2 'Experiment' objects
/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/documents.py:207: 
UnorderedObjectListWarning: 
  Pagination may yield inconsistent results with an unordered object_list: 
  <class 'data_refinery_common.models.models.Experiment'> QuerySet.
  object_list, self._doc_type.queryset_pagination
```

### Solution or next step

Find where this query is coming from and possibly replace with an explicitly ordered query.
Or maybe - and I'm not sure about this - possible add a default ordering to experiments a useful option would be ```id``` or ```created_at```

**Comment by davidsmejia** [comment]
<img width="350" alt="Screen Shot 2019-08-29 at 10 33 01 PM" src="https://user-images.githubusercontent.com/1075609/63989350-ff20bf80-caad-11e9-936b-b661f738223e.png">

**Comment by arielsvn** [comment]
Maybe related to https://github.com/AlexsLemonade/refinebio/pull/1518, I think it's the only change we have made recently on how ES is indexed.

**Comment by cgreene** [comment]
I think we must have been blowing away our search index on deploy. In the past, this didn't matter because we were constantly reindexing the entire thing. Now that we've gone incremental, we either need to not blow away our index on deploy or, probably better, to reindex things fully as part of the initial deploy process.

**Comment by cgreene** [comment]
After a manual reindexing we're back to normal.
