### ISSUE TITLE
Samples endpoint is not filtering by specie

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1570]
### Context

In the downloads page, we use `/samples` to list details about samples on each specie

### Problem or idea

https://api.refine.bio/v1/samples/?dataset_id=1631c0c2-1b71-4124-9927-58d2e7ef757e&organism__name=DANIO_RERIO&offset=0&limit=10

The parameter `organism__name=DANIO_RERIO` doesn't seem to be working and the endpoint is returning all samples in the dataset.

### Solution or next step

Investigate why the parameter isn't working.

**Comment by cgreene** [comment]
Fixed by #1624
