### ISSUE TITLE
Find samples that cause non-operational errors due to malformed sequence data

### ISSUE THREAD

**Issue by hbeale** [AlexsLemonade/refinebio#1571]
### Context

We've put together a tool that salvages malformed sequence data files. We're looking for examples of malformed sequence data.  

### Problem or idea

Can you help us find example of RNA-Seq samples that fail your pipeline because they are malformed? I think Salmon would be unable to read them. These would be non-operational failures (i.e. failures not due to a problem in queue processing, but due to the data, e.g. not correctly paired fastq).

A list of SRA Ids would be great. Thanks!

**Comment by cgreene** [comment]
Hi @hbeale : we're trying to figure out what the best way to address this would be. Do you know which errors from salmon are potentially indicative of these types of files? Would it be helpful for us to dump a list of errors that we've encountered with salmon processing and supply that to you? We're excited to help but struggling with next steps. Thanks!

**Comment by hbeale** [comment]
thanks, @cgreene! I'm not very familiar with Salmon errors. If you send send a list of errors with some or all of the SRA ids that caused them, I can test directly which errors correspond to fastq that meet our criteria. Is that in reach?

**Comment by cgreene** [comment]
Additional detail from our call - the desired output is, for all RNA-seq samples that failed to be processed, the error messages that they ended with (including blank, which we attribute to out of memory).

**Comment by kurtwheeler** [comment]
I think I have code that's actually working to pull these errors! We've been having trouble with previous attempts at querying for this timing out because there's so much data. This is the code that is currently running (and has been for about a half hour):
```
from django.db.models import OuterRef, Subquery
from data_refinery_common.models import Sample, ProcessorJob
from data_refinery_common.performant_pagination.pagination import PerformantPaginator as Paginator

PAGE_SIZE = 1000

latest_job = ProcessorJob.objects.filter(
    original_files__samples=OuterRef('id')
)

# This is the query we'd like to run, but it times out. I'm leaving it
# here because I think it's easier to tell what we're doing when it's
# not split across several queries.
# samples = Sample.objects\
#     .filter(technology='RNA-SEQ', is_processed=False)\
#     .exclude(results__computedfile__filename='quant.sf')\
#     .annotate(
#         reason=Subquery(latest_job.values('failure_reason')[:1])
#     )\
#     .filter(reason__isnull=False)\
#     .values('accession_code', 'reason')

unprocessed_rnaseq_samples = Sample.objects.filter(technology='RNA-SEQ', is_processed=False)

samples_with_quant = set(Sample.objects.filter(
    results__computedfile__filename='quant.sf'
).values_list('id', flat=True))

paginator = Paginator(unprocessed_rnaseq_samples, PAGE_SIZE, 'created_at')
page = paginator.page()
page_count = 0

sample_failure_reasons = []
# Handle one page worth of samples at a time so we don't time out.
while page:
    print("Handling page " + str(page_count))
    page_ids = {sample.id for sample in page.object_list}
    samples_without_quant = Sample.objects\
                                  .filter(id__in=page_ids)\
                                  .exclude(results__computedfile__filename='quant.sf')
    samples_without_quant = page_ids - samples_with_quant
    samples = Sample.objects\
                    .filter(id__in=samples_without_quant)\
                    .annotate(
                        reason=Subquery(latest_job.values('failure_reason')[:1]))\
                    .filter(reason__isnull=False)\
                    .values('accession_code', 'reason')
    sample_failure_reasons.extend(list(samples))
    if page.has_next():
        page = paginator.page(page.next_page_number())
        page_count += 1
    else:
        break

with open('/tmp/reasons.txt', 'w') as fd:
    fd.write('accession_code, failure_reason')
    for result in sample_failure_reasons:
        fd.write(result['accession_code'] + ', ' + result['reason'])
        print(result['accession_code'], result['reason'])
        break
```

**Comment by kurtwheeler** [comment]
Ok it finished!!! It still included a lot of operational errors. However, I filtered out a lot of them with:
```
cat reasons.txt | grep -v 'Bad Nomad' | grep -v 'transcriptome index' | grep -v 'Salmon timed out' | grep -v 'Sample has a good computed file,' | grep -v 'Cannot allocate memory' | grep -v 'that has already been started' | grep -v 'Missing file for processor job' | grep -v 'Unhandled exception caught while running processor function' | grep -v 'Affy' | grep -v 'fasterq-dump' | grep -v 'Exception caught while zipping processed directory' > filtered_reasons.txt
```
However there are still 34525 lines in that file and I didn't go through every one of them to make sure I got all the operational errors so there could be some more mixed in there. 

The file is still 77MB, so I can't just attach it to this comment, however I've uploaded it to S3 so you can download it from this link: https://refinebio-external-sharing.s3.amazonaws.com/filtered_reasons.csv

It's a CSV file with the sample accession code in the first column and the failure_reason in the second (with newlines escaped). Let me know if you have any problems with it or if you have additional questions!!

**Comment by cgreene** [comment]
@hbeale - could you let us know if this gets you what you need? We're going to close this for now and we'd love feedback as you get to dig into this list. Thanks!
