### ISSUE TITLE
Some organisms are missing QN targets that should have them

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1572]
### Context

We don't have a rat QN target. There's a lot of rat samples so we should be able to make one.

Remember, we can create a QN target for any organism for which we have processed 100 samples from the same affy platform.

### Problem or idea

Jackie has provided the following list of organisms, their largest platform, and how many samples there are for that platform. We would expect most if not all of these organisms to have a QN target.

[affymetrix_platforms_for_QN_reference.txt](https://github.com/AlexsLemonade/refinebio/files/3591306/affymetrix_platforms_for_QN_reference.txt)

### Solution or next step

Look into why we don't have a QN target for rat or other organisms that we would expect to have one for and generate them.

**Comment by cgreene** [comment]
🐀 ➡️ 📈
