### ISSUE TITLE
OrganismIndex should be versioned and include genome build information

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#158]
### New Issue Checklist
- [x] The title is short and descriptive
- [ ] The issue contains an:
  - [ ] Idea (new feature, user story, etc)
  - [x] Problem
- [x] You have explained the:
  - [x] Context
  - [x] Problem or idea
  - [x] Solution or next step
  
### Context

In the refactor we are adding a table named OrganismIndex which will be used for storing information about indices built by the so called "Index Refinery". The first one we're building is for Salmon indices. Every now and then as Ensembl updates their genomes we'll want to rebuild these indices.

### Problem or idea

We need to give each build of these indices a different version so we can track which version was used when processing RNAseq data.

### Solution or next step

Come up with a way of versioning different pre-built indices. I would propose using a date since it's simple and this really isn't a good application of semantic versioning.

**Comment by cgreene** [comment]
Is this closed #310

**Comment by kurtwheeler** [comment]
Yes, the `organism_index` table now has a `source_version` field which is set to the version of the Ensembl  release which was used to build it.
