### ISSUE TITLE
.quant file request

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#1587]
### Context

I was contacted by Maria Chikina ( @mchikina ), who would like access to a large number of .quant files for a project.

### Problem or idea

It is not currently possible to get quant files.

### Solution or next step

We could tackle this in a couple ways:
* The API could allow one to request quant files for RNA-seq samples. Most of our web-based users probably won't want this functionality, so we probably wouldn't initially expose it via the React UI.
* We could make "compendia" of quant files. We'd put them in a directory and zip them, along with the metadata.

**Comment by mchikina** [comment]
Also, any metadata (like tissue, etc) would be useful.

**Comment by jaclyn-taroni** [comment]
@mchikina are you looking specifically for human samples? If so, you can likely leverage [MetaSRA](http://metasra.biostat.wisc.edu/) for the tissue labels.

**Comment by mchikina** [comment]
This is great. Hopefully the tissue information will come out automatically but it would be nice to have something to verify.

**Comment by arielsvn** [comment]
@mchikina we now have the ability to generate datasets that include `quant.sf` files. Do you need one with human samples? or any other type of samples?

**Comment by mchikina** [comment]
Yes. Human would be a top priority for me. I am also interested in mouse.

**Comment by arielsvn** [comment]
@mchikina you can download all of our human `quant.sf` files [here](https://s3.amazonaws.com/data-refinery-s3-circleci-prod/HOMO_SAPIENS_1_1574170428.zip) (it's `256gb` compressed).

**Comment by arielsvn** [comment]
All our mouse `quant.sf` can be downloaded [here](https://s3.amazonaws.com/data-refinery-s3-circleci-prod/MUS_MUSCULUS_1_1574233541.zip), this one is `185gb` compressed.

I'm closing this issue, feel free to re-open or file a new one if you need something else.
