### ISSUE TITLE
Implement whitelist for sequencing platforms

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#159]
### New Issue Checklist
- [x] The title is short and descriptive
- [x] The issue contains an:
  - [ ] Idea (new feature, user story, etc)
  - [x] Problem
- [x] You have explained the:
  - [x] Context
  - [x] Problem or idea
  - [x] Solution or next step
  
### Context

Salmon, our RNA-seq quantification tool of choice, is not appropriate for every sequencing technology that's out there. For instance, Salmon should not be used for long-read sequencing (e.g. PacBio).

### Problem or idea

We'll need to come up with a whitelist of platforms for use with Salmon (somewhat related: #115 and #145). Here's a screenshot of the platform options in the European Nucleotide Archive search:

![127f0941c48647c492bfd382282a15fe](https://user-images.githubusercontent.com/19534205/37291363-d8a1af1e-25e4-11e8-9273-e751734abbc1.png)

### Solution or next step

Illumina and Ion Torrent are good to go. PacBio and Nanopore are long-read technology. I will need to further investigate the less familiar platforms.

**Comment by jaclyn-taroni** [comment]
For Keytar Kurt, I think we should focus on running Illumina and Ion Torrent.

**Comment by kurtwheeler** [comment]
> Illumina and Ion Torrent are good to go.

Since those are the only two we need for Keytar Kurt I think we should remove this from that milestone. This is still something we're gonna need to do later, but not before Keytar Kurt.

**Comment by jaclyn-taroni** [comment]
So from my "make a list" point of view -- this is closed for now. Should another "implementation" ticket be filed?

**Comment by jaclyn-taroni** [comment]
It occurred to me that a list of machines not be the only info required for this, from #231:

> Essentially, I am asking: Will a list of machines be sufficient to accomplish this? Do we need to create a summary list of sequencing machines from SRA similar to how we're doing so for GEO (#220)?

**Comment by jaclyn-taroni** [comment]
We're interested in _whole_ transcriptome sequencing (RNA-seq). We'll be using the SRA library source metadata to help with this, i.e., only looking at `TRANSCRIPTOMIC` data

**Working off of this list:** https://github.com/AlexsLemonade/refinebio/issues/222#issuecomment-386704996 (note the open question [here](https://github.com/AlexsLemonade/refinebio/issues/222#issuecomment-386709966) as of the writing of this comment)

**I used the following documentation:**

* Comparison of Illumina platforms: https://www.illumina.com/systems/sequencing-platforms.html 

* Ion Torrent Transcriptome Brochure: https://tools.thermofisher.com/content/sfs/brochures/Transcriptome-Brochure.pdf; see also: https://www.thermofisher.com/us/en/home/life-science/sequencing/rna-sequencing.html

### Supported

#### Illumina

* `Illumina Genome Analyzer II`, `Illumina Genome Analyzer IIx`, 
* [`Illumina HiScanSQ`](https://www.illumina.com/documents/products/datasheets/datasheet_hiscansq.pdf)
* Assuming all HiSeq instruments are (somewhat) equal: `Illumina HiSeq 1000`, `Illumina HiSeq 1500`, `Illumina HiSeq 2000`, `Illumina HiSeq 2500`, `Illumina HiSeq 3000`, `Illumina HiSeq 4000`
* NextSeq: `NextSeq 500`, `NextSeq 550`

#### Ion Torrent

`Ion Torrent Proton`, `Ion Torrent S5`, `Ion Torrent S5 XL`

### Unsupported

* `HiSeq X Ten` and `HiSeq X Five` are only appropriate for whole-genome sequencing
* `Illumina MiSeq` - Doesn't do `Whole-Transcriptome Sequencing` or `Gene Expression Profiling with mRNA-Seq` according to Illumina
* `Illumina MiniSeq` -  Doesn't do `Whole-Transcriptome Sequencing` or `Gene Expression Profiling with mRNA-Seq` according to Illumina
* `Ion Torrent PGM` - [Looks like](https://www.thermofisher.com/us/en/home/life-science/sequencing/next-generation-sequencing/ion-torrent-next-generation-sequencing-workflow/ion-torrent-next-generation-sequencing-run-sequence/ion-pgm-system-for-next-generation-sequencing.html) it supports targeted sequencing only 

### Platforms that are potentially missing from the list

`Illumina Genome Analyzer IIe`

**Comment by jaclyn-taroni** [comment]
@kurtwheeler @Miserlou @dongbohu - does this require an implementation ticket or an update to name?  If not, can I go ahead and close this for now?

**Comment by jaclyn-taroni** [comment]
Update: We're going to use this ticket to track implementation. I have updated the ticket name and removed my assignment.

**Comment by jaclyn-taroni** [comment]
_Processed_ RNA-seq data sometimes lives in GEO, where it will often be linked to its raw data counterpart in SRA. Here's an example: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE72536 

Based on my understanding of the system, we are not capturing this relationship. As a result, I propose that we do not `NOOP` any sequencing data (i.e., use these platforms) from GEO or ArrayExpress for Keytar Kurt because we might be capturing a bunch of duplicates. (If we're somehow capturing this relationship at the _sample_ level, I can be persuaded that I am wrong.)
