### ISSUE TITLE
API: Expose quant files

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#1602]
### Context

With #1587 it became clear that we should allow computational folks to access these.

### Problem or idea

There is no way to add `quant.sf` files to a collection for downloading. We probably want to expose these only via the API (perhaps, in the front-end, we could provide information for the samples with only quant files by linking to the newly written quant file documentation).

### Solution or next step

We should modify the API to allow folks to retrieve quant files if they verify that they really, really want them.

**Comment by kurtwheeler** [comment]
Part of this will be getting the total number of processed samples. This query can be converted into django ORM in order to get this number:
```
data_refinery=> select count(*) from samples where id in (select distinct(sample_id) from sample_result_associations where result_id in (select result_id from computed_files where filename ='quant.sf'));
 count  
--------
 711857
(1 row)

```

**Comment by arielsvn** [comment]
Any recommendations on how to include the `quant.sf` files inside the dataset? I was thinking of adding an additional field to the dataset objects, something like `include_quant_files`. Then if the user aggregates the dataset **by experiment**, we can include each sample quant file in the corresponding folder.

Is this structure good?

```
SRP119033 (experiment accession)
--- SRP119033.tsv
--- quant.sf (folder)
    --- SRR1550948.sf
    --- SRR1550946.sf
```

**Comment by jaclyn-taroni** [comment]
I like the following for autocomplete purposes:
```
SRP119033 (experiment accession)
--- SRP119033.tsv
--- SRR1550948_quant.sf
--- SRR1550946_quant.sf
```

**Comment by arielsvn** [comment]
Tested on staging https://staging.refine.bio/dataset/51c9b468-a53d-4fe2-abc4-e68b477cf984
