### ISSUE TITLE
Create quantpendia for all organisms

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1603]
### Context

Will build off of https://github.com/AlexsLemonade/refinebio/issues/1601

### Problem or idea

#1601 made it so we can run smasher jobs on just quant files. Now we want to run a smasher job for the full organism for all organisms.

### Solution or next step

This is a two parter:
  1. Make it so compendia jobs can run for just quant files.
  2. Run compendia jobs for all organism.

**Comment by arielsvn** [comment]
We have quantpendias for all organisms now, except mouse, but we're building it for #1587.
