### ISSUE TITLE
Downloaded Data Numbers - API

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#1604]
### Context

Sprint planning meeting.

### Problem or idea

We do not currently have a way to get `1 PB -Over a petabyte of raw data will be processed` from the about page based on actual downloaded data.

### Solution or next step

We should add an API endpoint to calculate this.

**Comment by arielsvn** [comment]
New api is still timing out for this https://api.refine.bio/v1/stats-about/

**Comment by arielsvn** [comment]
Discussed with @kurtwheeler  and @davidsmejia, two ideas came up:

- Increase the timeout for that endpoint
- Take another look at the queries to see if we can optimize them further

**Comment by cgreene** [comment]
Can we hard code for now? Thinking about what gets us there asap.
