### ISSUE TITLE
Allow adding quant.sf files to datasets but only via the API

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1605]
### Context

We want to let people get quant.sf files if they want them.

### Problem or idea

The API will currently prevent users from adding samples to a dataset if they do not have normalized data. However we now want to let people get quant.sf files via the API, but not via the frontend.

### Solution or next step

Remove the API's check that prevents un-normalized samples from being added to a dataset.

**Comment by arielsvn** [comment]
Seems like the API only does this check when users use a special parameter to add all samples in an experiment. Which they can do with `GSE1234: ['ALL']`. This is used by the frontend in the search page.

Via the API people should be able to create datasets for samples with `quant.sf` files.
