### ISSUE TITLE
Many computed files were not uploaded to S3 without triggering failure

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1627]
### Context

I found something horrifying while working on https://github.com/AlexsLemonade/refinebio/pull/1625

We have not been failing jobs if we failed to upload the results to S3. That's pretty bad.

It looks like this happened 14617 times:
```sql
data_refinery=> select count(*) from computed_files where s3_bucket is NULL;
 count 
-------
 14617
```

### Problem or idea

We should regenerate all of these computed files by rerunning the processor jobs that produced them originally. This is also exciting though because I think a number of tximport errors were caused by a missing `quant.sf` file. I didn't know how that could happen but this explains it. Once we rerun these we can potentially get a much better tximport success rate.

### Solution or next step

Create a management command to regenerate these computed files. It's possible that some of them could even be for the same samples. So rather than queuing one job per computed file, we should get all the distinct samples related to these computed files, then make a new downloader job for each of them.

**Comment by kurtwheeler** [comment]
https://github.com/AlexsLemonade/refinebio/issues/1131 may be related... It's not quite how I would expect that error to look if it was though...

**Comment by arielsvn** [comment]
@kurtwheeler can we close this now that we ran the job?

Checked the db and we seem to have more computed files that were not uploaded to S3

```sql
data_refinery=> select count(*) from computed_files where s3_bucket is NULL;
 count 
-------
 18051
(1 row)
```

**Comment by kurtwheeler** [comment]
We reran these samples over this weekend. When looking into this issue, the relevant logs can be found with:

```
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=data-refinery-log-group-circleci-prod;stream=log-stream-processor-docker-circleci-prod;start=2019-09-27T00:00:00Z;end=2019-09-29T23:59:59Z
```

**Comment by cgreene** [comment]
Ok - closing this and we can go back later to find failure reasons that may be ops related.
