### ISSUE TITLE
500 error when adding study to a dataset

### ISSUE THREAD

**Issue by ben-heil** [AlexsLemonade/refinebio#1649]
### Context

When I [search for studies](https://www.refine.bio/search?q=sepsis) and attempt to add them to my dataset, the https://api.refine.bio/v1/dataset/ POST endpoint returns a 500 error.

![image](https://user-images.githubusercontent.com/15317110/65604851-21571180-df76-11e9-9ffc-75aed8ff80dc.png)

### Problem or idea

1. Throwing an error instead of adding the study to a dataset
2. When a 500 error is thrown, the progress bar on the website acts as if nothing went wrong, it may be helpful to have a 'something went wrong' alert if an error occurs

### Solution or next step

It's unclear to me what the next step would be to fix the error. Maybe check other parts of the API to see whether a server went down vs a software bug

**Comment by ben-heil** [comment]
The samples endpoint also appears to be down

![image](https://user-images.githubusercontent.com/15317110/65605529-3e401480-df77-11e9-9eb8-1e03525bb0b7.png)

**Comment by arielsvn** [comment]
Thanks for reporting the issue @ben-heil, seems like this was caused by a migration we were testing recently. We'll try to fix it asap.

**Comment by cgreene** [comment]
This should be working again. @ben-heil can you try it?

**Comment by ben-heil** [comment]
Yep, it works. Thanks @arielsvn!
