### ISSUE TITLE
Start the Front End Project!

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#166]
We need a 'frontend' sub-project to house all of the front-end assets!

This will also mean scaffolding the actual front-end project, defining and documenting the development and deployment pipelines, and creating a test-suite.

I think it would probably be best if this project lived in a `frontend` directory of this repository rather than as a separate repo so that tickets are all in the same place.

**Comment by ramenhog** [comment]
@miserlou Hmm, I think keeping the frontend repo separate might be better for scalability. That way, we can run them, fix bugs, and deploy them separately without getting in the other stack's way.

**Comment by cgreene** [comment]
From comparing ADAGE/cognoma:

ADAGE = monolithic repo
Cognoma = component-specific repos

Cognoma ends up being quite a bit easier to deploy. For ADAGE, we can't really deploy a new version of the frontend separately from the backend. I wonder if the :waffle: could give us the benefits of easy deployment + the ability to look across issues easily.

However, if both the frontend and the backend require updates (i.e., the frontend needs an endpoint that may not yet have been deployed yet) it would need to degrade gracefully if they are not synced. #randomthoughts

**Comment by ramenhog** [comment]
Yeah, I've really liked how Cognoma's frontend is separate. And even though I've had frontend changes relying on a backend change, I've just mentioned in my frontend PR that it's waiting on a backend deployement of the related issue. And that works fine 👍
