### ISSUE TITLE
Changes to README in compendium downloads

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#1661]
### Context

Related to: https://github.com/AlexsLemonade/refinebio-docs/issues/114, https://github.com/AlexsLemonade/refinebio-docs/issues/109, and https://github.com/AlexsLemonade/refinebio/issues/1603

### Problem or idea

This file says "species compendium" and is tailored to what we now refer to as a "normalized compendium": https://github.com/AlexsLemonade/refinebio/blob/dev/workers/README_COMPENDIUM.md

### Solution or next step

- [ ] Change that file to say "normalized compendium"
- [ ] Create a new README for quantpendia
- [ ] Include the new README in quantpendia per https://github.com/AlexsLemonade/refinebio-docs/issues/109#issuecomment-533257832

I can tackle the first two points.

**Comment by cgreene** [comment]
Closed via #1664
