### ISSUE TITLE
Paralleize correct Affy CDFs command

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1693]
### Context

#1276 

We have a lot of experiments from GEO. Like 800k or something. So far the correct_affy_cdfs command has only made it through about 20k.

### Problem or idea

We gotta go faster than this cause we want this to finish before we get out of beta.

### Solution or next step

Instead of having the management command check each experiment, we should just have it fire off a job that will check the experiment, and if necessary unsurvey it and resurvey it. It can either do the resurveying itself or it can kick off a new survey job to reuse that machinery.

Either way I think we should have the management command only create so many so fast so we don't overload GEO. I'm thinking 100 jobs per minute so we can get through it in about a week:

800k (jobs) / 100 (jobs per minute) / 1440 (minutes per day) = 5.5 days

**Comment by cgreene** [comment]
Re-calculation - we don't need to do this right now. 🎢
