### ISSUE TITLE
Combine multiple samples from an experiment into a matrix

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#172]
### Problem or idea & context

If a user wants an entire experiment (i.e., provides an experiment accession number), we should provide this data in the form of a matrix rather than multiple files for individual samples. Once samples are either processed with `SCAN` or, in the case of submitter-processed data from ArrayExpress, `sample_table.txt` files are obtained, we'll need to bind/join these samples together (as columns) to provide the experiment matrix to the user. (Right now, this only applies to microarray data, as we plan to use tximport at the experiment level.)

### Solution or next step

Based on a quick, preliminary discussion with @Miserlou,`pandas` might be the way to go.

**Comment by kurtwheeler** [comment]
To be clear, we'll still want to store the outputs for each sample in case someone is looking to only retrieve a single sample's processed outputs?

@jaclyn-taroni do you think it makes sense to tackle this before https://github.com/AlexsLemonade/refinebio/issues/182 so as to make the output of that more easily decipherable/usable by you when you go to verify the correctness of the crunch?

**Comment by jaclyn-taroni** [comment]
> To be clear, we'll still want to store the outputs for each sample in case someone is looking to only retrieve a single sample's processed outputs?

Yep, that's correct. Storing outputs at the single-sample level also lends itself to use cases like, "Give me only the control samples for these experiments and aggregate them" in my opinion

>  do you think it makes sense to tackle this before #182 so as to make the output of that more easily decipherable/usable by you when you go to verify the correctness of the crunch?

So it would probably be helpful for me to have this taken care of, but I would not consider it a blocker.

**Comment by kurtwheeler** [comment]
So after discussing with @Miserlou we decided that this should just be done as a normal merging/aggregating/smushing step rather than being done beforehand and storing both, which would effectively result in us storing double the amount of data on a permanent basis.

I'm closing this since I've already discussed it with @jaclyn-taroni
