### ISSUE TITLE
Create command to delete invalid compendias

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1735]
### Context

https://github.com/AlexsLemonade/refinebio/pull/1734

Compendia need a QN target so they can be quantile normalized. We need 100 samples on the sample platform to create a QN target. Therefore any organisms without 100 samples on the same platform should be ineligible for a compendium.

### Problem or idea

We created a compendium for Bos Inidicus which you can see only has 57 samples: https://www.refine.bio/search?filter_order=organism&organism=bos_indicus

### Solution or next step

In https://github.com/AlexsLemonade/refinebio/pull/1734 I should have prevented us from trying to create a compendium for this situation.

However, we should still:
  * Look into how the compendia was successful despite not having a QN target to do that step.
  * Delete this and any other compendia that should have failed to be created in the first place.

**Comment by arielsvn** [comment]
> Look into how the compendia was successful despite not having a QN target to do that step.

`BOS_INDICUS` samples are associated with the platform `bovine` for which we have 2389 processed microarray samples

```
>>> Sample.objects.filter(platform_accession_code='bovine', is_processed=True, technology='MICROARRAY').count()
2389
```

That's the platform that was used to create that compendia. This should be addressed by https://github.com/AlexsLemonade/refinebio/pull/1753 where `BOS_INDICUS` will be combined in the same compendia with `'BOS_TAURUS', 'BOS_GRUNNIENS'`

To close this issue we'll still need to create a command to delete the invalid compendias
>Delete this and any other compendia that should have failed to be created in the first place.
