### ISSUE TITLE
We should create a single compendia for organisms that share platforms

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1736]
### Context

We have a compendium for `BOS_INDICUS` despite the fact that all the samples for it were collected using the platform for `BOS_TAURUS`. 

### Problem or idea

We should collapse organisms to a single compendium when they share a platform.

### Solution or next step

So it's not immediately obvious how we should implement this. The reason I say that is because when we build the dataset in the foreman management command `create_compendia.py` we don't look at platforms. We just add the accession code for every sample associated with the dataset and let the compendium figure out what to do.

I guess that while we're doing that we'll have to:
  * Check what the biggest platform is for that organism.
  * Check to see if it is used for any other organism.
  * If it's not then it's business as usual.
  * But if it is we should:
    * Check to see if that organism has any other platforms.
    * If it does then we should scream about it so we know these mixed cases exist.
    * If it doesn't then we should add all samples from that organism to the dataset.

**Comment by arielsvn** [comment]
Does this mean that one compendium can be associated with more than one organism?

Right now they are `ComputedFiles` which can only have a single organism.

**Comment by arielsvn** [comment]
Talked with @kurtwheeler, and we came up with a plan to solve this (The answer to the previous questions is yes).

1. Change the relationship to many-to-many between compendia computed files and Organisms
    - Add many-to-many relationship
    - Populate that using the existing relationship
    - Remove the old relationship (can only happen after step #2 below)
2. Correctly assign the organisms to the computed file when we generate a compendium. https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L369
3. Modify the command that triggers the compendia to handle creating compendiums with multiple organisms. https://github.com/AlexsLemonade/refinebio/blob/dev/foreman/data_refinery_foreman/foreman/management/commands/create_compendia.py

**Comment by arielsvn** [comment]
> If it does then we should scream about it so we know these mixed cases exist.

@kurtwheeler do we need to scream? (log an error?) I checked on prod and this seems to happen for a lot of Organisms. For example `GORILLA`'s biggest platform is `IlluminaHiSeq2000`, which is also used by `HOMO_SAPIENS`. 

These are a few other organisms whose biggest platform is also `IlluminaHiSeq2000`

```
PETROMYZON_MARINUS
ANAS_PLATYRHYNCHOS
CIONA_SAVIGNYI
ASTYANAX_MEXICANUS
GADUS_MORHUA
```

**Comment by jaclyn-taroni** [comment]
The platform/machine for RNA-seq doesn't tell us anything about the organism. `IlluminaHiSeq2000` is a sequencing machine and therefore is general. I think @kurtwheeler is using "biggest platform" in the same sense that we use it when generating QN targets: Affymetrix microarray platform.

**Comment by arielsvn** [comment]
@jaclyn-taroni thanks! I updated the condition, now it's getting the biggest platform for samples where `has_raw=True, technology="MICROARRAY", is_processed=True`. Does this list make more sense?

Organism | Biggest platform | Other Organism also using this platform
------------ | ------------- | ------------
ANAS_PLATYRHYNCHOS | chicken | GALLUS_GALLUS
CHLOROCEBUS_SABAEUS | rhesus | MACACA_MULATTA
CAPRA_HIRCUS | hgu133a | HOMO_SAPIENS
MUS | mogene20st | MUS_MUSCULUS
MUS_MUSCULUS | mouse4302 | HOMO_SAPIENS


<details><summary>Full table</summary>

Organism | Biggest platform | Other Organism also using this platform
------------ | ------------- | ------------
ANAS_PLATYRHYNCHOS | chicken | GALLUS_GALLUS
CHLOROCEBUS_SABAEUS | rhesus | MACACA_MULATTA
CAPRA_HIRCUS | hgu133a | MUS_MUSCULUS
MUS | mogene20st | MUS_MUSCULUS
ORYCTOLAGUS_CUNICULUS | hgu95av2 | HOMO_SAPIENS
FELIS_CATUS | hugene10st | MUS_MUSCULUS
UNIDENTIFIED | mogene21st | MUS_MUSCULUS
MUS_MUSCULUS_DOMESTICUS | mouse4302 | MUS_MUSCULUS
MICROCEBUS_MURINUS | hgu133plus2 | MUS_MUSCULUS
SACCHAROMYCES_PASTORIANUS | yeast2 | SACCHAROMYCES_CEREVISIAE
PSEUDOMONAS_PUTIDA | paeg1a | ESCHERICHIA_COLI
LEYMUS_TRITICOIDES | barley1 | ZEA_MAYS
PONGO_ABELII | hgu133a2 | MUS_MUSCULUS
PROCAPRA_PRZEWALSKII | bovine | OVIS_ARIES
TRITICUM_TURGIDUM_SUBSP._DURUM | wheat | TRITICUM_AESTIVUM
MUS_MUSCULUS_MUSCULUS_X_M._M._CASTANEUS | mouse4302 | MUS_MUSCULUS
PAPIO_ANUBIS | hgu133plus2 | MUS_MUSCULUS
TRYPANOSOMA_CRUZI | hgu133plus2 | MUS_MUSCULUS
XENOPUS_MUELLERI | xenopuslaevis | MUS_MUSCULUS
MUS_SPRETUS | mouse4302 | MUS_MUSCULUS
RATTUS_NORVEGICUS | rat2302 | MUS_MUSCULUS
ARABIDOPSIS_THALIANA | ath1121501 | DROSOPHILA_MELANOGASTER
MUSCULUS | mogene20st | MUS_MUSCULUS
PAN_TROGLODYTES | hgu133plus2 | MUS_MUSCULUS
MARMOTA_MONAX | hgu133plus2 | MUS_MUSCULUS
MUS_MUSCULUS_X_MUS_SPRETUS | mouse4302 | MUS_MUSCULUS
BOECHERA_GUNNISONIANA | ath1121501 | DROSOPHILA_MELANOGASTER
SACCHAROMYCES_CEREVISIAE_VIN13 | yeast2 | SACCHAROMYCES_CEREVISIAE
MUS_MUSCULUS_MUSCULUS | mouse4302 | MUS_MUSCULUS
CHLOROCEBUS_AETHIOPS_VERVET | rhesus | MACACA_MULATTA
HETERODERA_GLYCINES | soybean | GLYCINE_MAX
ARABIDOPSIS_THALIANA_X_ARABIDOPSIS_HALLERI_SUBSP._GEMMIFERA | ath1121501 | DROSOPHILA_MELANOGASTER
APTENODYTES_PATAGONICUS | chicken | GALLUS_GALLUS
COTURNIX_JAPONICA | chicken | GALLUS_GALLUS
MACACA_RADIATA | rhesus | CHLOROCEBUS_SABAEUS
VIGNA_UNGUICULATA | soybean | GLYCINE_MAX
PHYTOPHTHORA_SOJAE | soybean | GLYCINE_MAX
PHASEOLUS_COCCINEUS | soybean | GLYCINE_MAX
DROSOPHILA_MAURITIANA | drosgenome1 | DROSOPHILA_MELANOGASTER
DROSOPHILA_TEISSIERI | drosgenome1 | DROSOPHILA_MELANOGASTER
RORIPPA_SYLVESTRIS | ath1121501 | DROSOPHILA_MELANOGASTER
TRITICUM_CARTHLICUM | wheat | TRITICUM_AESTIVUM
MUS_SP. | mogene10st | MUS_MUSCULUS
CERVUS_ELAPHUS | hgu133plus2 | MUS_MUSCULUS
MUS_CAROLI | mgu74av2 | MUS_MUSCULUS
FESTUCA_RUBRA_SUBSP._FALLAX | wheat | TRITICUM_AESTIVUM
MUS_MUSCULUS_CASTANEUS | mouse4302 | MUS_MUSCULUS
ALOPECURUS_MYOSUROIDES | wheat | TRITICUM_AESTIVUM
ARABIDOPSIS_HALLERI_SUBSP._GEMMIFERA | ath1121501 | DROSOPHILA_MELANOGASTER
RANA_PIRICA | xenopuslaevis | MUS_MUSCULUS
AVENA_SATIVA | barley1 | ZEA_MAYS
SACCHAROMYCES_PASTORIANUS_WEIHENSTEPHAN_34/70 | yeast2 | SACCHAROMYCES_CEREVISIAE
SACCHAROMYCES_CEREVISIAE_EC1118 | yeast2 | SACCHAROMYCES_CEREVISIAE
CARICA_PAPAYA | ath1121501 | DROSOPHILA_MELANOGASTER
ARABIDOPSIS_LYRATA_SUBSP._PETRAEA | ath1121501 | DROSOPHILA_MELANOGASTER
SACCHAROMYCES_CEREVISIAE_SK1 | yeast2 | SACCHAROMYCES_CEREVISIAE
PANTHOLOPS_HODGSONII | bovine | OVIS_ARIES
ORYZA_LONGISTAMINATA | rice | ORYZA_SATIVA
PAPIO_CYNOCEPHALUS | hgu133a2 | MUS_MUSCULUS
GLYCINE_SOJA | soybean | GLYCINE_MAX
DROSOPHILA_SECHELLIA | drosophila2 | DROSOPHILA_MELANOGASTER
PSEUDOMONAS_AERUGINOSA_PAHM4 | paeg1a | ESCHERICHIA_COLI
EIMERIA_TENELLA | chicken | GALLUS_GALLUS
SACCHAROMYCES_BOULARDII | ygs98 | SACCHAROMYCES_CEREVISIAE
TRITICUM_MONOCOCCUM | wheat | TRITICUM_AESTIVUM
HOMO_SAPIENS | hgu133plus2 | MUS_MUSCULUS
ACOMYS_CAHIRINUS | mogene20st | MUS_MUSCULUS
CHLOROCEBUS_AETHIOPS | hgu133plus2 | MUS_MUSCULUS
RATTUS_NORVEGICUS_ALBUS | ragene10st | HOMO_SAPIENS
SCHIZOSACCHAROMYCES_POMBE_972H- | yeast2 | SACCHAROMYCES_CEREVISIAE
TRITICUM_TURGIDUM_SUBSP._DICOCCOIDES | wheat | TRITICUM_AESTIVUM
RATTUS_RATTUS | rat2302 | MUS_MUSCULUS
BUBALUS_BUBALIS | bovine | OVIS_ARIES
PSEUDOMONAS_AERUGINOSA | paeg1a | ESCHERICHIA_COLI
AEGILOPS_TAUSCHII_X_TRITICUM_TURGIDUM | wheat | TRITICUM_AESTIVUM
RORIPPA_AMPHIBIA_X_RORIPPA_SYLVESTRIS | ath1121501 | DROSOPHILA_MELANOGASTER
XENOPUS_BOREALIS | xenopuslaevis | MUS_MUSCULUS
SACCHAROMYCES_CEREVISIAE_CEN.PK113-7D | yeast2 | SACCHAROMYCES_CEREVISIAE
XENOPUS_LAEVIS_X_XENOPUS_MUELLERI | xenopuslaevis | MUS_MUSCULUS
HORDEUM_VULGARE_SUBSP._SPONTANEUM | barley1 | ZEA_MAYS
SORGHUM_BICOLOR | barley1 | ZEA_MAYS
SACCHAROMYCES_BAYANUS | yeast2 | SACCHAROMYCES_CEREVISIAE
SACCHAROMYCES_CEREVISIAE_X_SACCHAROMYCES_KUDRIAVZEVII | yeast2 | SACCHAROMYCES_CEREVISIAE
FESTUCA_ARUNDINACEA | wheat | TRITICUM_AESTIVUM
ARABIDOPSIS | ath1121501 | DROSOPHILA_MELANOGASTER
BRASSICA_OLERACEA_VAR._ITALICA | ath1121501 | DROSOPHILA_MELANOGASTER
BOS_GRUNNIENS | bovine | OVIS_ARIES
PHASEOLUS_VULGARIS | soybean | GLYCINE_MAX
AEGILOPS_TAUSCHII | wheat | TRITICUM_AESTIVUM
ARABIDOPSIS_LYRATA | ath1121501 | DROSOPHILA_MELANOGASTER
RORIPPA_AMPHIBIA | ath1121501 | DROSOPHILA_MELANOGASTER
DROSOPHILA_SANTOMEA | drosgenome1 | DROSOPHILA_MELANOGASTER
PSEUDOMONAS_AERUGINOSA_UCBPP-PA14 | paeg1a | ESCHERICHIA_COLI
LACTOBACILLUS_DELBRUECKII_SUBSP._BULGARICUS | ygs98 | SACCHAROMYCES_CEREVISIAE
MESOCRICETUS_AURATUS | mogene10st | MUS_MUSCULUS
ARABIDOPSIS_THALIANA_X_ARABIDOPSIS_LYRATA | ath1121501 | DROSOPHILA_MELANOGASTER
SECALE_CEREALE_X_TRITICUM_TURGIDUM_SUBSP._DURUM | wheat | TRITICUM_AESTIVUM
PAPIO_HAMADRYAS | hgu133a2 | MUS_MUSCULUS
SACCHAROMYCES_CEREVISIAE_S288C | yeast2 | SACCHAROMYCES_CEREVISIAE
HORDEUM_VULGARE | barley1 | ZEA_MAYS
MACACA_MULATTA | rhesus | MACACA_FASCICULARIS
SACCHAROMYCES_UVARUM | yeast2 | SACCHAROMYCES_CEREVISIAE
SACCHAROMYCES_CEREVISIAE_BY4741 | yeast2 | SACCHAROMYCES_CEREVISIAE
PLASMODIUM_FALCIPARUM_3D7 | plasmodiumanopheles | HOMO_SAPIENS
ARABIDOPSIS_HALLERI | ath1121501 | DROSOPHILA_MELANOGASTER
ALOE_VERA | ath1121501 | DROSOPHILA_MELANOGASTER
ARABIDOPSIS_LYRATA_SUBSP._LYRATA | ath1121501 | DROSOPHILA_MELANOGASTER
MUSA_SP. | ath1121501 | DROSOPHILA_MELANOGASTER
MACACA_FUSCATA | rhesus | CHLOROCEBUS_SABAEUS
DROSOPHILA_YAKUBA | drosgenome1 | DROSOPHILA_MELANOGASTER
PSEUDOMONAS_AERUGINOSA_TBCF10839 | paeg1a | ESCHERICHIA_COLI
CARDAMINE_SP._SIM-2007 | ath1121501 | DROSOPHILA_MELANOGASTER
MUS_MUSCULUS_MUSCULUS_X_M._M._DOMESTICUS | mouse4302 | MUS_MUSCULUS
XENOPUS_LAEVIS_X_XENOPUS_BOREALIS | xenopuslaevis | MUS_MUSCULUS
PONGO_PYGMAEUS | hgu95av2 | HOMO_SAPIENS
OENOCOCCUS_OENI | yeast2 | SACCHAROMYCES_CEREVISIAE
ELYMUS_REPENS | barley1 | ZEA_MAYS
VIGNA_SUBTERRANEA | soybean | GLYCINE_MAX
OVIS_ARIES | bovine | EQUUS_CABALLUS
BRASSICA_NAPUS | ath1121501 | DROSOPHILA_MELANOGASTER
DROSOPHILA_SIMULANS | drosgenome1 | DROSOPHILA_MELANOGASTER
PSEUDOMONAS_AERUGINOSA_PA14 | paeg1a | ESCHERICHIA_COLI
BOS_TAURUS | bovine | OVIS_ARIES
SACCHAROMYCES_CEREVISIAE | yeast2 | MUS_MUSCULUS
XENOPUS_LAEVIS | xenopuslaevis | MUS_MUSCULUS
DANIO_RERIO | zebrafish | MUS_MUSCULUS
CAENORHABDITIS_ELEGANS | celegans | DROSOPHILA_MELANOGASTER
DROSOPHILA_MELANOGASTER | drosophila2 | MUS_MUSCULUS
SCHIZOSACCHAROMYCES_POMBE | yeast2 | SACCHAROMYCES_CEREVISIAE
PLASMODIUM_FALCIPARUM | plasmodiumanopheles | HOMO_SAPIENS
BOS_INDICUS | bovine | OVIS_ARIES
ANOPHELES_GAMBIAE | plasmodiumanopheles | HOMO_SAPIENS
LEPIDIUM_SATIVUM | ath1121501 | DROSOPHILA_MELANOGASTER
MACACA_FASCICULARIS | hgu133plus2 | MUS_MUSCULUS
PSEUDOMONAS_AERUGINOSA_PAO1 | paeg1a | ESCHERICHIA_COLI
MUS_MUSCULUS | mouse4302 | HOMO_SAPIENS

</details>

**Comment by jaclyn-taroni** [comment]
It does make a bit more sense to me -- mallard being measured on chicken, green monkey being measured on rhesus. But I'm not sure we want to give users domestic goat measured on human. If these are all the cases, this is a small enough number where we can make decisions "manually" in conjunction with how many samples meet these conditions (e.g., how many human samples are measured on `mouse4302`) provided we can easily get that information...

**Comment by arielsvn** [comment]
We want to update the algorithm that groups the organisms that should be merged when creating the compendiums.

- Remove the QN Targets that should not exist https://github.com/AlexsLemonade/refinebio/issues/1757

- Only consider organisms with QN Targets
    - Create groups with all other organisms that have the same Genus and have processed samples on at least one Microarray platform.

**Comment by arielsvn** [comment]
@jaclyn-taroni @jashapiro @cgreene I ran the updated algorithm and got the following organism groups for the compendiums, do they look reasonable?

```
['HOMO_SAPIENS']
['MUS_MUSCULUS', 'MUS_CAROLI', 'MUS_MUSCULUS_CASTANEUS', 'MUS_MUSCULUS_DOMESTICUS', 'MUS_MUSCULUS_MUSCULUS', 'MUS_MUSCULUS_MUSCULUS_X_M._M._CASTANEUS', 'MUS_MUSCULUS_MUSCULUS_X_M._M._DOMESTICUS', 'MUS_MUSCULUS_X_MUS_SPRETUS', 'MUS_SP.', 'MUS_SPRETUS']
['RATTUS_NORVEGICUS', 'RATTUS_NORVEGICUS_ALBUS', 'RATTUS_RATTUS']
['DROSOPHILA_MELANOGASTER', 'DROSOPHILA_MAURITIANA', 'DROSOPHILA_SANTOMEA', 'DROSOPHILA_SECHELLIA', 'DROSOPHILA_SIMULANS', 'DROSOPHILA_TEISSIERI', 'DROSOPHILA_YAKUBA']
['MACACA_MULATTA', 'MACACA_FASCICULARIS', 'MACACA_FUSCATA', 'MACACA_NEMESTRINA', 'MACACA_RADIATA']
['ARABIDOPSIS_THALIANA', 'ARABIDOPSIS_HALLERI', 'ARABIDOPSIS_HALLERI_SUBSP._GEMMIFERA', 'ARABIDOPSIS_LYRATA', 'ARABIDOPSIS_LYRATA_SUBSP._LYRATA', 'ARABIDOPSIS_LYRATA_SUBSP._PETRAEA', 'ARABIDOPSIS_THALIANA_X_ARABIDOPSIS_HALLERI_SUBSP._GEMMIFERA', 'ARABIDOPSIS_THALIANA_X_ARABIDOPSIS_LYRATA']
['GALLUS_GALLUS']
['DANIO_RERIO']
['SACCHAROMYCES_CEREVISIAE', 'SACCHAROMYCES_BAYANUS', 'SACCHAROMYCES_BOULARDII', 'SACCHAROMYCES_CEREVISIAE_BY4741', 'SACCHAROMYCES_CEREVISIAE_CEN.PK113-7D', 'SACCHAROMYCES_CEREVISIAE_EC1118', 'SACCHAROMYCES_CEREVISIAE_S288C', 'SACCHAROMYCES_CEREVISIAE_SK1', 'SACCHAROMYCES_CEREVISIAE_VIN13', 'SACCHAROMYCES_CEREVISIAE_X_SACCHAROMYCES_KUDRIAVZEVII', 'SACCHAROMYCES_PASTORIANUS', 'SACCHAROMYCES_PASTORIANUS_WEIHENSTEPHAN_34/70', 'SACCHAROMYCES_UVARUM']
['BOS_TAURUS', 'BOS_GRUNNIENS', 'BOS_INDICUS']
['ORYZA_SATIVA', 'ORYZA_LONGISTAMINATA', 'ORYZA_SATIVA_INDICA_GROUP', 'ORYZA_SATIVA_JAPONICA']
['ZEA_MAYS']
['SUS_SCROFA', 'SUS_SCROFA_DOMESTICUS']
['CAENORHABDITIS_ELEGANS']
['GLYCINE_MAX', 'GLYCINE_SOJA']
['OVIS_ARIES']
['EQUUS_CABALLUS']
['VITIS_VINIFERA', 'VITIS_AESTIVALIS', 'VITIS_CINEREA_VAR._HELLERI_X_VITIS_RIPARIA', 'VITIS_CINEREA_VAR._HELLERI_X_VITIS_RUPESTRIS', 'VITIS_CINEREA_VAR._HELLERI_X_VITIS_VINIFERA', 'VITIS_HYBRID_CULTIVAR', 'VITIS_RIPARIA', 'VITIS_ROTUNDIFOLIA']
['SCHIZOSACCHAROMYCES_POMBE', 'SCHIZOSACCHAROMYCES_POMBE_972H-']
['POPULUS_TRICHOCARPA', 'POPULUS_ALBA', 'POPULUS_BALSAMIFERA', 'POPULUS_DELTOIDES', 'POPULUS_EUPHRATICA', 'POPULUS_FREMONTII_X_POPULUS_ANGUSTIFOLIA', 'POPULUS_MAXIMOWICZII_X_POPULUS_NIGRA', 'POPULUS_NIGRA', 'POPULUS_SIMONII', 'POPULUS_SP.', "POPULUS_SP._CV._'OKANESE'", "POPULUS_SP._CV._'WALKER'", 'POPULUS_TOMENTOSA', 'POPULUS_TREMULA', 'POPULUS_TREMULA_X_POPULUS_ALBA', 'POPULUS_TREMULA_X_POPULUS_TREMULOIDES', 'POPULUS_TREMULOIDES', 'POPULUS_TRICHOCARPA_X_POPULUS_DELTOIDES', 'POPULUS_X_CANADENSIS']
['XENOPUS_LAEVIS', 'XENOPUS_BOREALIS', 'XENOPUS_LAEVIS_X_XENOPUS_BOREALIS', 'XENOPUS_LAEVIS_X_XENOPUS_MUELLERI', 'XENOPUS_MUELLERI']
['ANOPHELES_GAMBIAE']
['ESCHERICHIA_COLI', 'ESCHERICHIA_COLI_8624', 'ESCHERICHIA_COLI_APEC_O2', 'ESCHERICHIA_COLI_BW25113', 'ESCHERICHIA_COLI_B_STR._REL606', 'ESCHERICHIA_COLI_CFT073', 'ESCHERICHIA_COLI_K-12', 'ESCHERICHIA_COLI_O08', 'ESCHERICHIA_COLI_O157', 'ESCHERICHIA_COLI_SCI-07', 'ESCHERICHIA_COLI_STR._K-12_SUBSTR._DH10B', 'ESCHERICHIA_COLI_STR._K-12_SUBSTR._MC4100', 'ESCHERICHIA_COLI_STR._K-12_SUBSTR._MG1655', 'ESCHERICHIA_COLI_STR._K-12_SUBSTR._W3110', 'ESCHERICHIA_COLI_UTI89']
['TRITICUM_AESTIVUM', 'TRITICUM_CARTHLICUM', 'TRITICUM_MONOCOCCUM', 'TRITICUM_TURGIDUM', 'TRITICUM_TURGIDUM_SUBSP._DICOCCOIDES', 'TRITICUM_TURGIDUM_SUBSP._DURUM']
['MUSTELA_PUTORIUS_FURO']
['PSEUDOMONAS_AERUGINOSA', 'PSEUDOMONAS_AERUGINOSA_PA14', 'PSEUDOMONAS_AERUGINOSA_PAHM4', 'PSEUDOMONAS_AERUGINOSA_PAO1', 'PSEUDOMONAS_AERUGINOSA_TBCF10839', 'PSEUDOMONAS_AERUGINOSA_UCBPP-PA14', 'PSEUDOMONAS_PUTIDA']
['GOSSYPIUM_HIRSUTUM', 'GOSSYPIUM_ARBOREUM', 'GOSSYPIUM_BARBADENSE', 'GOSSYPIUM_HERBACEUM']
['HORDEUM_VULGARE', 'HORDEUM_VULGARE_SUBSP._SPONTANEUM']
['STAPHYLOCOCCUS_AUREUS', 'STAPHYLOCOCCUS_AUREUS_SUBSP._AUREUS_MU50', 'STAPHYLOCOCCUS_AUREUS_SUBSP._AUREUS_N315', 'STAPHYLOCOCCUS_AUREUS_SUBSP._AUREUS_RN4220', 'STAPHYLOCOCCUS_AUREUS_SUBSP._AUREUS_STR._NEWMAN', 'STAPHYLOCOCCUS_AUREUS_SUBSP._AUREUS_USA300']
['CITRUS_SINENSIS', 'CITRUS_CLEMENTINA', 'CITRUS_LIMON', 'CITRUS_MAXIMA', 'CITRUS_RETICULATA', 'CITRUS_RETICULATA_X_CITRUS_TRIFOLIATA', 'CITRUS_UNSHIU', 'CITRUS_X_PARADISI', 'CITRUS_X_TANGELO']
['LEPIDIUM_SATIVUM']
```

**Comment by jaclyn-taroni** [comment]
@arielsvn LGTM

**Comment by cgreene** [comment]
I agree - there are some things here that some folks might think are too far, but they can always filter those samples if they feel particularly strongly. Looks good!

**Comment by arielsvn** [comment]
#1753 should take care of bundling multiple organisms in the same compendia as long as they share the same Genus and at least one microarray platform.

All of these organisms will be stored in a `ComputedFileAnnotation`

**Comment by arielsvn** [comment]
Addressed by https://github.com/AlexsLemonade/refinebio/pull/1915 and https://github.com/AlexsLemonade/refinebio/pull/1753
