### ISSUE TITLE
Add data requests as tickets

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#1738]
### Context
We're getting to the point where posting data requests to slack isn't convenient anymore.

### Problem or idea

Add the data request as a ticket to github so science team can track and address them as they deem appropriate. 

Also, add the email addresses to a hubspot list so we can easily manage communications.

### Solution or next step
Tagging @arielsvn and @davidsmejia for next steps.

**Comment by dvenprasad** [comment]
related: https://github.com/AlexsLemonade/refinebio-frontend/issues/721

**Comment by kurtwheeler** [comment]
@dvenprasad do you have an existing hubspot list you'd like these to be added to? If not could you create one we can add requesters to?

Are we going to be able to tell which email address requested which dataset? I can't see any way to include that information in the list: https://developers.hubspot.com/docs/methods/lists/update_list

**Comment by dvenprasad** [comment]
Created a list called `CCDL-data-requesters`. 
I can add a contact property where we can populate the data request details.

Alternate proposal: I think we would need to create/update contact and update field, maybe? 
Then on the hubspot end, we can create a dynamic list which would populate a list based on whether data request details is populated or not. 
https://developers.hubspot.com/docs/methods/contacts/create_contact
