### ISSUE TITLE
Zip file is being generated twice for the compendia

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1752]
### Context

We reuse a lot of the smasher logic when creating the compendias

### Problem or idea

As part of the compendia creation process we call `_smash`

https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L62-L63

`_smash` generates a zip file for the dataset, then we ignore this file and create another one in the compendia

### Solution or next step

We should remove the compression part from `_smash`

**Comment by kurtwheeler** [comment]
My refactor already addressed this https://github.com/AlexsLemonade/refinebio/pull/1749
