### ISSUE TITLE
Why is there no chimp QN target?

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1756]
### Context

The frontend says we have ~300 chimp samples processed on an affy array, that should be sufficient to trigger a QN target.

### Problem or idea

We don't have a chimp QN target.

### Solution or next step

It's not clear that this is actually incorrect. All of the chimp samples the frontend reports are part of experiments that also contain human samples. Initial check looks like the chimp samples weren't actually process, the frontend is just reporting the human samples from those experiments as chimp since the experiment is for both.

Look into this and see if it's actually an issue that needs to be fixed.

**Comment by arielsvn** [comment]
Looks like we only have 64 processed samples for Chimp, all of them Microarray, so we shouldn't have QN targets for that organism.

```
>>> Organism.objects.get(name='CERVUS_ELAPHUS').sample_set.filter(is_processed=True).count()
64
```

@jashapiro had an idea to only index the experiments on the organisms that have samples processed. This could improve the accuracy of the numbers in the filters.

**Comment by kurtwheeler** [comment]
Awesome, nice work @arielsvn. I like that idea too! I'm gonna close this and make a new issue to improve the accuracy of the numbers in the filters.
