### ISSUE TITLE
Improve accuracy of sample numbers by organism in the filters

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1758]
### Context

https://github.com/AlexsLemonade/refinebio/issues/1756

### Problem or idea

It looks like we have a lot more chimp samples processed than we do. This is because the chimp samples belong to experiments that also contain human samples and those experiments are just reporting how many samples they have processed, despite the fact that (at least in some cases) all of those samples are actually human.

### Solution or next step

As mentioned here: https://github.com/AlexsLemonade/refinebio/issues/1756#issuecomment-540693551, @jashapiro had the idea that we should only index an experiment for an organism once that organism has at least one processed sample.

This won't make the numbers perfectly accurate, but it at least will prevent some experiments from contributing to the counts of an organism that they have zero processed samples for.

**Comment by jashapiro** [comment]
I don't think it was my idea...

**Comment by kurtwheeler** [comment]
Well you've got the credit for it now!!!!
