### ISSUE TITLE
Create an Executive Dashboard

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#177]
Our jobs are crunching nicely, but we don't have particularly good visibility into the state of the system. We should create an Executive Dashboard to give us insights into the health and state of our system.

The features that this dashboard should have include, but are not limited to:

* Length of Queues (Total and by Type)
* Estimated Time Til Completion (Total and By Type)
* Average Time of Task
* Number of Experiments/Samples Created
* Size of compute cluster
* Estimated cost of completion (Total and by Type)

It would be particularly good to have something of these metrics visualized, perhaps by using the [VX](https://github.com/hshoff/vx) library.

Another approach would be to use [Graphite](https://graphiteapp.org/) or [Prometheus](https://prometheus.io/docs/introduction/comparison/). Another another approach would be to use something hosted and proprietary like [DataDog](https://www.datadoghq.com/pricing/).

**Comment by Miserlou** [comment]
Another big one is jobs that failed/errored, and what those errors were (grouped, ideally).

**Comment by ramenhog** [comment]
Using evaluations for all calculations.

**Comment by Miserlou** [comment]
Decision was made to base this on custom API endpoints rather than raw Nomad endpoints, since Nomad is a Lovecraftian hellscape.

**Comment by ramenhog** [comment]
**Charts we want:**

1. Total Length of Queues segmented by Type - Pie
2. Size of Queues by Type over Time - Line
3. Percent Failed Segmented by Error Type - Pie 
4. Total Estimated Time Til Completion - Number
5. Estimated Time Til Completion for Job Type - Number
6. Median/Max/Min Time of Task - Numbers
7. Number of Experiments/Samples created over Time - Line
8. Total Number of Experiments/Samples created til now - Number
9. Size of computer cluster - Number
10. Estimated cost of completion - Number
