### ISSUE TITLE
Fix the unit tests

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1770]
### Context

The unit tests have been broken for a while on `dev`.

### Problem or idea

It makes it a lot harder to tell when we've broken something.

### Solution or next step

We should fix the tests on `dev`.

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio/pull/1742 should fix the main tests

**Comment by cgreene** [comment]
<img width="921" alt="Screen Shot 2019-10-14 at 11 54 01 AM" src="https://user-images.githubusercontent.com/542643/66765199-62598c00-ee79-11e9-9496-e192047838cf.png">

Success!

**Comment by arielsvn** [comment]
I think we still have some intermittent errors, got this now on the `common_smasher_tests`

```
======================================================================
ERROR: test_get_platform_from_CEL (data_refinery_common.test_microarray.MicroarrayTestCase)
----------------------------------------------------------------------

rpy2.rinterface.RRuntimeError: Error in loadNamespace(name) : there is no package called 'affyio'
```

**Comment by kurtwheeler** [comment]
I think this is a caching issue. What's the link for that circle run?

**Comment by arielsvn** [comment]
I re-ran it to see what happens, will keep an eye to see if it happens again.

Here's a similar failure, also from missing R packages, in `salmon_and_api_tests`  https://circleci.com/gh/AlexsLemonade/refinebio/24739?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by kurtwheeler** [comment]
Ok so I think there's one or more docker caching layer volumes with bad caches that think they're good. I think we need to bust those caches.

The easiest way we could do this would be add a cache busting command (literally `RUN echo 'cache busted'` in the Dockerfile) to those images above the R installation steps. Then we just have to run enough jobs with that line to be sure that we busted it on every Docker Caching Layer volume. Then we can remove the command from the Dockerfile to clean up.

Unfortunately this is going to make for two long deploys as we rebuild the images with/without the cache busting command.

**Comment by kurtwheeler** [comment]
![image](https://user-images.githubusercontent.com/4026833/68332667-3199fa80-00a5-11ea-92f9-8326f75cf8d9.png)

We have a whole page of green!! I'm gonna call this one done!
