### ISSUE TITLE
Unexpected Normalization Results

### ISSUE THREAD

**Issue by ben-heil** [AlexsLemonade/refinebio#1774]
### Context

Using the default parameters on the refine.bio website, I downloaded a dataset of RNA and microarray samples for use in a transfer learning model. When looking at the outputs of the model, I noticed that the RNAseq outputs were a few orders of magnitude higher than the microarray ones. On further investigation, I found that the this was because the RNA-seq data had much higher gene expression across the board. 

The documentation mentioned that there could be issues with genes with low expression, so I also checked the mean expression of the housekeeping gene GAPDH (ENSG00000111640). Where the microarray samples had an average expression of 4.8, the RNA-seq samples had an average of 13338.

More details on the context here: https://github.com/greenelab/whistl/issues/1

### Problem or idea

It may be the case that this is intended behavior, and I don't understand quantile normalization well enough to recognize it. If so, then this isn't a problem so much as an observation. If not, then maybe something went wrong in normalizing the data from SRP049820 and  SRP132709.

### Solution or next step

Depends on whether this is the expected behavior. Further investigation I guess?

**Comment by cgreene** [comment]
This sounds like data that are not quantile normalized.

**Comment by cgreene** [comment]
I just created a dataset aggregated by experiment. https://www.refine.bio/dataset/168f1568-ec14-43b0-a8a9-626348d18226

I did not click any of the advanced options, such as don't QN. The data are not quantile normalized though.

Array:
<img width="635" alt="Screen Shot 2019-10-14 at 3 51 55 PM" src="https://user-images.githubusercontent.com/542643/66778737-9a24fb80-ee9a-11e9-81d3-0805c65481bb.png">


RNA-seq:
<img width="701" alt="Screen Shot 2019-10-14 at 3 51 49 PM" src="https://user-images.githubusercontent.com/542643/66778747-9f824600-ee9a-11e9-8f66-462102aa9196.png">

**Comment by arielsvn** [comment]
Thanks for reporting this @ben-heil. We just pushed a fix for this, you should be able to get quantile normalized data now. Let us know if you have any other issues.

**Comment by ben-heil** [comment]
Awesome, thanks for the quick response!

**Comment by ben-heil** [comment]
I created [a new dataset](https://www.refine.bio/dataset/351ab01e-795d-44fc-867a-90d6ebdcfbd9) redownload the RNAseq samples, and now the download page threw a 'Failure reason: 'float' object cannot be interpreted as an integer' error

**Comment by kurtwheeler** [comment]
@ben-heil sorry about that, we released a bug yesterday that broke out dataset download code. I've since triggered your job for reprocessing, it completed successfully, and it is ready for download!

**Comment by ben-heil** [comment]
Great, thank you!
