### ISSUE TITLE
Sample metadata files for download after aggregation

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#178]
### Problem or idea

When we do aggregations across experiments, how do users receive the sample metadata? 

### Context

For example, let's say a user has chosen to aggregate all samples from Experiment A and a subset of 5 samples from Experiment B. When they download the data, should they receive a zip file containing a files with each sample's metadata or should they receive a zip file with a single file containing all samples' metadata from A and 5 files for the sample metadata from B? 

### Solution or next step

@jaclyn-taroni suggested that they receive two files containing sample metadata from each experiment. Tagging @Miserlou for an implementation perspective.

**Comment by jaclyn-taroni** [comment]
Related: #221

**Comment by dvenprasad** [comment]
The users will receive two files containing sample metadata from each experiment.
