### ISSUE TITLE
Redirect to latest version of the API when people use unversioned endpoint

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1795]
### Context

Our API is versioned with endpoints like 

https://api.refine.bio/v1/transcriptome_indices/

### Problem or idea

The docs have a lot of endpoints that reference unversioned endpoints like

https://api.refine.bio/transcriptome_indices/?organism=DANIO_RERIO&length=LONG

Which now returns 404, we should automatically redirect to the latest endpoint version if someone uses those.

### Solution or next step

We need to investigate if there's a recommended approach to implement this.

**Comment by cgreene** [comment]
Update the docs, but if someone goes to an unversioned endpoint potentially return something more specific than a generic 404.

**Comment by cgreene** [comment]
Closed by #2001
