### ISSUE TITLE
GSE13015 Missing data

### ISSUE THREAD

**Issue by ben-heil** [AlexsLemonade/refinebio#1832]
### Context

I was looking through the data again, and I found that GSE13015 was missing data for a bunch of genes. Here's an expression heatmap for the first 100 genes for each of the 39 samples for context:

![image](https://user-images.githubusercontent.com/15317110/67572498-4d47ed00-f704-11e9-861a-cb44ae76c235.png)
 

### Problem or idea

More of a question than a problem: is this kind of data missingness expected for a beadchip study?

### Solution or next step

If this is expected behavior I'll leave the sample out of my analysis (unless there's a good way to impute that much missing gene expression data?)

Otherwise I'll redownload the sample after a bug fix

**Comment by jaclyn-taroni** [comment]
Hi @ben-heil, I've taken a quick look at this experiment on GEO. The raw data is not in a form that we would have been able to process and the submitter-processed data also looks different than I would expect. This accession is also no longer available at ArrayExpress. I would not recommend including this experiment in your analysis.

**Comment by jaclyn-taroni** [comment]
Based on what I found on GEO, my intuition is that this experiment was made available due to a failure to fail in our submitter-processed/NOOP pipeline.

**Comment by ben-heil** [comment]
Okay, thanks for your help!
