### ISSUE TITLE
Validate that the newest rat compendia is equivalent to previous ones

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1835]
### Context

We've been creating rat compendias as we've iterated on the compendia code because it's a good size for testing. https://github.com/AlexsLemonade/refinebio/pull/1820 dramatically changed the way we build the matrix.

### Problem or idea

Rather than repeatedly calling `merge` or using `concat`, we instead are sorting each sample's data by the gene identifiers and directly assigning the values in a preallocated matrix. This should work correctly, but we should make sure because if we did something wrong then we'll just have mangled the data in hard-to-detect ways.

### Solution or next step

Look at a rat compendia that was generated before that change and look at another that was generated after. They should be either identical or nearly-identical with a low error margin.

**Comment by davidsmejia** [comment]
So this looks pretty good. I checked two versions of the rat compendia. 

Older Rat Compendia id is `5732534`
Latest Rat Compendia id is `5732599`

```python 
import pandas as pd

new = pd.read_csv('new.tsv', sep='\t')
old = pd.read_csv('old.tsv', sep='\t')

old.equals(new) # returns false

corr = new.corrwith(old, index=1, method='pearson') # index=1 is by column so sample here

corr.max() # 1.0000000000000004
corr.min() # 0.9999999999999996

**Comment by cgreene** [comment]
Oh good! I daresay those correlations are quite high!

**Comment by kurtwheeler** [comment]
Woooo!!! Nice work David!!
