### ISSUE TITLE
Structuring content for Docs page

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#184]
### Problem or idea

We need to come up with a list of topics which will be placed on the Docs page on the GUI to help users:

- Understand how refine.bio is getting the data: What are the sources, how are we choosing the datasets, etc. 

- Understand what they are downloading. i.e details of processing information (Ex: difference between aggregatable and non-aggregatable) and rationale behind some of the choices (if needed) 

- Understand the options of available download files

-  Some uses cases illustrating different ways users can use the data.

### Solution or next step

Have a TOC (table of contents) laid out so we start working on copy for documentation.
Tagging @jaclyn-taroni and @cgreene to help identify what should go in the Docs page.

**Comment by cgreene** [comment]
Some thoughts:

* What type of data does refine.bio support?
* Where does refine.bio get data from?
* What can I download from refine.bio?
* How do you process the data?
* Why are some datasets listed as "non-mergeable"? (thinking this might be a better word than aggregatable, but happy to go to that if preferred)
* What have people done with downloaded files?
* What are metadata? What do we know about each assay?
* What does "Corrected" metadata mean?
* What does "Predicted" metadata mean?

(we can fill in "predicted" for the version when we start doing that / we should probably mark metadata fields that we have "corrected" from the source just in case the user sees a mismatch with what's in GEO/ArrayExpress/SRA/ENA/etc).

**Comment by jaclyn-taroni** [comment]
I agree with @cgreene's thoughts above. 

> What have people done with downloaded files?

This refers to _Some use cases illustrating different ways users can use the data_, is that correct?

**Comment by dvenprasad** [comment]
How do I cite data from refine.bio?

**Comment by dvenprasad** [comment]
How do I cite data from refine.bio?

**Comment by cgreene** [comment]
@jaclyn-taroni : yup - that was the use cases thing. and @dvenprasad : very important & I agree 👍

**Comment by cgreene** [comment]
btw we should note for #165 that we may want to track what we corrected from a provenance point of view so that we can put a little note to the user

**Comment by dvenprasad** [comment]
Proposed TOC:
- Source Data
  - Types of Data
  - Sources
  - Metadata
        - Submitter Supplied
        - Corrected Metadata
        - Predicted Metadata

- Downloadable Files
  - Gene Expression Matrix
  - Sample Metadata
  - Quality Reports

- Citing refine.bio

- Processing Information
  - refine.bio/CCDL processed
     - RNA-seq pipelines
    - microarray pipelines
    - Recommended pipeline
  - Submitter Processed
  - Aggregations
    - Aggregatable 
    - Non-Aggregatable

- Use Cases for Downstream Analysis

In addition, we can compile an FAQ and add it to the docs page. Some of the questions could be:
- What is the difference between refine.bio/CCDL processed and Submitter Processed datasets?
- What does a recommended pipeline mean?
- Why are some datasets listed as "non-mergeable"/non-aggregatable?
- How do you process the data?
- What type of data does refine.bio support?
- What does "Corrected" metadata mean?
- What does "Predicted" metadata mean?

**Comment by dvenprasad** [comment]
How can I link the sample metadata file to the Gene expression Matrix? 

@cgreene mentioned this in the design review. The docs seem to be the best place to capture it so we can direct users to it.

**Comment by cgreene** [comment]
@ramenhog : what would you like us to use to write the docs so that they integrate well into the website?

**Comment by jaclyn-taroni** [comment]
@dvenprasad thinks this is in a good enough spot for now so I will close it.
