### ISSUE TITLE
Nested Metadata Information: Examples

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#185]
### Problem or idea

We were in the design review and a question came up about the nested metadata. What is there? We need a few examples to decide what we should do with this and how prominently it should be displayed.

### Context

This is a request for information.

### Solution or next step

Please export some examples from a few of the nested metadata fields. Next step to find examples: @dvenprasad

**Comment by dvenprasad** [comment]
I cannot find other nested data apart from bioassaydata. I'm looking at the data from the neuroblastoma crunch.

**Comment by cgreene** [comment]
🎉  I think this makes our lives easier. I'm going to close this. I don't think that data in particular needs to make it into the display to the users.
