### ISSUE TITLE
Find needs of MultiQC

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#187]
### Problem & context

We would like to provide quality control reports for samples. [MultiQC](http://multiqc.info) provides this capability for RNA-seq experiments. See [example report](http://multiqc.info/examples/rna-seq/multiqc_report.html).

### Solution or next step

The purpose of this ticket is to track what types of input MultiQC accepts and what we're interested in serving up.

**Comment by jaclyn-taroni** [comment]
Why is this labeled for `VJackieP2` @cgreene? This particular tool will be useful for RNA-seq data. Should we file another ticket for Agilent quality measures (don't yet know what those would be off the top of my head) for this milestone?

**Comment by cgreene** [comment]
It seemed like it'd be nice to know by the time we wrap up that milestone, because VJackieP3 has the wrapping up the salmon processor as part of it. I wanted us to know what we needed for multi-QC before that.

**Comment by jaclyn-taroni** [comment]
Gotcha!

**Comment by jaclyn-taroni** [comment]
In general, it seems that (see: http://multiqc.info/docs/#running-multiqc) MultiQC will parse any log files in the `analysis directory` you give it.

#### [Salmon](https://github.com/ewels/MultiQC/tree/3d719e94b53a4d34f9267db06fdcff028b0287ce/multiqc/modules/salmon)

Here's a report I generated for one sample: [multiqc_report.html.zip](https://github.com/AlexsLemonade/refinebio/files/1889827/multiqc_report.html.zip)

This corresponds to this sample: [`jaclyn-taroni/ref-txome/athaliana/quants/SRR074262_quant`](https://github.com/jaclyn-taroni/ref-txome/tree/79e2f64ffe6a71c5103a150bd3159efb784cddeb/athaliana/quants/SRR074262_quant).

It looks to me that the main info/files that it is presenting are 1) the fragment length distribution from [`libParams/flenDist.txt`](https://github.com/jaclyn-taroni/ref-txome/blob/79e2f64ffe6a71c5103a150bd3159efb784cddeb/athaliana/quants/SRR074262_quant/libParams/flenDist.txt) and 2) the `percent_mapped` and `num_mapped` from [`aux_info/meta_info.json`](https://github.com/jaclyn-taroni/ref-txome/blob/79e2f64ffe6a71c5103a150bd3159efb784cddeb/athaliana/quants/SRR074262_quant/aux_info/meta_info.json) 

As noted in https://github.com/AlexsLemonade/refinebio/issues/131#issue-298390191, we likely want to include information about the inferred library type & strand mapping bias that is not captured with this tool currently.

**Comment by Miserlou** [comment]
Upstream seems very open to new features if you want to try to move our needs upstream. I'd love to have all of our QC stuff handled by a single tool.

**Comment by jaclyn-taroni** [comment]
Prior to running Salmon, we might consider running [FastQC](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/) on the compressed (.gz) FASTQ files 

#### [FastQC](https://github.com/ewels/MultiQC/tree/3d719e94b53a4d34f9267db06fdcff028b0287ce/multiqc/modules/fastqc)

I think users will be most interested in the following QC information:

* [Sequence duplication](http://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/8%20Duplicate%20Sequences.html)  
* GC content: [% GC](http://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/1%20Basic%20Statistics.html) & [Per Sequence GC Content](http://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/5%20Per%20Sequence%20GC%20Content.html) (note `salmon quant` will be run with `--gcBias` for paired-end samples)
* [Per sequence quality scores](http://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/3%20Per%20Sequence%20Quality%20Scores.html)

MultiQC displays all of this information (and more).

**Comment by jaclyn-taroni** [comment]
_Some future considerations_: We plan to filter the input FASTQ files to only the reads _unmapped_ by Salmon (#83) and we can then use this for quality control by aligning them to the genome with [STAR](https://github.com/alexdobin/STAR) (#84). MultiQC has a [STAR module](https://github.com/ewels/MultiQC/tree/3d719e94b53a4d34f9267db06fdcff028b0287ce/multiqc/modules/star) (docs [here](http://multiqc.info/docs/#star)).

The STAR % Aligned is displayed in the [General Stats](http://multiqc.info/examples/rna-seq/multiqc_report.html#general_stats) table of the report. That is also the case in the Salmon report I posted. So we'll need to keep in mind how to display this information, as we're not doing the STAR alignment on the entire set of reads and that could get confusing for users.

**Comment by jaclyn-taroni** [comment]
Closing this for now as we've reached the immediate goal
