### ISSUE TITLE
Staging deploys not working - might also affect prod?

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1879]
### Context

We tried to deploy staging several times but it [failed](https://circleci.com/gh/AlexsLemonade/refinebio/26390)

### Problem or idea

Looking into the logs for this deploy, I found an error:

```
1 error(s) occurred:

* aws_iam_policy_attachment.fleet_role: 1 error(s) occurred:

* aws_iam_policy_attachment.fleet_role: [WARN] Error attaching policy with IAM Policy Attachment EC2SpotFleetRole:
– NoSuchEntity: Policy arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetRole does not exist or is not attachable.
        status code: 404, request id: d8eef2b5-6b33-43c2-ae7c-a9e0d2eedb27
```

### Solution or next step

Not sure how to proceed here as I couldn't find any articles on how to fix this. Except for [one forum](https://forums.aws.amazon.com/thread.jspa?messageID=922505&tstart=0) where they said the policy is deprecated?

/cc @kurtwheeler

**Comment by arielsvn** [comment]
Looks like we could solve this by using `AmazonEC2SpotFleetTaggingRole` instead of `AmazonEC2SpotFleetRole`. [ref](https://docs.aws.amazon.com/batch/latest/userguide/troubleshooting.html#spot-instance-no-tag)

**Comment by kurtwheeler** [comment]
This worked!! The last deploy succeeded!
