### ISSUE TITLE
Refactor logic which determines what should be done with a given experiment

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#188]
### Problem or idea

Currently the logic of what should be done with an experiment is scattered across the surveyors which makes it hard to track down what's going on when there's unexpected behavior.

### Context

There's two different ways that the surveyor logic is scattered:
* One is that there are three management commands based on what source the data is coming from.
* The other is that once a survey job starts for a given experiment, logic is performed to see what should be done with it.

### Solution or next step

I think there should be a single component which is responsible for determining what should be done with a given experiment. I can think of two options to accomplish this:
1. Having a single point of entry which makes a request, parses out enough information to decide what to do, and then performs logic to determine what should be done and then fire off the correct surveying code.
2. Have a single module which contains similar logic, but can be called from various surveyors and then return what should be done.

I think I like the latter method for managing pipeline logic more I think. However I think it's actually useful to have different management commands for different sources so we can have different help texts for them and already with only three sources they have different parameters. Shoehorning them into a single command would probably be messier than it is now. Therefore what I propose is to create a function which accepts:
* source_type
* platform
* has_raw
* has_processed
   
as arguments and returns a pipeline that should be run on that experiment along with a field which indicates whether raw or processed data should be downloaded.

**Comment by kurtwheeler** [comment]
@Miserlou and @dongbohu I think I am going to try to implement my proposed solution this weekend. If either of you have any strong feelings that I should do this in a different way it'd be great to hear about them before I implement this. However it is Friday evening so if you don't get back to me I'll just do this and if there's changes I need to make I'll make them.

**Comment by cgreene** [comment]
When you say surveyor here, do you mean processor: "once a survey job starts for a given experiment"?

My impression is that surveyors look at endpoints and identify what's there. Downloaders download. Then things would get kicked to one or more processors. Some of the "what should we do" logic is going to have to rest within a processor because it will depend, in part, on some of the analyses of the data itself.

**Comment by kurtwheeler** [comment]
> Then things would get kicked to one or more processors.

Which processor does it get kicked to though? This is determined by a combination of metadata and whether or not there is raw data available (which generally is also conveyed in the form of metadata). The surveyor is already gathering, parsing, and storing metadata about the experiment so it's a great time to figure out which processor it should be kicked to once it's been downloaded. If the actual data itself needs to be analyzed to determine what to do with it, then we can have the surveyor assign it to a processor capable of doing so. At the moment though I'm not aware of any scenarios we've yet run into which require that processor-picks-a-processor flow.

**Comment by kurtwheeler** [comment]
> Building it into the surveyors seems like it might vary per resource.

I think this is true and I'm not sure how to avoid it. I think it makes sense to keep as much of the logic in the surveyor as possible for the following reasons:
* It will make debugging somewhat easier to have the logic triggered sooner rather than later. If there's a bug in the logic we'll be able to see it immediately rather than the experiment making it halfway through the system.
* Having a consolidated location for this kind of logic will make it much easier to debug when things go wrong because we'll know where to look and have a single flow which decides as much as possible that we can trace bad examples through to determine what goes wrong.
* What data the Downloader should obtain also needs to be decided. Based on what is available for a given experiment we may want to download different things. One example is that if there's no raw data then often we want to download the processed data and no-op it. The decision to download processed data is very much linked with the decision to no-op it, so it seems to make the most sense to just figure that out once.

Ultimately I think there are two points we won't be able to avoid including routing logic. One is at the beginning because we have to decide what data we want to download or even if the experiment is appropriate for us to do anything with. The other is once we have the data downloaded because there will be times when we need to look at the data itself to decide exactly what a processor should do. Given a choice between the two places to have the bulk of the logic live I would prefer to have it happen as soon as possible.

**Comment by cgreene** [comment]
I'm a little skeptical that it will make debugging easier. To an extent, this may depend on how much of the logic ends up built into reusable functions that are shared across surveyors and how much ends up within each surveyor in a way that is unique to that surveyor. It also depends how easy we make it to debug the processors via logging, rerunning, etc.

I'd lean towards a surveyor that is responsible for comparing against the processor-known list, the can aggregate list, and the no-op list. For RNA-seq data I think it should check that things are from a species we have an index for.

I think the next steps are:
* Whitelisted platform -> use assigned processor.
* no-op combinable -> use id-fixer processor
* no-op not combineable -> use no-op processor

For the whitelisted platforms & processable species, RNA-seq data will be a bit different. On those, we'll need to send things first to a QC runner / RNA-seq router processor. That one will likely be the best option to determine next steps (i.e., salmon, quit & run screaming, etc).

I would be wary of building more routing logic than this (or what is absolutely necessary to decide whether or not something should be initially downloaded) into the surveyor.

**Comment by kurtwheeler** [comment]
It seems to me that we're saying the same thing. What you've specified in further detail here is essentially one example of what I was proposing to do for everything. (Everything meaning Array Express, SRA, and Transcriptome since surveyors are oriented around the source of the data rather than the type.)

> I would be wary of building more routing logic than this (or what is absolutely necessary to decide whether or not something should be initially downloaded) into the surveyor.

I'm not sure what other routing logic there is left.

**Comment by cgreene** [comment]
Ok 👍 . There will be additional routing for deciding what to do based on QC - largely for RNA-seq samples.

**Comment by kurtwheeler** [comment]
This ticket has been struck by the scope-creeper!!!

When I first started poking at this my intention was to just refactor existing logic into a consolidated location. After a conversation or two with @Miserlou we came up with a very good way to rework a lot of the logic and to improve some of the models along the way. The plan we came up with was:
- [ ] Move the technology, platform_name, and platform_id fields to be sample-specific
- [ ] Store the machine/chip for each sample.
- [ ]  Next, we need to add the sequencer whitelist to the project.
- [ ] Use the two whitelists to determine the manufacturer by checking which list the machine/chip is in.

Once we've accomplished those we'll know the following fields for every sample:
* The Technology (MicroArray or RNASeq)
* The manufacturer
* The source (Geo, AE, or SRA)
* Whether there is raw data or not.

These four fields should be enough to determine the appropriate processing to do with each sample. However while attempting to implement the first step, moving platform-related properties to the sample level, I ran into some issues with the way we're determining the platform for Array Express. For starters, any time a single experiment had more than one platform we didn't determine the platform in the surveyor. Next, there is an issue where the metadata about samples doesn't always have the correct platform. After looping @jaclyn-taroni into the conversation the following was determined:
* We should be using brainarray-friendly platform names (i.e. `hgu133plus2`) as the values for platform-name. These can be determined by parsing the .CEL files, which means that they are the most reliable we'll get.
  * However, the only way we have to generate these values is by parsing the CEL header and that header doesn't contain any other platform information.
  * However, @jaclyn-taroni is creating a set of mappings between GEO platform accessions, brainarray-friendly names, and Array Express accession.
* So with those mappings we can get the platform name out of the metadata, determine the corresponding brainarray-friendly platform name, check if we support it, and then if so download the raw data.
* Once we've downloaded the raw data we can read the CEL header to determine if the metadata was correct or not. If its not correct, we'll update the field on the sample.
* There is an assumption baked into this plan that when the metadata about platform accessions is wrong, it won't be so wrong that we'll have thought we could support it but cannot or vice versa. If this assumption is wrong, it will hopefully be in a very small number of cases which we can worry about later.

I believe that this metadata-correction work probably constitutes it's own ticket, which will need to be completed before this one can.

**Comment by jaclyn-taroni** [comment]
I will note explicitly that the CEL header bit is only relevant for Affymetrix.
