### ISSUE TITLE
We should display the backend & frontend versions somewhere on the page

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#190]
### New Issue Checklist
- [x] The title is short and descriptive
- [x] The issue contains an:
  - [x] Idea (new feature, user story, etc)
  - [ ] Problem
- [x] You have explained the:
  - [x] Context
  - [x] Problem or idea
  - [x] Solution or next step

### Context

In Cognoma, there was some question about which backend/frontend were deployed. This led to some time spent trying to track that down

### Problem or idea

Since the GitHub repos are not linked, it'd be handy if both the UI and the backend exposed version information.

### Solution or next step

The refine.bio page would - somewhere - have version information for both the backend and frontend on it. Maybe out of the way at the bottom. The API would have a documented endpoint to snag version info.

**Comment by dvenprasad** [comment]
This requirement has been noted and designed for in #269 . The version information will be displayed in the footer.
