### ISSUE TITLE
Smasher jobs don't mark datasets as failures when they fail

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1923]
### Context

There's a couple places in the smasher code where we delay failing the job so that the job can make it to the `_notify()` function so it can let the user know that their dataset failed to process.

### Problem or idea

The job eventually gets marked as a failure like we want. However the dataset object does not, nor does the failure_reason get set on the dataset object. This means that the frontend just forever shows the dataset as processing.

### Solution or next step

Fix this bug by fixing the smasher's flow. Doing it like that is such a hack. We should have two notify functions, one for successes, one for failures. If the job fails we should call the `_notify_failure()` function and then properly exit the processor, setting the `failure_reason` and `success` fields of the dataset object. If we succeed then the pipeline should be allowed to continue to the `notify_success()` function.

**Comment by arielsvn** [comment]
This is one of the datasets that failed and still shows as processing https://www.refine.bio/dataset/e3bb15c7-2aa8-44b2-84d2-b24ff8091b8c
