### ISSUE TITLE
Comendium Results Svd Algorithm had a typo 

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#1927]
### Context

svd_algorithm was not correctly set on compendium_result records

### Problem or idea

We need to write a migration that copies the `computed_file.svd_agorithm` to `compendium_result.svd_algorithm` before we remove those columns. 

### Solution or next step

Make a PR that batch updates the ~250 compendium results.

**Comment by cgreene** [comment]
Fixed by #1928
