### ISSUE TITLE
Certbot didn't get installed or run on API instance

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1934]
### Context

#1933 

### Problem or idea

I fixed 1933 by installing and running certbot. It's in the API startup script, so I'm not sure why it didn't happen during the deploy.

### Solution or next step

Figure out why it didn't happen and make sure it does in the future.

**Comment by cgreene** [comment]
Did this work on your most recent deploys?

**Comment by kurtwheeler** [comment]
Indeed it did! 

However that makes figuring out why it didn't a while ago really hard :(
