### ISSUE TITLE
Compendium Missing Generated File

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#1962]
### Context

`RATTUS_NORVEGICUS/rattus_norvegicus.tsv` is missing.

<img width="832" alt="Screen Shot 2019-11-27 at 10 29 50 PM" src="https://user-images.githubusercontent.com/1075609/69775087-ae306e00-1165-11ea-9a64-1035c56ea079.png">

### Problem or idea

This should be included. I looked it up, I removed this when removing the s3 copy to remove the extra computed files.
This means that any compendia generated in the past 9 days are not available as well.

### Solution or next step

Deploy fix for compendia output file.
I will add a list of compendia here that need to be regenerated.
Regenerate those compendia.

**Comment by cgreene** [comment]
Closed by #1963
