### ISSUE TITLE
The annotation package, pd.huex.1.0.st.v1, could not be loaded

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1986]
### Context

I'm seeing this error message in our logs:
```
2019-12-09 01:39:11,785 i-056f1616d982e5f85 [volume: 0] data_refinery_workers.processors.utils ERROR [processor_job: 29527291] [failure_reason: Encountered error in R code while running AFFY_TO_PCL pipeline during processing of /home/user/data_store/GSE56583/GSM1364698_h_10282009_5-21-10_S2.CEL: Error in { :
  task 1 failed - "The annotation package, pd.huex.1.0.st.v1, could not be loaded."
]: Processor function _run_scan_upc failed. Terminating pipeline.
```

Most likely related to #1831 

### Problem or idea

We have the HUEX v2, but not v1 it looks like: https://github.com/AlexsLemonade/refinebio/blob/dev/workers/affymetrix_dependencies.R#L126

Bioconductor has v2 but not v1 it seems:
  * https://bioconductor.org/packages/release/data/annotation/html/pd.huex.1.0.st.v2.html works but
  * https://bioconductor.org/packages/release/data/annotation/html/pd.huex.1.0.st.v1.html doesn't
  * A search for pd.huex.1.0.st https://bioconductor.org/help/search/index.html?q=pd.huex.1.0.st/ only returns results for v2.

### Solution or next step

I'm not sure.

@jaclyn-taroni any ideas? Do you know another place we could try to get the CDF for v1 for this platform?

**Comment by cgreene** [comment]
This makes it sound like there will not be a CDF for v1 of this platform, but it may be safe to override and use v2:
http://aroma-project.org/chipTypes/HuEx-1_0-st-v2/

**Comment by cgreene** [comment]
I talked with @jaclyn-taroni and she says we should do this override 👍

**Comment by cgreene** [comment]
Figure out if this is why #1691 didn't fully process. We would ideally like to find an experiment run with v1 and v2 together. We'd like to process that on staging by renaming the CDFs. Then we'd like to look at gene expression from both sets and make sure the values aren't widely divergent.

**Comment by cgreene** [comment]
@jaclyn-taroni says there's an instance where we sanitize what comes off the CEL header and this is a similar issue

**Comment by kurtwheeler** [comment]
We already have a function that does special conversion of Affy platforms here: https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/array_express.py#L78

I think we just have to add an extra check in there.

**Comment by davidsmejia** [comment]
Wow this is turning out to be quite the rabbit hole. Looks like the current fix for this will work but I am experiencing the same issue as here: https://github.com/AlexsLemonade/refinebio/issues/1538

Not really sure what to do about this. I re-queued 1368 samples with the override and all of them appear (I haven't checked all of them) to be unable to get to processing with the following errors: 

`Was told to redownload file(s) that are already downloaded!`
`Failed to extract any downloaded files.`

Not sure about next steps outside of debugging retrying GEO downloader jobs...
I do have a suspicion that this will work if we scale down and then back up and then re-queue the samples. 🤷‍♂
