### ISSUE TITLE
Create additional environments for local/staging and make environments better!

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#199]
### Context

We do not have enough environments! We currently have `test`, `dev`, and `prod`. `test` is appropriate for running tests, `dev` is appropriate for local development, and `prod` is appropriate for cloud development.

### Problem or idea

In https://github.com/AlexsLemonade/refinebio/pull/192#pullrequestreview-110516826 Rich points out that this is not sufficient. We need to have the following environments in total:

```
test
local
dev
staging
prod
```

### Solution or next step

Create the `local` and `staging` environments, make them work correctly, and test that everything works. I think that at the current `dev` environment is actually what we want `local` to be, and that the current `prod` environment is what we actually want `dev` to be. Therefore the way I think this issue should be approached is to change `dev` to `local`, change `prod` to `dev`, and then create `staging` and `prod` from scratch.

**Comment by jaclyn-taroni** [comment]
Was this closed by #315? If not, let's update this to note what still needs to be done.

**Comment by kurtwheeler** [comment]
This was closed... I thought I had closed this before. Oh whelp.
