### ISSUE TITLE
Transcriptome index endpoint is broken

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1993]
### Context

https://api.refine.bio/v1/transcriptome_indices/HOMO_SAPIENS?length=short

returns 

```
{
    "detail": "Not found."
}
```

### Problem or idea

We have a transcriptome index for human:
```
data_refinery=> select id from organisms where name='HOMO_SAPIENS';
 id 
----
 57
(1 row)

data_refinery=> select count(*) from organism_index where organism_id =57;
 count 
-------
     4
(1 row)
```

### Solution or next step

Why doesn't this endpoint return anything? Figure that out and fix it!

**Comment by davidsmejia** [comment]
This has been merged with #2012

**Comment by cgreene** [comment]
Just tested - working! 👍

**Comment by cgreene** [comment]
Docs update needed to get folks to the correct URL: https://github.com/AlexsLemonade/refinebio-docs/pull/125

**Comment by cgreene** [comment]
This is the current URL for the resources described above: https://api.refine.bio/v1/transcriptome_indices/?organism_name=HOMO_SAPIENS&length=SHORT
