### ISSUE TITLE
Statuscake didn't alert us that the API was down all night

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1997]
### Context

I got a slack message this morning asking when the API might come back up.

### Problem or idea

That was the first I had heard that it was down. I thought we had statuscake set up so that our users wouldn't be the first to notify us when our API is down.

### Solution or next step

Fix statuscake again. If it's not already configured to do so, send it to #ccdl-general and #devops so that it doesn't get lost in the spam that's in #robots

**Comment by cgreene** [comment]
Also let's set up an EC2 health check.

**Comment by davidsmejia** [comment]
This should be fixed, I the StatusCake alerts were paused... 🤦‍♂

**Comment by cgreene** [comment]
I think there was a deploy yesterday. API is back up but I didn't see any statuscake alerts. Was this because we weren't down for 15 mins?

**Comment by davidsmejia** [comment]
Yeah i saw statuscake pinging the api in the logs. So I'm pretty sure it was just back up too quick to not be picked up.
