### ISSUE TITLE
We need a mechanism to prevent master Docker images from being overwritten

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#200]
### Context

Currently, any tagged commit whose tag starts with letter `v` will trigger a rebuild of Docker images resulting in new Docker images with tags matching the commit's tag.

### Problem or idea

If someone were to tag a commit with an identical tag to the tag of the Docker image that is currently being used by production, then the production images would be overwritten by that code. This could happen on any commit to the repo.

### Solution or next step

We need a way to make sure that Docker images built by commits to master cannot be overwritten by any other commit.

**Comment by dongbohu** [comment]
One workaround: if Docker Hub API provides a way to allow CircleCI know whether a certain image (including its tag) already exists, then CircleCI can skip the re-build process if it overwrites an existing image.

**Comment by kurtwheeler** [comment]
Yeah that seems like a solid solution. Make all the images immutable! Looks like this will check if the image:tag exists: https://stackoverflow.com/questions/32113330/check-if-imagetag-combination-already-exists-on-docker-hub

I <3 immutability!

**Comment by dongbohu** [comment]
Looks good. I will play with it tomorrow.

**Comment by dongbohu** [comment]
Fixed in #208.
