### ISSUE TITLE
Bump Django Version

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#2003]
### Context

#1975 #1976 #1977 #1978 #1979

### Problem or idea

_The context should lead to something, an idea or a problem that you’re facing. Put that here._

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by kurtwheeler** [comment]
Closed by https://github.com/AlexsLemonade/refinebio/pull/2011
