### ISSUE TITLE
Create a sketch file containing JSON which is returned by the API

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#201]
### Context

@dvenprasad has said that having a sketch file containing JSON that was returned by the API would help her figure out what kind of text will go into the design prototypes she's been creating.

### Problem or idea

We should hit our local API to get some JSON responses and then put them into a sketch file. I'm not exactly sure what that entails so part of this is figuring that out.

### Solution or next step

It seems as though @ramenhog may be the best person for this task. @dvenprasad can help provide more details as necessary. I'm not super clear on details more than that.

**Comment by ramenhog** [comment]
Is this what you're thinking of @dvenprasad ?

**Comment by dvenprasad** [comment]
It's more along the these lines:
[https://github.com/airbnb/react-sketchapp/tree/master/examples/profile-cards-graphql](https://github.com/airbnb/react-sketchapp/tree/master/examples/profile-cards-graphql)

**Comment by ramenhog** [comment]
Just talked to @dvenprasad about react-sketchapp after looking into it more and we agree that it doesn't seem a great fit for our workflow/team atm. So going to try the Craft approach now 👍

**Comment by cgreene** [comment]
Ok - my interpretation based on the most recent @ramenhog comment is that this should be closed. If this isn't correct, please re-open.
