### ISSUE TITLE
Re-queueing samples from GEO are not being extracted

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#2031]
### Context

Can't process this sample [GSM708631](https://www.refine.bio/samples/GSM708631) with the error `Failed to extract any downloaded files.`

As far as I can tell this is only occuring with microarray/affy processor jobs.
#1986 
https://github.com/AlexsLemonade/refinebio/issues/1538#issuecomment-530124920

Trying to re-requeue sample via [requeue_samples](https://github.com/AlexsLemonade/refinebio/blob/996bcafaa1077ad9697918f06c9578279fb825ba/foreman/data_refinery_foreman/foreman/management/commands/retry_samples.py#L24) which is erroring out [here](https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/downloaders/geo.py#L393).

### Problem or idea

The geo downloader correctly identifies that the original file for this sample exists but I believe that it incorrectly returns `sample.needs_processing() -> false` because
 `sample.has_blocking_jobs() -> true`

So original file is downloaded, geo downloaded sees that it exists, tries to see if it should be processed, says no, skips it in the results set, then says there was nothing to extract....

### Solution or next step

Either we are not checking existing jobs correctly [here](https://github.com/AlexsLemonade/refinebio/blob/dev/common/data_refinery_common/models/models.py#L840) or we are not correctly setting one of the checked attributes when jobs fail. (In the issue that lead me here it most likely would be somewhere around [here](https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/array_express.py#L178).

We should dig a little deeper and find out which one and either fix the check or run a migration to fix historical errors.

**Comment by kurtwheeler** [comment]
As part of verifying this fix, please test by rerunning the samples affected by https://github.com/AlexsLemonade/refinebio/issues/1986
