### ISSUE TITLE
Investigate opportunities for reducing cost

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2042]
### Context

It's been a while since we've gone through and thought of any of all ways we can reduce cost.

### Problem or idea

https://github.com/AlexsLemonade/refinebio/issues/1284 was a good idea, and the PR that addressed it, https://github.com/AlexsLemonade/refinebio/pull/2008, introduced a deployment parameter `full_stack` that could be used to run a smaller stack in staging unless there's something specific we want to test.

Additionally we could look into downsizing some of the resources that the prod stack uses to either make them smaller or fewer. For example, now that we aren't running at quite so much scale or with so much urgency, we could just have a single nomad server instead of three. If it goes down it can be recovered easily enough.

### Solution or next step

Investigate ways we can reduce costs and make a NEW issue/issues to actually implement those changes. This is just an investigations issue to figure out what we can do and how much work various improvements might be.

**Comment by kurtwheeler** [comment]
Ok so I've come up with some ideas about how we can reduce our AWS costs!!! I'm going to list them here first so that we can decide whether or not we want to implement each idea. If we do, we can make a new issue to actually do the thing.

**Comment by kurtwheeler** [comment]
Idea 1:

We could use a single Nomad server for the staging stack. This would have less redundancy when we're running, but we already don't trust Nomad to not mess up so it being perfect isn't very important for our system.

Estimated savings: ~$150-200 a month

Initial assessment of `Should we do this?`: YES

**Comment by kurtwheeler** [comment]
Idea 2:

We could use a single Nomad server for the prod stack. This would have less redundancy when we're running, but we already don't trust Nomad to not mess up so it being perfect isn't very important for our system.

Estimated savings: ~$150-200 a month

Initial assessment of `Should we do this?`: probably. This does make prod overall less stable, but I can't think of anything catastrophic that could result.

**Comment by kurtwheeler** [comment]
Idea 3:

Reduce max number of jobs that can be queued at a single time by 50-75% and then drop the size of the Nomad servers by a proportional amount. The size of servers that we're currently using have a cap of ~20k jobs, but we don't need to run at such extreme scales any more so we could probably be fine with a limit of ~5k jobs.

Estimated savings: ~$600-900  a month

Initial assessment of `Should we do this?`: Probably. This will involve changing code because the maximum number of jobs in the queue is something that our code enforces since Nomad has none of the features we need.

Also note that this reduces the cost of our nomad server costs by 50-75%. If we do ideas 1 and 2 then those will reduce our nomad server costs by 66%, leaving them at ~$300 a month, so savings from this idea would only be ~$150-225.

**Comment by kurtwheeler** [comment]
Idea 4:

Reduce the size of the staging RDS instance. It currently is just as big as the prod one and it really doesn't need to be. We could probably use an instance a quarter the size and still be fine.

Estimated savings: ~400 a month

Initial assessment of `Should we do this?`: YES

**Comment by kurtwheeler** [comment]
Idea 5:

Reduce the size of the prod RDS instance. At some points when we were running really big we put some load on our database. However we no longer need to run so large to get things done quickly, so in combination with Idea 3 we could reduce the max size we run at so we could drop this database size by at least half.

Estimated savings:  >$200 a month.

Initial assessment of `Should we do this?`: Maybe. This could introduce a lot of headaches potentially. Might be a good idea to start with Idea 4 and see how things do in staging on a smaller instance. Then again staging doesn't have enough data to get the load issues we have with the prod instance.

**Comment by kurtwheeler** [comment]
Idea 6:

Reconsider the size of the smasher instance. Right now we give smasher jobs 28GB of RAM to run with. I think that amount was chosen pretty arbitrarily. If half as much was good enough, we'd save some money, because that is a fairly large instance.

Estimated savings: Depends on size reduction but it could be $200-400 a month maybe? (I'm not entirely sure if our `Linux m5.2xlarge` cost is limited to that one instance or if we used others throughout the month).

Initial assessment of `Should we do this?`: Not clear. I don't know how much RAM is needed by our smasher jobs nor do I really have a good idea of what our plan is if someone makes a dataset large enough to OOM-kill it.

**Comment by cgreene** [comment]
@kurtwheeler : are there any cases where we should clearly just buy reserved instances for either a 1-year or 3-year term? Especially things we're using on demand that are always up.

**Comment by kurtwheeler** [comment]
Hmm, that's a good idea. I think it could make sense for the API instance and the RDS instance.

The API is definitely a good candidate for that, because even if at some point the instance becomes too small for our load, we can just spin up a second instance. It's already behind a load balancer.

The RDS instance makes sense because we're definitely going to need that around for years. However we might want to try figuring out if we can use a smaller size before locking ourselves in for so long. https://aws.amazon.com/rds/reserved-instances/ says:

> Reserved Instances can save you up to 69% over On-Demand rates when used in steady state.

So the cost savings of switching to a reserved instance would be higher than switching to an instance half as big. However if we did both that would be the maximum savings.

**Comment by kurtwheeler** [comment]
Oh yeah, we could also do that for the cognoma instances probably.

Everything else seems like it may need to get bigger or smaller (like the smasher instance) or like our plans for it might change (like the Nomad servers if we replace Nomad).

**Comment by kurtwheeler** [comment]
I just had another idea! We should use smaller EBS volumes. The 9TB ones we use are rather expensive and now that we aren't running at such scale or for such long periods of time, we won't have as much of an issue with the disk filling up.

**Comment by kurtwheeler** [comment]
I've created https://github.com/AlexsLemonade/refinebio/issues/2106 because it blows up our deploy-a-dev-stack times, but apparently it could save us ~$50 dollars as well to just hose our own elasticsearch service.

**Comment by kurtwheeler** [comment]
Ok, I've created new issues for all the different ideas except for Idea 6: reduce the smasher instance size. (I think that one might not be such a good idea because it will limit the size of dataset that can be downloaded from us.) Therefore this issue doesn't need to stay open any more.
