### ISSUE TITLE
Set up AWS CloudTrail to get more detailed info on compendia downloads

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2043]
### Context

We set up google analytics for our compendia page. However this doesn't tell us much more than the fact that someone started downloading the compendia.

### Problem or idea

It'd be nice to know if someone finished downloading it, where they were from, and anything else we can.

### Solution or next step

Use AWS CloudTrail to track as much info about compendia downloads as possible.

**Comment by arielsvn** [comment]
I was able to enable Cloudtrail logging for one of the buckets following [this guide](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/enable-cloudtrail-events.html). There're multiple [log events](https://docs.aws.amazon.com/AmazonS3/latest/dev/cloudtrail-logging.html) that get added which seem irrelevant.

Moving forward we need to do the following for this ticket:

1. Ensure compendiums are saved in the bucket `data-refinery-s3-compendia-circleci-prod` #2072 

2. Enable Couldtrail logging with cloudwatch [terraform config here](https://www.terraform.io/docs/providers/aws/r/cloudtrail.html), try to reduce the volume of events that are logged.

3. Find out a way to visualize the stats for each compendia file
