### ISSUE TITLE
Veryify that packageAnnotation override works as expected

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#2046]
Problem: 
We need to verify that #2015 works.

Context:
Huex Packages weren't able to be processed because the annotation package for huex v1 doesn't exist. So we are overriding it with v2 and we need to make sure that the values aren't wildly out of the ordinary.

Next Steps:
First address this #2031 
Then test via:

I like this solution! Our ideal test case would be a dataset that contains both v1 samples (failed to process) and v2 samples (successfully processed). I wonder if the experiment that was requested ( https://www.refine.bio/experiments/GSE131617/genes-associated-with-the-progression-of-neurofibrillary-tangles-in-alzheimers-disease ) does just that. It looks like about half of the samples failed to process. If we're lucky those are on v1.

Then we'd plot each gene (ensembl ID's) average expression for v1 samples against its average expression for v2 samples and add a diagonal 1-1 line. If the answers from Affymetrix are correct, we'd see a more or less diagonal line here. If the answers from Affy in the various threads are wrong (spots change position on the array) we'll see essentially a random positioning of points.

The first step is ideally to find an experiment with some V1 and some V2 though. 🤞 that it's the one that was requested.

_Originally posted by @cgreene in https://github.com/AlexsLemonade/refinebio/pull/2015#issuecomment-569051745_

**Comment by davidsmejia** [comment]
```>>> failed_jobs = ProcessorJob.objects.filter(failure_reason__icontains="pd.huex.1.0.st.v1")
>>> failed_jobs.count()
1368
>>> ofpks = failed_jobs.distinct().values_list("original_files", flat=True).distinct()
>>> ofpks.count()
1368
>>> v1_samples = Sample.objects.filter(original_files__in=ofpks).distinct()
>>> v1_samples.count()
1368
>>> v1_samples_processed = v1_samples.filter(is_processed=True)
>>> v1_samples_processed.count()
753
>>> v1_samples_processed = v1_samples.filter(is_processed=True).distinct()
>>> v1_samples_processed.count()
753
>>> v1_experiments = Experiment.objects.filter(samples__in=v1_samples_processed).distinct()
>>> v1_experiments.count()
46
>>> v1_experiments_samples_sum = sum([exp.samples.filter(is_processed=True).count() for exp in v1_experiments.all()])
>>> v1_experiments_samples_sum
982
```

This is confusing, I need to figure out why the total samples are going up, I have checked before to see if there were any experiments that contained both package annotation types and it seemed as though there were none. but there looks to be 229 samples coming from somewhere I can't identify yet.

**Comment by davidsmejia** [comment]
Ok so I need to create a list of known v1 samples and make sure that I check against this when I generate my v1 dataset, its possible that those 229 samples are v1 and they failed for another reason before we re-ran them since the package override solution shipped before the requeue sample solution shipped so we would have to retry them without the annotation override and see if they fail. I think for now the move is just to use the ones we know are v1.

**Comment by davidsmejia** [comment]
# The Results Are In
<details><summary>Script Used</summary>
<p>

```python

# v1 Dataset = f67b097c-a2e6-46f0-a7b9-12d5ddbc0887

# v2 Dataset = f5ae590a-91e8-4540-8a9a-e0f3a2a25e96


import pandas as pd
import plotly.express as px
import os
import random

print("graphing v1 v v2 experiments")

# path to the extracted archive datasets - renamed for readability
v1fp = "/Users/david/Downloads/huex_v1"
v2fp = "/Users/david/Downloads/huex_v2"

v1_dataframes = []
v2_dataframes = []


def outer_join(dataframes):
    return pd.concat(dataframes, axis=1, join="outer", ignore_index=False, verify_integrity=False,)


def get_all_dataframes(fp, frames_list):
    for folder in os.listdir(fp):
        folder_path = os.path.join(fp, folder)
        if os.path.isdir(folder_path):
            file_path = os.path.join(fp, folder, "%s.tsv" % folder)
            frames_list.append(pd.read_csv(file_path, sep="\t"))


get_all_dataframes(v1fp, v1_dataframes)
get_all_dataframes(v2fp, v2_dataframes)

random.shuffle(v2_dataframes)

v1_experiments_count = len(v1_dataframes)
print("%s v1 experiments" % len(v1_dataframes))


def graph_average_comparison(x, y, x_column, y_column):

    # create dataframe from average expression
    x_average = pd.DataFrame({x_column: x.mean(axis=1)})
    y_average = pd.DataFrame({y_column: y.mean(axis=1)})

    averages = [x_average, y_average]

    # outer join along gene id's
    xy_average = outer_join(averages)

    # plot data
    plot = px.scatter(xy_average, x=x_column, y=y_column)
    # print the graph
    plot.show()


# graph 1 Compare v1/v2

# dataset 1
# All experiments using v1
graph1_v1_df = outer_join(v1_dataframes)


# datset 2
# random experiments that contain same or fewer samples as max v1

# randomize our selection
v2_dataframes_copy = v2_dataframes.copy()
random.shuffle(v2_dataframes_copy)

# from shuffled list take as many experiments as there are for v1
graph1_v2_dataframes = v2_dataframes_copy[:v1_experiments_count]

graph1_v2_df = outer_join(graph1_v2_dataframes)

# graph the averages
graph_average_comparison(
    graph1_v1_df, graph1_v2_df, "v1_average_gene_expression", "v2_average_gene_expression"
)

# dataset 3 and 4
# 51 randomly selected experiments with the same sample

graph2_v2_dataframes_copy = v2_dataframes.copy()
# shuffle again and make 2 lists of different experiments
random.shuffle(graph2_v2_dataframes_copy)

# take every other
graph2_v2_x = outer_join(graph2_v2_dataframes_copy[:v1_experiments_count:2])
# take every other offset by 1
graph2_v2_y = outer_join(graph2_v2_dataframes_copy[1:v1_experiments_count:2])

graph_average_comparison(graph2_v2_x, graph2_v2_y, "v2_random_selection", "v2_random_selection_2")
```

</p>
</details>

## Graph 1: Version 1 vs Version 2

<img width="1680" alt="Screen Shot 2020-02-12 at 4 52 18 PM" src="https://user-images.githubusercontent.com/1075609/74381023-b7ba9100-4db8-11ea-9c84-eef1aa0c7d46.png">

## Graph 2 Version 2 vs Version 2

<img width="1680" alt="Screen Shot 2020-02-12 at 4 52 30 PM" src="https://user-images.githubusercontent.com/1075609/74381169-f6e8e200-4db8-11ea-9e8e-a9eee8b0f65e.png">

**Comment by davidsmejia** [comment]
@cgreene @jaclyn-taroni Is this interpretable? If not I could use a suggestion for next step. Feel free to close the issue if this seems like the expected result. 🚀

**Comment by jaclyn-taroni** [comment]
What are the axis values @davidsmejia? SCAN values pre-QN?

**Comment by davidsmejia** [comment]
All axis are average gene expression. Graph 1 plots genes where x is v1 and y is v2 and Graph2 plots average gene expression from 2 different subsets (no overlap) of v2 experiments

**Comment by davidsmejia** [comment]
Let me try exporting the tsv of merged and averaged values, they do look too high to make sense now that you mention it.

**Comment by davidsmejia** [comment]
@jaclyn-taroni correct scan values no qn

**Comment by davidsmejia** [comment]
I'm not sure now, some values are pretty high... This is just from the merge

  | Gene | GSM1825262 | GSM1825263
-- | -- | -- | --
0 | ENSG00000000003 | -0.18284439877816000 | -0.12619489822417200
1 | ENSG00000000005 | 0.07956868054798210 | 0.3628394323718710
2 | ENSG00000000419 | 5.556392481501050 | 6.235072630164530
3 | ENSG00000000457 | 2.930046823372500 | 3.1574853592993900
4 | ENSG00000000460 | 0.7763205701480980 | 1.346035820387140
5 | ENSG00000000938 | 32.74231000631610 | 26.711939837669600

**Comment by jaclyn-taroni** [comment]
That looks like it could be correct -- those values are higher than I expect for hgu133plus2 for example but I have not run SCAN on any Human Exon arrays outside of this context so very well could be expected.

**Comment by cgreene** [comment]
I agree with Jackie. These values are higher than I see on other affymetrix platforms but this is an array type I haven't used before. We were worried that the CDFs might be wrong for v1, since there was no available CDF for that platform. Instead, we see a nice diagonal line and v1 is indistinguishable from v2. It looks like the random comments on the internet asserting that are backed up by your evidence. Nice work!

**Comment by cgreene** [comment]
Woo! 🎊 I'm going to close this. The evidence that is here convinces me that the non-documented CDF file for v1 is the same as v2.
