### ISSUE TITLE
Implement Multi-QC

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#205]
Stub for now

**Comment by Miserlou** [comment]
This is assigned for this sprint but still has no information..

Running MultiQC is as simple as
```
pip install multiqc
multiqc .
```

But I assume we want to tackle #203 first?

**Comment by jaclyn-taroni** [comment]
Note I've also filed https://github.com/ewels/MultiQC/issues/733

**Comment by Miserlou** [comment]
I have a demo of this working (and it'll be trivial to add to other pipelines).. but what pipelines should we be expecting to run this on? Does this only ever apply to the Salmon pipeline? It doesn't seem to do anything with CEL files, should it?

**Comment by jaclyn-taroni** [comment]
> I have a demo of this working (and it'll be trivial to add to other pipelines).. but what pipelines should we be expecting to run this on? Does this only ever apply to the Salmon pipeline?

Yes, it only runs on the RNA-seq pipeline which will include Salmon and FastQC (for now). 

> It doesn't seem to do anything with CEL files, should it?

No, anything done on Affymetrix raw data is going to be tracked over on #202

**Comment by jaclyn-taroni** [comment]
Question that came up during discussion around the experiment page (see https://github.com/AlexsLemonade/refinebio/issues/246#issuecomment-386708504) - will MultiQC reports be on a sample or experiment basis? I'm fairly sure it will be _per sample_ for the moment. Does it make sense to have an HTML report per experiment in the future?
