### ISSUE TITLE
Processing info: Sample is not available but only tximport is run on it

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#2054]
Ex:
https://www.refine.bio/experiments/SRP074593/gene-expression-profiling-of-drosophila-s2r-cells-following-rnai-mediated-knockdown-of-transcription-factors

![Screen Shot 2020-01-03 at 2 58 39 PM](https://user-images.githubusercontent.com/15315514/71745903-8e155e00-2e39-11ea-92d4-de1927766356.png)

We should just show the submitter supplied info, since the samples aren't really processed through our pipeline

**Comment by arielsvn** [comment]
#2056 added a fix on the code, I still have to add a migration to fix the data

**Comment by arielsvn** [comment]
Found another experiment with samples were we it seems we ran both salmon and tximport but the sample is not processed

https://www.refine.bio/experiments/ERP017365/impc-high-throughput-rna-seq-of-1135-lines
