### ISSUE TITLE
Sample Metadata Format

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#206]
### Context

We were in a design review meeting and we realized that we have not yet defined how we will return sample metadata from the frontend (or API) to users.

### Problem or idea

We should define the format we will use. Eventually, we will want to provide users with sample code, at least for Python and R, that will load both the data and the metadata and provide ways to perform analyses over this.

### Solution or next step

We should begin the conversation @kurtwheeler @dongbohu @Miserlou and @jaclyn-taroni .

**Comment by jaclyn-taroni** [comment]
Related: #221
