### ISSUE TITLE
Use remote backend to store terraform state files

### ISSUE THREAD

**Issue by dongbohu** [AlexsLemonade/refinebio#207]
### Problem or idea

Use `terraform remote config` to ease statefile maintenance. 

### Context

Right now the CircleCI deployment is using a S3 bucket to store terraform state files, but the process of downloading/decrypt/deploy/encrypt/uploading is manual and error prone. I just noticed that it is possible 
to configure a remote backend (such as AWS S3) in terraform to store the state files and the whole process can be done automatically:
https://www.terraform.io/intro/getting-started/remote.html
This will make the CircleCI deployment script `run_terraform.sh` mush simpler.
 
### Solution or next step

Use the same S3 bucket, but configure the remote backend before deployment in CircleCI.

**Comment by cgreene** [comment]
Tagging for `Miso` as this may touch on stability / reliability.
