### ISSUE TITLE
Re-enable QN Test step in compendia generation

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#2092]
### Context

Looks like we generate compendias with `is_public=False` https://github.com/AlexsLemonade/refinebio/pull/1891

### Problem or idea

We disabled QN Test step in the compendia and made them private while we restore that. I was testing the compendia generation and spent some time trying to figure out why they didn't appear in the API.

Created this issue to keep track of this.

### Solution or next step

- re-enable QN test step
- Make the generated `ComputationalResult` public https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L396-L397

**Comment by kurtwheeler** [comment]
Closed by #2905
