### ISSUE TITLE
Dataset Request GSE75083

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#2111]
### Context

A user requested this.

### Problem or idea

We didn't process any samples from it. It looks like some samples are illumina beadchip and others are agilent. I expect that we won't be able to process all of the samples.

### Solution or next step

Someone on the science team should take a look at this experiment. If it's not going to be feasible in a short time-frame, we should get back to the requestor and let them know that we won't be able to process it.

**Comment by arielsvn** [comment]
A few of these samples have `Could not detect PValue column!` as their failure reason.

[Experiment link](https://www.refine.bio/experiments/GSE75083/progranulin-deficiency-promotes-circuit-specific-synaptic-pruning-by-microglia-via-complement-activation)

**Comment by davidsmejia** [comment]
Below is the code to determine pval in the headers...

```python
    for header in headers:
        if "DETECTION_PVAL" in header.upper().replace(" ", "_"):
            # Could be <SAMPLE_ID>.Detection Pval, etc
            if "." in header:
                job_context["detectionPval"] = header.split(".")[-1]
            else:
                job_context["detectionPval"] = header
            break
        else:
            job_context["job"].failure_reason = "Could not detect PValue column!"
            job_context["success"] = False
            job_context["job"].no_retry = True
            return job_context
```

However this is what the headers text looks like:

**Comment by davidsmejia** [comment]
actually that solution would be problematic since the value would be correct if the "." was separating detection.pval

Maybe something like:
```python
    for header in headers:
        if "DETECTION_PVAL" in header.upper().replace(".", "_").replace(" ", "_"):
            # Could be <SAMPLE_ID>.Detection Pval, etc
            job_context["detectionPval"] = "Detection Pval{}".format(
                header.upper().split("PVAL")[-1]
            )
            break
        else:
            job_context["job"].failure_reason = "Could not detect PValue column!"
            job_context["success"] = False
            job_context["job"].no_retry = True
            return job_context

**Comment by davidsmejia** [comment]
Ok so that last comment isn't what the rscript is looking for either 
I needs to be "detected.pval"

**Comment by davidsmejia** [comment]
I think this would be the better solution... since we are looking for something the r script can use as a regex to match which columns are pvalues and set whatever was bookended with detection and pval.

This regex reads like match "detect" then any amount of word characters until a single non-word character then match "pval" then unlimited word characters until the end of the word.


```python
for header in headers:
    # check if header contains detection and pval
    pvalue_header = re.match(r"(detect\w*\b).(pval\w*\b)", header, re.IGNORECASE)
    if pvalue_header:
        #Could be <SAMPLE_ID>.Detection Pval, etc
        job_context["detectionPval"] = pvalue_header.string
        break
 ```

![Screen Shot 2020-02-10 at 3 12 51 PM](https://user-images.githubusercontent.com/1075609/74186038-e0575500-4c17-11ea-897a-fd708a431ab8.png)

**Comment by davidsmejia** [comment]
As per #2130 decided it would be best to keep `r"detection.pval(\w*\b)"` as the best way to get the column header for the pval we want.

**Comment by davidsmejia** [comment]
Ok some new developments after running this. 

"Error: The number of expression columns [154] did not match the number of p-value columns [163]."

Which is a difference of 9 which probably means this is the issue 

> Gene expression study in multiple brain regions from a mouse model of progranulin deficiency
Please note that 9 outlier samples were excluded from data analysis. Therefore, there are 326 raw data columns (i.e. 163 samples) in the non_normalized data matrix while 154 samples are represented here.
>
>For arrays from Agilent platform, there are 16 samples/experiments were carried out, and 1 sample was excluded from analysis, therefore 15 samples are represented in the records.

**Comment by cgreene** [comment]
I am leaning towards telling the person we couldn't process it automatically via our system and sharing this situation. If we make a change to allow mismatched column numbers it feels like we're going to increase the risk that we mis-assign values to samples.

The work that you've done for this already should make our processing much better for _other_ experiments!

**Comment by cgreene** [comment]
I just sent this to our requestor:

> We looked into processing this, but if we alter our system to process this experiment it adds to the risk that we will incorrectly process others. In these cases, our general approach is to avoid including bad data at the potential expense of missing certain valuable datasets. If you'd like to see the work that we did for this dataset, please feel free to take a look at this issue where we tracked our development process. The main issue with this dataset is that detection p-value columns are included for samples that were not: https://github.com/alexslemonade/refinebio/issues/2111
