### ISSUE TITLE
Beadchip samples look like noise in human compendium

### ISSUE THREAD

**Issue by ben-heil** [AlexsLemonade/refinebio#2114]
### Context

I was doing some exploratory data analysis for the samples I'm working with in whistl, and noticed bands of what appeared to be random noise through the data. On further inspection, each of these bands appears to come from a study using a beadchip as the sequencing platform.

The x-axis entries of these heatmaps are samples, while the y-axis entries are genes. The three noise bands below correspond to GSE58411, GSE40553, and GSE83456.

![image](https://user-images.githubusercontent.com/15317110/73485580-5a165580-4371-11ea-8bcb-f023d3b547f1.png)

*Zoom, enhance*

![image](https://user-images.githubusercontent.com/15317110/73485590-613d6380-4371-11ea-878b-d80a1ff022ba.png)

### Problem or idea

I know that some issues with beadchips have been mentioned in the past, but I'm unsure whether they are supposed to be this noisy.

### Solution or next step

I'll pull these samples out of my analysis, but wanted to make that the noise wasn't due to a pipeline issue before doing so

**Comment by kurtwheeler** [comment]
For this sprint we will just focus on investigating what is going on, and then we will fix/address whatever issues we identify in the following sprint.

**Comment by davidsmejia** [comment]
@ben-heil Looks like the detection pvalue for those experiments are very high. I don't think anyone would recommend using them in your analysis.

**Comment by davidsmejia** [comment]
We will be regenerating this and other compendium soon, without submitter-processed data until we can ensure the integrity of the data.

**Comment by ben-heil** [comment]
Sounds good, thanks!
