### ISSUE TITLE
Question about supplying predicted metadata labels

### ISSUE THREAD

**Issue by erflynn** [AlexsLemonade/refinebio#2127]
### Context

Metadata labels for features such as sex are missing from much of the data. Often researchers want to query for studies that contain mixed sex samples, or look at the sex breakdown, and examine whether sex affects the results.  I have worked on method for predicting sample sex using on microarray expression levels.  The code for the method is [here](https://github.com/erflynn/exprsex), beta version. It has been tested on GEO microarray data, and I have labels for most of human GEO microarray expression studies (set up with our pre-processing pipeline). I am adding an additional function to the output so we can input sample_id + expression data, and return (sample_id, predicted_sex, proba_score). I am also interested in setting this up for other predicted metadata labels in the future.

### Problem or idea
Are you interested in these labels? How should I construct the output so that you can incorporate this into refine.bio? What information do you need in terms of labels, documentation, and performance? I can provide example labels for GEO samples and a sample.

### Solution or next step
Can you help me figure out how to set this up?

In parallel, I can start working on downloading and checking performance on refine.bio processed datasets.

Thanks!

**Comment by kurtwheeler** [comment]
Hello @erflynn!

We've discussed what format would be useful for your metadata to be in. We'd like for the data to be in JSON format, the structure of which will be a list of objects, one per sample. Each sample can have multiple attributes included in it. A template for each sample would be like:

```JSON
{"sample_accession": "<SAMPLE_ACCESSION_CODE>",
 "attributes": [{"<MAPPED_ONTOLOGY_ID>": {"value": <VALUE>,
                                          "probability": <PROBABILITY>,
                                          "unit": "<UNIT>"}
                }
                ...
               ]
}
```

Where:
  *  `SAMPLE_ACCESSION_CODE` is an accession code from GEO, ArrayExpress, or SRA (probably just GEO and ArrayExpress for your use case)
  * `MAPPED_ONTOLOGY_ID` is an ontology identifier available in the Ontology Lookup Service (https://www.ebi.ac.uk/ols/index) such as https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000047. It would be ideal if preference could be given to Open Biomedical Ontologies (http://www.obofoundry.org/).
  * `VALUE` is either:
    * `true` to indicate that the sample has that attribute
    * a numeric value
    * or another `MAPPED_ONTOLOGY_ID`
  * `PROBABILITY` is a floating point value from 0.0 to 1.0 indicating how likely it is that the metadata label is accurate.
  * `UNIT` (optional) is another `MAPPED_ONTOLOGY_ID` corresponding to the unit for the value such as https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001486. This is only required if `VALUE` is a numeric value.
    

As an example, if you wanted to provide metadata for a sample with accession GEO123456 that indicated it was age 31, the data was collected as a control for an experiment, and 75% likely to be female you could do so with:

```JSON
{"sample_accession": "GEO123456",
 "attributes": [{"PATO:0000047": {"value": "PATO:0000384",
                                  "probability": 0.75}},
                {"PATO:0001486": {"value": 31,
                                  "probability": 1.0,
                                  "unit": "NCIT:C29848"}},
                {"EFO:0001461": {"value": true,
                                 "probability": 1.0}}
               ]
}
```

**Comment by erflynn** [comment]
Hi @kurtwheeler -- thanks for the description and examples! This is very helpful. I'll go ahead and reformat it like this. 

In terms of the sample ID, so far I have only worked with GEO data -- is it a problem that many of the GSMs are duplicated in ArrayExpress? Also do you want this just on the sample level or do you want this also organized by study-level ID or some other way?

**Comment by kurtwheeler** [comment]
It's not an issue that many of the GSMs are duplicated in ArrayExpress. We actually have code that can convert between them and won't make separate Experiment objects for the same experiment that is in both AE or GEO, it'll just use the GEO accession.

I think sample level is find unless you have additional study-level metadata that we should be adding onto our Experiment objects. If it's just metadata about samples, then just leaving it at the sample level will be fine.

I'm going to close this issue just for our tracking purposes, but if you have any additional questions or comments feel free to reopen it and comment.

**Comment by erflynn** [comment]
great! thank you.

**Comment by erflynn** [comment]
Here is a sample file with attributes for 500 human samples (saved as a .txt for uploading purposes but it has a json object).

Is this what you're looking for?

If so, how should I transfer the rest of the files? I have all of human, rat, and mouse (and can do more or send github code I used). I also have a write up I'd like to send describing this - where should that go? 

[human_500_sex_lab.txt](https://github.com/AlexsLemonade/refinebio/files/4283900/human_500_sex_lab.txt)

**Comment by kurtwheeler** [comment]
Hi @erflynn! That looks great!

I think maybe the best way would be to just add them to this repo in a Pull Request. You can add a new sub-directory in `config` called `externally_supplied_metadata`. The writeup you have can go in the Methods section of the PR. 

Does that work for you?
