### ISSUE TITLE
Get author list for publications linked to datasets/experiments

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#214]
### Context

During a meeting about features for the search page, searching for datasets/experiments by author came up as a feature we might want.

### Problem or idea

To facilitate this, we likely want to extract an author list given a PubMed ID that is linked to/associated with a dataset/experiment/sample.

### Solution or next step

Here's some information I've tracked down: 

* [Get article metadata](https://www.ncbi.nlm.nih.gov/pmc/tools/get-metadata/) information from the PubMed Central documentation. In this example, we'd probably want the second link. Looks to me like one encodes the PMID information into a URL and the info can be returned as JSON.
* There is likely to be some functionality for this in [Biopython](http://biopython.org) based on [this blog post by Marco Bonzanini](https://marcobonzanini.com/2015/01/12/searching-pubmed-with-python/).

**Comment by Miserlou** [comment]
Would you want all authors of a paper or just the lead? We already get PubMed ID and Author (if available) which we could easily show similar results on, but we don't get all of the other contributors, I think.

**Comment by jaclyn-taroni** [comment]
What does lead author mean? First author?

**Comment by Miserlou** [comment]
I assumed that the contact information we got was for the first author, but
looking at an example it seems (at least for this one case) that it isn't
the lead author, but rather another member of the team - possibly just the
one who actually bothered to upload the data. (And, of course, the people
who actually deal with transferring data and organizing metadata are surely
the lowliest members of the team.)

**Comment by jaclyn-taroni** [comment]
Yea, the majority of the time, a user would want to search by senior/last author (the PI, generally) and that individual may or may not be the submitter. For that reason, all author information would be good to grab from PubMed.
