### ISSUE TITLE
EngagementBot: Summarize into weekly digest 

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#2140]
### Context

Engagement bot is noisy! 🎉 

### Problem or idea

Too noisy. Summarize the download information into a weekly digest instead.
Summarize:
- number of downloads
- Total number of unique downloaders
- Number of new downloaders and their locations. 

### Solution or next step
Include other stats I may have not thought of.

**Comment by kurtwheeler** [comment]
Basic plan: create a cron job that summarizes the dataset and compendia downloads for each week and pushes it to slack. This can either run on the API or the Foreman.

**Comment by arielsvn** [comment]
Do we really need the weekly digest on slack? We have some of this information on the [dashboard](https://www.refine.bio/dashboard) that we could update with location information

![image](https://user-images.githubusercontent.com/1882507/76693543-497a2000-663d-11ea-9ec8-1d5a6f2a021d.png)

**Comment by cgreene** [comment]
There are stakeholders who may not check the dashboard but who are in slack, and this is a way to communicate more broadly with them about the impact. That includes some data science team members as well as leadership at ALSF.

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio/issues/2140 Adds a command to post the summary in the last N days.

In order for this to be closed, we'll also need to set up a cron job, similar to:

https://github.com/AlexsLemonade/refinebio/blob/dev/infrastructure/api-configuration/api-server-instance-user-data.tpl.sh#L137

I'll add it in another PR after testing #2140
