### ISSUE TITLE
Code coverage is always failing

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2145]
### Context

All my PRs have a red X instead of a green checkmark even when all the tests pass because we don't have enough code coverage to make codecov happy.

### Problem or idea

That check should be more lenient.

Also the numbers seem to vary wildly. Some PRs that barely change anything make a difference of 6-17% and I don't know why.

### Solution or next step

Can we at least make it so that code cov doesn't cause our PRs to fail the checks? I'm not entirely sure what's going on with the coverage numbers, so that might also merit some looking into.

**Comment by kurtwheeler** [comment]
It seems likely that the `common` project would be an issue for code coverage, because most of its code gets called by the other projects after they've installed the `common` dependency. @arielsvn did you do anything to try to address that issue while working on this configuration?

**Comment by arielsvn** [comment]
> It seems likely that the common project would be an issue for code coverage, because most of its code gets called by the other projects after they've installed the common dependency.

Yes, in the case of the `common` project, I couldn't find a way to measure the coverage because it's installed as a dependency of the other projects. Not sure there's a way to solve it

**Comment by arielsvn** [comment]
I think I found what's causing the fluctuations in the coverage, some of the tests are not being executed even though the circleci status displays it as if it succeded. For example:

https://circleci.com/gh/AlexsLemonade/refinebio/30737?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Should have failed with `Could not build ccdlstaging/dr_compendia after three attempts.`

@kurtwheeler any idea why that test didn't fail?
