### ISSUE TITLE
Use only a single Nomad server

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2170]
### Context

https://github.com/AlexsLemonade/refinebio/issues/2042

Ideas 1 and 2 cause I think we should just do them both.

### Problem or idea

We could use a single Nomad server. This would have less redundancy when we're running, but we already don't trust Nomad to not mess up so it being perfect isn't very important for our system.

### Solution or next step

Reduce the number of Nomad servers to just one, taking out the other two from each stack.

**Comment by cgreene** [comment]
Closed with #2179
