### ISSUE TITLE
Reduce size of the EBS volumes for the Nomad cluster

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2175]
### Context

https://github.com/AlexsLemonade/refinebio/issues/2042#issuecomment-578818717

### Problem or idea

The EBS volumes we currently use are 9TB so that we don't have to worry about them filling up whilst processing data. However we never run for days at a time anymore so they won't have a chance to fill up.

### Solution or next step

Reduce the size down to at least 2TB. We can consider going even lower if that doesn't cause any issues for a few different crunches.

**Comment by cgreene** [comment]
Closed with #2179
