### ISSUE TITLE
sample file with metadata labels - how to send

### ISSUE THREAD

**Issue by erflynn** [AlexsLemonade/refinebio#2181]
Here is a sample file with sex labels for 500 human samples (saved as a .txt for uploading purposes but it has a json object), using the format you described.

Is this what you're looking for?

If so, how should I transfer the rest of the files? I have all of human, rat, and mouse (and can do more or send github code I used). I also have a write up I'd like to send describing this - where should that go? 

[human_500_sex_lab.txt](https://github.com/AlexsLemonade/refinebio/files/4283900/human_500_sex_lab.txt)

_Originally posted by @erflynn in https://github.com/AlexsLemonade/refinebio/issues/2127#issuecomment-594200481_

**Comment by kurtwheeler** [comment]
Whoops I originally posted this in the other, closed, issue.

Hi @erflynn! That looks great!

I think maybe the best way would be to just add them to this repo in a Pull Request. You can add a new sub-directory in config called externally_supplied_metadata. The writeup you have can go in the Methods section of the PR.

Does that work for you?

**Comment by erflynn** [comment]
Great! Will do. I will get the sex labels to you tomorrow or Friday and let you know if I have qs. Just as an FYI the files are ~30-50MB for human and mouse.

For a project I'm working on, I also now have: (1) (imputed from expression) cell line vs. non-cell line labels for microarray (similar set up to sex labels), and (2) (normalized using n-gram matching) mapping of harmonized refine.bio cell_line field to Cellosaurus cell line IDs (~80% mapping in human, I can easily map a different ontology if desired, these do not have a probability associated). Are you also interested in these labels? 

Thanks so much!

**Comment by kurtwheeler** [comment]
We certainly are interested in those labels, as long as you can map them to an ontology within OBO. Looks like http://www.obofoundry.org/ontology/clo.html or http://www.obofoundry.org/ontology/bto.html might be good candidates!

**Comment by erflynn** [comment]
Great! I will work on this, it should be easy to map. 

I just submitted a PR for the microarray sex labels. I am not sure if you want to wait until I have the full set of metadata labels I'm working on? (This includes RNAseq sex labels, imputed cell line vs tissue, cell line metadata and drug metadata normalization.) I will keep you updated, and just wanted to start the process going, but is fine to wait until then.

Thanks!
