### ISSUE TITLE
Remove all frontend related configuration from terraform

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#2188]
### Context

https://github.com/AlexsLemonade/refinebio-frontend/issues/862

### Problem or idea

The frontend is being hosted on [ZEIT](https://zeit.co/ccdl) now, so there's no need for all the terraform configuration that created S3 buckets and cloudfront distributions.

### Solution or next step

We should remove all code related to the frontend from terraform.

**Comment by kurtwheeler** [comment]
This was closed by #2924
