### ISSUE TITLE
Handling Multiple Pipelines on a per Sample Basis

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#219]
### Context

Originally part of #156 but at this point it isn't relevant for Milestone Keytar Kurt. Filing this as a separate issue so it doesn't get lost.

### Problem or idea

On an experiment level, is it possible to have versioning? For example, Version A of an experiment can mean Pipeline X has been applied to some of samples and Y has been applied to some others. Version B can mean Pipeline Y and Pipeline Z have been applied to different subsets of samples. This will make it easier represent experiments where multiple pipelines have been applied to samples?

### Solution or next step
Question for @jaclyn-taroni @Miserlou, and @kurtwheeler

**Comment by Miserlou** [comment]
Handled
