### ISSUE TITLE
Create a platform summary list for GEO

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#220]
### Context

We need a whitelist/blacklist for platforms which specifies for each given platform whether we process raw data, download processed data, or skip the experiment entirely. See https://github.com/AlexsLemonade/refinebio/issues/145 for more detail.

### Problem or idea

In order to be able to create a whitelist/blacklist of platforms, we need to know what platforms have how many samples. This has been done for Array Express [here](https://github.com/data-refinery/data-refinery/files/1709001/ae_platform_counts_sorted_with_names.pdf).

### Solution or next step

Create a script which will pull a list of all Experiments from GEO, create surveyor jobs, and collect the metadata. This should not do any crunch, so the code will need to be temporarily modified to not queue downloader jobs. Once the metadata has been collected and stored in our database, we can create a query to see how many assays have been performed with each platform.

The final output should be a table similar in format to [the one for array express](https://github.com/data-refinery/data-refinery/files/1709001/ae_platform_counts_sorted_with_names.pdf)

### New Issue Checklist

- [X] The title is short and descriptive.
- [X] You have explained the context that led you to write this issue.
- [X] You have reported a problem or idea.
- [X] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
Note that #145 has been replaced by #228 for the Keytar Kurt milestone

**Comment by jaclyn-taroni** [comment]
Something like a .tsv is preferable over a PDF

**Comment by Miserlou** [comment]
![screen shot 2018-05-08 at 5 01 18 pm](https://user-images.githubusercontent.com/139987/39782895-7949eac0-52e1-11e8-880d-9f61672ef0aa.png)

Full list: https://gist.github.com/Miserlou/b41c61c3838a8954d5163b00a563caa6

**Comment by jaclyn-taroni** [comment]
Thanks @Miserlou! How easy/difficult would it be to have organism information in there like in the ArrayExpress table in the initial comment? That will help move #227 along.

**Comment by Miserlou** [comment]
With organisms here: https://gist.github.com/Miserlou/0b43dea059c7e12f27e144b7d0046f8b

There are actually quite a few Danio rerio GPLs in there, but most only have <50 samples..
