### ISSUE TITLE
Normalize platform accessions across ArrayExpress, GEO, and SRA

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#222]
### Context

We want to facilitate the display of platform information, the ability to filter by platform, and the scaling across an entire platform (chip). This means we have to identify each chip/sequencing instrument, which may have aliases within and across repositories.

Using **`Agilent 4x44K`** as an example:

* **ArrayExpress**
	* [`A-AGIL-28`](https://www.ebi.ac.uk/arrayexpress/arrays/A-AGIL-28/) on ArrayExpress
	* May be related (requires more investigation): [`A-GEOD-13497`](https://www.ebi.ac.uk/arrayexpress/arrays/A-GEOD-13497), [`A-GEOD-16876`](https://www.ebi.ac.uk/arrayexpress/arrays/A-GEOD-16876), [`A-MEXP-2183`](https://www.ebi.ac.uk/arrayexpress/arrays/A-MEXP-2183)
* **Gene Expression Omnibus**
	* [`GPL4133`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL4133)
	* [`GPL6480`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL6480)
	* [`GPL9822`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL9822)
	* [`GPL16022`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL16022)
	* [`GPL16297`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL16297)

### Problem or idea

This really has two steps 1) a human manually curates the list (at least until proven otherwise) and 2) the mapping occurs on the backend using said list  

_Note: the web interface for GEO does contain some notion of relationships between platform accessions (see: [`GPL6480`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL6480)). This information could be obtained when we work on #220. @kurtwheeler is investigating._

### Solution or next step

I will go through the lists generated [here](https://github.com/AlexsLemonade/refinebio/issues/115#issuecomment-364265976) and via #220 to satisfy step 1 above as I think this can be completed in tandem with #228  

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
>Note: the web interface for GEO does contain some notion of relationships between platform accessions (see: GPL6480). This information could be obtained when we work on #220. @kurtwheeler is investigating.

@kurtwheeler has investigated!!!

```python
import GEOparse
gse = GEOparse.get_GEO(geo="GPL6480")
gse.metadata['relation']
```
outputs:
```python
['Alternative to: GPL4133', 'Alternative to: GPL9822', 'Alternative to: GPL16022', 'Alternative to: GPL16297']
```

**Comment by cgreene** [comment]
Could you collapse these `alternative to` ones to the most common alternative before making the mega-list of platforms?

**Comment by Miserlou** [comment]
It'd be great if we could also harmonize SRA platform information as well. Ideally, we should choose on a single representation for platforms and stick to it for our internal representation (with the ability to convert from any platform into that chosen one).

Ex, SRA sample metadata returns `'platform_instrument_model': 'IlluminaHiSeq2000',`, GEO calls this [GPL13112](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL13112) - and has 99970 samples for it! I assume there others, probably also with awesome numbers in the thousands for no reason.

**Comment by Miserlou** [comment]
Also fun, the same machine has a different GPL for different organisms it scanned for.. some awesome reason.

ex: 
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL13112
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL11154

Even better, it has no relation between them:

```python
import GEOparse
gse = GEOparse.get_GEO(geo="13112")
gse.metadata['relation']
*** KeyError: 'relation'
```

It does, however, return all of the samples:
```python
len(gse.metadata['sample_id'])
99970
```

**Comment by Miserlou** [comment]
GPLs can be queried like so: https://www.ncbi.nlm.nih.gov/gds?term=Illumina%5BTitle%5D&term=GPL%5BETYP%5D (thanks @kurtwheeler).

There are 3922 GPLs with "Illumina" in the title, which is slightly higher than the original guess of "about 2".

**Comment by jaclyn-taroni** [comment]
> There are 3922 GPLs with "Illumina" in the title, which is slightly higher than the original guess of "about 2".

Note that this includes Illumina BeadChips. This is how I would approach it for the GEO sequencing instrument bit -- search by name of machine (in this example `Illumina HiSeq 2000`): https://www.ncbi.nlm.nih.gov/gds/?term=Illumina+HiSeq+2000%5BTITLE%5D+AND+GPL%5BETYP%5D

Which should turn up every GPL (essentially organism) associated with that instrument.

**Comment by jaclyn-taroni** [comment]
If I go to ENA Advanced Search and select `Read` for Select domain (here: https://www.ebi.ac.uk/ena/data/warehouse/search) and then look at the "Instrument model" dropdown, I think the screenshot of this list is a good starting point of machines/search terms

![image](https://user-images.githubusercontent.com/19534205/39366990-7d2f9d38-4a03-11e8-9d18-34ff778fc832.png)
![image](https://user-images.githubusercontent.com/19534205/39366999-84a9daf6-4a03-11e8-9c12-ad30eef26588.png)


I will follow up on #159 with a formal list after a little bit more research

**Comment by Miserlou** [comment]
Done. GEO is scraping currently.

**Comment by jaclyn-taroni** [comment]
Quick question about methodology - Did you use the instrument name as part of your query? I am asking because I am wondering if there exists a body of data that have typos in the instrument names or if this is controlled such that that is a non-issue.

**Comment by jaclyn-taroni** [comment]
@Miserlou can you post some information about your methodology please? I think using these machines with their (typo-less) names should be sufficient for Keytar Kurt, but it would be good to know moving forward.

**Comment by Miserlou** [comment]
I think they're actually all controlled across all platforms in the fields we're looking at so machine names will be acceptable for KK.

**Comment by jaclyn-taroni** [comment]
Here's what the landscape looks like _just_ for Affymetrix GeneChip Human Genome HG-U133 Plus 2

A-AFFY-44
A-GEOD-570
A-GEOD-15308
A-GEOD-16311
A-GEOD-13916
A-GEOD-9101
A-GEOD-17810
A-GEOD-14877
A-GEOD-8542
A-GEOD-19109
A-GEOD-11670
A-GEOD-16356
A-GEOD-10371
A-GEOD-22945
A-GEOD-10175
A-GEOD-9486
A-GEOD-23432
A-GEOD-16268
A-GEOD-5760
A-GEOD-6879
A-GEOD-14837
A-GEOD-20182
A-GEOD-15445
A-GEOD-7869
A-GEOD-8019
A-GEOD-4866
A-GEOD-7567
A-GEOD-6671
A-GEOD-6791
A-GEOD-17996
A-GEOD-22321
A-GEOD-11433
A-GEOD-11084
A-GEOD-16100
A-GEOD-17811
A-GEOD-9102
A-GEOD-13695
A-GEOD-10881
A-GEOD-6732
A-GEOD-17929
A-GEOD-15676
A-GEOD-15394
A-GEOD-9454
A-GEOD-9828
A-GEOD-9419
A-GEOD-13232
A-GEOD-10335
A-GEOD-6823
A-GEOD-10274
A-GEOD-13668
A-GEOD-16006
A-GEOD-18121
A-GEOD-19883
A-GEOD-9987
A-GEOD-23270
A-GEOD-18850
A-GEOD-9099
A-GEOD-11364
A-GEOD-16372
A-GEOD-8715
A-GEOD-4454
A-GEOD-16273
A-GEOD-17394
A-GEOD-10184
A-GEOD-19918
A-GEOD-10925
A-GEOD-17392
A-GEOD-20635
A-GEOD-24355
A-MEXP-2335
A-GEOD-16066
A-GEOD-9324
A-GEOD-19171
A-GEOD-19633

GPL570
GPL15308
GPL16311
GPL13916
GPL9101
GPL17810
GPL14877
GPL8542
GPL19109
GPL11670
GPL16356
GPL10371
GPL22945
GPL10175
GPL9486
GPL23432
GPL16268
GPL5760
GPL6879
GPL14837
GPL20182
GPL15445
GPL7869
GPL8019
GPL4866
GPL7567
GPL6671
GPL6791
GPL17996
GPL22321
GPL11433
GPL11084
GPL16100
GPL17811
GPL9102
GPL13695
GPL10881
GPL6732
GPL17929
GPL15676
GPL15394
GPL9454
GPL9828
GPL9419
GPL13232
GPL10335
GPL6823
GPL10274
GPL13668
GPL16006
GPL18121
GPL19883
GPL9987
GPL23270
GPL18850
GPL9099
GPL11364
GPL16372
GPL8715
GPL4454
GPL16273
GPL17394
GPL10184
GPL19918
GPL10925
GPL17392
GPL20635
GPL24355
GPL16066
GPL9324
GPL19171
GPL19633

Note that `GPLXXXXX` from GEO becomes `A-GEOD-XXXXX` in ArrayExpress

**Comment by jaclyn-taroni** [comment]
Note that yesterday I found an issue with the ArrayExpress platform list where the platform _name_ did not match the _platform accession_. The _species_ and _platform accessions_ appeared to be correctly paired just based on checking a few.

**Comment by jaclyn-taroni** [comment]
Something to keep an eye on while we do this -- 
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/array_express.py#L90

`HGU95Av2` and `HGU95A` are different platforms

**Comment by jaclyn-taroni** [comment]
Here's the list of 90 BrainArray-supported Affymetrix platforms that I think are appropriate for Keytar Kurt: [affy_brainarray_supported.zip](https://github.com/AlexsLemonade/refinebio/files/2000991/affy_brainarray_supported.zip)

It contains all the GEO and ArrayExpress accession numbers for each of the 90 platforms (one .tsv for each platform). Again, note that for each `GPLXXXXX` it becomes `A-GEOD-XXXXX` in ArrayExpress.

Here's the mapping between the "BrainArray friendly" name and the human readable name (https://github.com/AlexsLemonade/refinebio/issues/188#issuecomment-388448506): [affy_brainarray_name_mapping.txt](https://github.com/AlexsLemonade/refinebio/files/2000998/affy_brainarray_name_mapping.txt)

I use the most popular (as measured by number of samples) "title" of the platform as the human readable name.

**Comment by jaclyn-taroni** [comment]
Okay, here's all of the Affymetrix information: 
[affymetrix_supported_platforms_keytar_kurt.zip](https://github.com/AlexsLemonade/refinebio/files/2005446/affymetrix_supported_platforms_keytar_kurt.zip)

This includes both BrainArray and non-BrainArray supported platforms. I used the [BrainArray website](http://brainarray.mbni.med.umich.edu/Brainarray/Database/CustomCDF/22.0.0/ensg.asp) and the bioconductor platform design packages (see [the R dependencies](https://github.com/AlexsLemonade/refinebio/blob/cfe2066052b40e28f4eafb08ef4874d298ded609/workers/r_dependencies.R
)) as guides. (I've removed a few BrainArray platforms that were previously included for reasons such as "not genome wide" -- [GPL88](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL88), for example)

Some notes: 
* Anything I could not find on GEO was left out.
* In general, if there was ambiguity in the platform on GEO (e.g., the information in the square brackets in the title didn't match the rest of the text) and there were a small number of samples, I've left it off for now. 
* The filenames for each of the .tsvs (platforms) and the `expected_cel_header` of `keytar_kurt_affymetrix_name_mapping.tsv` are what I expect to be in the CEL header once it's stripped of punctuation and converted to all lowercase (see also: https://github.com/AlexsLemonade/refinebio/issues/188#issuecomment-388448506). We'll have to make sure this assumption holds.
  * I'm not sure about the header names of the Human PrimeView arrays. They appear to have two versions (+/- external spike-ins) but these may be the same chip.
* I use the most popular (as measured by number of samples) "title" of the platform as the human readable name, but I've removed information like ` [transcript (gene) CSV version]`.

Also, there are 123 platforms in here! 🎉

**Comment by jaclyn-taroni** [comment]
Illumina BeadArray Info: [illumina_beadarray_supported_keytar_kurt.zip](https://github.com/AlexsLemonade/refinebio/files/2009853/illumina_beadarray_supported_keytar_kurt.zip)

Some of the GPL tables don't contain the Illumina identifiers I would expect to be there based on the "official" GPLs in GEO. However, this doesn't necessarily tell us what identifiers are used in the Illumina raw data (e.g., `*non-normalized*`; see also: https://github.com/AlexsLemonade/refinebio/issues/196#issue-313055470).

In addition, I expect some of these are noisy or incorrect for any number of reasons -- submitter used the incorrect GPL or I made a mistake while mapping these to the best of my knowledge/ability. Thus, much like the CEL header issue for Affymetrix, I think we should move towards data-driven platform detection. I've put some initial thoughts on https://github.com/AlexsLemonade/refinebio/issues/232#issuecomment-389302061 but have some more ideas about detecting "ref" vs. "wg" chips, etc.

**Comment by jaclyn-taroni** [comment]
In my opinion, it is reasonable to do data-driven platform detection for Illumina chips as well as Affymetrix at this point (see: https://github.com/AlexsLemonade/refinebio/issues/232#issuecomment-390421762), so this should be kept in mind as this is being implemented.
