### ISSUE TITLE
Find a better way to mount the volumes in the instances

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#2234]
### Context

https://github.com/AlexsLemonade/refinebio/pull/2227

### Problem or idea

Processing instances get the correct volume attached but it doesn't get mounted correctly sometimes.

I was able to get the volume mounted manually by running the following commands from [client-instance-user-data.tpl.sh](https://github.com/AlexsLemonade/refinebio/blob/dev/infrastructure/nomad-configuration/client-instance-user-data.tpl.sh#L59-L73) on the instance:

```bash
ATTACHED_AS=`lsblk -n --sort SIZE | tail -1 | cut -d' ' -f1`
mount /dev/$ATTACHED_AS /var/ebs/
chown ubuntu:ubuntu /var/ebs/
```

#2227 was an attempt at solving that by increasing the time we wait before calculating what volume needs to be mounted.

### Solution or next step

That didn't work, so we'll need to either increase the timeout or find a more sophisticated way to detect when the volume is attached and can be mounted.

**Comment by kurtwheeler** [comment]
This is also made obsolete by Batch!
