### ISSUE TITLE
Downloaded RNA-seq compendium for Pseudomonas aeruginosa missing quant.sf files

### ISSUE THREAD

**Issue by georgiadoing** [AlexsLemonade/refinebio#2246]
### Context
I went to download the RNA-seq (not normalized) compendium for Pseudomonas aeruginosa through the web server

https://www.refine.bio/compendia?c=rna-seq-sample

### Problem or idea
I got a 586.8 KB zip file that contained sub directories for individual experiments but in those directories was only metadata .tsv files, no quant.sf files or raw data files. 

The metadata files also appeared to be from microarray experiments (at least he few I checked). I'm not sure if this is a separate issue/ticket or related, so thought I'd mention it.

### Solution or next step
I have not tried downloading the compendium through the API or any other means, just this one way. I did have success downloading the normalized compendium of Pseudomonas aeruginosa microarray data from the web server though.

**Comment by kurtwheeler** [comment]
Hi Georgia!

Thanks for reporting this!!! That doesn't look right at all to me. I've checked out our database and it looks like the file we created and uploaded was that same size. It looks like something went wrong, but I'm not entirely sure what yet.

I'm going to start by reprocessing this compendium and seeing if it Just Works. If not @arielsvn will dig into why not further!

**Comment by kurtwheeler** [comment]
Hi Georgia!

Thanks for reporting this!!! That doesn't look right at all to me. I've checked out our database and it looks like the file we created and uploaded was that same size. It looks like something went wrong, but I'm not entirely sure what yet.

I'm going to start by reprocessing this compendium and seeing if it Just Works. If not @arielsvn will dig into why not further!

**Comment by arielsvn** [comment]
@georgiadoing I generated a new version of the Rna-Seq compendium for Pseudomonas aeruginosa, try downloading it again. It's now ~86mb. I made sure that all experiment folders contain quant files inside.

I'm closing this, feel free to re-open if you find any other issues with this compendium and thanks for filing the issue!

**Comment by georgiadoing** [comment]
Awesome - just downloaded new compendium -thanks!
