### ISSUE TITLE
Avoid creating EBS volumes now that the instances use SSD drives

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#2254]
### Context

https://github.com/AlexsLemonade/refinebio/issues/2006#issuecomment-617441102

### Problem or idea

With https://github.com/AlexsLemonade/refinebio/pull/2243 we started using SSD that comes with the instances and has 900gb.

That PR is not complete, as the codebase still uses the `max_clients` variable to create EBS volumes. These won't be needed.

There're several places that are dependant on the volumes:

- [client-instance-user-data.tpl.sh](https://github.com/AlexsLemonade/refinebio/blob/dev/infrastructure/nomad-configuration/client-instance-user-data.tpl.sh) Assigns to each instance the volume index
- [format_nomad_with_env.sh](https://github.com/AlexsLemonade/refinebio/blob/dev/scripts/format_nomad_with_env.sh#L249-L298) Registers nomad jobs based on the number of volumes we'll have available.
- Terraform code to create the [EBS volumes](https://github.com/AlexsLemonade/refinebio/blob/dev/infrastructure/disk.tf#L7-L20)
- On the foreman we use `get_active_volumes` which queries nomad's available volumes to see if we have capacity

### Solution or next step

@kurtwheeler recommended that we should set `max_clients=10` and remove the code that creates the EBS volumes, however we need to find a way to assign a volume index to each one of the instances.

**Comment by wvauclain** [comment]
Closed by #2358

I'll open a new issue for assigning volume IDs
