### ISSUE TITLE
Add database tables to track reproducibility information.

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#229]
### Context

Reproducibility is one of the primary requirements of our system. An important part of reproducibility is knowing what versions of programs and dependencies were used to produce our outputs. We have taken a lot of measures to make sure this information is tracked _in some way_, but we currently don't have a good way to expose this information to users other than providing a system version and pointing them to sift through github.

### Problem or idea

We need database tables dedicated to storing this information. Me, @jaclyn-taroni, and @dvenprasad had a discussion about this and came up with an initial specification of these tables which we think we will make displaying this information easy.

##### programs
This table tracks the programs we run. Every combination of command, program_version, and system_version should be unique in the table. Its columns are:
__id__
__program__: the name of the program (ex: salmon)
__program_version__
__command__: the way we run this command so people know what options we used
__system_version__

##### processing_steps
This table tracks the order of steps used to achieve a computational result. Every combination of computationalresult_id and program_id should be unique. Its columns are:
__computationalresult_id__
__program_id__: an id relating to the `programs` table.
__order__: the step in processing that this was run to produce the computational result

##### dependencies
This table tracks all of the dependencies our system has that are not programs. It is functionally the same as programs, but is split off so that the database enforces that a dependency can never be listed as a `processing_step`. Each combination of all of its fields except id should be unique. Its columns are:
__id__
__package_name__: the name of the program (ex: salmon)
__package_version__
__system_version__

These tables will allow us to display the full pipeline for a computational result with detailed information about each step. We probably won't do too much in the UI with the `dependencies` table other than just display the full thing on a page if someone wants to look for it. However exposing it in the API will allow a savvy user to ask "hey for refine bio 1.2.6, what version of annotation array was used" with a call like `curl http://refine.bio/api/dependencies?system_version=1.2.6` or to potentially build this into our clients later.

### Solution or next step

I think that there should probably just be a CSV file for both the `programs` and `dependencies` tables which gets loaded into the database upon each deploy. Note that when I say loaded I do not mean to empty the table and reload it, but just add the data on top of what is already there. We will need to make sure that these csvs are accurate for every release. If we want to get fancy with it we could have our dependency files read it in to ensure they are installing the versions specified.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
Just chatted with @kurtwheeler -- the UI piece of this is not strictly necessary for Keytar Kurt, but it would be good to have it implemented on the backend.

**Comment by kurtwheeler** [comment]
#170 is related

**Comment by arielsvn** [comment]
Are there any endpoints exposing this information?? We need them for https://github.com/AlexsLemonade/refinebio-frontend/issues/65

**Comment by dongbohu** [comment]
@kurtwheeler and @jaclyn-taroni: I am confused about the `order` column in `processing_steps` table. Can you give me an example?

**Comment by jaclyn-taroni** [comment]
@kurtwheeler the initial drawing we had from brainstorming is floating around the CCDL space still, attaching it might be helpful?

**Comment by kurtwheeler** [comment]
@jaclyn-taroni I just dug it up, it's pretty messy so it's probably not the most helpful here. I think we mainly used it as a visual aid for discussion.

However the `order` column is fairly straight forward. Any given ComputationalResult has some set of processors applied to it in some order. This table is for tracking those steps and the order they were performed in. Therefore if the `order` column were to be 5 for a given processing_step, then that means that it was the 5th step in the pipeline to be applied to the data to create the ComputationalResult.

Does that clear things up? I'm happy to provide an example of what a few tables might look like with a few rows in them if it's needed.

**Comment by kurtwheeler** [comment]
Also, @arielsvn there are not yet endpoints exposing these tables because these tables have not yet been implemented.

**Comment by dongbohu** [comment]
@kurtwheeler: Thank you for your clarification yesterday. I put more thoughts on the three tables and came up with a few more questions:

1. Both `programs` and `dependencies` tables have the column `system_version`. What does this column refer to exactly? The Linux kernel version (4.4.x), the Linux distribution version (ubuntu 16.04, etc), or the Python version? 
I noticed that `ComputationalResult` table also has this column, which seems to refer to Python version. It makes sense because all `ComputationalResult` were generated by Python (at least as one of the steps), but it may not make that much sense in `programs` table. For example, `salmon` is compiled by C++ compiler and it has nothing to do with Python.

2. Some programs are launched with different options in different scenarios. For example, `salmon quant` may be called with `-1 left_read_file -2 right_read_file` or `-r single_read_file`. I suppose they should be separate records in `programs` table? 

3. In `process_steps` table, since the `ComputationalResult_id` and `program_id` should be unique together, does it make more sense to add `program_id` directly to `ComputaionalResult` table as a new column? 

4. According to your description of `dependencies` table, it sounds like a complimentary of `programs` table. So `salmon` should be a record in `programs` table but never in `dependencies`, right? A better example is probably something like `r-base` package?

**Comment by cgreene** [comment]
I'm a bit concerned - how will we keep this from getting out of sync with the processor docker images (which are the SPOT for this if I'm not mistaken). Is there a way to connect things to docker image versions and to extract the version information for certain, specific packages when a docker image with a new version is used in a processor?

**Comment by cgreene** [comment]
We'd store: `processor` and `processor_version` and each `processor_version` would have associated with it the versions of key packages that were used. Also, this doesn't appear to keep anything about the version of - for example - transcriptome indices that are used. Are those handled elsewhere? How is that done?

**Comment by dongbohu** [comment]
To keep the records in these tables sync with the actual programs, we could populate these tables inside a container of the docker image by launching the relevant commands, such as `salmon --version`, then parse the output info and dump them into the database.

**Comment by cgreene** [comment]
I do think keeping the record at the level that manages the environment (i.e., the processor version) is safer. We might have some samples processed by one processor version and others processed by another processor version. I am worried that we might, in a few years, find cases where the results are changed by package versions we didn't choose to store.

**Comment by dongbohu** [comment]
We have an `OrganismIndex` model to keep track of index information. See `models.py`.

**Comment by Miserlou** [comment]
@dongbohu - the purpose of `system_version` was intended to correspond to the version of the _complete refine.bio system deployed_ - ex, `1.0.0` or `985d3818ff7b0d05a6e837c0549277d16900be8e` (in whichever want to choose), the idea being that it should be possible to recreate sample in the context of the entire find/fetch/process/smash pipeline, not just as an individual component. Without this information, then running a particular version of a processor which may have been pre-processed by a different downloader or fetched from a different source could lead to an unexplainable inconsistency. If this is the source of truth then it wouldn't strictly be necessary to have separate tables for processor versions, and the information could just be stored in a `ArrayField` or similar.

The approach described in this ticket is probably easier for us to surface this information and make it available to researchers, but we have to make sure that we are properly populating these tables (should this be done at deploy-time or at run-time?), and that we still keep track of system-wide information.

**Comment by dongbohu** [comment]
@Miserlou: So `system_version` here refers to `__version__` defined in `refinebio/common/data_refinery_common/_version.py`?

**Comment by Miserlou** [comment]
It should probably be defined by an outside source and passed in at run time. Likely a git tag or hash.

**Comment by kurtwheeler** [comment]
I would think a git tag would be the way to go, I think we've already discussed using git tags to cut versions anyway.

**Comment by kurtwheeler** [comment]
@dongbohu to address your other questions:

> Some programs are launched with different options in different scenarios. For example, salmon quant may be called with -1 left_read_file -2 right_read_file or -r single_read_file. I suppose they should be separate records in programs table?

Honestly this is probably a better question for @dvenprasad or @jaclyn-taroni because it'll come down to the amount of granularity we want to be able to display to users. I would think that it might be obvious that we use the two-read salmon options for samples that have paired reads and the single read for samples that don't, however really it comes down to what we want to be able to tell the user about it.

> In process_steps table, since the ComputationalResult_id and program_id should be unique together, does it make more sense to add program_id directly to ComputaionalResult table as a new column?

I don't think so because ComputationalResults can have more than one program_id. How would you associate multiple programs and the order they are run in if there's just one column on the ComputationalResult table?

> According to your description of dependencies table, it sounds like a complimentary of programs table. So salmon should be a record in programs table but never in dependencies, right? A better example is probably something like r-base package?

Yes, this seems to make the most sense to me as well.


Finally @cgreene about:

> I'm a bit concerned - how will we keep this from getting out of sync with the processor docker images (which are the SPOT for this if I'm not mistaken). Is there a way to connect things to docker image versions and to extract the version information for certain, specific packages when a docker image with a new version is used in a processor?

So I think that this will be much alleviated by using git tags to manage versions. When we make a git tag, we have circleci automatically rebuild all the docker images and tag them with that tag. So if we cut a new version, say 1.0.0, then we'll have a git tag `v1.0.0` and a docker image tagged `ccdl/dr_affymetrix:v1.0.0`. This means that Dockerhub will be storing exact records of the environments we used for processing. If there's ever a question about a historical environment that we didn't store in a table somewhere, we can start a container with the historical image, get a bash shell, and figure out what the version was. This isn't an efficient or scalable method, so we'd only want to use it for a scenario where someone is asking about a dependency or we find ourselves says "shoot, we really should have stored that", but it will ensure that we have full knowledge of the environment used to produce a ComputationalResult.

I do think that one thing I didn't consider when I first wrote this up, is that we might actually want different processors to use different versions of the same program, even within a single version of the system. Supporting that wouldn't be possible if as I said:
> command, program_version, and system_version are unique in the `programs` table

**Comment by cgreene** [comment]
I still like the idea of storing things at the processor docker image level for software + storing the series of processors that were run to produce any given sample, along with the specific refine.bio version used. I guess that I am still confused about what storing things at the command level gives us. If I saw some way that we were going to keep this list of commands up to date, that'd be great - but it seems difficult to keep synced with the processors (unless it is somehow automatically extracted from the processor code).

Here's my major concern: if it's not done automatically, someone will forget once or twice. At that point, reconstructing what we need will become challenging.

**Comment by dongbohu** [comment]
@kurtwheeler: What is the advantage of having different versions of a program in different processors? For example, both `transcriptome_index` and `salmon` processors use `salmon` program, but if they have different versions, we will have to verify that the index generated by `salmon index` in `transcriptome_index` processor is valid input for `salmon quant` command in `salmon` processor.

**Comment by kurtwheeler** [comment]
> What is the advantage of having different versions of a program in different processors?

I'm not sure that there is one, there's definitely not at this point. However not being able to support different versions of the same program could be a pretty big limitation on the system long term. I can think of at least a few scenarios where we might want to do so at some point. For example trying to compare differences between software versions or something...

**Comment by dongbohu** [comment]
Thanks @kurtwheeler. Due to the upcoming deadline, I am going to implement the most straightforward  model for now. We can always tweak it later.

**Comment by kurtwheeler** [comment]
Sounds good :+1:

**Comment by kurtwheeler** [comment]
> I still like the idea of storing things at the processor docker image level for software

@cgreene I'm not 100% clear on what you mean. Are you saying that rather than have columns for the `system_version`, we'd instead store `processor_image_name` and include the image tag in there for that?

**Comment by cgreene** [comment]
@kurtwheeler : I don't really see the purpose of `programs` and `dependencies` tables over instead tying things to `processors` and having those processors expose the programs, steps, and selected dependencies. Ideally this would be done in a way that is directly extracted from the processor code so that it's as easy as possible to keep in sync. I do see the reason for keeping track of the version of refine.bio that something was processed with.

**Comment by dongbohu** [comment]
@cgreene: I just saw your message. The part that we can't decide now seems to be the best way to compile information of the programs that are being used by processors. 

As I mentioned earlier, since this issue is blocking Ariel's front end work now, I will create a prototype and populate some data on backend so that he can continue the front end coding. 

Whether we want to use one table (your proposal) or three tables (@kurtwheeler original proposal), it will be relatively easy to modify later. And the modification won't affect other tables in the database.

**Comment by kurtwheeler** [comment]
> I don't really see the purpose of `programs` and `dependencies` tables over instead tying things to processors and having those processors expose the programs, steps, and selected dependencies.

@cgreene do you think you could flesh out that idea a little more? `processors` is a bit of an overloaded term, are you proposing a `processors` table which contains all of that information?

> Ideally this would be done in a way that is directly extracted from the processor code so that it's as easy as possible to keep in sync.

That seems like a very hard problem to me. I'm not sure how I would approach such a problem nor how I'd be sure that there's no edge cases my solution would miss (which would then result in the same unreliability we're trying to avoid by automating it). If anyone has a good idea of how to do this I'm all for it though.

**Comment by leipzig** [comment]
At least for the dependency issue it sounds like what you want is to be able for a container to report its `apt list` `pip freeze` and `sessionInfo()` in some kind of orderly fashion that can be stored in a table for human inspection at runtime, so you are not completely "black boxing" the provenance of your results.

**Comment by dongbohu** [comment]
Here is a comment from Kurt on the PR meant to fix this issue:
https://github.com/AlexsLemonade/refinebio/pull/313#pullrequestreview-128570427

> For every single ComputationalResult we're going to have one row for every program/dependency that it needed. If this is say ~10 per result, that means that once we process 1 million results the ProcessStep table will be 10 million rows. However just about every result output by each processor should have a similar set of steps. Therefore I think that if we create an intermediate table, say processor_pipelines or pipelines, then we'll only need one or two of those per processor and our ProcessStep table will have less than a hundred or two rows. Then we can just add a single column to ComputationalResult with the pipeline it used. Sorry I didn't think about this sooner!!!

I am adding my thought for further discussion later:

As a matter of fact, right now `ComputationalResult` already has a field `pipeline` in the model, which is a string. To enable the association between `ComputationalResult` and the exact programs used, the current `string` field is not good enough, because different versions of refine.bio may share identical pipeline names. Suppose we have another table `processors` which has the following fields:
- name: such as `salmon (single read)`, or `salmon (double reads)`, etc
- system_version: refine.bio version

Then a `ComputationalResult` record must know system_version at runtime in order to be associated with a certain pipeline.

**Comment by jaclyn-taroni** [comment]
Replaced by new approaches: #320, #321, #322, #323 and #324
