### ISSUE TITLE
Create platform summary list for SRA

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#231]
### Context

We'll need to determine what sequencing instruments we will support for Keytar Kurt (#159). We already have [some idea](https://github.com/AlexsLemonade/refinebio/issues/222#issuecomment-384982412).

### Problem or idea

The instrument list [here](https://github.com/AlexsLemonade/refinebio/issues/222#issuecomment-384982412) was taken from the search UI of European Nucleotide Archive.

It is currently unclear to me what is needed to accomplish #159 for this milestone. Essentially, I am asking: Will a list of machines be sufficient to accomplish this? Do we need to create a summary list of sequencing machines from SRA similar to how we're doing so for GEO (#220)?

### Solution or next step

Tagging the backend team -- @Miserlou, @kurtwheeler, @dongbohu -- for discussion.

### Related issues

#159, #222, #223 

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
Ideally this will be done by the same person who does #220 because they are similar and should have mostly the same challenges.

**Comment by jaclyn-taroni** [comment]
Something like a .tsv is preferable over a PDF for this

**Comment by Miserlou** [comment]
instruments = {
    'HiSeq X Five': {'experiments': 87, 'runs': 91, 'studies': 21},
    'HiSeq X Ten': {'experiments': 73995, 'runs': 110383, 'studies': 743},
    'Illumina Genome Analyzer II': {'experiments': 113572, 'runs': 140128, 'studies': 6345},
    'Illumina Genome Analyzer IIx': {'experiments': 67959, 'runs': 77104, 'studies': 4554},
    'Illumina HiScanSQ': {'experiments': 4390, 'runs': 5178, 'studies': 287},
    'Illumina HiSeq 1000': {'experiments': 17641, 'runs': 18946, 'studies': 917},
    'Illumina HiSeq 1500': {'experiments': 16525, 'runs': 17994, 'studies': 800},
    'Illumina HiSeq 2000': {'experiments': 1433392, 'runs': 1625848, 'studies': 48428},
    'Illumina HiSeq 2500': {'experiments': 752483, 'runs': 819271, 'studies': 34153},
    'Illumina HiSeq 3000': {'experiments': 11803, 'runs': 13178, 'studies': 456},
    'Illumina HiSeq 4000': {'experiments': 64149 , 'runs': 91695, 'studies': 1922},
    'Illumina MiSeq': {'experiments': 899744, 'runs': 912366, 'studies': 15594},
    'Illumina MiniSeq': {'experiments': 3558, 'runs': 3558, 'studies': 63},
    'Illumina NovaSeq 6000': {'experiments': 109, 'runs': 99952, 'studies': 11},
    'Ion Torrent PGM': {'experiments': 39532, 'runs': 40514, 'studies': 1948},
    'Ion Torrent Proton': {'experiments': 12341, 'runs': 13064, 'studies': 622},
    'Ion Torrent S5': {'experiments': 1214, 'runs': 1214, 'studies': 14},
    'Ion Torrent S5 XL': {'experiments': 52, 'runs': 57, 'studies': 4},
    'MinION': {'experiments': 1510, 'runs': 1632, 'studies': 241},
    'NextSeq 500': {'experiments': 160742, 'runs': 187145, 'studies': 6465},
    'NextSeq 550': {'experiments': 8201, 'runs': 8844, 'studies': 152}
}
