### ISSUE TITLE
Best practices for programatically downloading compendium data

### ISSUE THREAD

**Issue by ben-heil** [AlexsLemonade/refinebio#2339]
I'm currently working on a project that uses the normalized human compendium as a data source. Ideally I'd like to have a script that downloads the data automatically for the users once they accept the refine.bio terms of use.

I can write a script that uses the API to pull down the data. Doing so requires users to create AWS credentials to interface with the bucket where the data is stored, and ideally I don't want to add a step for end users.

When I use the download option on the website the response has a 'download_url' field that isn't present when I query the API from a script. I could save the download URL and use it in a script, but that seems like it would be much more fragile.

As far as I can tell, I'm querying the same API at the same endpoint as the website, but getting a different result. Is there a way for me to retrieve `download_url`? Or is there a better way to retrieve the information.

**Comment by kurtwheeler** [comment]
`download_url` is provided to all requests that provide a valid API token in the `HTTP_API_KEY` header. This is done as a way to make sure users have accepted the terms of use. See https://api.refine.bio/v1/#tag/token for reference.

**Comment by kurtwheeler** [comment]
BTW,

> I could save the download URL and use it in a script, but that seems like it would be much more fragile.

would be very fragile as those download urls expire after some period of time I don't remember off the top of my head but I think is maybe 1 day.

If this adequately answers your question, feel free to close this :)

**Comment by ben-heil** [comment]
Ahhh I see, I got a token but failed to activate it. Thanks!
