### ISSUE TITLE
Speed up end-to-end tests

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#234]
### Context

With the current base image, end to end tests cannot be done quickly because pulling the image and pushing it to a local registry take forever. However with the completion of #55 we will not have such a large image so this can be done quicker.

### Problem or idea

We should become paying clients of CircleCI so that we can parallelize our builds. Once we do so we  should shoot to get the tests running in under a half hour.

### Solution or next step

My initial suggestion for how to parallelize is to have these test threads running simultaneously:
- [ ] One to run the general tests that are fairly lightweight.
- [ ] One to run individual processors.
- [ ] One to run end to end tests.

These may or may not all be necessary or the best way to do this. 

SCAN.UPC is the processor which requires the annotation packages which really blow up the size of our Docker images the most. Therefore if we just make sure we don't run it during end-to-end tests, we won't need to push the image to a local registry which will speed things up a lot. We can instead pull that image and run a processor to test it, which I believe will probably be the longest test we'll have.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
I just looked into this. As an open source project, we do have parallelism already (4 containers). However, it needs to be enabled in the config file:
https://circleci.com/docs/2.0/configuration-reference/#jobs

**Comment by kurtwheeler** [comment]
Oh awesome then.

**Comment by kurtwheeler** [comment]
I dropped [this comment](https://github.com/AlexsLemonade/refinebio/issues/233#issuecomment-385493027) on https://github.com/AlexsLemonade/refinebio/issues/233 which potentially could have sped things up but it doesn't work.
