### ISSUE TITLE
Clean up the logic around EBS creation and mounting

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2363]
### Context

https://github.com/AlexsLemonade/refinebio/pull/2360#pullrequestreview-439453100

### Problem or idea

We have a lot of things commented out related to creating and mounting EBS volumes.

### Solution or next step

Once we know that working without EBS works, we can remove all of the commented-out code relating to EBS.

**Comment by kurtwheeler** [comment]
I cleared this out in the Batch PR.
