### ISSUE TITLE
API Endpoint: Search

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#237]
### Context

We currently have endpoints for all of the different objects we have, but we don't a single endpoint for searching multiple content types.

### Problem or idea

The `/search` endpoint should be the primary interface to all of the experiments and samples. This should also have the ability to apply filters, to detect and convert between source ID types, and return matching results in the next.

### Solution or next step

Filters have been defined, we need a few example queries and fixtures to test around.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
@Miserlou did #245 close this or should it stay open because:
> Probably going to need more work but at least this lands it so FE devs can work off it. Queries can certainly do with optimization.

?

**Comment by Miserlou** [comment]
Yeah this was closed by 245
