### ISSUE TITLE
Find a way to assign volume IDs to instances without EBS

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2376]
### Context

https://github.com/AlexsLemonade/refinebio/issues/2254

### Problem or idea

We stopped creating EBS volumes now that we do all of the processing on the SSDs, but now we can only run one instance at once because instances are always assigned volume index 0.

### Solution or next step

Brainstorm ways to assign volume indices to instances. Maybe we can query nomad for active instances?

**Comment by kurtwheeler** [comment]
Querying nomad might create race conditions if multiple instances are starting up simultaneously.

What if we [tag](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#Using_Tags_CLI) each instance with an index and then have them query for it in their startup scripts?

**Comment by wvauclain** [comment]
Can the spot request tag instances with a unique index?

**Comment by kurtwheeler** [comment]
Ohhh right.... hmm, there might be more elegant solutions, but what if we just.... made 1GB EBS volumes for it?
