### ISSUE TITLE
Our disk is filling up

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2424]
### Context

Ever since we switched to running on SSDs, disk space has been kind of tight, but we could also run into this before.

### Problem or idea

If too many downloader jobs run before the backlog is cleared by processor jobs, the disk of our instance can fill up.

We tried to fix this using a nomad constraint to block downloader jobs from running when disk space dropped below a certain threshold, but unfortunately nomad only calculates disk usage at startup so the constraint was never violated

### Solution or next step

@kurtwheeler suggested limiting how many downloader jobs get placed into the nomad queue, either rate-limiting them or limiting them if there are too many processor jobs in the queue.

**Comment by wvauclain** [comment]
We just deployed https://github.com/AlexsLemonade/refinebio/pull/2430 and are working through some samples. I will keep monitoring the disk usage on our instance.

**Comment by kurtwheeler** [comment]
We were able to run for a few days without this disk filling up! This too seems to be fixed!
