### ISSUE TITLE
Upgrade all docker images to use Ubuntu 18.04 as a base

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2439]
### Context

In #2415 we changed our instance Ubuntu version to 18.04.

### Problem or idea

It seems like it'd be good to match the instance version with the docker image, and it would probably speed up our build times since `apt` will have less to update.

### Solution or next step

Switch all our docker images to use `FROM ubuntu:18.04` and test them thoroughly.

**Comment by cgreene** [comment]
If we're going to make a jump, do we want to go to 20.04 instead so that we don't have to do this again for some time?

**Comment by kurtwheeler** [comment]
Hmm, that seems to make sense. I can't think of any reason not to that we won't run into while testing it.
