### ISSUE TITLE
[Discussion] Only create spot request if needed

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2445]
### Context

On the staging server we usually set `max_clients = 0` and disable the smasher to save costs.

### Problem or idea

Theoretically you could still spin up an instance, but it wouldn't get any work even if you surveyed something.

### Solution or next step

It should be simple to just disable the spot instance in terraform if `max_clients` is set to 0.

**Comment by kurtwheeler** [comment]
This is no longer relevant in a post-Nomad world.
