### ISSUE TITLE
Experiment Page: Scope, Design Decisions, and Mockups

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#246]
### Context

This is to define scope and requirements for experiment page design iteration.

### Relevant Features for experiment page

- #### Display
  - Processing steps (Use Cases: 15, 21)
  - Mandatory GEO fields (Use Cases: 11, 15
  - Indicate if a metadata field was corrected. 

- #### Actions
    - Add experiment to dataset

### Samples Table
There are 2 contexts where the user is presented with the samples table
- To view samples related to an experiment
- To view all samples from the downloads page where there are multiple experiments

- #### Display
  - ~~Segmentation within the table - by matched results or by experiments when displaying multiple experiments (Based on prior discussion)~~ ( Not supporting matching for keytar_kurt)
 - Sorting by experiment accession (Downloads page) 
  - ~~View Experiment metadata- in cases where multiple experiments are displayed. (Based on prior discussion)~~ ( Dependent on segmenting the table) 

- #### Actions
  - Add a subset of samples to dataset
  - ~~Add/Remove metadata fields (columns)~~ ( Adds too much to the scope.)
  - Be able to filter metadata fields (Use Case: 16)

  ----

### Eleven
Applicable to: Data Whiz, Bio Expert, Physician

I'm a bioinformatician that wants to predict lab- or institution-specific effects in _C. albicans_ gene expression data. I need to do some preliminary analyses. I attempt to remove nuisance variables (like strain or platform-specific effects) and then cluster samples. I want to know if the resulting clusters are enriched for different institutions. I need the submitter supplied organization name and associated email address to do this experiment.

##### System Actions
1. User must be able to download a matrix of gene expression values for an organism.
2. User must be able to easily extract the mandatory GEO fields through the API and GUI.

----

### Fifteen

Applicable to: Data Whiz

I'm a ML researcher that has built a classifier that can predict the presence or absence of a particular mutation in a tumor using gene expression data as input, dropping all near zero variance genes. Now I want to identify cell lines that have similar mutation profiles. Once I find these, I’d like to identify collaborators who have uploaded samples to GEO with such profiles.

##### System Actions
1. Users must be able to extract uploader’s contact information via API.

----
### Sixteen

Applicable to: Data Whiz

I'm a bioinformatician that would like to predict response to [rituximab](https://en.wikipedia.org/wiki/Rituximab) regardless of diagnosis or tissue assayed. I need all human gene expression data that includes rituximab treatment _and_ contains paired samples for patients (pre- and post-treatment).

##### System Actions
1. Users must be able to sort and filter samples within datasets to help them explore it.

----

### Twenty-one

Applicable to: Data Whiz, Bio Expert, Physician

I am a computational biologist. I found a processed dataset which is perfect for my downstream analysis. Before I download it, I would like to gain a better understanding of the quality of the samples.

##### System Actions
1. User must have access to quality reports from processing. They should be able to view a high-level quality report easily (without having to download the data).
2. User must have access to processing steps for the dataset.
3. They should also have access to the detailed quality report. This could be in form of a file part of the data download zip.

### Solution or next step

@jaclyn-taroni, @Miserlou, @ramenhog and I will have a whiteboarding session to outline workflows and layout.

**Comment by jaclyn-taroni** [comment]
Questions for discussion with dev team:
* Is protocol information stored on a _per sample_ or _per experiment_ basis? Does this depend on the data source/repository (e.g., GEO v. ArrayExpress)
* Is it possible to identify if _all_ samples within an experiment were processed the same way (i.e., in cases where all samples are from the same platform)? If so, we can "collapse" this information to the experiment level for display.
* Will users be able to download quality reports for all samples in an RNA-seq experiment for Keytar Kurt? Related: #205

**Comment by jaclyn-taroni** [comment]
Something that came up during discussion for #216 and is important here -- for experiments directly submitted to ArrayExpress, there are often (always?) not sample accession numbers (the equivalent of `GSMXXXXX` on GEO). Here is an example: https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-2452/samples/

**Comment by dvenprasad** [comment]
Note:
Protocol information gets concatenated in the protocol description field in the experiments table. For example, this is the protocol information presented on ArrayExpress for E-GEOD-16237:

![screen shot 2018-05-08 at 10 44 25 am](https://user-images.githubusercontent.com/15315514/39764112-e59a001e-52ac-11e8-8a37-cc2ab0cd58e9.png)

and this what is stored in the database:
![screen shot 2018-05-08 at 10 46 39 am](https://user-images.githubusercontent.com/15315514/39764210-1b8384ac-52ad-11e8-9aee-4f144d8e45d2.png)

I have an older version of the table so @Miserlou is it this how it is stored in the latest version?

**Comment by dvenprasad** [comment]
Summary of yesterday's High-Fi review
- Processing Information: For Affymetrix platforms, display platform design and BrainArray package version information. For Illumina, display illumina.db version

- For some cases of submitter processed datasets, we do gene identifier conversion and the processing information should reflect that.

- Indications of "refine.bio processed" or "Submitter processed" are too small.

Note: The Sample tables is a stub. 
HighFi Mockups:
![experiment-page](https://user-images.githubusercontent.com/15315514/40195594-eb69075c-59db-11e8-977d-64a4a15c876c.png)

![experiment-page-processing-info](https://user-images.githubusercontent.com/15315514/40195605-f477e2f0-59db-11e8-9255-d09f181f3bbe.png)

![experiment-page-processing-info-submitter-supplied](https://user-images.githubusercontent.com/15315514/40195608-f77d6b32-59db-11e8-9958-75143ed144ed.png)

![experiment-page-processing-info-rna](https://user-images.githubusercontent.com/15315514/40195612-fa10d74e-59db-11e8-91ab-e5ff006a6fdc.png)

**Comment by dvenprasad** [comment]
Invision mockups
[https://invis.io/U5J0JEBJMZG#/297243710_experiment-Page](https://invis.io/U5J0JEBJMZG#/297243710_experiment-Page)

The badges (for the illustration) are in the MidFi Project's Assets section.

Guidelines and states for checkboxes and numbered badges are in the master.sketch file in https://github.com/AlexsLemonade/refinebio-design

@arielsvn let me know if you need anything else. 

Note: These mockups are without the table component. I will pair with the dev team to build that out.
