### ISSUE TITLE
Most SRA experiments are missing alternate_accession_code

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2462]
### Context

We don't seem to have many alternate accession codes for SRA experiments:

```
select count(*) from experiments where technology='RNA-SEQ' and alternate_accession_code is not null;
 count 
-------
   366
(1 row)

```

### Problem or idea

There must be some kind of issue with out SRA surveyor. Let's try to fix it and resurvey the metadata for SRA experiments.

### Solution or next step

The regular expression at https://github.com/AlexsLemonade/refinebio/blob/dev/foreman/data_refinery_foreman/surveyor/sra.py#L359 looks like it could maybe be too narrow. Or perhaps https://github.com/AlexsLemonade/refinebio/blob/dev/foreman/data_refinery_foreman/surveyor/sra.py#L279 is overwriting itself or being too narrow as well?

Most of these experiments should have GEO accessions according to @cgreene

**Comment by wvauclain** [comment]
I modified the test to see if it works on [SRP193559](https://www.refine.bio/experiments/SRP193559/inactivation-of-cftr-by-crispr-cas9-alters-transcriptional-regulation-of-inflammatory-pathways-and-other-networks) which does not have an alternate accession listed but definitely has one, and it worked locally, so that part works.

Maybe the pagination is off on the management command, or there was some other issue? I will continue to investigate.

**Comment by wvauclain** [comment]
Update: I ran the management command on staging while watching the output, and after a while it failed with this exception:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/user/data_refinery_foreman/foreman/management/commands/update_experiment_metadata.py", line 59, in handle
    experiment.samples.first().accession_code
  File "/home/user/data_refinery_foreman/surveyor/sra.py", line 292, in gather_all_metadata
    SraSurveyor.gather_experiment_metadata(metadata)
  File "/home/user/data_refinery_foreman/surveyor/sra.py", line 140, in gather_experiment_metadata
    SraSurveyor.gather_library_metadata(metadata, grandchild)
  File "/home/user/data_refinery_foreman/surveyor/sra.py", line 95, in gather_library_metadata
    raise UnsupportedDataTypeError("library_strategy not RNA-Seq.")
data_refinery_foreman.surveyor.sra.UnsupportedDataTypeError: library_strategy not RNA-Seq.
```
Let me add some exception handling to the management command, then we can run it again and see if we can get more experiments.

**Comment by wvauclain** [comment]
I reran the management command on staging with my bugfix, and here were the new results:
```
>>> Experiment.objects.filter(source_database="SRA", alternate_accession_code__isnull=False).count()
1327
>>> Experiment.objects.filter(source_database="SRA", alternate_accession_code__isnull=True).count()
775
```

**Comment by wvauclain** [comment]
This was fixed when we ran the management command two days ago. We are still missing alternate accession codes for ENA experiments that are also hosted on ArrayExpress, but that's tracking in https://github.com/AlexsLemonade/refinebio/issues/2488 so I'm going to close this.
