### ISSUE TITLE
Our end-to-end tests hang if a container errors on start

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2469]
### Context

I'm trying to track down the last thing causing our end-to-end tests to fail.

### Problem or idea

It looks like the containers were dying on start for some reason that I am still looking into, but the end-to-end tests were still waiting on them to finish.

### Solution or next step

Figure out why we are still waiting on containers that were marked "dead" in Nomad.

**Comment by kurtwheeler** [comment]
This is a Nomad problem and we don't use nomad any more so I am no mad at this problem!
