### ISSUE TITLE
Document what we currently test in our processor tests (methodology for scientists edition)

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#2470]
### Context

Context is #2458 and related to https://github.com/AlexsLemonade/sci-projects/issues/51

> Upgrade all of our docker containers to Ubuntu 20.04. Unfortunately CRAN doesn't make 20.04 packages with R less than version 4.0, so we also have to upgrade some of the bioconductor packages.

Only two tests related to the `no_op` pipeline are failing, but at first we were not really sure what we should test for the processors and tested relatively basic things like making sure the tximport output was summarized to the gene-level rather than the transcript-level (based on my and @kurtwheeler's recollection). 

So it's hard to say with confidence if the parts of the `no_op` pipeline touched by those two tests are the only parts of processing we expect to be impacted.

### Problem or idea

To determine if upgrading our images will affect processing in anyway, it makes sense to first take inventory of what our processor tests are testing to focus any follow-up on areas where we are not confident our tests would catch something with processing implications. If we're going to do that, it is probably a good idea to document that somewhere in an easily digestible Markdown document, because it's not the last time we'll run into something like this and I can imagine this saving me some time in the future!

I also think this might help with:

* A manuscript (https://github.com/AlexsLemonade/refinebio-docs/issues/86) -- it seems like it could be of interest to readers
* Informing additional unit tests we think we may be needed

### Solution or next step

I am planning to accomplish this as I try to understand the processing implications of #2458. I'm not sure where this file should go yet.

**Comment by kurtwheeler** [comment]
Here are my high level notes of what we test for each processor from looking over the code. I'm happy to provide more details on anything:

Affy:
    We fail on errors, but otherwise only check that it creates a file with the expected name as the output file.
Compendia:
    We just check the metadata is correct and skips samples without computed files.
Quantpendia:
    We check that the files exist in locations, probably sufficient for what it does.
    We also check the metadata a bit.
GEO:
    Illumina:
        Basic test just for success and making sure files exist.
        Checks that the wrong species fails platform detection
        Check detection of mislabeled sample
    Agilent:
        Checks that file gets created
No_op:
    some various tests for different scenarios but it does check filesize of outputs.
QN:
    We check that some values are almost equal.
Salmon:
    We have a lot of tests
    We check the outputted quant files against a reference to make sure they're strongly correlated.
    We check to make sure the unmapped reads are identical
Smasher:
    We have some tests, including running a few stat checks on the last frame.
    There's quite a few tests there actually!
Transcriptome:
    Not too much actually, just make sure the files are there

**Comment by jaclyn-taroni** [comment]
The next step for this is for me to break this up into individual issues for documentation _somewhere_. I'm going to remove the estimate and assign myself.

**Comment by davidsmejia** [comment]
This happened : )
