### ISSUE TITLE
Downloading Aspera in our docker images no longer works

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2479]
### Context

[Our affy tests are now failing on CircleCI](https://circleci.com/gh/AlexsLemonade/refinebio/34660?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

### Problem or idea
```
Step 19/34 : RUN wget -q https://download.asperasoft.com/download/sw/cli/3.7.7/aspera-cli-3.7.7.608.927cce8-linux-64-release.sh
 ---> Running in 4601ed63c1ba
The command '/bin/sh -c wget -q https://download.asperasoft.com/download/sw/cli/3.7.7/aspera-cli-3.7.7.608.927cce8-linux-64-release.sh' returned a non-zero code: 8
```

### Solution or next step

Maybe the problem is that we are using an old version of Aspera?

The first step is to figure out what wget's error code 8 means, then go from there.

**Comment by wvauclain** [comment]
Okay, I tried running it locally without the `--quiet` option and I got this:
```
$ wget https://download.asperasoft.com/download/sw/cli/3.7.7/aspera-cli-3.7.7.608.927cce8-linux-64-release.sh
--2020-08-10 11:47:18--  https://download.asperasoft.com/download/sw/cli/3.7.7/aspera-cli-3.7.7.608.927cce8-linux-64-release.sh
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving download.asperasoft.com (download.asperasoft.com)... 184.72.56.59
Connecting to download.asperasoft.com (download.asperasoft.com)|184.72.56.59|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-08-10 11:47:18 ERROR 403: Forbidden.
```
And the same thing for `download.asperasoft.com`. It looks like we need to find the new way to download aspera.

**Comment by kurtwheeler** [comment]
Ooof

**Comment by cgreene** [comment]
https://download.asperasoft.com/download/sw/cli/3.9.6/ibm-aspera-cli-3.9.6.1467.159c5b1-linux-64-release.sh

☝️ works. I wonder if they got rid of old versions due to some security flaw...

**Comment by wvauclain** [comment]
@cgreene that URL 403s for me

**Comment by cgreene** [comment]
👀  me too now! I thought I just downloaded it, but maybe that was the desktop client. Perhaps misconfigured server on their end?

**Comment by cgreene** [comment]
Yep - what I actually downloaded was https://download.asperasoft.com/download/sw/client/3.9.6/ibm-aspera-desktopclient-3.9.6.176292-linux-64.deb 😢
