### ISSUE TITLE
Multi-species RNA-seq Experiments

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#2516]
### Context

We don't currently process these successfully because we don't separate tximport by species. In the past, we've considered this and not bothered because we didn't expect many experiments like this. This came up again in #2515

### Problem or idea

This is common enough now that we've had 2 experiments requested of this type. Discussing with @kurtwheeler this seems manageable, so let's try.

### Solution or next step

Give it a shot.

**Comment by wvauclain** [comment]
Closing, we are now tracking this in https://github.com/AlexsLemonade/refinebio/issues/2806
