### ISSUE TITLE
Trouble downloading Dataset `GSE37382`

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/refinebio#2526]
### Context

The `GSE37382` dataset is central to the [issue](Alexslemonade/refinebio-examples#196) that references updating the microarray `refinebio-example` PCA notebook that already exists and uses the dataset in that repository.

### Problem or idea

 When attempting to download the refinebio dataset for experiment `GSE37382` (https://www.refine.bio/experiments/GSE37382), I only got as far as the `Your dataset is being processed` page. When tried again with another email address, the same issue was encountered.
<img width="576" alt="Screen Shot 2020-08-27 at 12 17 23 PM" src="https://user-images.githubusercontent.com/43576623/91471876-a290e580-e864-11ea-9d6c-004a71bdf6cf.png">
<img width="879" alt="Screen Shot 2020-08-27 at 12 17 29 PM" src="https://user-images.githubusercontent.com/43576623/91471883-a3c21280-e864-11ea-94bb-07e90701d3a3.png">

### Solution or next step

According to brief Slack conversation, this may possibly be an issue with the Smasher disk?

**Comment by kurtwheeler** [comment]
I cleaned up the disk and this is working again. Sorry about that, thanks for reporting!
