### ISSUE TITLE
Write out specs for refine.bio python client

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2537]
### Context

We want a python client for the refinebio API

### Problem or idea

I've got some ideas for how the python client should be implemented.

### Solution or next step

I need to write these out. Maybe provide a target README even.

**Comment by cgreene** [comment]
We also have design docs put together from a previous collaboration on this.

**Comment by kurtwheeler** [comment]
This is done! #2539
