### ISSUE TITLE
Filters/Search Stats Endpoint

### ISSUE THREAD

**Issue by ramenhog** [AlexsLemonade/refinebio#254]
### Context
A new filters/modified search stats endpoint is needed for the filters sidebar on the results page

### Problem or idea
We don't currently have an endpoint that returns all the possible filters for the current query as shown in the design (we only have an endpoint that returns a list of available organisms that isn't tied to the query):
   * organisms
   * technologies
   * includes publication

### Solution or next step
This endpoint definitely needs to be created for the frontend results page to be fully functional as designed. I'd definitely be into pairing to get this endpoint out 👍 

### Screenshot of Results Design
![screen shot 2018-05-14 at 10 32 21 am](https://user-images.githubusercontent.com/4724065/40003749-1d729e56-5762-11e8-93f1-435c1eb80c7d.png)

**Comment by Miserlou** [comment]
What do you mean by a stats endpoint? I thiiiink this should be doable without any new endpoints.

To add new filter fields, they simply need to be added to this line: https://github.com/AlexsLemonade/refinebio/blob/dev/api/data_refinery_api/views.py#L98

**Comment by ramenhog** [comment]
We did talk about this during yesterday's tech team meeting but just wanted to summarize for the ticket. We need to get a response back from that backend that shows a list of all the filters that can be applied to the current search and the number of experiments associated with each filter.
