### ISSUE TITLE
Datasets are not downloading with either `download now` or cart download

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio#2576]
### Context
I tried this with two datasets and neither are downloading. I don't know if this is front end or back end. 

These are two datasets I tried downloading either by `Download Now` or by the cart and neither worked. Both seemed to do nothing when I clicked the download button. 

 https://www.refine.bio/experiments/GSE24528/expression-analysis-of-zebrafish-melanoma-and-skin-from-the-mitf-brafv600e-p53-line and https://www.refine.bio/experiments/GSE37418/novel-mutations-target-distinct-subgroups-of-medulloblastoma

I don't know how to get a non-screenshot file of this but here's the report with some errors. 
<img width="1430" alt="Screen Shot 2020-10-18 at 4 35 39 PM" src="https://user-images.githubusercontent.com/23458084/96385287-eddabc80-1160-11eb-9690-3f3f39c18ad2.png">

### Problem or idea

 I don't know what this means but hopefully someone on the dev team does. Let me know how I can help.

**Comment by kurtwheeler** [comment]
I got this working by the way! The smasher instance's disk didn't automount again... I'll leave this open until I look into why.

**Comment by kurtwheeler** [comment]
This hasn't been a problem with the new smasher instance through Batch.
