### ISSUE TITLE
Tar file of CEL and CHP files given upon download

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio#2577]
### Context

This is a second hand report from a user friend and I wasn't able to replicate it because of #2576 , but apparently `https://www.refine.bio/dataset/b37a9aa9-ef34-4ab8-998c-def1957b1da9` yielded a download of a tar file filled with CEL files for this affy dataset: https://www.refine.bio/experiments/GSE100130/rna-expression-data-from-developing-enteric-nervous-system-ens-and-bowel

Here's image that was sent to me for the contents of the download file. 
![image000000](https://user-images.githubusercontent.com/23458084/96387721-38186980-1172-11eb-8ece-1d27853c83f3.jpg)

I wanted to report this because it is quite strange, but again, I'm not able to replicate it and I don't know how to look into it further. (`Regenerate files` did not work). 

If #2576 is fixed and this problem is also resolved, then we can feel free to delete this issue.

**Comment by kurtwheeler** [comment]
I downloaded this dataset and this is what I got:

```
$ unzip -d dl_dataset dataset.zip 
Archive:  dataset.zip
   creating: dl_dataset/GSE100130/
  inflating: dl_dataset/LICENSE.TXT  
  inflating: dl_dataset/README.md    
  inflating: dl_dataset/aggregated_metadata.json  
  inflating: dl_dataset/GSE100130/GSE100130.tsv  
  inflating: dl_dataset/GSE100130/metadata_GSE100130.tsv
```

Maybe it was a temporary issue? Can you ask your friend to try again?

**Comment by cansavvy** [comment]
I had my friend retry download and I tried download as well and we both got the metadata and data files as expected. So looks like whatever was causing this problem was temporary or was resolved otherwise. :+1:
