### ISSUE TITLE
Some samples were not processed because of being erroneously set to no_retry=True

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2583]
### Context

I think I found some easy-to-process samples while resolving https://github.com/AlexsLemonade/refinebio/issues/2432!

### Problem or idea

```
drpostgresuser=> select count(*), no_retry from processor_jobs where success='f' and retried='f' and failure_reason like '%there is no package called %' and num_retries=1 group by no_retry;
-[ RECORD 1 ]--
count    | 1744
no_retry | t
```

### Solution or next step

Just setting no_retry=False for the samples for https://www.refine.bio/experiments/GSE88884/ worked, so I think maybe it could work for these 1744 samples as well.

**Comment by cgreene** [comment]
Nice! 🚀

**Comment by kurtwheeler** [comment]
These all got run successfully!!!
