### ISSUE TITLE
Our method for building ENA URLs seems to have broken

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2593]
### Context

I was trying to run the experiment for #2592 but the downloader jobs all failed.

### Problem or idea

It seems to be caused by us creating the wrong ENA URL here:

We create `ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR115/008/SRR11523548/SRR11523548.fastq.gz`, but [ENA](https://www.ebi.ac.uk/ena/browser/view/SRR11523548) shows it as being `ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR115/048/SRR11523548/SRR11523548_1.fastq.gz`.

### Solution or next step

I believe that function works based off of patterns that we found. It seems like things may have shifted or went an increment that caused it to seem different. I'm not exactly sure, but perhaps it can be fixed or perhaps there's a less hacky/brittle way of determining this FTP URL.

**Comment by jashapiro** [comment]
There is! Use the ENA API: Here is some R code I used to get file urls a project at a time. It should be adaptable...

```
get_sample_df <- function(SRA_project){
  fields <- paste("run_accession",
                  "sample_accession",
                  "sample_alias",
                  "sample_title",
                  "experiment_title",
                  "fastq_ftp",
                  "fastq_md5",
                  "fastq_bytes",
                  sep = ",")
  ena_url <- stringr::str_interp("http://www.ebi.ac.uk/ena/data/warehouse/filereport?accession=${SRA_project}&result=read_run&fields=${fields}")
  ena_table <- readr::read_tsv(ena_url) %>%
    tidyr::separate_rows(fastq_ftp, fastq_md5, fastq_bytes, sep = ";")
}

**Comment by jashapiro** [comment]
The docs have improved somewhat from when I was working that out: https://www.ebi.ac.uk/ena/portal/api/#/Portal%20API/fileReportUsingGET

**Comment by jashapiro** [comment]
For the specific query listed above, the problem seems to be there are 2 files rather than the 1 expected?

I used the following query to the API:
`https://www.ebi.ac.uk/ena/portal/api/filereport?accession=SRR11523548&format=JSON&result=read_run`

And received the following response:
```
[
  {
    "run_accession": "SRR11523548",
    "fastq_ftp": "ftp.sra.ebi.ac.uk/vol1/fastq/SRR115/048/SRR11523548/SRR11523548_1.fastq.gz;ftp.sra.ebi.ac.uk/vol1/fastq/SRR115/048/SRR11523548/SRR11523548_2.fastq.gz",
    "fastq_bytes": "3974785619;4302276858",
    "fastq_md5": "d8a50de0f8ad36e08928698104d9da93;8a61cc0d417da6c00c716b3026e1ae59",
    "submitted_ftp": "",
    "submitted_bytes": "",
    "submitted_md5": "",
    "sra_ftp": "ftp.sra.ebi.ac.uk/vol1/srr/SRR115/048/SRR11523548",
    "sra_bytes": "6189199087",
    "sra_md5": "d4a0bdc21c8207e3a69bf7278429b01b"
  }
]
```
