### ISSUE TITLE
Retrieving samples information is very slow

### ISSUE THREAD

**Issue by grapesmoker** [AlexsLemonade/refinebio#2655]
### Context

I am trying to retrieve a list of samples from the `samples` endpoint, filtered by experiment accession code. Example call:

`https://api.refine.bio/v1/samples/?experiment_accession_code=GSE11611`

### Problem or idea

I would expect this call to complete fairly quickly; instead, either the call clearly times out and produces a 404 instead of the correct error code (see screenshot), or it takes about 20 seconds to complete. If I also supply a limit parameter `&limit=10`, the call usually succeeds but does so in about 12 or 13 seconds. Any larger limits (e.g. 100) fail after 30 seconds.

![Screen Shot 2021-02-01 at 4 50 59 PM](https://user-images.githubusercontent.com/1723233/106522674-0d96b600-64ae-11eb-80d8-33dd7d2e2f1a.png)

### Solution or next step

The amount of data being transferred here seems quite small; when limit is set to 10, I see between 5 and 10 kb of JSON being transferred. This seems like a call that should return quite quickly, so the problem looks like something on the backend.  Either there's something wrong with the filtering logic or there's a missing index somewhere.

**Comment by kurtwheeler** [comment]
Thanks for reporting this! That sounds like a bug of some sort. I'll take a look and see if I can figure anything out!

**Comment by davidsmejia** [comment]
I'm closing this issue though technically it is currently still unresolved. The queries have been improved by #2655 but the database needs to be worked on in general which will fix this specific issue. We are currently tracking those changes on #2874.
