### ISSUE TITLE
There's a lot of 500/400 errors being reported by sentry

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2663]
### Context

https://sentry.io/organizations/greenelab/issues/?project=1236818

### Problem or idea

These seem to be fairly consistent. We should investigate what's causing them.

### Solution or next step

Figure out why and fix them if possible.

**Comment by kurtwheeler** [comment]
While you're in there, add `filter_by` to special filters in the samples endpoint.

**Comment by kurtwheeler** [comment]
https://github.com/AlexsLemonade/refinebio/pull/2669 did not address this.

https://github.com/AlexsLemonade/refinebio/pull/2711 hopefully will, but we may need to go even larger.

**Comment by davidsmejia** [comment]
This is currently being tested with a larger elasticsearch box
