### ISSUE TITLE
Rework stats endpoint to use Batch instead of Nomad for job reporting

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2678]
### Context

#2584 

### Problem or idea

The stats endpoint that is used by the dashboards queries Nomad to see how many jobs are running/pending. Now that Nomad is being replaced by Batch, this will need to change as well.

### Solution or next step

Query Batch instead of Nomad for the stats endpoint.

**Comment by wvauclain** [comment]
Closing, this is duplicated here: https://github.com/AlexsLemonade/refinebio/issues/2701
