### ISSUE TITLE
Allow users to download transcriptome indices

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#268]
### Context

We use `salmon` to build indices which are then used while running `salmon` to process RNASeq data. These indices are based on data which we retrieve from ensembl.org.

### Problem or idea

Ensembl releases a new version every now and then. In April they released version 92. This broke our transcriptome code because rest.ensembl.org does not accept a release number as a query parameter. This means that we cannot rebuild old transcriptome indices using the same code that built them in the first place. In order for the data processed using those indices to be reproducible, we'll need to allow users to download the version of the transcriptome index which was used for the data they are interested in.

### Solution or next step

Since we cannot rebuild old transcriptome indices, we should store them and allow users to download any of them.

I'll note that this could become moot if Ensembl adds a `release` parameter to their REST API. I have emailed the mailing list requesting this.

### New Issue Checklist

- [X] The title is short and descriptive.
- [X] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
See http://lists.ensembl.org/pipermail/dev/2018-May/013012.html for a more in depth description of the problem and (hopeful) followup from the mailing list.

**Comment by jaclyn-taroni** [comment]
Possibly related: #79

**Comment by jaclyn-taroni** [comment]
During tech team meeting this morning, we decided to remove this from Keytar Kurt

**Comment by kurtwheeler** [comment]
Ok @Willv19 is going to tackle this before he gets to https://github.com/AlexsLemonade/refinebio/issues/341 since that will need these indices. I've come up with a rough outline of how to accomplish this:
 1. Create an S3 bucket within terraform to store the OrganismIndex files.
 2. Modify the OrganismIndex model to include an `s3_url` field which points to where the index is stored within S3.
 3. Modify the `transcriptome_index` processor so that it uploads the processed indices to the correct S3 bucket.
4. Deploy these changes.
5. Create a script to trigger surveyor jobs for all organisms in http://ensemblgenomes.org/  http://useast.ensembl.org/index.html.
6. Run the script within the staging or a dev stack and debug it until all of the organisms are processed.
7. Add an API route to retrieve the URLs for these indices. Basically a route like `/transcriptome_indices?organism=GALLUS_GALLUS&length=short` should do it.

**Comment by jaclyn-taroni** [comment]
@Willv19 was this closed by #363?

**Comment by Willv19** [comment]
Yes
