### ISSUE TITLE
Landing Page and Footer: Scope, Design Decisions, and Mockups

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#269]
### Context

This is to define scope and requirements for landing page and footer

#### landing page
- Search Bar
- Set value proposition: (Copy on #183)
  - Harmonized data
  - Build and download custom datasets
  - Summary stats, which could be samples/species, samples/date or petabytes of data/time

#### Footer

The footer needs to include the following information:
- Social (twitter, github, and gitter)
- Links to CCDL and ALSF
- Links to Privacy policy, and Terms and Conditions
- Licensing info 
- Version information

### Solution or next step
I will whiteboard out a rough draft of the layout for the landing page and footer.

**Comment by dvenprasad** [comment]
@Miserlou Do you have information needed for creating visualizations like number of samples/ species, samples/time, and petabytes/time? (Time refers to when the sample was added to the data source)

**Comment by cgreene** [comment]
It may be important to note that you mean petabytes of _raw_ data. Not processed. 😁

**Comment by Miserlou** [comment]
There is a `/stats` endpoint available but to be honest we should just hardcode reasonable estimates of the values we want.

We don't have it as a deliverable yet but the "compendium" releases should be part of the value prop/offering rather than stats (if you need 3), as they're a booster but not a valueprop in their own right.

Other notes: 
Don't link to the Gitter since it's abandoned
Long-form "about" link in footer
Docs in the footer
Tutorials/Blog in the footer
Contact/feedback form/link in the footer
Ideally 'Donate' in the footer if we can get that sorted out properly?

**Comment by dvenprasad** [comment]
Summary of today's LowFi Review

- The summary stats are going to be pre-computed, so the data displayed will be a little dated
- @jaclyn-taroni Can you please suggest a few example search terms?
- @ramenhog Can you please clarify whether we can leave out First and Last Name on the MailChimp form for sign up?

LowFi Mockups:
<img width="907" alt="landing-page-final" src="https://user-images.githubusercontent.com/15315514/40511955-5148300a-5f6f-11e8-8c4e-405575fba788.png">

<img width="883" alt="footer-v2" src="https://user-images.githubusercontent.com/15315514/40511961-573a6276-5f6f-11e8-9528-797d16c58b81.png">

**Comment by jaclyn-taroni** [comment]
Suggestions for example search terms: `Notch`, `medulloblastoma`, `GSE16476`

**Comment by jaclyn-taroni** [comment]
Related: #190

**Comment by dvenprasad** [comment]
Summary of the HighFi Review: 

- Brainstorm for new tagline (copy above search bar)

- Use variation #2 with a straight footer

Variation 1:
![variation1](https://user-images.githubusercontent.com/15315514/40731885-10d239d6-6400-11e8-99f5-193e5180fe07.png)

Variation 2:
![variation2](https://user-images.githubusercontent.com/15315514/40732014-5bdebd28-6400-11e8-81ec-128007d706a1.png)

Variation 3:
![variation3](https://user-images.githubusercontent.com/15315514/40732024-61de664c-6400-11e8-8254-5b498c9afdff.png)

**Comment by dvenprasad** [comment]
Invision mockups
[https://invis.io/V8JTYDYNKCM#/300190943_landing-Page](https://invis.io/V8JTYDYNKCM#/300190943_landing-Page)

The badges (search and build dataset) are in the MidFi Project's Assets/Badges section.

Guidelines and states for checkboxes and numbered badges are in the master.sketch file in https://github.com/AlexsLemonade/refinebio-design
(Note: No new guidelines has been added since the last iteration) 

@ramenhog @arielsvn  let me know if you need anything else.
