### ISSUE TITLE
Determine ensembl version via API call rather than hardcoding versions.

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#274]
### Context

Ensembl released a new version of its API's and this broke our code:https://github.com/AlexsLemonade/refinebio/pull/266#pullrequestreview-122598723

### Problem or idea

The ensembl mailing list replied to the concern I raised about it: http://lists.ensembl.org/pipermail/dev/2018-May/013014.html

The upshot is that they do archive the last five releases, but at special URLs. The more useful information is that the current release can be found by hitting http://rest.ensembl.org/info/software?content-type=application/json. So we can harden our code by using that rather than hardcoded version numbers.

### Solution or next step

Rather than having `MAIN_DIVISION_ASSEMBLY_VERSION` and `OTHER_DIVISIONS_ASSEMBLY_VERSION` hardcoded in `foreman/data_refinery_foreman/surveyor/transcriptome_index.py`, first hit the endpoint to determine the correct version to specify.

I tagged this as a SCIENCE issue because I think we need @jaclyn-taroni and @cgreene to make sure that automatically using to the latest version of ensembl won't be undesired behavior. I'll note that it's not like we'll automatically reprocess all the organism indices when a new version is released, we'll just use the latest version whenever we do decide to rerun the Index Refinery.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
Using the latest version whenever we decide to update the indices seems fine. We need to know which version was used for a specific organism though, and we also need to store the transcriptome indices that we have used and make them available (potentially) to users. Doesn't have to be a fancy approach - sticking them in a bucket with a link to them should be fine.

**Comment by jaclyn-taroni** [comment]
I agree

**Comment by jaclyn-taroni** [comment]
Was this closed by #310?

**Comment by cgreene** [comment]
Looks like it. https://github.com/AlexsLemonade/refinebio/pull/310/files#diff-aad5724ec88845dd627fd8338f38ed27R127

Should be safe to close.
