### ISSUE TITLE
Rename array_express and no_op processors

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2747]
### Context

The `array_express` and `no_op` processors are not accurate names. array_express refers to where the data comes from, not what is done to it. no_op is short for No Operation, but in fact the processor does gene identifier conversions.

### Problem or idea

These processors should be renamed throughout the project.

### Solution or next step

Rename the array_express processor to affymetrix and the no_op processor to gene_identifier_conversion.

**Comment by wvauclain** [comment]
Closing, this is also tracked in https://github.com/AlexsLemonade/refinebio/issues/2702
