### ISSUE TITLE
Create separate RAM tiers for Compendia jobs and dispatch based on Organism

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2772]
### Context

Right now Compendia jobs only have one set amount of ram. However compendia jobs for Human and Mouse require way more RAM than the rest of the organisms.

### Problem or idea

In the past we've dealt with this by changing that value and redeploying. That is burdensome, requires dev time, and is slower.

### Solution or next step

We should have two ram tiers for Compendia/Quantpendia jobs and put Human/Mouse jobs on the big one and the rest on the small one.

**Comment by wvauclain** [comment]
Once we do this we should be able to fix these lines:
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/create_compendia.py#L396,L397

**Comment by wvauclain** [comment]
Related to https://github.com/AlexsLemonade/refinebio/issues/2744

**Comment by kurtwheeler** [comment]
Closed by #2908
