### ISSUE TITLE
Samples that make it to `illumina.R` don't process successfully

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2793]
### Context

Still trying to find a reference file for the Illumina tests

### Problem or idea

I found an experiment [GSE56080](https://www.refine.bio/experiments/GSE56080/orphan-nuclear-receptor-err-is-required-for-pancreatic-islet-beta-cell-maturation) that processed a sample successfully, but if you look at the output file these are the entire contents:
```tsv
GeneID	Ad-EGFP-1.AVG_Signal
```

The actual input file is not empty though.

### Solution or next step

It looks like the process of converting `GSE56080_non-normalized.txt.sanitized` into `GSE56080_non-normalized.PCL` filters out all of the rows; maybe for a good reason but the processor job probably shouldn't succeed.

**Comment by wvauclain** [comment]
I figured out the cause of this issue; it turns out that
https://github.com/AlexsLemonade/refinebio/blob/65b724cf8dc47c211cb37fd2a252e5423df7032a/workers/data_refinery_workers/processors/illumina.R#L428
is not selecting the right column, so R _helpfully_ gives us an empty vector instead of throwing an error :disappointed: 

This causes a new error, however, because it turns out that probe IDs do not correspond to a unique gene ID!

For example, [ILMN_1651268](https://useast.ensembl.org/Homo_sapiens/Location/Genome?fdb=funcgen;ftype=ProbeFeature;array=HumanRef-8_V3;vendor=ILLUMINA;id=ILMN_1651268) maps to both [ENSG00000165714](https://useast.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000165714;r=12:12357078-12471233) and [ENSG00000280689](https://useast.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000280689;r=12:12357078-12471233). @jaclyn-taroni hypothesized that this could be an issue with poor probe quality, but `ILMN_1651268` has perfect probe quality so filtering based on quality didn't help.

I looked through Ensembl this morning and I found something interesting though: [the two genes above are alleles](https://useast.ensembl.org/Homo_sapiens/Gene/Alleles?db=core;g=ENSG00000165714;r=12:12357078-12471233). I checked this for another probe that maps to multiple gene IDs, and [it held](https://useast.ensembl.org/Homo_sapiens/Gene/Alleles?db=core;g=ENSG00000237541;r=6:32741391-32747198;t=ENST00000374940) for [that probe too](https://useast.ensembl.org/Homo_sapiens/Location/Genome?fdb=funcgen;ftype=ProbeFeature;array=HumanHT-12_V4;vendor=ILLUMINA;id=ILMN_3249667).

@jaclyn-taroni do other microarray manufacturers also have this issue? If so, how do we deal with it in e.g. the Affymetrix processor? Hopefully, that is the only reason why high-quality probes are mapping to multiple genes.

**Comment by jaclyn-taroni** [comment]
@wvauclain for information gathering purposes, do you have the version number for the Illumina annotation package you're working with handy?

**Comment by wvauclain** [comment]
I think it's 1.26.0, from
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/illumina_dependencies.R#L25,L34

**Comment by wvauclain** [comment]
Closed in https://github.com/AlexsLemonade/refinebio/pull/2844
