### ISSUE TITLE
Batch parameter validation failure

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2809]
### Context

Spinning up a devstack

### Problem or idea

When spinning up the devstack I got spammed with a bunch of copies of this message:

```
Parameter validation failed:
Unknown parameter in input: "tags", must be one of: jobDefinitionName, type, parameters, containerProperties, nodeProperties, retryStrategy, timeout
Unknown parameter in containerProperties: "executionRoleArn", must be one of: image, vcpus, memory, command, jobRoleArn, volumes, environment, mountPoints, readonlyRootFilesystem, privileged, ulimits, user, instanceType, resourceRequirements, linuxParameters
Unknown parameter in containerProperties: "secrets", must be one of: image, vcpus, memory, command, jobRoleArn, volumes, environment, mountPoints, readonlyRootFilesystem, privileged, ulimits, user, instanceType, resourceRequirements, linuxParameters
Unknown parameter in containerProperties: "logConfiguration", must be one of: image, vcpus, memory, command, jobRoleArn, volumes, environment, mountPoints, readonlyRootFilesystem, privileged, ulimits, user, instanceType, resourceRequirements, linuxParameters
```

### Solution or next step

I think the issue is in the batch job definitions (since there were so many copies of this), so investigate and figure out what we're doing wrong there

**Comment by kurtwheeler** [comment]
Are you sure this isn't just caused by https://github.com/AlexsLemonade/refinebio/issues/2808? I think that some of these parameters may have been added in more recent versions of terraform, so if you had an older version this error message wouldn't surprise me.

**Comment by wvauclain** [comment]
Figured out the issue, it was an issue on my machine. Added more info to https://github.com/AlexsLemonade/refinebio/issues/2810
