### ISSUE TITLE
Add more documentation around spinning up a devstack

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2810]
### Context

Currently spinning up a devstack to run end-to-end tests

### Problem or idea

I've ran into a couple issues where I had to install extra packages. The packages so far:

```
awscli < you also need to sign in
python3-boto3 < for deregister_batch_job_definitions.py
psql < for deploy.sh
```

### Solution or next step

Document this somewhere

**Comment by kurtwheeler** [comment]
Thank you for keeping track of this! I forgot that I had installed those along the way.

**Comment by wvauclain** [comment]
An important roadblock I just figured out: you need to install `awscli` and `boto3` using `pip3` instead of Ubuntu's repositories. Ubuntu's repositories (at least on my machine) have out-of-date versions of both programs, which caused https://github.com/AlexsLemonade/refinebio/issues/2809
