### ISSUE TITLE
Add `is_queued` parameter to job endpoints

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2812]
### Context

I removed the `nomad` parameter: https://github.com/AlexsLemonade/refinebio/commit/73dc56d84567f076d79b577af2ea242e91e12563#diff-a7ce68dcae10038cb21e2da530be6a6f05e1cd96155be7dce54fc237070ef3a4L53

### Problem or idea

That was used by the frontend, which was broken by this change.

### Solution or next step

Readd the parameter, except call it `is_queued` instead.

**Comment by wvauclain** [comment]
Closed by https://github.com/AlexsLemonade/refinebio/pull/2813
