### ISSUE TITLE
Sample metadata field names should be prefixed during smashing flattening

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2856]
### Context

We flatten sample's metadata into a single row during smashing and compendia creation so that we can put it in a TSV.

The way we do this has caused this error: https://sentry.io/share/issue/6a0a516965d34aafbe4e455434452f22/

### Problem or idea

The sample's annotation metadata uses the key `status` in both the top level and a nested object:
```
{
   "status":[
      "Public on Jan 07 2014"
   ],
   "characteristics_ch1":[
      "tissue: Breast",
      "predicted risk: low",
      "hu306 classification: HER2-enriched",
      "her2: over-expression",
      "er: positive",
      "survival time (year): 5.50",
      "event: disease-free",
      "status: alive"
   ],
}
```

When we flatten this object, there are two values for `status`: `"Public on Jan 07 2014"` and `"alive"`. This causes the conflict message we saw.

### Solution or next step

Prefix field names with their nested data structure, so that we end up with a `status` field and a `characteristics_ch1_status` field.

**Comment by wvauclain** [comment]
While I agree that this is the best option, we should think about the consequences of this change on our end-users, because this would be a breaking change in the metadata that we supply to them.
