### ISSUE TITLE
Surveyor Commands in Readme

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#2880]
I was trying to run a surveyor job locally but the readme was referencing a file that didnt exist. Per Kurt we should rename `run_surveyor.sh` to `run_management_command` to make things more consistent.

Part of the docs I'm referring to:
https://github.com/AlexsLemonade/refinebio#surveyor-jobs

Next steps:
Make sure that gets changed or update the readme.

**Comment by kurtwheeler** [comment]
This was fixed in https://github.com/AlexsLemonade/refinebio/pull/2783
