### ISSUE TITLE
What should we do when "tximport" fails in Salmon pipeline?

### ISSUE THREAD

**Issue by dongbohu** [AlexsLemonade/refinebio#289]
### Context

This question was brought up when PR #278 is reviewed:
https://github.com/AlexsLemonade/refinebio/pull/278#discussion_r191561485

### Problem or idea
In current implementation, if `tximport ` fails, `job_context['success']` is set to false and the following steps (`salmontools` and `fastqc`, etc) will be terminated. This may not be completely sensible, because `tximport` is done at experiment level, but all the other steps in Salmon pipeline are at sample level. Even if for some reason `tximport` fails, we may still be able to do `salmontools` and `fastqc` steps.

### Solution or next step
In the long run, it may make more sense to separate the experiment level `tximport` from Salmon pipeline and put it in its own pipeline.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
If `tximport` fails we probably did something wrong. I don't think we'll want to return anything to the user until after we investigate the cause of the failure. We will want to make sure that failures at this stage are bubbled up as errors so that we can dig into them (and maybe reported via Sentry?).

**Comment by kurtwheeler** [comment]
As per a discussion with @cgreene and @jaclyn-taroni a couple days ago, I believe this issue is now closed because we're sending the errors into Sentry so we'll know about them and the current behavior sounds like it is desired.
