### ISSUE TITLE
Create loading spinner

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#292]
### Context

refine.bio doesn't have a custom spinner. 

### Problem or idea

Create a loading spinner which fits with refine.bio's theme to display when pages/results are loading

### Solution or next step
I will design a spinner.

**Comment by cgreene** [comment]
Rotating DNA portion of the refine.bio logo? 😀

**Comment by dvenprasad** [comment]
Yes, DNA hourglass! Maybe won't use the logo though.

**Comment by dvenprasad** [comment]
An alternative to using the spinner can be using skeleton screens for loading, given that we have a large amount of information to display. 

[https://blog.ionicframework.com/improved-perceived-performance-with-skeleton-screens/](https://blog.ionicframework.com/improved-perceived-performance-with-skeleton-screens/)

@ramenhog @arielsvn 
I'm not sure if this is an optimum solution from a front-end perspective but we should discuss this an option post keytar kurt.

**Comment by Miserlou** [comment]
Not a back-end issue, moving here: https://github.com/AlexsLemonade/refinebio-frontend/issues/182
