### ISSUE TITLE
Modify Samples end point to return detailed information

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#296]
### Context

The [experiments page](https://projects.invisionapp.com/d/main#/console/13557531/297243710/preview) needs to display a Table with detailed information about the Samples associated with an experiment.

### Problem or idea

We don't have an endpoint that returns detailed information for the samples associated with one experiment.

On https://github.com/AlexsLemonade/refinebio-frontend/pull/48 we're doing an individual request for each sample in the experiment. This means we're also not able to sort the samples there.

### Solution or next step

It would be good to modify the Samples List endpoint so that it returns detailed information for a sample, and add some parameter to sort the samples.

Also, it would be good if that endpoint returns the samples associated with some experiment, right now we have to send the individual ids in the url (`?ids=1,2,3,4`). 

@Miserlou @kurtwheeler @ramenhog

**Comment by kurtwheeler** [comment]
This looks like it should be a simple enough change. The only question I have is whether we want the list samples endpoint to return detailed information by default, when passed an extra parameter, or to have a new endpoint for listing detailed samples. I suspect @Miserlou will have strong opinions about this.

**Comment by Miserlou** [comment]
Are you asking for the Samples result to be modified, or for the Experiments endpoints to use the detailed sample serializer
