### ISSUE TITLE
Fix failing test_common job

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/refinebio#3020]
```
#20 785.6 Downloading package from url: https://bioconductor.org/packages/3.11/bioc/src/contrib/sva_3.36.0.tar.gz
#20 787.4 edgeR (NA -> 3.28.1) [CRAN]
#20 787.4 Skipping 1 packages not available: locfit
#20 787.4 Installing 2 packages: locfit, edgeR
#20 787.4 Installing packages into '/usr/local/lib/R/site-library'
#20 787.4 (as 'lib' is unspecified)
#20 788.3 Error: Failed to install 'unknown package' from URL:
#20 788.3   (converted from warning) package 'locfit' is not available (for R version 3.6.3)
#20 788.3 Execution halted
#20 ERROR: executor failed running [/bin/sh -c Rscript install_affy_only.R]: exit code: 1
------
 > importing cache manifest from ghrc.io/alexslemonade/refinebio/dr_common_tests:
------
------
 > [17/22] RUN Rscript install_affy_only.R:
------
executor failed running [/bin/sh -c Rscript install_affy_only.R]: exit code: 1
Could not build ccdlstaging/dr_common_tests after three attempts.
Error: Process completed with exit code 1.
```

https://github.com/AlexsLemonade/refinebio/runs/6312124113?check_suite_focus=true#step:11:19905

Could someone suggest a proper way to get it resolved? My understanding is that [locfit package](https://cran.r-project.org/web/packages/locfit/index.html) is no longer available for R v3.*

Is upgrading R environment (the ubuntu version?) the right way to fix this?

**Comment by arkid15r** [comment]
@davidsmejia @jashapiro would appreciate your input here.

**Comment by jashapiro** [comment]
We don't want to upgrade the R environment, as that would require a lot of other changes.  Looking at previous versions of `locfit` here: https://cran.r-project.org/src/contrib/Archive/locfit/ and comparing to the release date of Bioconductor 3.11 that the rest of the packages there are using, (April 28, 2020), it seems like the best version for `locfit` will be `1.5-9.4`, which is just one version previous and does support R 3.x. 

So I think we should be able to just add
`devtools::install_version('locfit', version='1.5-9.4')`
to `install_affy_only.R`
https://github.com/AlexsLemonade/refinebio/blob/a21a6ecba77bf518026962323461b0ef536b39e8/workers/install_affy_only.R#L7-L10

If there are other places in the codebase where `locfit` is being installed (these may be hidden if imported by Bioconductor packages as here) this may well come up again.

Ah, the joy of R dependencies!
