### ISSUE TITLE
Initialize foreman/gatherer

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#3060]
### Context

We need to incorporate the code from `refinebio-accession-gathering` into the foreman.

### Solution or next step

- add the code to the foreman app in foreman/gatherer
- We will want to make the code executable from inside the foreman as a management command
- we will want to save to the new `accession_backlog` table when running a command
- we will want to make sure when writing to the backlog that the experiments have not already been surveyed

Target the feature/automatic-accessions branch

**Comment by arkid15r** [comment]
Implemented in https://github.com/AlexsLemonade/refinebio/pull/3067
