### ISSUE TITLE
Create a cron job to populate accessions backlog

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#3061]
### Context

We would like accession gathering to be automatic (and later automatic surveying) so let's create a cron job that runs the newly created `gatherer`. We should be running this command on a weekly every sunday. The command to populate the 

### Solution or next step

- Add separate `gather_weekly_accessions.py` to gatherer
- Add cron rule that runs this command every sunday that reads `--since` the last sunday.

Target the feature/automatic-accessions branch

**Comment by arkid15r** [comment]
Implemented in #3068
