### ISSUE TITLE
Rollback Bioconductor to ver 3.6

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#3192]
### Context

Refinebio workers should be running [Bioconductor 3.6 on R version 3.4.2](https://bioconductor.org/news/bioc_3_6_release/). The current version on production and staging has packages installed with version 3.11. This was done in an effort to get the images to build so that we could deploy.

At the time of updating to 3.11/12 the tool that we had for pinning R dependencies was [cranlock](https://github.com/AlexsLemonade/cranlock) and now that we have a solution in place using [renv](https://rstudio.github.io/renv/articles/renv.html) we should be able to pin nested dependencies.

After going through the history we started with 3.6 then switched to the latest release, then to 3.12, then rolled back to 3.11. Over that time many of the dependencies have switched versions and will most likely need to be rolled back as well. 

Here are the more important commits that capture the changes we want to "revert". 

- When bioc was pinned to 3.11 - https://github.com/AlexsLemonade/refinebio/commit/edf40e8321493ae98780f9bd29ef84fb55c5d626
- When bioc was pinned to release - https://github.com/AlexsLemonade/refinebio/commit/cf67fe54a68581ab32862c67f018e7f64608238e

For more context, this is a more holistic view of what has changed, but this includes changes we want to keep. This is more for reference as you roll back specific images I believe this will be useful. 

- https://github.com/AlexsLemonade/refinebio/compare/e8cbafeceef84f772ad475b0627486598f4e0a4e...dev

Also here is the commit history of `affymetrix_dependencies.R` which is the starting point I used to go commit by commit until I reached a point in time where we were installing version 3.6.
- https://github.com/AlexsLemonade/refinebio/commits/4d098817b2c8ad28a778f0445ca4f9e572f4f0b4/workers/affymetrix_dependencies.R

### Problem or idea

The obvious problem here is that we want to go back to using bioconductor 3.6. As we currently have a PR for [switching to renv for managing R dependencies](https://github.com/AlexsLemonade/refinebio/pull/3184) we should incorporate the rollback and pinning into that PR. The strategy will remain the same and we just want to make sure that we rebuild the lockfile before merging.

Also, we expect this rollback to cause issues with builds and tests. I think it makes sense for us to first solve for the building after rolling back and then create separate issues for the tests.

### Solution or next step

Essentially we want the builds to be successful after the rollback and we will tackle any breaking tests in future PRs.

- All changes below to happen in https://github.com/AlexsLemonade/refinebio/pull/3184
- Rollback to bioc 3.6
- Update to solve for dependencies 
- Create a new lockfile
- Create new issues for the new breaking tests.

- We should also create a test to prevent this type of problem from coming up again.

**Comment by arkid15r** [comment]
Resolved by PRs linked above.
