### ISSUE TITLE
Change ComputationalResult command field to array

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#320]
### Context

During a meeting about provenance, we discussed updating the ComputationalResult table command field to be an array rather than a string.

### Problem or idea

`command` field should include all commands involved to generate this result.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.

**Comment by dongbohu** [comment]
Done by #346.
