### ISSUE TITLE
How should we build and version the docs?

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#321]
### Context

During a provenance meeting, the questions of what we use to build docs and how we will version them (e.g., capture if we have changed a decision -> change in a processor code -> update docs) came up. It is related to the discussion initiated over on #184.

### Problem or idea

We need to identify the tool or tools we will used to write and build the documentation. We need a strategy for updating the documentation in a case like I've outlined above.

### Solution or next step

@ramenhog: what would you like us to use to write the docs so that they integrate well into the website?
Once this is decided, we'll need to figure out the versioning bit with multiple members of the team.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
I was thinking about this a bit more. I agree that versioning is important. Especially if a processor changes, we will want the docs to be from the version that processed a sample in question (with an option to see the latest docs if requested).

**Comment by ramenhog** [comment]
Do we want to keep the docs within the app itself? Or do we want to use an external tool for managing the docs?

**Comment by jaclyn-taroni** [comment]
+1 for markdown

**Comment by cgreene** [comment]
I'm not sure if the frontend repo is ideal. It _may_ become important to be able to link to the documentation associated with the exact processor version (aka refine.bio commit) that was used. For everything else, we could have docs that are up to date with the current system. We have not yet had a change to a processor that has resulted in something that would change the docs. If we wanted to kick this can down the road a bit we could, but one day we're going to have to figure out how we want to solve it.

**Comment by cgreene** [comment]
☝️ this would potentially be aided by having docs specific to the processor live near the processor code & semantic versioning on the processors.

**Comment by ramenhog** [comment]
Would using the github wiki for `refinebio` work?

**Comment by cgreene** [comment]
Would we link people to this wiki or would we somehow import this wiki content onto the page? If we'd link people out, it'd depend on what @dvenprasad thinks.

**Comment by ramenhog** [comment]
We would link people out if we use the wiki. I don't think it makes sense to iframe that content into the frontend app.

**Comment by cgreene** [comment]
Ok - then @dvenprasad : what do you think of this approach?

**Comment by ramenhog** [comment]
Here's a link to Github's docs about the wiki: https://guides.github.com/features/wikis/#creating-your-wiki

**Comment by dvenprasad** [comment]
I would prefer if the the docs look like they live within in refine.bio. 
Maybe something simple like this: [https://docs.haiku.ai/](https://docs.haiku.ai/)

**Comment by cgreene** [comment]
Those don't appear to have versioning information. If we started to use semantic versioning for our processors, then we could do something like that. Or we could go with that for now, but we will have to come up with a good solution when we need to cross this bridge. I'd be more comfortable doing that if we had some sort of rough idea as to what the plan would be then.

**Comment by ramenhog** [comment]
Haiku looks like it's using gitbook: https://www.gitbook.com/

It looks like it supports versioning now.

**Comment by cgreene** [comment]
Hmm - looks like it could be a good solution! Commits to/from github are also bi-directional so it sounds like GitHub stays as the single point of truth. Also, markdown is supported 😁 

@ramenhog: does this look good from your point of view?

**Comment by dvenprasad** [comment]
This sounds good to me.

**Comment by cgreene** [comment]
I was doing a bit of testing in #337. It looks like GitBooks allows editing directly on GitBooks as well. When someone does that, it makes a commit to the branch in question here. Should I attempt to disable that so that things only go one way (from GitHub -> GitBooks) or are we ok with changes to the docs coming through without review if they come in via GitBooks?

**Comment by ramenhog** [comment]
You know I'm all about that one-way data flow 😉 #ReactRedux4Lyfe

**Comment by jaclyn-taroni** [comment]
>  Should I attempt to disable that so that things only go one way (from GitHub -> GitBooks)

Agree

**Comment by cgreene** [comment]
I have looked through all of the docs that I can find on the integration + the settings and there _does not appear to be a way_ to make it one-way only. We could agree never to edit on GitBooks, but that appears to be the only option if we want to use GitBooks. https://docs.gitbook.com/integrations/github

**Comment by jaclyn-taroni** [comment]
> We could agree never to edit on GitBooks

This feels a tad dangerous to me as a person that could possibly forget we agreed to never do that.

**Comment by cgreene** [comment]
I don't disagree. @dvenprasad and @ramenhog: were there other options for this type of service that were appropriate for our workflow, or is this more or less all that there is?

**Comment by ramenhog** [comment]
That's the main one I'm familiar with. I've just seen it used for a lot of frontend tech documentation.

**Comment by cgreene** [comment]
Docusaurus looks like it could work for us. It looks like we might need to play a bit with the CI system to make sure we call the correct command to enable versioning on deployments that have a tag.

https://docusaurus.io/docs/en/versioning

**Comment by dvenprasad** [comment]
I think we can use [ReadTheDocs](https://docs.readthedocs.io/en/latest/index.html) if @cgreene and @jaclyn-taroni feel that they would be comfortable working with it.

I'm not a fan of their layout but they have search feature which is +1 from a UX perspective.

**Comment by ramenhog** [comment]
I am also 👍 with ReadTheDocs

**Comment by jaclyn-taroni** [comment]
@cgreene 

supports markdown: http://docs.readthedocs.io/en/latest/getting_started.html#in-markdown
versioning info: http://docs.readthedocs.io/en/latest/versions.html

**Comment by cgreene** [comment]
I have used it in the past and I am 👍 on it. I wasn't sure if it met our design needs. Is it sufficiently theme-able? It sounds like yes, if @dvenprasad is not telling us no. 😁

**Comment by dvenprasad** [comment]
it looks like they have a CSS file rtd.css which we can modify. It's a yes from me.

**Comment by cgreene** [comment]
Decision made! Read the docs it is!
