### ISSUE TITLE
Fix test_salmon Missing salmontools and tximport test data

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/refinebio#3213]
### Context

In order to restore staging/prod deploy process CI/CD tests need to be fixed.

### Problem or idea

```
Running all tests..
Downloading 'salmon quant' test data...
Cloning into '/home/runner/work/refinebio/refinebio/workers/test_volume/salmontools'...
fatal: could not read Username for 'https://github.com': No such device or address
Error: Process completed with exit code 128.
```

### Solution or next step

Resolve exit code 128 error.

**Comment by arkid15r** [comment]
It seems to be caused by https://github.com/AlexsLemonade/refinebio/blob/c4b4a6ad9392b911eec754c81b50a0b05b5f4d41/workers/run_tests.sh#L82
```
  # Download salmontools test data
  rm -rf "$volume_directory"/salmontools/
  git clone https://github.com/dongbohu/salmontools_tests.git "$volume_directory"/salmontools

  # Download tximport test data
  rm -rf "$volume_directory"/tximport_test/
  git clone https://github.com/dongbohu/tximport_test.git "$volume_directory"/tximport_test
```

Need some ideas on how to resolve this.

**Comment by arkid15r** [comment]
I'd like some guidance on this as the tests/data might need to be updated since the salmontools test data is no longer available.

**Comment by davidsmejia** [comment]
closing this and opening: https://github.com/AlexsLemonade/refinebio/issues/3223
