### ISSUE TITLE
Create human readable templated field on ComputationalResult

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#323]
### Context

We were in the provenance meeting.

### Problem or idea

We want a human readable form of the processor metadata + some key versions.

### Solution or next step

This will be compiled at run-time based on a human-written template for each processor and stored on `ComputationalResult`.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by dongbohu** [comment]
This one overlaps with #322 and #361.
