### ISSUE TITLE
Create and Associatate 'Processor' and 'Pipeline' objects with 'ComputationalResult' objects

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#324]
### Context

In the interest of provenance and reproducibility, we need to associate `ComputationalResults` with an explicit `Processor` model which tracks the purpose, program, image and environment of a processor, and a `Pipeline` object which defines an explicit association of the various `ComputationalResult` objects which are produced during the transformation of a sample into a smashable ComputedFile.

### Problem or idea

Processor objects should contain a docker image string in the form `accountname/imagename:systemversion`, and an `environment` JSONField which contains information about key packages, extracted at runtime, as well as a SHA1 hash of that field's contents which can be used for fast lookup. In addition, it should have a short name and a human-readable name that can be used for compiling a Pipeline's human readable name.

The Pipeline object should have an ArrayField containing the PKs of ComputationalResult objects. (ArrayFields in Postgres preserve order, so no step_number field is necessary.) Pipelines should have a human_readable_name, which can either be explicit or a dynamic property compiled from the Processor objects it is related to through ComputationalResults.

### Solution or next step

A hypothetical schema from the whiteboard:

![20180618_121031](https://user-images.githubusercontent.com/139987/41548932-4e56a4a8-72f2-11e8-88a5-7ec09afb88e1.jpg)

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Related/superset of:

https://github.com/AlexsLemonade/refinebio/issues/320
https://github.com/AlexsLemonade/refinebio/issues/321
https://github.com/AlexsLemonade/refinebio/issues/322
https://github.com/AlexsLemonade/refinebio/issues/323

**Comment by dongbohu** [comment]
Fixed in #346.
