### ISSUE TITLE
Combine Coverage Outputs and Track with Coveralls

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#326]
### Context

We are using `coverage` as part our tests, but we're not measuring this value over time (so we don't even notice when tests fail in such a way that it drops to 0%). 

We should combine the outputs of our coverage files (`coverage run`, `coverage report`, `coveralls`)and then use [Coveralls](https://coveralls.io/) to track this value over time.

### Problem or idea

This metric makes it harder to steer our ship, so we will want to start doing this once we're happy with the general function and stability of the system.

### Solution or next step

Set up a Coveralls account and update the Circle requirements and config.yml. We may need to use CircleCI artifacts to do this properly, although we might not as sometimes Coveralls can figure this out by itself since the commit hash is the same.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Willv19** [comment]
If python-coveralls doesn't have a solution for you, an alternate solution might be to just manually replace all references using `sed`. This should work:
```
cat workers/test_volume/.agilent.coverage | sed "s/\/home\/user/workers/g" > workers/test_volume/.agilent.coverage
```

**Comment by Miserlou** [comment]
I'm not thrilled about the maintainability of that solution, but it's better than nothing.. want to try adding that in a new commit in my branch?

**Comment by kurtwheeler** [comment]
We're using codecov to accomplish this these days.
