### ISSUE TITLE
Conversion of submitter-supplied gene identifiers to Ensembl gene ID: Illumina BeadArray

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#328]
### Context

A subset of what was originally envisioned for #186. As of the writing of this ticket/#307, we add support for the detection of submitter-supplied gene identifiers and conversion to Ensembl gene IDs. Currently, this requires us to generate and store a mapping between the identifiers we will support conversion from and the Ensembl gene ids (see: https://github.com/AlexsLemonade/refinebio/pull/307#issuecomment-396364904). We have only generated this data for Brainarray-supported Affymetrix.

### Problem or idea

We'll need to generate this mapping for the supported Illumina BeadArray platforms: https://github.com/AlexsLemonade/refinebio/issues/232#issuecomment-389302061 and https://github.com/AlexsLemonade/refinebio/issues/232#issuecomment-389609871 (also related: https://github.com/AlexsLemonade/refinebio/issues/222#issuecomment-389571978).

### Solution or next step

I will work with the backend team to generate this mapping for supported Illumina BeadArray platforms. The initial solution to this likely involves using the `.db` Illumina packages and filtering by probe quality as [is done in the Illumina SCAN processor](https://github.com/AlexsLemonade/refinebio/blob/e9900fa42459ab1b06e8980f5d8849705351f338/workers/data_refinery_workers/processors/illumina.R#L424). I think it makes sense to tackle this or at least discuss it at the same time as #232 because the same packages will be required.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
@Miserlou was this closed by #375?

**Comment by Miserlou** [comment]
Closed by #375!
