### ISSUE TITLE
Initial version of cross-technology aggregation

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#330]
### Context

We'd like to provide the ability to combine samples from microarray and RNA-seq. I imagine this is going to be a concern almost exclusively when "smashing" by species rather than by experiment.

### Problem or idea

For Marimba Miso, from https://github.com/AlexsLemonade/refinebio/issues/186#issuecomment-395187013:
>if there are a mix of technologies:

> aggregating by experiment -> return untransformed output from tximport
> aggregating by species -> log2(x + 1) tximport output

In the near future, we'd like to do something [like this](https://github.com/AlexsLemonade/refinebio/issues/186#issuecomment-395218310).

### Solution or next step

The smasher logic should take the technology and the aggregation type into account when smashing RNA-seq data and transform when appropriate.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
From the parent:

> The Troyanska lab had something a little more complicated that I think Chad Myers wrote but we should do this for now.

Does anybody have a paper on this to share for my files?

**Comment by cgreene** [comment]
It may be earlier than this, but it's roughly described in the hefalmp paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2694471/

> We collected 635 human microarray data sets from the NCBI Gene Expression Omnibus (GEO) repository (Barrett et al. 2005) comprising 14,671 conditions; see Supplemental Table 1 for a complete list. These were processed largely as in Huttenhower and Troyanskaya (2008), with additional manipulation to handle single-channel data and the ambiguity of human probe mapping. Within each data set, negative and very small (less than two) single-channel values were removed, genes with missing values in >30% of the conditions were removed, and the remaining missing values were imputed using KNNImpute (Troyanskaya et al. 2001) with k = 10 (cutoff values recommended by Hibbs et al. [2007] and Troyanskaya et al. [2001], respectively).
> 
> Probe IDs were mapped to HGNC symbols using the appropriate GEO platform files. When multiple probes mapped to a single HGNC symbol, a consensus set of probes was generated by finding pairwise Euclidean distances more likely to have been generated from the data set's distribution of intragene probe pairs than from the distribution of intergene probe pairs. If this consensus set contained at least half of the probes mapping to a gene symbol, the consensus set's average value became the expression vector for that gene.
