### ISSUE TITLE
Rename 'Refine.bio Mail Robot' to something descriptive

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#3322]
### Context

'Refine.bio Mail Robot' isn't super descriptive of what we use that email for. We use it to provide information about the datasets - processed or failed and the name should reflect that.

Also am a little concerned of the word robot getting it flagged and pushed into a non-primary inbox folder. 

### Problem or idea

Rename it `refine.bio Datasets` (yes, lower case r) 

### Solution or next step

@davidsmejia Is there anything else we use that email for?

**Comment by davidsmejia** [comment]
We can make that change [ here ](https://github.com/AlexsLemonade/refinebio/blob/e2a5b53b5abfe4d99fd7b5e988a62b1330ad9d74/workers/data_refinery_workers/processors/smasher.py#L434)

We only send emails for datasets - note that this sender is for successful and unsuccessful processing mails.
