### ISSUE TITLE
Update ALSF Address In Email

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#3371]
### Context

Alex's Headquarters have moved. We include the ALSF mailing address in the smasher email that gets sent out. The current address is outdated and needs to be updated.

Templates that need to be updated here:
- https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/smasher_email_error.html#L1849
- https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/smasher_email.html#L1842

### Solution or next step

Update the address to:

```
Alex’s Lemonade Stand Foundation for Childhood Cancer
333 E. Lancaster Ave, #414, Wynnewood, PA 19096 USA
```

**Comment by davidsmejia** [comment]
This change will also require updating the minified versions of these templates.

**Comment by arkid15r** [comment]
Implemented in https://github.com/AlexsLemonade/refinebio/pull/3372
