### ISSUE TITLE
Move github secrets to 1Password

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#3390]
### Context

We are now keeping the project secrets in 1Password. This issue is to track adding in that functionality and addressing side effects of the transition.

### Solution or next step

- Update actions to include loading secrets from 1Password
- Use a terraform variable for SSH public key in `infrastructure/`
- Add [environment](https://docs.sentry.io/platforms/python/legacy-sdk/advanced/) to sentry sdk initializations to [RAVEN_CONFIG](https://github.com/search?q=repo%3AAlexsLemonade%2Frefinebio+RAVEN_CONFIG&type=code)
- Update scripts to reference updated variable names (the OP_ name but without the OP for consistency across projects)

**Comment by arkid15r** [comment]
Resolved in https://github.com/AlexsLemonade/refinebio/pull/3391
