### ISSUE TITLE
Secrets Manager Secret value not set on deploy

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio#3406]
### Context

After testing the latest dev on staging I encountered a critical failure during our deploy. From what I can tell it looks like we are not populating `var.sentry_dsn`correctly during deployment.

This next comment might not be relevant but I wanted to include for completeness. This deployment was triggered via pushing the `v1.45.1-dev` tag. However this was encountered in a subsequent re-run of the GHA after fixing issues with the deploy box key.

### Problem or idea

Output from the deploy:

```bash

Error: putting Secrets Manager Secret value: InvalidRequestException: You must provide either SecretString or SecretBinary.

  on secrets.tf line 24, in resource "aws_secretsmanager_secret_version" "sentry_dsn":
  24: resource "aws_secretsmanager_secret_version" "sentry_dsn" {

```

### Solution or next step

- Make sure `sentry_dsn` gets populated correctly

**Comment by arkid15r** [comment]
Resolved in https://github.com/AlexsLemonade/refinebio/pull/3409
