### ISSUE TITLE
Create a static IP address for the prod/staging API and enable HTTPS

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#342]
### Context

In #315 I was able to get the API up and running and have our DNS point to it. However every time the instance is recreated during deploys its IP address changes so the DNS record becomes out of date and `http://api.staging.refine.bio` breaks.

Additionally when the DNS is working, it doesn't support HTTPS. The reason for both of these issues is that the top level domain `.bio` is not supported by AWS' Route53, so the methods we used previously for Cognoma's DNS, SSL, and ELBs aren't able to be reused here.

### Problem or idea

We should get a static IP address for the API servers so the DNS stops breaking and we should make them support HTTPS.

### Solution or next step

- [x] Put a load balancer in front of the API with an elastic IP address associated with it so that the IP address won't change.
- [ ] Create and install an SSL cert onto the API servers so they can support HTTPS.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
Closed by #343
