### ISSUE TITLE
"Identifier refinery" repository and gameplan for gene conversion Docker image

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#348]
### Context

**Related:** #186, #307, #328, #329 

We are currently putting together mappings between gene identifiers to be used for converting submitter-processed data to Ensembl gene IDs, as the majority of data we'll be processing from raw (RNA-seq, Brainarray-supported Affymetrix, and Illumina BeadArray) will use these identifiers. This requires us to use multiple resources and/or perform some custom filtering because we are removing certain probes based on quality when we process data from their raw state.

The initial pass we took at this process can be found here: https://github.com/AlexsLemonade/refinebio/pull/307#issuecomment-396364904

### Problem or idea

The code, Dockerfile(s), and the gene identifier files to be used for mapping should be made publicly available and reusable and be versioned. We should use a versioned DOI or link to get the gene identifier mappings into the Docker image used for gene conversion (more information on that below).

### Solution or next step

- Create an AlexsLemonade repository that contains the code and Dockerfile(s) necessary for reproducing our mappings. We should keep in mind that this will need to be updated periodically. 
- We should upload these mapping files that will be used in our own gene conversion pipeline to a research data repository that supports versioning like [Zenodo](https://zenodo.org/) or [figshare](https://figshare.com/).
- When building the gene conversion Docker image, we should `wget` the mappings from the data repository (explicitly specifying the version rather than using the latest). This version information should be captured in our system somehow. I am not sure which database table is most appropriate.

This is how I would probably approach this problem in my own research right now, but it's definitely open for discussion.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
The new repository lives here: https://github.com/AlexsLemonade/identifier-refinery
