### ISSUE TITLE
Design Server Error Flags

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#350]
### Context

@ramenhog and I discussed about handling unexpected server errors and decided that flag style messages would be appropriate. 

### Problem or idea

Create a design for error flags. 

### Solution or next step

I will create one and hand it over to @ramenhog.

**Comment by dvenprasad** [comment]
@ramenhog I've added the flags to master.sketch
[https://github.com/AlexsLemonade/refinebio-design](https://github.com/AlexsLemonade/refinebio-design)

**Comment by ramenhog** [comment]
Looks great! That's all I should need.
