### ISSUE TITLE
Do we really want the bracketed part of platform names to be displayed?

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#354]
### Context

@Miserlou saw some values in the database that made him think they might be errors, however they were actually correct. The values were on a sample with `platform_accession_code='chicken'` and `platform_name='[Chicken] Affymetrix Chicken Genome Array'`. However, as you can see [here](https://github.com/AlexsLemonade/refinebio/blob/dev/config/readable_affymetrix_names.csv#L10), these are actually valid values.

### Problem or idea

The `sample.platform_name` is going to be used by the frontend to display to the users. @Miserlou was curious if the `[Chicken]` part of the platform_name was really something we wanted to show. I generated that file using data that @jaclyn-taroni gave me, so I'm not really sure how necessary or not they are.

### Solution or next step

Let's get @jaclyn-taroni and @dvenprasad to either confirm that we want those brackets to be displayed or confirm that we should remove them.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
So `Chicken` is actually the platform name. If one was to say `Affymetrix Chicken Genome Array`, that could be ambiguous -- is it the Chicken array or the Chicken Gene 1.0 ST Array? I don't think `Affymetrix Chicken Genome Array` would have been enough information for me before I became highly familiar with lots of the Affymetrix projects while working through #228. I'm not tied to the particular display/wording: `[Chicken] Affymetrix Chicken Genome Array`

Let's see what @dvenprasad thinks.

**Comment by jaclyn-taroni** [comment]
I would be down with things outside brackets + ( expected cel header ). In this example:

`[Chicken] Affymetrix Chicken Genome Array` becomes `Affymetrix Chicken Genome Array (chicken)`

**Comment by dvenprasad** [comment]
@jaclyn-taroni Can you say bit more about the expected cel header? Is that how platform is coded in their download files?

**Comment by jaclyn-taroni** [comment]
It is what we expect will be in the _raw data_ we get from our data sources for this particular kind of microarray. 

> Is that how platform is coded in their download files?

This is a smasher question for @Miserlou -- will they get the _human readable name_ in the metadata?

**Comment by dvenprasad** [comment]
I want to make a note that this pattern of naming is not just for `Chicken` but also for `Bovine`, `Zebrafish`, `AG`, `Citrus`, `Cotton`, `Wheat`. 

I like  @jaclyn-taroni's idea of `platform_name (expected cel header)`. It formats well and also makes it easier for users to relate back to raw data (I could be wrong but it maybe useful if they want to process the raw themselves in a different way)

**Comment by jaclyn-taroni** [comment]
> it maybe useful if they want to process the raw themselves in a different way

I agree

**Comment by Miserlou** [comment]
There is will create some ugly ones, ex: `Affymetrix HT HG-U133+ PM Array Plate (hthgu133pluspm)` but I guess that's okay.  Is `(hthgu133pluspm)` really any better than `[HT_HG-U133_Plus_PM]`?

Either way, I think we can keep the data as it stands, but use an `@property` to generate whatever formatting we want in the response. I'm satisfied now that I know that `[Chicken] Expensive Chicken RNA Robot` makes sense.
