### ISSUE TITLE
CCDL training-associated data should be processed & available on staging

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#366]
### Context

The CCDL will be running an event July 18-20 to test out a curriculum for training childhood cancer researchers to process RNA-seq data. As part of the training, we'd like to get them to analyze public data alongside their own data.

### Problem or idea

Ideally they will get their public data from refine.bio. We'd like to have data in there for them. We have some idea of what they are interested in. It would be ideal to get the following into the staging server:
- [ ] All RNA-seq samples associated with https://www.ncbi.nlm.nih.gov/bioproject/359632 (can skip the microRNA-Seq ones at this time if it's easier)
- [ ] GSE85217
- [ ] GSE37382
- [ ] SRX3599593, SRX3599592, SRX476317, SRX476316
- [ ] GSE17714
- [ ] All of the RNA-seq samples associated with this bioproject: https://www.ncbi.nlm.nih.gov/sra?linkname=bioproject_sra_all&from_uid=395053
- [ ] GSE66533
- [ ] GSE14767
- [ ] Array Express E-TABM-873
- [ ] GSE25604
- [ ] GSE75793
- [ ] GSE92741

### Solution or next step

I assigned @kurtwheeler since he has processed the other crunches. 🍤  If we could get this processed soon (ideally by ~the 9th so we could start playing around with it in the context of the curriculum) that'd be ideal!

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
Looks like #268 will probably be wrapped up soon, but don't know what our plans are for running the index refinery. I think we'd like to have _Danio rerio_ and _Homo sapiens_ transcriptome indices available for training as well.

**Comment by Miserlou** [comment]
Should be okay to feed to the system:
```
Homo sapiens
Danio rerio
SRR5137164
SRR5137165
SRR5137166
SRR5137167
SRR5137168
SRR5137169
SRR5137170
SRR5137171
SRR5137172
SRR5137173
SRR5137174
SRR5137175
SRR5137176
SRR5137177
SRR5137178
SRR5137179
SRR5137180
SRR5137181
GSE85217
GSE37382
SRX3599593
SRX3599592
SRX476317
SRX476316
GSE17714
SRR5849874
SRR5849875
SRR5849876
SRR5849877
SRR5849878
SRR5849879
SRR5849880
SRR5849881
SRR5849882
GSE66533
GSE14767
E-TABM-873
GSE25604
GSE75793
GSE92741
```

**Comment by jaclyn-taroni** [comment]
When we get the _Danio rerio_ and _Homo sapiens_ transcriptome indices, we'll also need the tx to gene mapping text file that gets fed to `rsem-prepare-reference` -- we'll need that for `tximport`.
