### ISSUE TITLE
Allow PUT request on individual dataset endpoint on staging

### ISSUE THREAD

**Issue by ramenhog** [AlexsLemonade/refinebio#372]
### Context
On staging, when users try to add/remove experiments/samples from/to an existing dataset, they get the following error:

![screen shot 2018-07-09 at 9 40 07 am](https://user-images.githubusercontent.com/4724065/42457605-dfd14de2-8365-11e8-87de-94ec8a12dc1b.png)

This seems to be causing the issues related to modifying a dataset in `refine-bio/frontend`

### Problem or idea
We should allow PUT requests on the dataset endpoint on staging. This seems to be working locally.

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by Miserlou** [comment]
Should be closed by https://github.com/AlexsLemonade/refinebio/pull/369
