### ISSUE TITLE
Microarray smash job had a couple issues when analyzed by our data scientist

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#390]
### Context

I ran a crunch on GSE37382 and then smashed it together for @jaclyn-taroni. After using the data some she identified a couple issues with it.

### Problem or idea

1. Each sample had two columns, one which had `_x` appended to the sample name and one which had `_y` appended to the sample name.
2. Some metadata values seem to have been lost:

> any metadata that was not "smoothed" through Rich's pipeline -- I didn't have it
so, we did not have `histology` and `subgroup` for this dataset: https://www.ebi.ac.uk/arrayexpress/experiments/E-GEOD-37382/samples/?query=GSE37382
but I did have age and sex

### Solution or next step

Figure out what's happening with the smasher that's causing these issues and fix it. @jaclyn-taroni can provide additional details as needed.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Can you share the result file here?

**Comment by jaclyn-taroni** [comment]
What I have from @kurtwheeler is too big to post here

**Comment by Miserlou** [comment]
How big / how many samples? Can you share via Slack?

**Comment by kurtwheeler** [comment]
I reran this dataset on my greenelab machine locally because getting the staging UI to submit a smasher job wasn't working. I can give you the files on a USB though @Miserlou

**Comment by Miserlou** [comment]
Hopefully addressed in PR.

**Comment by Miserlou** [comment]
Closing as #391 should have addressed this, feel free to re-open if you can still reproduce.
