### ISSUE TITLE
The foreman crashes during large enough deploys

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#416]
### Context

If the Nomad agent goes down or the foreman loses the ability to talk to Nomad for other reasons, the 500s returned by the Nomad client will cause each of the threads to die.

### Problem or idea

We should make the foreman be resilient to the Nomad server being down.

### Solution or next step

Add exponential retries up to a total amount of time that is reasonable.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
@kurtwheeler made foreman more resilient in one of his closed branches
