### ISSUE TITLE
Add capabilities to designate that some jobs should not be retried

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#431]
### Context

Currently we try to run failing jobs three times. This can help catch intermittent errors, but it also can result in a lot of extraneous jobs for errors that aren't intermittent.

### Problem or idea

We should add a `do_not_retry` field to the jobs tables and then utilize it whenever we know an error won't go away in subsequent runs.

### Solution or next step

Modify the tables and then identify errors in our jobs that are not intermittent to use it fore.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
Was this closed by #549 @Miserlou ?
