### ISSUE TITLE
Shell call to salmon failed with error message: ### salmon (mapping-based) v0.9.1

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#434]
https://sentry.io/greenelab/staging-refinebio/issues/613738208/

```
Shell call to salmon failed with error message: ### salmon (mapping-based) v0.9.1
### [ program ] => salmon 
### [ command ] => quant 
### [ libType ] => { A }
### [ index ] => { /home/user/data_store/Homo_sapiens/index }
### [ unmatedReads ] => { /home/user/data_store/SRP095882/SRS1888280/SRR5137179.fastq.gz }
### [ threads ] => { 20 }
### [ output ] => { /home/user/data_store/SRP095882/SRS1888280/processed/ }
### [ seqBias ] => { }
### [ dumpEq ] => { }
### [ writeUnmappedNames ] => { }
Logs will be written to /home/user/data_store/SRP095882/SRS1888280/processed/logs
[2018-07-20 08:33:01.237] [jointLog] [info] parsing read library format
[2018-07-20 08:33:01.237] [jointLog] [info] There is 1 library.
[2018-07-20 08:33:01.294] [jointLog] [info] Loading Quasi index
[2018-07-20 08:33:01.299] [jointLog] [info] Loading 32-bit quasi index
[2018-07-20 08:33:01.305] [stderrLog] [info] Loading Suffix Array 
Exception : [Failed to read 8 bytes from input stream! Read 0]
salmon quant was invoked improperly.
For usage information, try salmon quant --help
Exiting.
```

**Comment by jaclyn-taroni** [comment]
@kurtwheeler - this could be due to the fact that some samples were run before transcriptome indices were generated

**Comment by jaclyn-taroni** [comment]
@Miserlou - we should check for the existence of transcriptome index before failing like this. We may have code that does this but should verify that it is working properly.

**Comment by kurtwheeler** [comment]
I just ran a salmon job for a sample for which we don't have a transcriptome index built for. It properly detected that and failed the job gracefully.

I do not know how to reproduce this salmon error. We may want to consider improving the logging around this so we can get a better idea of what's happening if/when this happens again.

**Comment by kurtwheeler** [comment]
Ok so it looks like the logging is pretty decent. I think that there were some things that were buggy while this was run that may have been fixed. However it's hard to say so I'd like to see this error come up again before I spend to much more time digging into it.

However I did discover https://github.com/AlexsLemonade/refinebio/issues/477 while looking into this.
