### ISSUE TITLE
Add search by author and institution

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#439]
### Context

Results from usability evals

### Problem or idea

Users would like to search by author or institution. The user may have an author in mind and would want to find all the datasets associated with that author. 

This was briefly discussed during the search page iteration. We chose to not include it because information about all authors was not available to us and the search would only be on Submitter's name. It is more useful for users to be able to search by the first author's name, but in most cases they are not the submitters. 

### Solution or next step
Discuss feasibility with @Miserlou and @jaclyn-taroni and determine determine next steps.

**Comment by Miserlou** [comment]
This is already added in my branch.

**Comment by Miserlou** [comment]
(At least for the backend)

**Comment by dvenprasad** [comment]
I want to add that there are other missing publication information. For example, @cgreene  pointed out that some of them have PubMed IDs but no Publication titles ([https://github.com/AlexsLemonade/refinebio-frontend/issues/151](https://github.com/AlexsLemonade/refinebio-frontend/issues/151)).

**Comment by jaclyn-taroni** [comment]
@Miserlou - does this mean we are obtaining _all_ author information from PubMed #214 ?
