### ISSUE TITLE
Link the PubMed ID/ Publication Title to the publication 

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#440]
### Context

Results from usability evals

### Problem or idea

Users mentioned on multiple occasions that they would like to be linked to the publication when looking at the publication title or PubMed ID. 

This was briefly discussed during the search page iteration. It was suggested that we look up the publication via pubmed API. 

### Solution or next step

Discuss feasibility with @Miserlou and @jaclyn-taroni and determine next steps.

**Comment by dvenprasad** [comment]
Getting the info from Pubmed  will help resolve #439

**Comment by Miserlou** [comment]
I think this is really a frontend issue since it'll just be a link to `https://www.ncbi.nlm.nih.gov/pubmed/?term={{experiment.pubmed_id}}`
