### ISSUE TITLE
Filters change based on filtered results isn't correct

### ISSUE THREAD

**Issue by Willv19** [AlexsLemonade/refinebio#441]
### Context

https://github.com/AlexsLemonade/refinebio-frontend/issues/185

### Problem or idea

The backend seems to return filters using both the search term and the applied filters to determine what filters can be applied. The expected behavior on the frontend would be to ignore the applied filters and just return the filters calculated from the search term itself. This allows someone to filter for multiple mutually exclusive things, like for samples from either Gallus gallus or Homo sapiens.

### Solution or next step

Alter the code that determines appropriate filters to disregard already applied filters. We also have to nail down the exact behavior we want from the filters, i.e. any sample that matches any of the filters should be returned, any sample that matches a filter from every category should be returned, etc.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by dvenprasad** [comment]
- Match samples with OR logic for filters within the same category
- Match samples with AND logic for filters between categories

For example: 
If I chose filters Homo sapiens, Gallus gallus(Organism), and RNA-seq(technology), I would expect samples which are RNA-seq and either Homo sapiens or Gallus gallus samples

**Comment by jaclyn-taroni** [comment]
@dvenprasad How should we prioritize this? Should we include that in this sprint?

**Comment by dvenprasad** [comment]
Yes, include it in the current sprint with high proirity since it's blocking https://github.com/AlexsLemonade/refinebio-frontend/issues/185
