### ISSUE TITLE
Build the infrastructure that builds the docs

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#446]
### Context

We decided to use read the docs in #321.

### Problem or idea

We now need to define where docs go based on what the build process needs.

### Solution or next step

@kurtwheeler offered to take a look at setting up read the docs.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Here: https://github.com/AlexsLemonade/refinebio-docs
and here: https://refinebio-docs.readthedocs.io/en/latest/
