### ISSUE TITLE
Create Management Command For Compiling Compendia

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#448]
### Context

We want to create _The Compendia_: all of the samples for every species smashed in a single gigantic matrix.

### Problem or idea

If we define a `create_compendia_ management command, we can build those datasets and dispatch the smash jobs without having it to do it manually. 

### Solution or next step

Make the thing!

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
Minor edit: all of the samples for each species is probably better. There are ways to map across species but they are dicey and definitely open research questions. We did hear some approaches presented at CSIG 2018, so hopefully good answers will start to come along soon!

**Comment by Miserlou** [comment]
PR'd here: https://github.com/AlexsLemonade/refinebio/pull/449#event-1758115124
