### ISSUE TITLE
Documentation content for September

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#450]
### Context

We need docs!

### Problem or idea

Adapted from #184 

**Proposed TOC:**

- Source Data
  - Types of Data
  - Sources
  - Metadata
        - Submitter Supplied
        - Corrected Metadata

- Downloadable Files
  - Gene Expression Matrix
  - Sample Metadata
  - Experiment Metadata

- Processing Information
  - refine.bio/CCDL processed
     - RNA-seq pipelines
     - microarray pipelines
  - Submitter Processed
  - Aggregations
  - Transformations (gene scaling, normalization)

- CCDL Developed Packages
   - SCAN (For Illumina Bead Array) 
   - Identifier Refinery
- Compendia

- Use Cases for Downstream Analysis

In addition, we can compile an FAQ and add it to the docs page. Some of the questions could be:
- What is the difference between refine.bio/CCDL processed and Submitter Processed datasets?
- How do you process the data?
- What type of data does refine.bio support?
- What does "Corrected" metadata mean?

### Solution or next step

How does this look @dvenprasad and @cgreene ? I've made some post Keytar Kurt updates.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

#### Related

#101

**Comment by dvenprasad** [comment]
There's currently no indication of corrected metadata on the front-end.

Would be how to combine their data with refine.bio's covered as one of downstream analysis use cases? 
Do you think it would be relevant to include how to cite refine.bio for this release?

**Comment by jaclyn-taroni** [comment]
> There's currently no indication of corrected metadata on the front-end.

Yes, that might be the case. However, there are some values being "smoothed" (see: https://github.com/AlexsLemonade/refinebio/pull/252). That should be in our docs in my opinion. If it needs to be indicated on the frontend, we should file a frontend issue.

**Comment by jaclyn-taroni** [comment]
> Do you think it would be relevant to include how to cite refine.bio for this release?

@cgreene how do folks typically cite a web server in the absence of a preprint in your experience?

**Comment by jaclyn-taroni** [comment]
> Would be how to combine their data with refine.bio's covered as one of downstream analysis use cases?

Maybe. I think of this as more of an "advanced use case" and how to combine data with refine.bio's is  broad. How one attacks the problem depends on the question at hand, so we'd need to pick one (maybe more than one) narrower use cases.

**Comment by jaclyn-taroni** [comment]
@dvenprasad should we plan to include screenshots in the documentation?

**Comment by dvenprasad** [comment]
Yes cropped screenshots would be useful. Also, maybe include icons/badges we use as indicators on the UI. For example, indicators for refine.bio processed and submitter processed.

**Comment by jaclyn-taroni** [comment]
FAQ: Why do the values differ a little bit if i download different datasets? https://github.com/AlexsLemonade/refinebio/issues/488#issuecomment-411522961

**Comment by jaclyn-taroni** [comment]
FAQ: Why do I get a limited number of genes back when I aggregate samples from different platforms? 

☝️ Currently, we drop genes that are not present in all samples. So if you include HGU133plus2, HGU133A, and HGU133B in your gene expression matrix, there will be a limited number of genes returned.

**Comment by jaclyn-taroni** [comment]
Note to self: For compendium section, make a table of the reference platforms for each species

**Comment by jaclyn-taroni** [comment]
FAQ: How can I find out what versions of software/packages were used to process the data?

**Comment by jaclyn-taroni** [comment]
I think it's more useful to track things over at https://github.com/AlexsLemonade/refinebio-docs/issues, so I am closing this.
