### ISSUE TITLE
We need a mechanism to retry previously failed experiments/samples

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#451]
### Context

The Foreman currently will retry jobs up to a certain number of times. After that number, it then assumes that the job is failing for a non-transient reason and gives up. The job may have failed because the data or metadata were mangled or wrong, but it also could fail because of a bug.

### Problem or idea

If there is a bug which causes one or more jobs to fail which is then fixed, we need a mechanism to retry the affected experiments/samples.

Currently there is a hacky workaround to get jobs to be retried: change the `num_retries` field for the last job that was tried to 1. This causes the Foreman to think the job hasn't been retried enough and it queues it up once again. This isn't a great solution for a few reasons:
  * It's very manual and requires direct manipulation of the database tables
  * It only works at a job level. If you want to retry experiment X you need to determine the samples for the experiment, then the files for the samples, then find which jobs were associated with those files.
  * The job is only retried once so if there's a transient error it will fail without trying again.

### Solution or next step

Create a Django management command to queue fresh jobs based on Experiment Accessions, Sample Accessions, or Job IDs. Ideally these could be specified via a file similar to the way the  `survey_all` management command works.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
So I've thought about this a bit more and I've decided that two separate mechanisms would probably be best:
  * One to delete an experiment and anything associated with it. (Which means then we can just re-run a surveyor job for that experiment)
  * One to retry a downloader or processor job which is no longer being retried (either because it hit the limit or because of https://github.com/AlexsLemonade/refinebio/issues/431)

**Comment by Miserlou** [comment]
> One to delete an experiment and anything associated with it

I'm not crazy about this. If an experiment fails to scrape, but it contains samples that are used by another experiment which did scrape.. there might be some problems.

**Comment by kurtwheeler** [comment]
Hmm, that's true. However when a surveyor job fails, there may be undiscovered samples associated with it, but yet the job won't rerun because the experiment already exists. Perhaps rather than `anything associated with it` we could delete `anything associated with it and not anything else`?
