### ISSUE TITLE
Audit our data cleanup/management practices throughout the project

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#452]
### Context

https://github.com/AlexsLemonade/refinebio/pull/386 will move processed files to S3 and cleans up the raw files that were direct inputs to the process. However if we download any supplemental or extraneous files or create any temporary files they may just end up sitting on disk in EFS, which is expensive.

### Problem or idea

Look through the various surveyors, downloaders, and processors we have and determine if they are downloading or creating any temporary files which should be cleaned up.

### Solution or next step

Once files have been identified that should be cleaned up but are not being cleaned up, add code to delete them.

A potential test to verify that data is being cleaned properly would be run some jobs and see that the EFS volume is empty after everything completes: all of the processed data should be in S3 and everything else should be deleted.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Related upstream ticket: https://github.com/guma44/GEOparse/issues/41

**Comment by jaclyn-taroni** [comment]
@Miserlou: may shake out during collaborative code review

**Comment by jaclyn-taroni** [comment]
@kurtwheeler: may not be required before 1% crunch

**Comment by jaclyn-taroni** [comment]
Would you say this can be closed now that you've gone through the majority of the code base @Miserlou @kurtwheeler @dongbohu ?

**Comment by Miserlou** [comment]
Yep we're good now
