### ISSUE TITLE
Running multiple salmon jobs for the same organism at once is dangerous

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#455]
### Context

While looking into https://github.com/AlexsLemonade/refinebio/issues/163 I noticed something concerning. I noticed that the test volume's processed directory has two sub-directories in it:
```
562M	data-refinery/workers/test_volume/processed/TEST/TRANSCRIPTOME_INDEX/Caenorhabditis_elegans_short_1527089586.tar.gz
739M	data-refinery/workers/test_volume/processed/TEST/TRANSCRIPTOME_INDEX/index
```

This is because I have run the tests already. If I hadn't yet run the tests it would only contain:
```
data-refinery/workers/test_volume/processed/TEST/TRANSCRIPTOME_INDEX/Caenorhabditis_elegans_short_1527089586.tar.gz
```

### Problem or idea

We're extracting OrganismIndex tarballs to:
```
data-refinery/workers/test_volume/processed/<ORGANISM_NAME>/TRANSCRIPTOME_INDEX/index
```
regardless of whether the index is long or short. This means that if a salmon job for a long index for organism X is running and then a salmon job for a short index for the same organism starts, the index file will be overwritten. If two jobs are running at the same time they both could be extracting the organism index to the same place.

### Solution or next step

Fix the bug where multiple salmon jobs can interfere with each other by running at the same time. This could be as simple as appending the length to the path `data-refinery/workers/test_volume/processed/<ORGANISM_NAME>/TRANSCRIPTOME_INDEX/index`, i.e `data-refinery/workers/test_volume/processed/<ORGANISM_NAME>/TRANSCRIPTOME_INDEX/index_short`.

However these organism indices are going to be a relatively minor amount of data. Should we just speed up all our salmon jobs by leaving `data-refinery/workers/test_volume/processed/<ORGANISM_NAME>/TRANSCRIPTOME_INDEX/index_short` and `data-refinery/workers/test_volume/processed/<ORGANISM_NAME>/TRANSCRIPTOME_INDEX/index_long` on the EFS disk uncompressed? Then we can just rip out all the decompression code and only compress the indices long enough to push them up to S3.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
I think that I fixed this already as part of a batch of fixes, but I'll confirm today.
