### ISSUE TITLE
Enable state locking for terraform remote backend

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#461]
### Context

We're now using terraform's remote backend feature to use our state directly from S3. However we aren't utilizing their state locking feature. This means that if multiple deploys try to run at the same time Bad Things :tm: could happen. However we deploy infrequently and only when someone triggers a deploy via a tag so this should be fine for the time being. I tried to set up the state locking but it just didn't seem to work and we've got more important issues to tackle first.

### Problem or idea

Long term it'd be good to utilize the state locking feature.

### Solution or next step

Set up state locking and make sure it works. I tested this by running terraform twice from the same machine and having each run do conflicting things to S3 buckets.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Is there an upstream ticket related to "it just didn't seem to work"?

**Comment by kurtwheeler** [comment]
> Is there an upstream ticket related to "it just didn't seem to work"?

No, I didn't dig into it deep enough to really figure out what was going wrong. I'm assuming there was something that I did wrong. However there wasn't any output which gave me something to work on and I didn't wanna spend the time to really dig in at this point.

**Comment by Miserlou** [comment]
Did #462 close this?

**Comment by kurtwheeler** [comment]
No, #462 closed https://github.com/AlexsLemonade/refinebio/issues/207 and spawned this because state locking was a black box it didn't seem worth debugging at the time.

**Comment by kurtwheeler** [comment]
This was closed by #1326
