### ISSUE TITLE
Some of our logs are being throttled causing us to lose some log records

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#477]
### Context

While investigating https://github.com/AlexsLemonade/refinebio/issues/434 I noticed that some of the log messages I expected to see were missing.

### Problem or idea

@Miserlou did a little poking around and determined that it's because our requests to push logs into CloudWatch are getting throttled. We potentially can punt on this issue for a while by increasing the buffer size, but that probably won't hold up at scale.

### Solution or next step

We may need to use another logging solution like an ELK stack or paying for a logging SASS such ass loggly.com.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Seems to be handled by logging way less stuff.
