### ISSUE TITLE
Remove Non-Expression Column from Illumina NO_OP

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#480]
### Context
During the Jackiecrunch, it was discovered that samples such as `GSM1089291-tbl-1.txt` contain a column field, likely a p-value:

```
ILMN_1885639	10.0000	0.7931
ILMN_2209417	10.0000	0.2029
ILMN_1765401	152.0873	0.0000
```

That apparently survive the gene conversion step:

```
ENSEMBL	10.0000	0.7931
ENSG00000105675	10	0.2029
ENSG00000085721	152.0873	0
```

We don't want these value as they will muck up the smasher.

### Problem or idea

How do we determine which is the correct column to keep? At what step should the extra data be chucked away?

### Solution or next step

Determine above then implement.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Also, the files are way, way bigger than they're supposed to be due to duplicated rows:

```
-rw-r--r-- 1 ubuntu ubuntu  97M Aug  2 18:41 GSM1361057-tbl-1.txt
```

**Comment by jaclyn-taroni** [comment]
A column that contains p-values should have values between zero and one. I think dropping them right before doing the conversion makes sense.

If this the first line in the file
```
ENSEMBL	10.0000	0.7931
```

I think what is happening is that the input data doesn't have a header, but when we read in the file, we assume that it does: 
https://github.com/AlexsLemonade/refinebio/blob/3939050215468cf517680119f2c521d127de6fc5/workers/data_refinery_workers/processors/gene_convert_illumina.R#L41

So whatever the first ID is, here `ILMN_1885639`, is set as the first column name and the column that contains these probe IDs ends up being dropped.

**Comment by Miserlou** [comment]
[GSM1361057-tbl-1.txt](https://github.com/AlexsLemonade/refinebio/files/2255166/GSM1361057-tbl-1.txt)

**Comment by Miserlou** [comment]
[GSM1089291-tbl-1.txt](https://github.com/AlexsLemonade/refinebio/files/2255178/GSM1089291-tbl-1.txt)

**Comment by jaclyn-taroni** [comment]
We noted this in person, but just for the sake of writing it down - [`GSM1361057`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1361057) is Affymetrix data, so that blow up may be a separate issue.

**Comment by jaclyn-taroni** [comment]
I believe we decided we should check for headers during our discussion yesterday.

**Comment by Miserlou** [comment]
This is taken care of for the simple case now. More complicated cases have other related issues.
