### ISSUE TITLE
Improve deploy times

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#490]
### Context

Currently our deploy times are atrocious, like over 3 hours. This is because we have the CircleCI box rebuild all the docker images before it actually starts touching any infrastructure. CircleCI takes so long to build the images because each time it is a new box so it cannot use caches for layers it has already built.

### Problem or idea

Figure out a way to rebuild docker images in a way such that we can reuse layers that have not changed since the images were last built.

### Solution or next step

I've looked into this issue some and come up with some potential solutions:
  * One option is to potentially use [CircleCI's artifacts features](https://circleci.com/docs/2.0/artifacts/) to save and reload the cache our selves
  * However that seems to basically be implementing a feature we'd have to pay for from circle: https://circleci.com/docs/2.0/docker-layer-caching/

However actually loading and using the layers might be somewhat slow since some of our images are large. However because this all happens within Circle's network maybe it'd actually go fairly fast.

The other ideas I have are a bit more hackish:
  * We could set up an EC2 instance to be our deploy machine. We could have CircleCI trigger something remotely and then have that box rebuild the images and run our deploy script. This would mean that box always has the cached layers so it'd be the fastest.
  * Even more hackish would be to do this from my Greenelab machine. It'd be basically the same idea, but would just  be cheaper and violate a bunch of best practices. We almost certainly shouldn't do this.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Can we move more R requirements into a different base image? Compiling R stuff is the bulk of deployment time.

**Comment by cgreene** [comment]
How much does it cost and can we just pay them?

**Comment by kurtwheeler** [comment]
> Can we move more R requirements into a different base image? Compiling R stuff is the bulk of deployment time.

We can but then we still have to pull the image onto circle, which ended up being pretty slow back when we had just the one giant image which was basically what we were doing and why we were doing it. This potentially could be a decent improvement anyway though.

**Comment by Miserlou** [comment]
Pulling source and compiling seems like it's slower than just downloading the compiled assets. :[

**Comment by kurtwheeler** [comment]
> How much does it cost and can we just pay them?

I made a request about this and they gave me a pricing sheet I'm pretty sure is meant to be confusing as far as actually calculating what our costs would be. Basically we have to use their performance plan and potentially pay extra for the docker layer caching.

Here is the pricing sheet they sent me: [pricing-infosheet (1).pdf](https://github.com/AlexsLemonade/refinebio/files/2263293/pricing-infosheet.1.pdf)

I just realized that it doesn't actually answer the question I asked them, which is how much that additional feature is. The sheet just says:
```
Add-Ons
$0.006 per 10 Credits
• Docker Layer Caching*
• 365 Day Data Retention
* May require additional credit usage or fees
```

I will reopen the ticket to see what the additional credit usage or fees would be.

**Comment by kurtwheeler** [comment]
Oh wait, it was hidden in the email. The additional fee is 15 dollars per month. If this is an option you'd like me to investigate further @cgreene, I can calculate how much build time we've used this month and estimate what we're looking at... It's frustrating that they've made this rather difficult to calculate, their pricing calculator doesn't support performance plans.
