### ISSUE TITLE
Determine Illumina experiments to add to zebrafish crunch

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#491]
### Context

We're going to run the zebrafish crunch for many reasons, but one of them is to test our provenance stuff. However there's no experiments which use illumina platforms included in that list.

### Problem or idea

We should add some illumina experiments to the zebrafish crunch so we can verify the provenance stuff is legit.

### Solution or next step

Find some experiment accession codes which use illumina.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
55 experiments from human, mouse, and rat:
```
GSE16835
GSE16990
GSE17946
GSE52185
GSE55468
GSE40878
GSE27276
GSE29521
GSE28302
GSE23898
GSE23932
GSE70053
GSE46932
GSE67057
GSE60102
GSE47063
GSE47592
GSE34198
GSE112676
GSE112681
GSE98895
GSE98897
GSE112307
GSE84426
GSE84433
GSE84437
GSE103357
GSE37013
GSE88744
GSE106321
GSE113469
GSE101448
GSE101462
GSE97594
GSE104237
GSE114059
GSE114061
GSE109030
GSE47541
GSE49631
GSE64838 
GSE112010
GSE33173
GSE84742
GSE72128
GSE67942
GSE64005
GSE38701
GSE60437
GSE53101
GSE56682
GSE19045 
GSE30793
GSE43213
GSE43214 
```
