### ISSUE TITLE
Sample names should match in gene expression matrix and metadata

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#500]
### Context

I am poking around at some data that has been processed #466. Specifically, I am working with `GSE12021`, which is Affymetrix SCAN processed data.

### Problem or idea

The sample identifiers do not match between the gene expression matrix (`GSE12021.tsv`) and the metadata (`metadata.tsv`), which will make mapping challenging for some users. Ideally the sample accession (`GSM302934`), which is present in the metadata files, would be used as the column name instead of the `.CEL` file name (`GSM302934_EB_56_B.CEL`). 

I'll note that this "file name as column header" behavior is the default behavior of Affymetrix SCAN. Something similar will also happening when processing Agilent two-color data with `SCAN.UPC` (file name + channel appended to the end of it). 

### Solution or next step

I will leave it to the backend team to come up with notes on implementation, but here are some things to keep in mind:

* I would like this "matching" to happen regardless of processor: Affymetrix SCAN, Illumina SCAN, Submitter-processed, Salmon + tximport. 
* Not all samples have accession codes. Specifically, ArrayExpress records sometimes do not have accession codes. In those cases, we obviously can not use accession codes as the sample ids in the gene expression matrix.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
How was this affected by #514 (if at all)?

**Comment by Miserlou** [comment]
This is handled for the majority of cases now. We use titles when we can and the filename with accession code if we can't. The only exception is two-channel samples, which we don't touch.
