### ISSUE TITLE
Add submitter processed protocol information to `/samples` endpoint

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#504]
### Context

Right now Submitter processed protocol information is hardcoded in the front-end.

### Problem or idea

Described by @jaclyn-taroni on https://github.com/AlexsLemonade/refinebio-frontend/issues/225 we need to show protocol information for each sample.

### Solution or next step

Add this information on the `/samples` endpoint.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by arielsvn** [comment]
Another option could be to add this to a different endpoint, the same that will return build information for each sample https://github.com/AlexsLemonade/refinebio-frontend/issues/99#issuecomment-411479678

That way we can keep `/samples` simpler.

**Comment by arielsvn** [comment]
Closed with https://github.com/AlexsLemonade/refinebio/pull/481

**Comment by dongbohu** [comment]
@cgreene, @jaclyn-taroni and @arielsvn: As you may know, depending the type of samples, the protocol information's formats are different. Here is an example of GEO sample:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM399040 
in which we will save the following fields as protocol information:
- Extraction protocol
- Label protocol
- Hybridization protocol
- Scan protocol
- Data processing

And here is an example of ArrayExpress protocol information (on experiment level):
https://www.ebi.ac.uk/arrayexpress/experiments/E-MEXP-31/protocols/

I wonder whether it makes sense to set the new `protocol_info` field in the database's `Sample` model as a `JSONField` type. It will give both back end and front end a lot more flexibility when scraping the information into the database or rendering it on web UI.

**Comment by cgreene** [comment]
In this case, I wonder if this is a subset #515? Resolving how that gets stored, and then how to present it, might solve both issues. It does mean that there will not be a single, clean submitter-supplied protocol. There already doesn't appear to be one though. It feels like a hack, but it could be possible to display the key/value for any field where the key contains `protocol` on the frontend.

Probably good to loop in @dvenprasad too.

**Comment by dongbohu** [comment]
@cgreene: Yes, it does make more sense to save sample's protocol information in `SampleAnnotation` model.

**Comment by dongbohu** [comment]
Implemented in this PR: https://github.com/AlexsLemonade/refinebio/pull/587
