### ISSUE TITLE
When aggregating by experiment, deliver sample metadata files per experiment

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#506]
### Context

Looking into some jackiecrunch data (see #466), specifically [`GSE12021`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE12021) and [`GSE56409`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE56409), where I have aggregated by experiment. 

### Problem or idea

`metadata.tsv` contains metadata for both `GSE12021` and `GSE56409`. If a user has chosen to aggregate by _experiment_, there's a good chance they have plans to either analyze each experiment separately OR they have the knowledge to combine the experiments themselves in a custom manner (and are probably more likely to be comfortable working with `metadata.json`). Thus, I think it might be more consistent with users workflows to deliver metadata TSV files for each experiment. 

I'll also note that this is consistent with my understanding of this whiteboard photo: https://github.com/AlexsLemonade/refinebio/issues/221#issuecomment-386344109

Here are the two metadata files for reference: [Archive.zip](https://github.com/AlexsLemonade/refinebio/files/2271845/Archive.zip)

### Solution or next step

To start, tagging @dvenprasad to weigh in.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by dvenprasad** [comment]
Based on the download summary when users aggregate by experiment, they will expect 1 metadata.tsv file per experiment.

**Comment by jaclyn-taroni** [comment]
Ah, that screenshot suggests it should be 1 metadata.json file per experiment as well then?

**Comment by dvenprasad** [comment]
Yes. That's also what's on the white board image comment.

**Comment by jaclyn-taroni** [comment]
And that file would contain _experiment metadata_ as well, based on #221

**Comment by jaclyn-taroni** [comment]
I'm going to change the title.

**Comment by jaclyn-taroni** [comment]
This is crossed off on the whiteboard in the office so I assume it was closed by #526
