### ISSUE TITLE
Notify users when their download fails

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#516]
### Context

If a user builds a dataset, clicks download, enters their email, and then the smash job fails they will never know.

### Problem or idea

We should still send an email at the end of smash jobs even if they fail, it should just tell the user that.

### Solution or next step

Send an email when smash jobs fail.

Bonus points if you can do it in a way that triggers the download page updating. (@dvenprasad do we have a page we can display in this case?)

Bonus bonus points if the email contains debugging information the user can dump into an issue.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
I'm going to assign this to :tamborine_tesla: because I think we need it before public beta

**Comment by dvenprasad** [comment]
I can whip up a state for a failed job.

Also, would it possible for them trigger re-trying the smash job?

**Comment by kurtwheeler** [comment]
> Also, would it possible for them trigger re-trying the smash job?

This is functionality we could build in the future. I'm not sure we would want to though because I don't know if smash jobs fail intermittently, so we would probably just be giving them false hope.

@Miserlou would be able to speak to that more definitively though.

**Comment by cgreene** [comment]
I think _we_ probably want to get notified if a smash job fails though. I don't think we have an expectation that a smash job would fail, so if it does then we should probably know about it in a loud way.

**Comment by kurtwheeler** [comment]
I do think this should happen already because it should send the error into sentry. I guess there's a question of do we want to let the user reach out to us in some way so they can keep track of our progress. If not then the failure email should probably include a blurb about how we've already been notified and will look into it.

**Comment by cgreene** [comment]
It might be good to give them an ID they can report to us if they want us to take a closer look. I worry that not all sentry errors are equivalent & we don't want to miss ones that fail at the delivery phase.

**Comment by Miserlou** [comment]
We do this.
