### ISSUE TITLE
Starting a download requires the front-end to send all the dataset's `data`

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#523]
### Context

When starting a download we have to make a `PUT` request to `/dataset/{datasetId}` with the parameters `start: true` and `token_id`.

### Problem or idea

This action also requires the front-end to send the data associated to the dataset, and if this isn't sent it returns an error:

```
KeyError at /dataset/93693157-f524-4615-9788-47894c8ad212/
'data'

Request Method: PUT
Request URL: http://localhost:8000/dataset/93693157-f524-4615-9788-47894c8ad212/
Django Version: 2.0.2
Python Executable: /usr/local/bin/python3.6
```

If we keep the data in the download in sync with the backend it doesn't make much sense to have to send it over again when starting the download.

### Solution or next step

Remove the requirement for `data`. And use what's in the database when a request to start a download is received.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
I think this is actually the expected behavior for an `HTTP PUT`.

**Comment by arielsvn** [comment]
Closing this. The overhead of sending the entire dataset shouldn't be significative.
