### ISSUE TITLE
Delivery and display of all sample annotations for initial release

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#532]
### Context

Discussion started here: #515. For the initial release, we do not yet have enough information to determine if displaying "selected" annotations will be possible.

### Problem or idea

For the moment, we'd like to make the following changes:

* Deliver _all_ sample annotations in tabular format (TSV)
* Make sure that a new `Additional Metadata` column will be shown in the sample table on the frontend. The value in the cell would be a link and clicking that link will launch a modal that shows all annotation data in JSON format. I will link to the associated front end ticket once it is filed.

### Solution or next step

For the first part regarding the TSV, @cgreene had some thoughts over on #515

> It seems like [nested values] could be [exported] as long as there was a determination of what character we would use to denote a hierarchy. In rare cases, this could conflict with characters used in the sample annotations, but that seems far better than making these data very difficult to access (i.e., leaving them as JSON only which - though I prefer it - most of our users will find inscrutable and unusable).

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by dongbohu** [comment]
Closed by: https://github.com/AlexsLemonade/refinebio-frontend/pull/261

**Comment by jaclyn-taroni** [comment]
The TSV delivery part of this has not yet been addressed.

**Comment by dongbohu** [comment]
Backend implemented in PR #629.
