### ISSUE TITLE
Release species compendia via research data repository

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#541]
### Context

We're planning to release species compendia 🎉 (related: #449, #508)

### Problem or idea

We'll want to periodically release these compendia via a research data repository and make sure we use a repository that supports versioning like [figshare](https://figshare.com) or [Zenodo](https://zenodo.org) (see: https://github.com/AlexsLemonade/refinebio-docs/pull/9#discussion_r210929699).

### Solution or next step

I can take a look at the limits, other pros and cons for figshare and Zenodo once Zenodo is back up.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
Is zenodo still dead? I went there just now and it appears to live again!

**Comment by jaclyn-taroni** [comment]
Aha! Looks like I needed to empty my caches.

**Comment by jaclyn-taroni** [comment]
Subsumed by #981
