### ISSUE TITLE
Update template for email sent after a data set is processed

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#543]
### Context

When a new download is processed we send an email to users. @dvenprasad created a design for it in https://github.com/AlexsLemonade/refinebio/issues/539

### Problem or idea

We should send emails with that template instead, I pasted the html code she created here https://gist.github.com/arielsvn/cb128188579d78b8b8de7faf69d1799e

### Solution or next step

We'll probably have to update the html https://github.com/AlexsLemonade/refinebio/blob/e1e5b8e0269ef58988468257418c05ec50f0daaf/workers/data_refinery_workers/processors/smasher.py#L359-L361

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
Updating to note that there is a PR: https://github.com/AlexsLemonade/refinebio/pull/546
