### ISSUE TITLE
Use collaborative code review as opportunity to revisit event logging levels

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#553]
### Context

Filing this based on discussions during demo day last week.

### Problem or idea

My main takeaway from Friday was that _expected errors_ should be set as `info` as to maximize the usefulness of Sentry, but there may be other things that should be noted here.

### Solution or next step

I've assigned this to @kurtwheeler so that he may fill in details as appropriate, but @dongbohu @kurtwheeler and @Miserlou will keep this in mind during collaborative code review.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [ ] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Ends up being a subissue of https://github.com/AlexsLemonade/refinebio/issues/553
