### ISSUE TITLE
We only store a single accession code for an experiment which can live in multiple databases

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#559]
### Context

This means that if a user knows the GEO accession of an experiment they would like to download, but we got it from SRA, we will tell them we don't have it.

### Problem or idea

We need a way to convert from the accession they are looking for to the accession that we stored.

### Solution or next step

We're not sure what the right way to do this is yet...

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
* Would we want to be able to display alternate accessions? cc @dvenprasad 
* Add as search keywords? aliases?

**Comment by dvenprasad** [comment]
@jaclyn-taroni and I met to discuss this.

- When someone searches with a GEO accession but we've picked it up from SRA, it should show up in the search results. Also applicable to similar cases involving GEO and ArrayExpress. 

- We will not display alternate accession codes on the UI since a portion of our user base will be confused by it. 

- On the Experiment page, we should add a field called "Source" and show the link to the experiment we surveyed the data from.

**Comment by kurtwheeler** [comment]
> When someone searches with a GEO accession but we've picked it up from SRA, it should show up in the search results. Also applicable to similar cases involving GEO and ArrayExpress.

> We will not display alternate accession codes on the UI since a portion of our user base will be confused by it.

These two seem like they could be confusing in concert.  If I search for `E-GEOD-XXX` but we have the accession as `GSMXXX` we want to display it as a search result, but not show the `E-GEOD-XXX` accession? If the user doesn't know that `E-GEOD-XXX == GSMXXX` then how would they know we are actually displaying the experiment they searched for? 

If I search for X and only one result comes up which is Y, I'm probably more likely to assume that its a bug with the search algorithm rather than I am to assume that Y is actually X.

**Comment by jaclyn-taroni** [comment]
The subset of users who know what the accession codes are and are therefore likely to search by accession code will probably be able to "grok" `GSEXXX` == `E-GEOD-XXX`. Many users think the `GSEXXX` are refine.bio internal accessions so added _more_ unfamiliar accession numbers could be confusing.

**Comment by kurtwheeler** [comment]
Ok, I'm comfortable with this assumption about our users, however we may want to verify this after a while using hotjar @devenprasad

**Comment by dvenprasad** [comment]
It is less confusing of the options. It's a trade off between a portion of users maybe being confused when they search by accession vs. a portion of users being confused by searching by all other things.

**Comment by kurtwheeler** [comment]
I can see that, although we also have the option of including a little link that says something like `Why did this experiment match my search results?` which links to docs explaining the relationship between accession codes. However I would only think that'd be worth doing if users start opening issues about our search not working right.

**Comment by jaclyn-taroni** [comment]
I'll just note (to potential future me) that any answer to `Why did this experiment match my search results?` would need to be more comprehensive than accession codes.

**Comment by kurtwheeler** [comment]
Only if we showed it all the time. We could choose to only display that under certain conditions and then tailor the link to condition it was shown, accession swaperoos being the first example.

**Comment by jaclyn-taroni** [comment]
I'm imagining it would be visible all the time in the docs, but perhaps not.
