### ISSUE TITLE
Unable to read Affy header error

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#568]
### Context

ZF crunch

### Problem or idea

We have a number of issues where we've failed to read an Affymetrix CEL file header, I think while [attempting to determine the relevant Brainarray package](https://github.com/AlexsLemonade/refinebio/blob/a744d7cc177369419238a161c2c43bce79298636/workers/data_refinery_workers/processors/array_express.py#L69): 

https://sentry.io/greenelab/staging-refinebio/?query=is%3Aunresolved+unable+to+read+affy+header

In the majority of cases, these are failing on files that are not CEL files which is expected. This includes: 

* [CHP files](http://dept.stat.lsa.umich.edu/~kshedden/Courses/Stat545/Notes/AffxFileFormats/chp.html) which contain gene-level _processed_ values and we do not want. An Affymetrix scanner will generate two files CHP and CEL -- it looks like a number of the experiments I spot checked have both of these files for each sample.
* [EXP files](http://wiki.c2b2.columbia.edu/workbench/index.php/File_Formats#Affymetrix_File_Matrix_Format_.28geWorkbench_.22.exp.22_format.29) which I believe are similar (plus detection p-values) and we also don't want. Similar to above, samples usually have both an EXP and a CEL file.

I'll also note that these look like they're exclusively coming from GEO (e.g., have `GSEXXXXX` in their paths) so perhaps ArrayExpress does not include these processed files in their raw files.

I can find two examples in there that seem to just be missing files.

### Solution or next step

Only attempt to process files with `.cel` or `.CEL` extensions. 

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
I think we should just avoid downloading anything that isn't CEL or TXT or TSV in the first place.

**Comment by jaclyn-taroni** [comment]
Can that be determined prior to downloading and unpacking? If so, agreed.

**Comment by kurtwheeler** [comment]
We haven't seen this issue in a long time. If it ever comes up again we can reopen or create a new one. I suspect it won't because of various improvements made to affy over the years.
