### ISSUE TITLE
Processor job failed without having failure_reason set. FIX ME!!!!!!!!

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#570]
It looks like we made a note to our future selves to fix something. We now encountered it. Last modified by @kurtwheeler

The line appears to be: https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/utils.py#L140

https://sentry.io/greenelab/staging-refinebio/issues/665389618/

```
Processor job failed without having failure_reason set. FIX ME!!!!!!!!
```

**Comment by kurtwheeler** [comment]
Just to note, this line itself isn't the problem, but rather a way of notifying us that there was a problem. I would like for that line to stay there forever, but eventually never get run because we always set the failure_reason when we encounter a failure.

**Comment by cgreene** [comment]
👍  I filed the ticket because when I encounter FIX ME with multiple exclamation points in a log I always file a ticket. 🤣

**Comment by kurtwheeler** [comment]
Makes sense haha, that's why it's there! I just wanted to make sure that when this gets fixed it gets fixed by setting the failure reason and not by changing the logging.

**Comment by cgreene** [comment]
Things have changed a lot since this time. I'm going to close this since in all likelihood we'll encounter it again if it's still an issue.
