### ISSUE TITLE
Use Pipeline model to populate samples.pipelines

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#574]
### Context

The pipelines property on the Sample model is using the obsolete ComputationalResult.pipeline field. 

### Problem or idea

This should be updated to use the new Pipeline model.

### Solution or next step

- [ ] Switch the Sample.pipelines property to use Pipeline
- [ ] Remove all places where we set result.pipeline
- [ ] Remove the pipeline property from the ComputationalResult model.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
@Miserlou : check to make sure business logic is not using obsolete stuff, if not - just take this out
