### ISSUE TITLE
Logging/monitoring for Nomad servers

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#58]

**Comment by cgreene** [comment]
Need some more clarity on this. Is this investigating solutions? Building a solution?

**Comment by kurtwheeler** [comment]
This issue has been supplanted by https://github.com/AlexsLemonade/refinebio/issues/146 and is being addressed by https://github.com/AlexsLemonade/refinebio/pull/152 and https://github.com/AlexsLemonade/refinebio/pull/137
