### ISSUE TITLE
Not enough overlapping ids detected! sample has enough overlapping ids

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#581]
I obtained the sample table file for [`GSM801253`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM801253) and the identifier refinery mapping for `zebrafish`. I calculated the overlap for all the  identifiers included in the mapping and got `0.7277966` for `PROBEID` which is greater than the `0.5` threshold

https://sentry.io/greenelab/staging-refinebio/issues/667298149/

```
Status code 1 from gene_convert.R: b"\nAttaching package: 'dplyr'\n\nThe following objects are masked from 'package:data.table':\n\n    between, first, last\n\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n\n\nAttaching package: 'rlang'\n\nThe following object is masked from 'package:data.table':\n\n    :=\n\nLoading...\nBioconductor version 3.6 (BiocInstaller 1.28.0), ?biocLite for help\nA new version of Bioconductor is available after installing the most recent\n  version of R; see http://bioconductor.org/install\nReading data file...\nReading master index...\nError: Not enough overlapping ids detected!\nExecution halted\n"
```

**Comment by Miserlou** [comment]
I wasn't able to reproduce since the the raw is available, we convert from CEL to PCL rather than performing the identifier detection. We can reopen if we find a repeatable example case.
