### ISSUE TITLE
Make QN targets publicly available

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#586]
### Context

Our QN targets will be uploaded to the same S3 buckets as the rest of our results.

### Problem or idea

That bucket is not publicly accessible. If someone wanted to view all the QN targets they could not.

### Solution or next step

- [x] Determine whether or not this is necessary
- [ ] Upload QN targets to a new bucket just for them which is publicly available.
- [ ] Add API support.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
@jaclyn-taroni can you weigh in on whether this will eventually be necessary or not?

**Comment by jaclyn-taroni** [comment]
If I want to make my own data comparable to refine.bio data, I need these. Similar situation/requirements to the transcriptome indices for Salmon.

**Comment by Miserlou** [comment]
An alternate and possibly easier approach would be to include them in the results archive.

**Comment by jaclyn-taroni** [comment]
We want to do this for organisms with at least 100 samples (https://github.com/AlexsLemonade/refinebio/issues/488). This is the list of the most popular Affymetrix microarray platform from #488: https://github.com/AlexsLemonade/refinebio/files/2258673/affymetrix_platforms_for_QN_reference.txt

**Comment by jaclyn-taroni** [comment]
Per our discussion in team meeting -- an API endpoint has been added, but I'm not sure about:

>  Upload QN targets to a new bucket just for them which is publicly available.

And I didn't see any species/organism information at `qn_targets`, which is important for use, but perhaps I'm not looking in the right spot. cc: @Miserlou 

https://github.com/AlexsLemonade/refinebio-docs/issues/73 relies on this.

**Comment by Miserlou** [comment]
It's attached to the annotation object
