### ISSUE TITLE
Obtain sequencing data from NCBI SRA

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#598]
### Context

@Miserlou's done some tests. Overall throughput from NCBI is looking good.

### Problem or idea

Instead of obtaining RNA-seq data from ENA, we'd obtain it from NCBI SRA. That requires a number of changes and considerations:
* We need to get the raw data files from NCBI. They come in `.sra` format.
* We'll need to convert from `.sra` files to FASTQ files, which are the input to `salmon quant` and `fastqc`. This requires us to use [SRA toolkit](https://github.com/ncbi/sra-tools). 
* One of the concerns we had with going through SRA is that sometimes `fastq-dump` output files that were interleaved paired end reads and Salmon quant wants paired reads in different files (#67). I'll note that _my read_ of the default behavior of the newer tool [`fasterq-dump`](https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump) won't give us interleaved reads, but unfortunately I don't have any examples for testing/to be absolutely certain. So we've chatted about a strategy based on the metadata for the 1% which I will detail below.

### Solution or next step

- [ ] Figure out how to format the URLs (I will let @Miserlou fill in details here)
- [ ] Install SRA toolkit on the [Salmon processor Dockerfile](https://github.com/AlexsLemonade/refinebio/blob/dev/workers/dockerfiles/Dockerfile.salmon). I was able to successfully install on a Docker image like so ([ref](https://github.com/inutano/docker-sra-toolkit)):
```
ENV SRA_VERSION 2.9.1
RUN wget "http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/${SRA_VERSION}/sratoolkit.${SRA_VERSION}-ubuntu64.tar.gz" && \
    tar zxfv sratoolkit.${SRA_VERSION}-ubuntu64.tar.gz && \
    cp -r sratoolkit.${SRA_VERSION}-ubuntu64/bin/* /usr/bin
```
- [ ] Add sra-toolkit version information to the [Salmon processor YAML](https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/salmon_quant.yml) probably as part of `cmd_line` (`fasterq-dump --version`)
- [ ] Use `fasterq-dump` on `.sra` files that we obtain with Aspera as the first step in the Salmon processing pipeline. 
  - I think we just want the default behavior so `fasterq-dump <PATH_TO_SRA_FILE>`. We'll get any unmated pairs in a `_3.fastq` file.
  - Note that the output of this will not be compressed, which is fine wrt passing them to `salmon quant` but there may need to be some tweaks, for example, in the [determining read length step](https://github.com/AlexsLemonade/refinebio/blob/3e69e5e98d509489305b91dcff4de864ae337468/workers/data_refinery_workers/processors/salmon.py#L100)? 
- [ ] If the library layout is reported to be paired in the metadata and we only have one file after `fasterq-dump`, throw an error. If we do this for the 1% crunch, we will get a sense of how often if ever this happens.

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Some quick notes:

* `ascp` command/URLs are in the format: `ascp -T -i /home/ubuntu/.aspera/connect/etc/asperaweb_id_dsa.openssh anonftp@ftp.ncbi.nlm.nih.gov:/sra/sra-instant/reads/ByRun/sra/ERR/ERR166/ERR1662590/ERR1662590.sra .` - I think that endpoint is load balanced but we could try with the other SRA-specific DNSes they provide just to see what happens.

* Can we leverage this to make ENA work better?

* We should build this is an additive rather than destructive way, it's possible we could improve our speed by multiplexing across different endpoints. 

This shouldn't be more than a ~two-three days of office work or one day of uninterrupted work.

10GB/s to the moon!

**Comment by jaclyn-taroni** [comment]
Noting a conversation we had in person: The FASTQ files will technically be files that have been acted on by a processor, but we don't want to keep them around as they are in essence raw data and will be even larger than expected because they are not compressed.

**Comment by Miserlou** [comment]
That's not a problem, we already do that in a few other places where we
have to sanitize/normalize files before they're fed into the R scripts.
