### ISSUE TITLE
Need to handle case where there is no brainarray package for a given organism.

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#64]
When this is the case, we should just not pass one into SCAN.UPC.

Tagging @jaclyn-taroni, as she realized this was an issue.

**Comment by cgreene** [comment]
In this case the steps are:
* Use manufacturer supplied files.
* Map the output to ensembl gene identifiers.

**Comment by jaclyn-taroni** [comment]
While #85 is being addressed, I think it makes sense to make at least some progress on this as well. For the time being, I think a bit of logic should do the trick -- if ENSG BrainArray package exists, supply it as `probeSummaryPackage` argument to SCAN, else don't supply this argument

**Comment by kurtwheeler** [comment]
@jaclyn-taroni could you provide an example of such an organism?

**Comment by cgreene** [comment]
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL84
