### ISSUE TITLE
New QN test at smash time

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#657]
### Context

We have a test during smash time that checks if data is from the same distribution (`ks.test`). RNA-seq data fails the KS test during smash.

### Problem or idea

When I conceptualized our current test methodology, I did not take into account all the zeroes in RNA-seq data. So it is possible for things to be successfully quantile normalized _and_ for this test to fail. If we want to leave a test here, we'll need a new approach. @cgreene suggested we take a look at the genes with the highest expression only. 

### Solution or next step

Here's where this test starts

https://github.com/AlexsLemonade/refinebio/blob/96272b936b679aeeb548f5541a74af9d75ab59c1/workers/data_refinery_workers/processors/smasher.py#L510

We need to find the _median_ value of `test_a` and `test_b` and include only the values greater than the median values in the test. In R, broken out by step, I would do that like so:

```
median_a <- median(test_a)
top_index_a <- which(test_a > median_a)
test_a <- test_a[top_index_a]
median_b <- median(test_b)
top_index_b <- which(test_b > median_b)
test_b <- test_b[top_index_b]
ks.test(test_a, test_b)
```
I am not confident porting this over to rpy2 at this point in the game (we can probably use numpy in the median calculation part), so perhaps @Miserlou and myself can pair on this and implement it quickly.

@cgreene please chime in if this differs from what you were thinking!

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
This plan sounds good to me. If, after an inner join, >50% of genes still have zero values in one of the data types that seems like something that we would really not want to return.
