### ISSUE TITLE
Create a template + copy for error emails

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#674]
### Context

@Miserlou and I discussed prettying up the error emails.

### Problem or idea
Currently, the emails look like this:

![screen shot 2018-09-28 at 3 00 49 pm](https://user-images.githubusercontent.com/15315514/46228196-52830e80-c32f-11e8-937c-da500e6ad1a7.png)

Instead, give a generic error message and and provide the specific error message so that we can look at it if they get in touch with us about the error. 

### Solution or next step
I will create a template for it.

**Comment by arielsvn** [comment]
The template is at https://gist.github.com/arielsvn/cb128188579d78b8b8de7faf69d1799e#file-email-error-min-html

**Comment by arielsvn** [comment]
Closed by https://github.com/AlexsLemonade/refinebio/pull/692
