### ISSUE TITLE
Dataset link on dataset delivery email should link to the dataset page on the website

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#676]
### Context

Noticed this walking through refine.bio

### Problem or idea
The dataset link on the dataset delivery email currently links to the s3 bucket. It should link to the dataset page.

<img width="1030" alt="screen shot 2018-10-01 at 10 44 58 am" src="https://user-images.githubusercontent.com/15315514/46295863-14702f80-c567-11e8-9dab-7fc4b42469af.png">

### Solution or next step

Tagging @Miserlou to update the link.

**Comment by Miserlou** [comment]
Why is this better? We also say `"Enter your email and we will send you the download link when your files are ready."`, which would seem like a lie if we make them go back to the website for no reason.

**Comment by dvenprasad** [comment]
'Download Now' button will still link them to the s3 bucket and let them download it directly. 
I'm saying that the`dataset` linked in  'Your dataset is ready for download' should link to this page, in case the users would like to see a summary of their dataset. 

![screen_shot_2018-10-01_at_11_40_37_am](https://user-images.githubusercontent.com/15315514/46299309-13430080-c56f-11e8-9fa7-8332409b2191.png)
