### ISSUE TITLE
Add error state to to the dataset

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#691]
### Context

When the smashing process fails we'll send an email with a link to the dataset page.

### Problem or idea

If the smashing process fails, the corresponding dataset stays as if it's being processed (`is_processing=true`). We need to mark the dataset as not being processed, and also add the error message.

### Solution or next step

Add `has_error` field to the dataset, and maybe add the error message as well.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Dataset already has this as `success` and `failure_reason` fields

**Comment by Miserlou** [comment]
Added them to serializer here: https://github.com/AlexsLemonade/refinebio/pull/690/commits/0a4f00f441de1276c95bfb44882ea8462b422d22
