### ISSUE TITLE
Improve developer experience: running locally

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#699]
### Context

The idea of "improving developer experience" has been coming up around the office consistently. We'll want to make sure folks external to the group can run things locally. 

### Problem or idea

Two ways (so far) of approaching this have come up:
1) Have team members pair (e.g., backend dev + data science team, cover Mac and Ubuntu) and set things up locally.  Take detailed notes about any sticking points -> improve documentation where needed.
2) Create a couple configurations of VMs that we can spin up to simulate fresh Mac and Ubuntu boxes. Then we can use the script created by https://github.com/AlexsLemonade/refinebio/issues/714 to install everything and run end_to_end tests to make sure that our instructions/script work smoothly.

### Solution or next step

Figure out which approach to take with this and improve things.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [ ] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Probably related: https://github.com/AlexsLemonade/refinebio/issues/714

**Comment by jaclyn-taroni** [comment]
I was able to set this up locally last sprint and there were documentation changes as part of #996 that cleared up some issues @cansav09 ran up while setting this up on her MBP. 

Also to document a conversation we had in person:
* It is not particularly helpful to the backend team for science team members to have this running locally when tracking down errors that arise in production. It is more helpful for us to document our "suspicions" based on our experience on any ticket in question.
* If science team members need a particular experiment or set of samples processed, they should tell the backend team to run it in production rather than run it locally.

**Comment by cgreene** [comment]
> If science team members need a particular experiment or set of samples processed, they should tell the backend team to run it in production rather than run it locally.

That makes me very nervous. Does this mean that the only way for Jackie or Candace to test a processor is to debug it _through_ Kurt or Rich? Or can you run a processor locally - just not via the entire refine.bio infrastructure?

Also, production? Seems dangerous.
