### ISSUE TITLE
Platform badge on search page always displays the mixed platform badge

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#701]
### Context

 Noticed this walking through refine.bio

### Problem or idea
On the search page the platform badge is always the mixed platform badge.
![screen shot 2018-10-05 at 11 33 39 am](https://user-images.githubusercontent.com/15315514/46544825-9a0b1c80-c892-11e8-8cbc-67c232d1f713.png)

But on the experiment page it displays the correct platform badge:
![screen shot 2018-10-05 at 11 34 54 am](https://user-images.githubusercontent.com/15315514/46544861-b3ac6400-c892-11e8-98ed-0f6fb56cf341.png)

Could be related to #589 

### Solution or next step
Tagging @arielsvn and @Miserlou for input

**Comment by Miserlou** [comment]
I thiiink there is already a fix for this that hasn't been deployed yet?
