### ISSUE TITLE
How will people cite refine.bio? 

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio#703]
### Context

@Miserlou reminded me about citation.

### Problem or idea

1) How can people cite refine.bio? What is the format? 
2) Can we provide citations for experiments which have publication on refine.bio? Maybe something they can import into their preferred citation manage. (This was briefly discussed on slack a while back) 
3) Can we include a citations.txt in their download which citations for the experiment they downloaded + refine.bio citation?

### Solution or next step

Tagging @cgreene, @jaclyn-taroni, @arielsvn and @Miserlou for input.

**Comment by jaclyn-taroni** [comment]
@cgreene how have you typically handled citations for web servers prior to any kind of preprint?

**Comment by cgreene** [comment]
We haven't in the past. We generally only put up citation language once the preprint was posted. Before then the page said something like "coming soon" or equivalent.

**Comment by jaclyn-taroni** [comment]
We need to add the citation information to the README(s) that comes as part of a dataset download.

**Comment by arielsvn** [comment]
Here's the readme that we add to the dataset https://github.com/AlexsLemonade/refinebio/blob/dev/workers/README_DATASET.md

**Comment by jaclyn-taroni** [comment]
@dvenprasad where on the frontend is the citation information going to go? I figured we could put something in the "friendly intro" section of the documentation: https://github.com/AlexsLemonade/refinebio-docs/blob/master/docs/index.md#contents  and also possibly in the FAQ of the primary docs.

**Comment by jaclyn-taroni** [comment]
Note to self: I will remove the "refine.bio is in beta" from `README_DATASET.md` at the same time I address this in that file.

**Comment by dvenprasad** [comment]
@jaclyn-taroni yep, those place sound good to me!

**Comment by jaclyn-taroni** [comment]
@dvenprasad is going to file a frontend ticket about putting the copy from https://github.com/AlexsLemonade/refinebio-docs/pull/111 and #1614. I'm tagging this with `future thoughts` because this ticket has a lot of things in it that we're not going to cover at the moment.
