### ISSUE TITLE
How do fasterq-dump'd results compare to results for fastq files obtained from ENA? 

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#706]
### Context

Related to #598 -- for technical reasons, we're now obtaining raw RNA-seq data from NCBI SRA rather than ENA. 

### Problem or idea

`fastq-dump` (`fasterq-dump` predecessor) does read filtering (see https://github.com/ncbi/sra-tools/issues/159#issuecomment-427269308) which filters out reads that are all Ns ([ref](https://edwards.sdsu.edu/research/fastq-dump/)).  We assumed that this, and other features of `fasterq-dump`, do not affect our results at the transcript quantification step (e.g., `salmon quant`). However, we didn't test this and we have some [scientific debt](http://varianceexplained.org/r/scientific-debt/).

### Solution or next step

1. Randomly select samples from SRA, ensuring that both paired-end and single-end are represented
2. Obtain the reads from ENA (fastq via ftp)
3. Obtain the reads from NCBI SRA using `fasterq-dump` from the SRA toolkit
4. Quantify transcripts with salmon quant from each NCBI-ENA "pair"
5. Check TPM, count correlations

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
I will get these organized and into a repo, but wanted to report back ahead of that. I took a look at the single-end experiment [`SRP036035`](https://www.ebi.ac.uk/ena/data/view/PRJNA236738) which has 6 samples. 

I downloaded the fastq.gz files via FTP from ENA and used `fasterq-dump <SAMPLE_ACCESSION> -e 10` to retrieve the fastq files from SRA. 

I built a Salmon index like so (50 bp reads)
```sh
salmon index \
  -t data/Homo_sapiens.GRCh38.cdna.all.fa.gz \
  -i transcriptome_index/hsapiens_short \
  --type quasi -k 23
```
So this is not our custom reference, but that's okay for this application.

I ran `salmon quant` and `tximport` with the same options as refine.bio and then compared the `lengthScaledTPM` for each sample between the two source repositories. If we take the average Spearman correlation for the samples we get: `0.9999968`.

This needs to be repeated for paired-end.

**Comment by jaclyn-taroni** [comment]
![correlation_plot](https://user-images.githubusercontent.com/19534205/46820471-44cc8080-cd54-11e8-82cf-1ec9588c0e52.png)

**Comment by cgreene** [comment]
My interpretation is that those are relatively high correlation values.

**Comment by jaclyn-taroni** [comment]
Repo here: https://github.com/jaclyn-taroni/sra-ena-compare
