### ISSUE TITLE
Improve dashboard/monitoring

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#707]
### Context

The dashboard is broken in a few obvious ways, but I also think the way the statistics are generated should be reviewed because I think some nuances of the data model aren't accounted for.

### Problem or idea

I think the following changes would be helpful:
- [x] Update the current statistics to be more accurate.
- ~~Include information from cloudwatch about nomad jobs~~
  -  ~~Add additional metrics in cloudwatch. I'd like to know what amounts of various jobs are in the queue over time in addition to the total number.~~
  - ~~Make the dashboard pull the stats from cloudwatch.~~
- [x] Update the layout of the dashboard so that the most important metrics will fit nicely on a TV screen. (So we can always have it up in the lab.)

### Solution or next step

There'll probably be a bit of discussion involved in hashing out exactly the right way to query the database for stats and which metrics are the most important to display on the TV.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
A lot of this is front-end work

**Comment by arielsvn** [comment]
Talked with @Miserlou about the dashboard (both backend/frontend):

- We should display average times for jobs. This is already being returned by the API, but we only show estimates for the total completion time

- Pick better colors

- The numbers of open/pending/completed jobs don't look right

- See if we can return statics for volume of data downloaded over time. It will be helpful for the landing page https://github.com/AlexsLemonade/refinebio-frontend/issues/64#issuecomment-431098557

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio-frontend/pull/411 adds average times to the dashboard and better colors.

**Comment by arielsvn** [comment]
#555 adds statics to the dashboard for the datasets. 

Nomad jobs stats are missing from there, I'm gonna wait until https://github.com/AlexsLemonade/refinebio/pull/1105 get's deployed to to see how those stats look on prod.

**Comment by Miserlou** [comment]
Mentioning here that the CW Metrics isn't a requirement any more since we have disabled queue-length autoscaling. The number of nodes and running jobs should suffice. The breakdown of "amounts of various jobs are in the queue over time in addition to the total number" is still relevant though, but I think this can be attained from the database and nomad server API so we don't need AWS.

**Comment by arielsvn** [comment]
Got some additional feedback on the dashboard from @kurtwheeler:

- [ ] Pie charts with Job by status should contain: successful, failed, pending and open
- [ ] Check last date in the line graphs
- [ ] Ensure dataset count contains only those dataset's with an email address
- [ ] Format byte values on the volume of data downloaded over time
- [ ] Add nomad job stats
- [ ] Sometimes numbers in pie charts are hard to read

**Comment by arielsvn** [comment]
closing this, will continue discussion on https://github.com/AlexsLemonade/refinebio-frontend/issues/623
