### ISSUE TITLE
Make jobs reduce retry count if they are sent a stop signal

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#708]
### Context

Our deploy process empties the Nomad queue so that we won't be running old code after we update the database model. This means that all of those jobs fail. The foreman detects this and marks those jobs as failed and requeues them.

### Problem or idea

The problem is that we only retry our jobs three times to account for temporary issues and this redeploy process counts against it. If we have a large queue that redeploy multiple times against then some jobs could hit their retry limit without ever really being started.

Additionally when spot instances are preempted the jobs will all have the same issue.

### Solution or next step

Make the jobs catch interrupt or stop signals or whatever Nomad sends when it stops jobs and whatever Amazon sends when it is preempting the instance. When they catch those signals, they should decrement the `num_retries` field of their job record in the database so it won't count against their retry limit.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
https://www.nomadproject.io/guides/operating-a-job/update-strategies/handling-signals.html + https://stackoverflow.com/a/1112350/1135467
