### ISSUE TITLE
tximport RDS object should be at the transcript level

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#722]
### Context

Looking into #508 & downloading files 

### Problem or idea

In #278, I made a mistake in asking @dongbohu to change the parameter below to `FALSE`.

https://github.com/AlexsLemonade/refinebio/blob/79d9d9032caaa7ffda6ad898862da16b82edcbab/workers/data_refinery_workers/processors/tximport.R#L49

This means that the `txi_out.RDS` file is at the gene-level rather than the desired transcript-level.

### Solution or next step

This parameter should set to `TRUE`

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Ops wise, the plan is to nuke all of the RDS objects we've created so far, fix this bug, and then keep everything going forward after that. If we need RDS for the things we've created so far, those can be re-run at a later date.

**Comment by jaclyn-taroni** [comment]
Okay, so, I revisited my notes on this and the way we currently have it is correct! :woman_facepalming:
