### ISSUE TITLE
Allow filtering samples on `/samples` endpoint

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#739]
### Context

https://github.com/AlexsLemonade/refinebio-frontend/issues/365

### Problem or idea

User will want to filter the samples displayed in the [SamplesTable](https://projects.invisionapp.com/d/main#/console/13557531/325148047/preview).

![image](https://user-images.githubusercontent.com/1882507/46971154-31d5eb00-d089-11e8-9265-ac33dc066a56.png)

### Solution or next step

Add a new parameter to `/samples` with the filter.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Can you describe the desired behavior and interface in a bit more detail?

**Comment by Miserlou** [comment]
Added here: https://github.com/AlexsLemonade/refinebio/pull/737 , just use the filter_by field

**Comment by arielsvn** [comment]
closed by #737
