### ISSUE TITLE
Build Numpy with LAPACK/ATLAS/BLAS

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#754]
We're building Numpy with the default configuration with `pip`, which leaves out some of the accelerated linear algebra features. This is going to make smashing, and particularly imputing, a lot slower than it needs to be.

### Solution or next step

Before install `numpy`:

```
sudo apt-get install liblapack-dev
sudo apt-get install gfortran
export LAPACK=/usr/lib/liblapack.so
export ATLAS=/usr/lib/libatlas.so
export BLAS=/usr/lib/libblas.so
pip install numpy scipy
```

Then confirm with:
```
python -c 'import numpy; numpy.show_config()'
```

**Comment by Miserlou** [comment]
Finally found an image that makes this work in a reasonable time: https://github.com/Miserlou/SampleGenerator/blob/master/Dockerfile

We might want to consider just using that as the base for impute jobs since getting all the requirements to play together is a huge pain the butt. It's certainly a lot faster, but eats a lot of memory.

**Comment by jaclyn-taroni** [comment]
Related to #508 and should probably be implemented in parallel
