### ISSUE TITLE
Enable SalmonTools

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#772]
### Context

If we were to process a large volume of RNA-seq data using on-demand instances, we should extract unmapped reads. These unmapped reads are of scientific interest.

### Problem or idea

In https://github.com/AlexsLemonade/refinebio/pull/673, SalmonTools was temporarily disabled because it was holding up processing (reported upstream: https://github.com/COMBINE-lab/SalmonTools/issues/2).

This was likely fixed here: https://github.com/COMBINE-lab/SalmonTools/pull/1

### Solution or next step

- [ ] Update Salmon Docker image to include the changes from https://github.com/COMBINE-lab/SalmonTools/pull/1
- [ ] Enable SalmonTools in the Salmon processor

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
This got reenabled at some point.
