### ISSUE TITLE
Docker daemon stopped on a Nomad node causing it to be unreachable

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#779]
### Context

I started running a staging test and the sole client instance wouldn't pick up any jobs despite having an `available` node status as far as the Nomad server was concerned. I looked into it and it looks like docker went down for some reason and this caused the client Nomad to be unable to communicate with the nomad cluster. When I restarted Nomad on the node the old logs got blown away, but there were a lot of messages like:
```
nomad RPC failed to server 10.0.124.208:4647: rpc error: EOF
```

### Problem or idea

I fixed this by restarting docker using the command we use to start it out of the client startup script. I then restarted the nomad client by once again reusing a command out of the client startup script.

### Solution or next step

I wasn't able to figure out what caused this so I don't know how to reproduce it or prevent it from happening again. However it could happen again so we should be aware and keep an eye out for it.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
We could probably use `systemd` to make sure that dockerd stays up.

**Comment by kurtwheeler** [comment]
We don't use Nomad any more! This is obsolete!
