### ISSUE TITLE
Implement extraction of unmapped read sequences (unmapped by Salmon)

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#83]
Use [salmontools](https://github.com/COMBINE-lab/SalmonTools) extract-unmapped command.

**Comment by kurtwheeler** [comment]
![salmon-gene-name](https://user-images.githubusercontent.com/4026833/35344221-908a92b8-00fa-11e8-9e42-5a9ec4d94c43.jpg)

**Comment by kurtwheeler** [comment]
Ok, so it turns out that the github repo I linked to above pretty much says what needs to be done. `salmontools extract-unmapped` will expect an `unmapped_reads.txt` file output from Salmon and the original FASTQ file that was passed into Salmon. Therefore it will make sense to do this within the same Processor as the current Salmon processor.

**Comment by kurtwheeler** [comment]
#84 answers the why of using STAR.

**Comment by jaclyn-taroni** [comment]
After chatting with @dongbohu, here's a more up to date sketch

![4_27_18 10_49 am office lens](https://user-images.githubusercontent.com/19534205/39369096-5d406628-4a09-11e8-8955-4ba044b391be.jpg)

**Comment by jaclyn-taroni** [comment]
Chatted with @dongbohu this afternoon - the output of `salmontools extract-unmapped` appears to be a FASTA file. We think it make sense to gzip it after the fact.

**Comment by dongbohu** [comment]
Implemented in #250.
