### ISSUE TITLE
API is Serializing Far Too Much Information

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#832]
### Context

Database queries are much faster, but now it's slow because of how much information we're serializing. 

### Problem or idea

I suggest we stop serializing complete sample lists in the Search and Experiment and just return accession codes so that the individual samples can be queried by the separate Samples API.

**Comment by arielsvn** [comment]
Merging https://github.com/AlexsLemonade/refinebio/pull/861 caused performance problems with the API

**Comment by cgreene** [comment]
Tests got commented out - should probably be uncommented (or at least looked at) as this is getting resolved:
https://github.com/AlexsLemonade/refinebio/pull/901/commits/319fe446244d451a096baa083248645152625df1#diff-e841c1c2392f296f719c2151aa8167aeR29
https://github.com/AlexsLemonade/refinebio/pull/901/commits/319fe446244d451a096baa083248645152625df1#diff-e841c1c2392f296f719c2151aa8167aeR64

**Comment by arielsvn** [comment]
Closing this to continue the discussion in https://github.com/AlexsLemonade/refinebio/issues/928. There're other recommendations there to improve performance.
