### ISSUE TITLE
Change brainarray to ensembl for gene expression processors

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#85]
Should mostly require rebuilding docker images which have different packages installed and then changing a few parameters.

@kurtwheeler and @jaclyn-taroni can provide further detail.

**Comment by jaclyn-taroni** [comment]
This will probably require a change to the reference PCL used for testing `SCAN.UPC` output (see #72)

**Comment by cgreene** [comment]
This line needs to look for ensg instead I think:
https://github.com/data-refinery/data-refinery/blob/dev/workers/r_dependencies.R#L43

We want to get these:
http://brainarray.mbni.med.umich.edu/Brainarray/Database/CustomCDF/22.0.0/ensg.asp

We are currently getting these:
http://brainarray.mbni.med.umich.edu/Brainarray/Database/CustomCDF/22.0.0/entrezg.asp

**Comment by cgreene** [comment]
This likely also needs to be changed to ensg:
https://github.com/data-refinery/data-refinery/blob/dev/workers/data_refinery_workers/processors/array_express.py#L77

And I agree with @jaclyn-taroni that we'll need a new reference PCL.

**Comment by Miserlou** [comment]
Where would one acquire such a new "reference PCL"?

**Comment by jaclyn-taroni** [comment]
I need to generate one, which means it will probably be Friday or Monday with the travel.

**Comment by Miserlou** [comment]
Ah, gotcha, thanks, no rush, I was just wondering if there was an online repo that I should be searching through.

**Comment by jaclyn-taroni** [comment]
New PCL: https://github.com/jaclyn-taroni/scan-test-pcl/blob/61f8dff63a24c053e4340245ea2cffde2be9f591/data/processed/GSM955780_DNA10204-303.pcl

I have not done a bunch of SCIENCE! with this file like the last test PCL. Ideally that would happen before we _really_ get going, but this should be enough to rewrite the test.

Here's the script for running SCAN itself: https://github.com/jaclyn-taroni/scan-test-pcl/blob/61f8dff63a24c053e4340245ea2cffde2be9f591/process_with_SCAN.R

Related: #141 and #71 -- note that I use `"hs"` as the organism code here: https://github.com/jaclyn-taroni/scan-test-pcl/blob/61f8dff63a24c053e4340245ea2cffde2be9f591/install_brainarray.R

**Comment by dongbohu** [comment]
Fixed in PR #180.
