### ISSUE TITLE
RNA-seq in organisms with strains

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#90]
For organisms with strains (e.g., _Pseudomonas aeruginosa_) – use transcriptome index of strain that is most prevalent in public data _and_ the transcriptome index of the strain reported by the submitter of the experiment with `salmon quant` (2 separate runs)

**Comment by jaclyn-taroni** [comment]
> strain that is most prevalent in public data 
would need to be determined

**Comment by kurtwheeler** [comment]
https://github.com/AlexsLemonade/refinebio/pull/2035 supports "blessed" strains. I think that is the route we're going for strains, so while we didn't implement something that uses two separate runs I think this can still be closed.
