### ISSUE TITLE
Run tximport before full RNA-SEQ experiment is ready

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#909]
### Context

We're having trouble making all the RNA-Seq data we have (mostly) processed available because we don't run tximport until the entire experiment is processed. So if an experiment has 100 samples and 99 of them have been processed but one failed, we can't let anyone get any of the samples because tximport hasn't been run.

### Problem or idea

We could find some kind of heuristic for a cutoff point and run tximport after that's been reached. If additional samples are processed after that, we could just rerun tximport and replace the previously generated data with the new stuff.

### Solution or next step

Is this something we want to do? If so what would our heuristic be? @jaclyn-taroni said in the demo day meeting that she would start thinking about these questions.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
I'm going to note some ideas about how we would figure this out.

Let's consider 50% of samples processed with Salmon as our starting point, which we can adjust once we've done an initial pass and have more information.

* Identify RNA-seq datasets of various scales/sample sizes that have been fully processed (e.g., through `tximport` step) in refine.bio. I expect that the 50% cut off is a bad idea for `n = 8` but may be perfectly fine in the 100s/1000s of experiments space.
* Obtain the `quant.sf` files for these experiments.
* Perform subsampling, going as low as 50% of the samples (to start), and process with `tximport`.
* Calculate the error between the `lengthScaledTPM` from the full dataset and the subsampled `lengthScaledTPM`

This should all be done with the `ccdl/dr_salmon` image.

**Comment by cgreene** [comment]
As a first step, could we get a count of how many samples are in each experiment and how many have been processed (for the ones that are either success / fail - not still in processing)? This way we know where to draw those thresholds for testing.

**Comment by Miserlou** [comment]
I originally suggested this idea as a fallback for [this change](https://github.com/AlexsLemonade/refinebio/commit/0e3298af14dc057493c65ba4308fbf65b6686f3b), which may render this particularly endeavor pointless anyway. We're expecting this to land today, so we should have the result by tomorrow. I wouldn't spend too much more time thinking about this issue until we see the result of that change.

**Comment by kurtwheeler** [comment]
Now that #1074 is merged in, we can do this whenever. However I think we should wait until we're back up and running, either with tmpfs or with reading .sra files directly before actually running this on the experiments which are ready for it since some of them failed due to what appeared to be a tximport-timeout.
