### ISSUE TITLE
Break tximport out into its own job type

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#911]
### Context

Last week @Miserlou had the idea that the tximport step of the salmon pipeline may be using a lot more more RAM than the rest of the job. It does make sense that we may be having trouble finishing salmon experiments because once we get to the very final step, tximport, we get OOM-killed.

This is something that could be checked by looking in our database. If this is really what is going on then we would expect to see a lot of salmon experiments where there is only one missing sample because that was the sample whose job ran tximport.

### Problem or idea

We can break tximport out of the salmon job type and into its own. Salmon jobs which would run tximport can then instead create a new processor job to do so and queue it up. This way we can tweak the RAM requirements for the tximport jobs separately. It also would give us more clarity as to how frequently the tximport step specifically is failing.

### Solution or next step

It may be worth trying to determine if we have a lot of salmon experiments that only are missing one sample from being processed before actually implementing this. However this is the easiest answer to get out of the database given that we can't use the `is_processed` flag on the samples table because it's not set to true until tximport is run for the whole experiment.

However regardless of whether or not tximport getting OOM-killed is really the main culprit of what's blocking experiments from finishing, we may want to implement this anyway because it could work nicely with #909 because I expect there are a number of experiments where some number of samples are unprocessable and tximport will never be triggered from within Salmon. Even once we implement #909, the remaining samples won't be able to be processed so they won't run tximport even once the threshold has been lowered. (For example, consider an experiment that is 75% processed but whose remaining samples we cannot process. Even if we set the cutoff at 60%, the remaining 25% of that experiment's samples won't finish the salmon steps of the salmon pipeline so they won't make it to the tximport part. We may need to make a one-off management command to queue tximport jobs for all the experiments which have processed all the samples which are processable.)

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
Oo - getting the info on what's missing here:
>  If this is really what is going on then we would expect to see a lot of salmon experiments where there is only one missing sample because that was the sample whose job ran tximport.

will also inform #909

**Comment by jaclyn-taroni** [comment]
Agreed!

**Comment by jaclyn-taroni** [comment]
Let's plan to at least include the "checking the database"/information gathering part of this for this sprint.

**Comment by cgreene** [comment]
Done via #1074
