### ISSUE TITLE
[Investigation] Pull stats on RNA-Seq experiments' completion rates.

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#914]
### Context

#909 and #911 would both benefit from having a better idea of how many RNA-Seq experiments are very close to being completed and how close they are. 

### Problem or idea

We should calculate these statistics for every experiment:
  * How many samples have had a successful processor job.
  * How many samples have a processor job `where success='f' and num_retries=2`.
  * How many samples there are total for the experiment
  * What the success percentage is.

### Solution or next step

Calculate these statistics and provide a summary and/or relevant takeaways.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
This is the code I used to do so:
```
from data_refinery_common.models import *

def get_stats_for_experiment(processed_sample_ids, experiment: Experiment):
    all_esls = ExperimentSampleAssociation.objects.filter(experiment_id=experiment.id)
    processed_esls = ExperimentSampleAssociation.objects.filter(
        sample_id__in=processed_sample_ids,
        experiment_id=experiment.id
    )
    total_samples = all_esls.count()
    processed_samples = processed_esls.count()
    if total_samples > 0:
        percent_processed = processed_samples / total_samples
    else:
        percent_processed = 0
    return {
        "experiment_accession": experiment.accession_code,
        "experiment_id": experiment.id,
        "total_samples": total_samples,
        "processed_samples": processed_samples,
        "unprocessed_samples": total_samples - processed_samples,
        "percent_processed": percent_processed
    }


sample_ids = SampleResultAssociation.objects.filter(result__in=multiqc_result_ids).values('sample_id')

multiqc_result_ids = ComputedFile.objects.filter(filename='multiqc_report.html').values('result_id')

experiment_stats = []
for experiment in Experiment.objects.all():
    experiment_stats.append(get_stats_for_experiment(sample_ids, experiment))

sorted_experiments = sorted(
    experiment_stats,
    key=lambda k: k['percent_processed'],
    reverse=True
)

import csv

with open('/tmp/experiment_progress.csv', 'w', newline='') as csvfile:
    fieldnames = [
        "experiment_id",
        "experiment_accession",
        "percent_processed",
        "total_samples",
        "processed_samples",
        "unprocessed_samples"
    ]
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for experiment in sorted_experiments:
        writer.writerow(experiment)
```

**Comment by kurtwheeler** [comment]
I was able to shepherd `ERP008771` along based on the results of this list. It was only two samples short and they finally completed after a few attempts on my part and now all 2232 samples from that experiment are available on the frontend: https://www.refine.bio/experiments/ERP008771

However it was a somewhat manual process. We're definitely going to wanna find a way to handle these cases in a more automated fashion. There were two main problems that I had to fix manually:
  * One of the samples had a successful downloader job without creating a processor job. I have opened #923 to address this and have already started implementing a bandaid.
  * The other sample had the `missing SRA file` problem. I fixed this by rerunning the downloader job for the sample. I think this pattern could be implemented in the error handling code for salmon jobs.

**Comment by Miserlou** [comment]
The missing SRA file problem (https://github.com/AlexsLemonade/refinebio/issues/930 and https://github.com/AlexsLemonade/refinebio/pull/932) should be solved going _forward_, but it will mean that many of the blocking samples in this list will likely need new downloaderjobs as well.

**Comment by kurtwheeler** [comment]
Yes. What I was thinking could generate those new downloader jobs is if we handle that error explicitly by recreating a downloader job for them, then retrying all those processor jobs that failed with that error, let them fail one last time in the same way, at which point the error handling code could re-create the downloader jobs.
