### ISSUE TITLE
[Notes] Make the API Faster

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#928]
Notes from today's investigation:

* We have so much data
* Full text search is bad
* Sample counts must be moved to an IntegerField on the Experiment object
* Platforms must be moved to a (StringField? ArrayField?) on the Experiment object
* experimentannotation_data search needs to be removed until a better solution can be found
* The four filter queries should be combined into a single one

**Comment by arielsvn** [comment]
ref https://github.com/AlexsLemonade/refinebio/issues/832

**Comment by cgreene** [comment]
We have had pretty good experience speeding up search w/ Elastic Search in the past. If that's the only part that's struggling, it's not horrible to do.

**Comment by arielsvn** [comment]
> Sample counts must be moved to an IntegerField on the Experiment object

Adding the sample counts might not do much, tested locally and it doesn't seem to be a significant difference between ordering by `total_samples_count` or `created_at`.

**Comment by arielsvn** [comment]
Another thing that might be good to move into the `Experiment` object is `samples__is_processed` and `samples__is_public`.

https://github.com/AlexsLemonade/refinebio/blob/86c22743a0db4e59fbe13eeff685621302ce02c7/common/data_refinery_common/models/models.py#L233-L237

Also removing that `.distinct()` call seems to reduce the response time slightly, not sure why do we need it there.

**Comment by Miserlou** [comment]
It's friggin fast now
