### ISSUE TITLE
Back Up Files Before Running fasterq-dump 

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#930]
### Context
`fasterq-dump` is garbage, and will corrupt local source files if it encounters a network error, which happens all the time, likely because we are constantly pummeling them with our magnificent high altitude orbital spam cannon.

A quick fix would be to extract the `.sra` file from a copy of the original file, so it can't be corrupted, which as forced a re-downloaded. I suspect this is a source of many of our blockages. 

### Problem or idea

Copy the file to a working directory and extract it from there.

**Comment by kurtwheeler** [comment]
This was closed by #935
