### ISSUE TITLE
More human, mouse, and rat microarray accessions

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio#931]
### Context

We need more microarray accessions. 

### Problem or idea

Since we prioritized human, mouse, and rat on #642 and therefore should have QN targets for those shortly, it makes sense to do all the supported microarray platforms for those organisms.

### Solution or next step

- [ ] Identify human, mouse, and rat supported microarray platforms from [our list](https://github.com/AlexsLemonade/refinebio/blob/c1df89fe178ea837b43a5b67112b553de9841fbf/config/supported_microarray_platforms.csv)
- For each supported platform, retrieve:
  - [ ] All GEO experiment accessions
  - [ ] All ArrayExpress experiment accessions

Ideally, this list will also tell us what platform each experiment is on, as that will give us more flexibility for sorting/prioritizing should the need arise.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
Quick question, for these:

> For each supported platform, retrieve:
> All GEO experiment accessions
> All ArrayExpress experiment accessions

there won't be overlap for experiments hosted on both sites will there?

**Comment by jaclyn-taroni** [comment]
There will be if GEO imports are included in the ArrayExpress list (e.g., `E-GEOD-`). The ArrayExpress lists should only contain ArrayExpress data.

**Comment by kurtwheeler** [comment]
> We for sure want the GEO and ArrayExpress as separate lists?

No preference, just don't want the same experiment showing up as multiple accessions.

> Also, did you want me to exclude accessions from the previous lists?

That would be ideal, yes.

**Comment by cansav09** [comment]
Okey dokey.

**Comment by kurtwheeler** [comment]
This is excellent @cansav09! Thanks a bunches! I've put this into our production queue!
