### ISSUE TITLE
SuperSeries Metadata?

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#94]
Is there a way to programmatically discover if something is a superseries?

Regular series:
* https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE4840
* https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE4841
* https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE4843

SuperSeries (containing those regular series):
* https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE4845

**Comment by jaclyn-taroni** [comment]
Here's another example: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE26106

This one includes 3 series on different platforms: [Agilent](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE25935), [Illumina expression array](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE28893), [Illumina SNP array](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE26105)

**Comment by arielsvn** [comment]
Maybe using this metadata property?

![image](https://user-images.githubusercontent.com/1882507/62327989-ee196a00-b47f-11e9-9f37-c2218f337dc4.png)

**Comment by arielsvn** [comment]
Here are the queries, seems that we have `2799` super series in the db.

```
data_refinery=> select accession_code, experiment_annotations.data->>'relation' from experiments inner join experiment_annotations on experiments.id = experiment_annotations.experiment_id where experiment_annotations.data->>'relation' like '%SuperSeries%' limit 3;
 accession_code |                                                                        ?column?                                                                         
----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------
 GSE31217       | ["SuperSeries of: GSE31185", "SuperSeries of: GSE31186", "BioProject: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA145961"]
 GSE23203       | ["SuperSeries of: GSE26949", "SuperSeries of: GSE26950", "SuperSeries of: GSE26951", "BioProject: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA131527"]
 GSE37165       | ["SuperSeries of: GSE37163", "SuperSeries of: GSE37164", "BioProject: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA158599"]
(3 rows)

data_refinery=> select count(*) from experiments inner join experiment_annotations on experiments.id = experiment_annotations.experiment_id where experiment_annotations.data->>'relation' like '%SuperSeries%' limit 1;
 count 
-------
  2799
(1 row)
```
