### ISSUE TITLE
Foreman's retry_jobs management command is omitted from the README

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#958]
### Context

The README doesn't mention the `retry_jobs` management command.

### Problem or idea

The README should say what the `retry_jobs` command is and how to use it and why.

### Solution or next step

Add documentation about the `retry_jobs` command.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by cgreene** [comment]
Has been done.
