### ISSUE TITLE
Question about smashing again a failed dataset

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#961]
### Context

When there's an error with [a dataset](https://www.refine.bio/dataset/82b4a143-b8ca-4648-bd8c-6fda69491b3c) we show this message 

![image](https://user-images.githubusercontent.com/1882507/50451341-6d025f00-0901-11e9-8251-da6c9ddc35e4.png)

### Problem or idea

We want to be able to allow the user to try generating the download again. For this I'm trying start the same dataset again, by sending `{start: true}`, but this doesn't change the state of a failed dataset.

In this case, should we be able to restart a failed dataset, or should we create a new one and trigger the smashing for that one.

### Solution or next step

Tagging @Miserlou and @kurtwheeler for input.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by jaclyn-taroni** [comment]
I'll note that in the particular case @arielsvn showed me, it was a single sample. The text of the error message + what I know of our testing suggests that this particular case would probably not successfully smash currently.

**Comment by arielsvn** [comment]
just remove try again buttton

**Comment by dvenprasad** [comment]
For me: 
Give @arielsvn an updated copy to convey we were unable to smash these sample and they can file an issue with us with the error message.

**Comment by arielsvn** [comment]
WIP at [arielsvn/961-remove-dataset-retry](https://github.com/AlexsLemonade/refinebio-frontend/compare/arielsvn/961-remove-dataset-retry)

**Comment by dvenprasad** [comment]
@arielsvn 

Replace `Please try again` and the download button with:
` We encountered a problem while getting your dataset ready. We apologize for the inconvenience.`

Modify the contact us copy to: 
`Please contact ccdl@alexslemonade.org or file a ticket on Github with the following error message for further assistance. <error message>`
