### ISSUE TITLE
We need a mechanism for creating downloader jobs for missing files.

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#978]
### Context

https://github.com/AlexsLemonade/refinebio/issues/930 means that at least some files that were downloaded are now missing and need to be re-downloaded. Additionally and probably more importantly, we killed our EBS volumes so all of the data we've downloaded so far is now missing. We don't currently have any mechanism to re-download data that has had a successful downloader job.

### Problem or idea

We need to have processor jobs re-create the downloader jobs that created them if the processor job detects that one or more files it needs is missing.

### Solution or next step

I think that basically the way to do this is to:
  - Find all the places where processor jobs check to see if their original_files exist. I think this is probably each processor's `prepare_files` function, but it could potentially be broken out to be part of `start_job` so that it's just one place. Here's an example of what I mean: https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/salmon.py#L78
  - Anywhere that check is, instead of logging an error and failing the job, call a util function which will recreate the downloader job that originally downloaded the original files associated with the processor job.
  - This recreated downloader job should have the same associations to original_files as the processor job.

Unfortunately I don't think this will work for Array Express and GEO because of extracted files. This is tricky because processor jobs are only associated with files they're supposed to process, not the compressed files that got extracted to produce those files. Therefore if you only know the original file the processor job was for, it's not immediately obvious how to find the compressed original_file that should be associated with the downloader job. HOWEVER, both the compressed original_file and the extracted original_file have the same `source_url` field. Therefore, for an array express or GEO job I would expect the flow to be something like:
  - Get the original file for the processor job.
  - Query original_files to find the original file where `original_file.filename == source_url.split("/")[-1]` is true
  - Create a new downloader job associated with that original file and let the foreman queue it.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by Miserlou** [comment]
Sounds good, I think the processor job should self-delete after going through this to avoid marking complete or marking as a retry.
