### ISSUE TITLE
Zenodo Access

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#981]
@jaclyn-taroni edit.

A few comments/concerns that came up yesterday in team meeting about archiving species compendia on Zenodo:
- File size limits for individual datasets -- will we have individual "concepts" or record for each species or will compendia for all species live in the same record?
- Getting our heads around how the DOI versioning works
- Making sure multiple team members are able to update the record (e.g., shared permissions of some kind)

**Comment by jaclyn-taroni** [comment]
From the current [Zenodo policies](http://help.zenodo.org/):

>**What are the size limits in Zenodo?**
> We currently accept up to 50GB per dataset (you can have multiple datasets); there is no size limit on communities. However, we don't want to turn away larger use cases. If you would like to upload larger files, please contact us, and we will do our best to help you. Please be aware that we cannot offer infinite space for free, so donations towards sustainability are encouraged

Not sure if creating a [community](https://zenodo.org/communities/) could be useful to us -- all refine.bio projects could be included in said community and we'd be the curators (not sure that gets around the shared permissions issue above).

Here's an example community around data from an individual lab: https://zenodo.org/communities/mkuijjer/?page=1&size=20

**Comment by cgreene** [comment]
Create a CCDL user. All uploads should come via the CCDL user. We will also create a CCDL community to tie the organisms together. This is a workaround for zenodo #1325

**Comment by cgreene** [comment]
We now have a CCDL user.
